starship/starship

src/modules/rust.rs

This PR adds support for `rust-toolchain.toml` in the rust module.
A related Issue is #417, and this just adds some lines to PR #426.
I haven't opened a issue for this, but when I enter a directory with `rust-toolchain.toml` rustup started to install the toolchain. This is the same issue as #417 but with `.toml` file.

fix(rust): support for `rust-toolchain.toml`

---

docs/config/README.md
src/formatter/string_formatter.rs

String formatter treats empty string as it was `None`
Closes #2700
Closes #1855

feat: treat empty string as none when formating

---

src/context.rs
src/modules/battery.rs
src/modules/mod.rs

I noticed right after @matchai merged that the implementation of `BatteryInfoProvider` had an old name from when the interface was called `BatteryStatusProvider`, this fixes that mistake.
The name is confusing.

style: fix name of battery info provider implementation

---

src/module.rs

Comments are mere suggestions that can easily be ignored (proof: look at the PR). Instead we should enforce ALL_MODULES ordering in a test.
ALL_MODULES is supposed to be in alphabetical order but is not.

style: enforce ALL_MODULES ordering in test

---

src/modules/custom.rs

Moving the OS check before other checks so that there is no performance hit for running the match in the incorrect OS.
I noticed that the `when` config condition always runs, even in an OS that did not match. This causes a performance hit on Windows, as the command might not exist there, and it will take a while to continue. I noticed 2 to 3 second pauses on Windows. These pauses do not happen on Linux.
Related to #2750 and #2751.

perf: Improve custom config OS check

---

src/init/mod.rs

This PR replaces the quoting code for `starship init` with quoting via `shell_words::quote`. It also adds `sprint_pwsh()` in addition to `sprint()` to better account for string escaping in PowerShell.
~~@exactly-one-kas I think this might fix #2767, but I'm not sure what kind of path was failing for you. Can you please confirm whether this fixes your issue?~~
Edit: it seems to fix it
Closes #2767

fix(init): improve starship path escaping

---

docs/config/README.md
src/modules/docker_context.rs

As described in #2022 and the Docker official documentation, the Docker Context can also be overriden by the `DOCKER_HOST` and `DOCKER_CONTEXT` environment variables. This PR detects the enviroment variables and updates the docker_context module accordingly.
The main motivation is to follow how the docker context works when those enviroments are set, accordingly to expected behavior.
Closes #2022 
We wrote some additional tests for the modules to ensure the correct behavior of the module.

feat(docker_context): Use DOCKER_HOST and DOCKER_CONTEXT enviroment variables 

---

docs/config/README.md
src/configs/dotnet.rs
src/modules/dotnet.rs

Add `via ` prefix to `dotnet` modules's default format config.
Make it consistent with other modules.
Before:
After:

fix(dotnet): make default format consistent with other modules

---

src/init/starship.nu

The nu init script was setting `STARSHIP_SESSION` instead of the correct `STARSHIP_SESSION_KEY` variable. 
Closes #

fix(nu): use correct session key variable name

---

src/init/starship.ps1

`Get-Error` does not exist in all versions of PowerShell, and attempting to use it on machines where it does not exist pollutes `$error`. Someone may be tempted to use `-ErrorAction Ignore` but since the command does not exist, it still ends up in `$error`
This is a dual bug fix because it actually gets errors on all machines now and it does not pollute `$error`.
In looking for unrelated errors, I kept seeing an error about `Get-Error` not existing, and narrowed it down to starship.
I also changed `-expand` to `-ExpandProperty` while I was at it because it is best practice.
`$error[0]` exists in all versions of PowerShell and will not cause issues even if there are no errors
I didn't test within starship, but I did at the console. First, I opened a fresh console with no errors and you can …

fix: PowerShell init - replace Get-Error with $error[0]

---

CONTRIBUTING.md
clippy.toml
src/bug_report.rs
src/configure.rs
src/init/mod.rs
src/lib.rs
src/main.rs
src/modules/custom.rs
src/modules/directory.rs
src/modules/dotnet.rs
src/modules/git_branch.rs
src/modules/git_commit.rs
src/modules/git_metrics.rs
src/modules/git_state.rs
src/modules/git_status.rs
src/modules/hg_branch.rs
src/modules/rust.rs
src/test/mod.rs
src/utils.rs

On Windows when running commands with their name instead of the path with `Command::new`, executable with that name from the current working directory will be executed.
This PR replaces all instances of `Command::new` with a new `create_command` function which will first resolve any executable paths and avoid this issue.
I also added clippy configuration options to prevent the use of `Command::new`.
`context.exec_cmd` isn't vulnerable because it already resolves paths.
Apart from the tests only `starship init <shell>` (excluding PowerShell), the rust module (if `$RUSTUP_TOOLCHAIN` is not set) and custom modules are vulnerable.  ~~The `Command::new` statement in the `rust` module can't be reached, because `context.get_env` will never return `None` on Windows.~~
Closes #

fix(windows): avoid inadvertly running exes from cwd

---

src/init/mod.rs

In #2848 I forgot removing the quotes from the bash snippet, which means paths might be quoted twice.
Closes #

fix(init): remove quotes in bash init

---

docs/config/README.md

updates git_commit default in README files to the actual default
it was incorrect

fix: update git_commit default in READMEs

---

docs/config/README.md

fix the shlvl module's symbol in the docs
Closes #1925

docs: fix shlvl module's symbol

---

.github/workflows/deploy.yml

See upstream: https://github.com/softprops/action-gh-release/pull/83

ci: Use default token for release action

---

docs/config/README.md
src/configs/status.rs
src/context.rs
src/init/starship.bash
src/init/starship.fish
src/init/starship.zsh
src/main.rs
src/modules/status.rs
src/test/mod.rs

Take pipeline_status variable and format values in the prompt
Bash and Zsh provide pipeline_status variable that contains exit code of processes in a pipe
It can be helpful to know the per-process exit code in a pipeline in order to know where a pipeline failed
This MR is based on this one https://github.com/starship/starship/pull/370
And closes this issue #1669 
It's also the continuation of this work https://github.com/starship/starship/pull/1948
Sample outpout

feat(status): Add pipestatus display in status module

---

src/print.rs

This PR changes the `explain` and `timings` commands to add quotes around the module outputs to make spaces inside the modules output more obvious.
Closes #2928
Before:
```
❯  (<1ms)                             -  A character (usually an arrow) beside where the text is entered in your terminal
starship  (6ms)                       -  The current working directory
```
After:
```
"❯ " (<1ms)                             -  A character (usually an arrow) beside where the text is entered in your terminal
"starship " (8ms)                       -  The current working directory
```

feat(explain): quote module values

---

docs/advanced-config/README.md

Add `italic` to style strings documentation in Advanced Config
Italic is mentioned in https://starship.rs/config/#style-strings but not https://starship.rs/advanced-config/#style-strings

docs: Add `italic` to Advanced Config styles

---

docs/presets/README.md

Changing the formatstring from double to single quotes with escapes ensures the time is shown correctly
Looked bad.
Before:
After:

fix: prevent cutting of the time

---

docs/config/README.md
src/modules/kubernetes.rs

Extends the existing feature of kubernetes context aliases with regular expressions, context aliases now can match on the context via regex, match groups can then be used in the alias for dynamic naming. E.g.:
```toml
[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"
```
This matches on `gke_infra-cluster-28cccff6_europe-west4_cluster-1` and produces the alias `gke-cluster-1`. This is very useful for cloud providers (GKE, Azure), as well as OpenShift clusters (`namespace/openshift-cluster/user` -> `.*/openshift-cluster/.*`).
Closes #800
Closes #839
Closes #851
I tested manually (my own kube context) and added tests to the kubernetes module which are supposed to show that existing functionality is not broken and the added functionality works as expected.

feat(kubernetes): implements regex matching for context aliases

---

docs/config/README.md
src/configs/package.rs
src/modules/package.rs

Have added the ability to use format the version of the package using
the `version_format` option. While doing this I have also done some
refactoring of the module to remove the if/else if/... block and replace
it with an iterator. This should make fix some edge cases where versions
are not correctly picked up due to other files an example would be a
python project that has a `pyproject.toml` file but using the
`setup.cfg` for the package version. It should also make it easier to
make the order of the list configurable in the future.
Related to #2236

feat(package): Add ability to format the version

---

Cargo.lock
Cargo.toml

I recently filed [this issue](https://github.com/baoyachi/shadow-rs/issues/61) with shadow-rs because it seemed to be the one blocked keeping starship [builds from being reproducibly](https://reproducible-builds.org/). My subsequent PR was merged a new release cut.
This PR bumps the starship dependency to the latest library version. Merging this should make future starship releases reproducible (provided there isn't something else overlooked, testing this is relatively hard until it gets to the packaging stage).
Closes #2975

Enable reproducible builds

---

docs/config/README.md
src/configs/jobs.rs
src/modules/jobs.rs

This PR adds two new config options (`number_threshold` and `symbol_threshold`) to fix the current behavior of `threshold` in the `jobs` module. The main issue is that *greater than* is a bit confusing. We now allow a *greater or equal than* logic that simplifies configuring the behavior of the module.
Namely, we follow:
> The two thresholds would be the minimum value at which they're shown.
> The default functionality is:
> • 0 jobs -> nothing
> • 1 job -> symbol
> • 2 jobs or more -> symbol + number
Which covers all of the use cases by separating the symbol and number thresholds. This PR adds several more tests to ensure the correctness of the feature.
One thing to note is that the `threshold` option will be deprecated and a warning is issued if its value in the config is different from …

fix(jobs): Add the symbol and number thresholds respecting the `threshold` option

---

docs/config/README.md
src/configs/red.rs
src/configs/v.rs
src/modules/red.rs
src/modules/vlang.rs

Have added version formatting to the red and vlang modules. Note the
docs for red already mentioned the `version_format` string but it had
not actually been added.
Closes #2236

feat(red,vlang): Add version formatting

---

.github/workflows/merge-dependabot.yml

Check for the primary fork of starship and only run the merge-dependabot job on
that fork.
The CI workflow that merges dependabot PRs will run even on forks of starship,
which probably don't have valid GH tokens. Certainly mine doesn't!

ci: disable dependabot cron on starship forks

---

src/modules/git_status.rs

This PR modifies the parser for the output of the `git` command in the `git_status` module. It ensures that, even when an index status is present or the file has been copied/renamed, the working tree status is correctly parsed and displayed in the prompt. This does not apply to merge conflict situations, in which only the merge conflict indicator is shown, as before.
This PR closes #2937.
In addition, files that were both renamed and modified were only shown as renamed, but not as modified.

fix(git_status): show working tree status if index status is present

---

src/context.rs
src/modules/git_metrics.rs
src/modules/git_status.rs
src/utils.rs

This PR changes `utils::exec_cmd` and `context.exec_cmd` to accept `AsRef<OsStr>` (this includes `&str`) instead of `&str` like `Command` from `std`.
This allows passing the git folder in the `-C` argument without `.to_string_lossy()` (which wouldn't work in the lossy case, but this fix still doesn't seem to fix the issue).
Closes #

refactor: allow passing OsStr as-is to `exec_cmd`

---

Cargo.lock
src/modules/cmake.rs
src/modules/crystal.rs
src/modules/dart.rs
src/modules/deno.rs
src/modules/golang.rs
src/modules/helm.rs
src/modules/java.rs
src/modules/julia.rs
src/modules/kotlin.rs
src/modules/lua.rs
src/modules/nodejs.rs
src/modules/package.rs
src/modules/python.rs
src/modules/rlang.rs
src/modules/scala.rs
src/modules/terraform.rs
src/modules/vagrant.rs

Updated some function names. Implemented utility method `get_command_string_output` because it's behavior was used in few modules. Updated java & python tests to test one thing (parsing version string to semantic version), not result of `VersionFormatter` which has it's own tests. 
This comment https://github.com/starship/starship/pull/2611#issuecomment-829797628

style: Improve modules consistency

---

.github/workflows/security-audit.yml

Much like the dependabot automerge, the security-audit cron task _also_ should
only run on the canonical repository.

ci: disable the security-audit cron on non-canonical forks

---

src/configure.rs

In addition to the comment about missing unset values add a comment at the top of the `print-confg` that shows how `$all` is expanded.
This works, but I'm not too happy with the output because it results in a very long line.
Closes #2923
New output:
```toml
format = '$all'      
scan_timeout = 30
command_timeout = 500
add_newline = true
```
If customer modules are present:
```toml
format = '$all'      
scan_timeout = 30
command_timeout = 500
add_newline = true
```

feat(print-config): list expanded `$all` variable

---

src/configure.rs

Due to the introduction of `utils::create_command`, commands now have stdin set to null, and stdout and stderr set to piped.
This prevented console editors from working when invoked via `starship config`
This just changes the io streams of the editor command back to inherit from piped/null.
In starship 0.56 `starship config` worked fine with vim
In starship 0.57 `starship config` does not display the editor UI in the terminal.

fix(config): make terminal editors work again when launched by `starship config`

---

install/install.sh

Instead of manually specifying formatting with here docs and long strings, this PR uses `printf` to generate the usage and install instructions output. The PR also adds the install instructions for PowerShell, Elvish, and NuShell from the project's README.
This makes the script easier to maintain and adds in the install instructions for three shells supported by the project but not in the install script.
I ran the install script and looked at the output.

refactor: install.sh to improve usage and install instructions

---

.github/chglog/release.yml

Changed release page commit group title order from alphabetical to 
1. feat
2. fix
3. docs
4. style
5. refactor
6. pref
7. test
8. build
9. ci
10. chore
11. revert
Now it closely matches Semantic PR conventional commit types.
Closes  #3038 
Tested on release v0.57.0, here is a truncated version of new release file it generates
```
* add support for xonsh ([#2807](https://github.com/starship/starship/issues/2807))
* **explain:** quote module values ([#2931](https://github.com/starship/starship/issues/2931))
...
* **clippy:** fix new clippy lints ([#2939](https://github.com/starship/starship/issues/2939))
* **git_status:** show working tree status if index status is present ([#2973](https://github.com/starship/starship/issues/2973))
...
* Fix typo …
```

docs(chglog): Change release page title order (#3038)

---

docs/advanced-config/README.md
docs/config/README.md
src/configs/starship_root.rs
src/context.rs
src/formatter/string_formatter.rs
src/init/starship.elv
src/init/starship.fish
src/init/starship.zsh
src/main.rs
src/print.rs
src/test/mod.rs

Many shells support a right prompt that appears on the far right hand side of the input line. This change makes it easy to configure a right prompt with starship.  
This change adds a `right_format` to the config for specifying the format of the right prompt. Modules that are included explicitly in `format` or `right_format` are removed from `$all` to avoid redundant output. A new clap flag `--right` tells starship to output the right prompt instead of the default (left) prompt. 
I've updated the init scripts for fish, zsh and elvish, but only tested with zsh so far. 
While it is possible to set the right prompt using starship today, it is cumbersome. The user must create an alternate config file and manually configure their shell to use it. What's more, the user would likely have to …

feat: Add support for RPROMPT (right prompt)

---

src/init/starship.zsh

A typo in the zsh init script was breaking the predicate to prevent adding duplicate hooks.
Minor nuisance, but it was gumming up my shell while testing

fix(zsh init script): avoid adding preexec commands twice

---

src/modules/battery.rs
src/utils.rs

This PR makes sure `%`-characters are always escaped, by moving the handling from the battery module to `wrap_colorseq_for_shell` where interpretable characters are already being handled for bash.
Closes #2891

fix(zsh): always escape percent character

---

docs/config/README.md
src/configs/fill.rs
src/configs/mod.rs
src/context.rs
src/formatter/string_formatter.rs
src/formatter/version.rs
src/module.rs
src/modules/fill.rs
src/modules/line_break.rs
src/modules/mod.rs
src/print.rs
src/segment.rs

Introduces a new `fill` module that fills up any remaining space in a line. When there are more than one `$fill`s in a line, the space is divided evenly between them. This allows the creation of prompts that right align some modules and even a form of centering. 
This behavior is implemented by specializing Segment to explicitly call out line breaks and fills. The fill width is calculate when converting Segments into ANSIStrings. This ensures that all line breaks are counted regardless of how they were added (see PR 2425). 
It also includes a change to `$all` to exclude any modules that are explicitly referenced elsewhere in the format, which makes it easier to move modules to the right hand side without rewriting the whole format string. (That change is also represented in …

feat: Add a fill module to pad out the line

---

src/configs/mod.rs

#3026 didn't add `format_right` to `FullConfig` meaning it was missing in the `starship print-config` output. I also added a test to ensure this doesn't happen again in the future.
Closes #

fix(print-config): add missing `format_right` to `FullConfig`

---

docs/config/README.md

Added `$cobol` to the `$all` list on the config page.
Touches up #2994
N/A

docs: Add missing modules to $all in config docs

---

Cargo.lock
Cargo.toml
src/context.rs
src/print.rs

This PR replaces `term_size` with `terminal_size`. `term_size` has become unmaintained, and `terminal_size` is the suggested replacement. Another option would have been `crossterm`, but that would have been a much larger  dependency.
Closes #

refactor: replace `term_size` with `terminal_size`

---

src/init/starship.ps1

`[System.Diagnostics.ProcessStartInfo]::new` which was introduced #2104 doesn't exist on Windows 8, but  `New-Object` works instead. Using the implementation from on older suggestion of mine https://github.com/starship/starship/pull/2104#discussion_r558873960.
Closes #3064

fix(windows): make powershell init work on windows 8 again

---

docs/config/README.md

Add missing double quotes to default value strings for Shell, Environment Variable, and Custom modules.
Closes https://github.com/starship/starship/issues/2935

docs(config): Add missing double quotes to default value strings

---

src/main.rs

This PR allows adding the `prompt` arguments to the `explain` and `timings` subcommands. The `explain` and `timings` implementations are already handling the additional arguments correctly without any changes.
The reason for the big diff is `cargo fmt`.
Closes #3040
```
starship.exe-explain 
Explains the currently showing modules
USAGE:
starship.exe explain [OPTIONS]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-d, --cmd-duration <CMD_DURATION>    The execution duration of the last command, in milliseconds
-j, --jobs <JOBS>                    The number of currently running jobs
-k, --keymap <KEYMAP>                The keymap of fish/zsh
-P, --logical-path <LOGICAL_PATH>    The logical path that the prompt should render for. This …
```

feat(explain): allow specifying prompt arguments in explain and timings subcommands

---

docs/config/README.md
src/configs/terraform.rs

Have updated which extentions trigger the terraform module, to remove                                                       
the `hcl` since this gives false positives as it is used by other                                                           
Hashicorp products and add the `tfstate` and `tfplan` which are more                                                        
accurate indicators.  
Closes #3071

fix(terraform): Improve module triggers

---

src/context.rs
src/init/starship.bash
src/init/starship.zsh

Modifies pipestatus parsing for the starship binary and changes the initscripts for bash/zsh to quote pipestatus. This allows starship to start without errors in the case where pipestatus is empty (usually due to interactions with other shell frameworks).
The previous implementation of pipestatus assumed that the arguments to pipestatus would be word-split (bash, zsh) or repeated by the shell (fish). Unfortunately, this causes a shell parse error if pipestatus is not set on first invocation (which can apparently happen if other shell frameworks are present).
There are two ways to fix this:
1. Modify the init scripts to not use `--pipestatus` at all when pipestatus is detected to be empty.
2. Quote the arguments to `--pipestatus`, which allows clap to detect an empty argument, and then …

fix: pipestatus quoting on Zsh/Bash

---

docs/.vuepress/config.js
docs/package-lock.json
docs/package.json

I added this [plugin](https://www.npmjs.com/package/vuepress-plugin-code-copy) to vuepress. This plugin adds a copy to clipboard button for all the code snippets. I think this a handy feature to have
Closes #3116
Closes #2960 
- [ x] I have tested using **Linux**

feat(docs): Add copy button for code snippets via plugin

---

docs/installing/README.md

Since I maintain the starship package over at Funtoo Linux, I thought I might as well mention that in the installation page in the docs :^)
I've ran the docs website locally to verify the changes are visually consistent with the rest of the installing page.

docs: add funtoo linux install steps

---

.gitattributes

The .gitattributes file says `/src/init/ text eol=lf`, which applies the `text eol=lf` only to the directory, not to the files in the directory.
```
$ git check-attr -a src/init/starship.zsh
```
(no output)
By changing the rule to `/src/init/* text eol=lf`, it is applied to all files within the directory instead.
```
$ git check-attr -a src/init/starship.zsh
src/init/starship.zsh: text: set
src/init/starship.zsh: eol: lf
```
Closes #3099
I don't actually have zsh on Windows, but I can see the problem using xxd.
Before:
```
$ starship init zsh --print-full-init | xxd | tail -n 1
00001180: 4253 5f43 4f55 4e54 2229 270d 0a         BS_COUNT")'..
```
(note the 0d 0a sequence at the end)
After changing .gitattributes and doing a clean checkout of the init directory:
```
$ starship init zsh …
```

fix: init script line endings

---

src/context.rs

I noticed that recent intermittent test failures have logged that file scanning takes longer than 20ms. In these cases, `ScanDir` is likely aborted because it takes longer than `scan_timeout` (20ms). This PR disables the scan timeout entirely in testing.
Related #886

fix: ignore scan_dir timeout in tests

---

docs/config/README.md
src/configs/ruby.rs
src/modules/ruby.rs

This PR adds a check in the ruby module for the environment variables `RUBY_VERSION` and `RBENV_VERSION`, which indicate that ruby is currently activated with RVM or rbenv (respectively). 
The variables to check are configurable with the `detect_variables` option.
Starship does not detect ruby environments activated with environment variables.
See my [comment](https://github.com/starship/starship/issues/698#issuecomment-961592678) in #698
I've tested this with rbenv and RVM.
```
brew install rbenv ruby-build
rbenv install 3.0.2
```
In a new terminal, `rbenv shell 3.0.2` adds the correct ruby version to the prompt (3.0.2).
```
\curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
source $HOME/.rvm/scripts/rvm
rvm install 3.0.1
```
In a new terminal, `source $HOME/.rvm/scripts/rvm` …

feat(ruby): Add environment variable checks to ruby module

---

src/init/starship.fish

`pipestatus` variable needs to be treated the same way as normal `status` variable, so we save it out in order to use it in the prompt.
Closes #3159

fix: save pipestatus in fish init functions

---

src/modules/python.rs

if config.pyenv_version_name is true and if there is a PYENV_VERSION environment present when executing starship module python the output uses the value of PYENV_VERSION otherwise it will show the version in the output of pyenv version-name.
Closes #2872
Executed these commands:
1. pyenv local 3.8.0
2. ./starship module python
3. export PYENV_VERSION="3.7.0"
4. ./starship module python
5. export PYENV_VERSION=""
6. ./starship module python

feat(python): Show value of PYENV_VERSION when present

---

.github/chglog/changelog.yml
.github/chglog/release.yml

Reverts starship/starship#3205
Chglog did not respect the changelog section order defined in the configuration in the last release, so it's being temporarily undone as we work out why.

chore(chglog): undo changes to chglog configuration

---

Cargo.lock
Cargo.toml
src/configure.rs

This PR updates `toml_edit` to `0.8.0` and updates the code accordingly.
Because there is no longer an obvious way to coerce a `toml_edit::Document` into an `toml_edit::Item`, the first loop iteration over the configuration keys is essentially handled manually now.
Closes #3202

build: bump toml_edit from 0.6.0 to 0.8.0

---

src/configure.rs
src/main.rs

`starship print-config` now takes an optional number of paths to filter the configuration by. It doesn't look like the `print-config` command is documented so I didn't add documentation for this new behavior.
Closes #2934 
```
$ starship print-config git_status git_branch.format
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'red bold'
stashed = '\$'
ahead = '⇡'
behind = '⇣'
up_to_date = ''
diverged = '⇕'
conflicted = '='
deleted = '✘'
renamed = '»'
modified = '!'
staged = '+'
untracked = '?'
disabled = false
[git_branch]
format = 'on [$symbol$branch]($style)(:[$remote]($style)) '
```

feat: print-config subset of config

---

docs/config/README.md
docs/presets/README.md
src/configs/mod.rs
src/configs/starship_root.rs
src/configs/sudo.rs
src/module.rs
src/modules/mod.rs
src/modules/sudo.rs

Add a sudo credential caching hint module. It's disabled by default to avoid cluttering the prompt too much, however users that want this feature only need to change `disabled = "false"`.
Closes #816 
I was only able to create one test.

feat(module): Add `sudo` module

---

src/modules/docker_context.rs

Fixed typo.
```
enviroment -> environment
```

fix: typo in docker_context.rs

---

src/context.rs
src/modules/directory.rs
src/modules/dotnet.rs
src/modules/git_branch.rs
src/modules/git_commit.rs
src/modules/git_metrics.rs
src/modules/git_state.rs

Modules that use `context.get_repo()` re-open the repo based on the reported workdir, which can be inaccurate and was a source of bugs. Instead, store the gitdir's path for later use.
Each module has its own unique way of handling git repos and what parts of `context::Repo` they use. This can result in inconsistencies across modules where one (git_status) might work while another (git_branch) might inexplicably fail.
Might be related to #2462. I had many issues with submodules that used relative `gitdir:` paths in their `.git` file.
This attempts to fix things somewhat, though a more consistent approach might be to just store the `git2::Repository` inside the `Repo` directly - is there any specific reason why this isn't currently done?

fix(git_branch): more robust handling of .git

---

src/modules/hostname.rs

This PR ensures the `trim_at` test handles unicode and does not panic if the chosen position is not a valid character boundary.
Closes #

test(hostname): fix `trim_at` test with unicode hostname

---

docs/config/README.md

Made the docs more clear about how to escape special characters in basic strings. Also updated the broken TOML spec link.
Closes #3283

docs(config): clarify special characters escaping

---

src/init/starship.ps1

These need to be stored before calling any PowerShell function or executable.
Otherwise the values will be overwritten and cannot be properly restored
or passed to starship.
Fixes: #3315

fix: Store $? and $LASTEXITCODE first in PowerShell

---

docs/.vuepress/styles/index.styl

- Removed superfluous bottom space in code blocks
- Also fixed the indistinguishable color of language text
N/A
Before:
After:

fix(docs): remove superfluous space

---

.cargo/audit.toml

`mockall` was updated to no longer depend on `difference`.
Related #3318
Closes #2835

chore(audit): unignore RUSTSEC-2020-0095 (`difference` is unmaintained)

---

docs/config/README.md
src/modules/status.rs

Add hex_status variable to status module containing the exit code in hex format.
This is useful on windows because many NTSTATUS codes have high bits set leading to large negative numbers (see below).
Refs: https://github.com/starship/starship/pull/2025
Before:
💥 -1073741510❯
After:
💥 0xC000013A❯

feat(status): Add hex_status

---

docs/faq/README.md

Changed 'STARHIP_LOG' (missing S) to 'STARSHIP_LOG' in examples in FAQ

docs: fix typo in FAQ page

---

src/modules/dart.rs

flutter 2.8.0 updated with dart 2.15, command `dart --version` will output in stdout.
Closes #3341

fix(dart): detect version output in stdout with dart 2.15+

---

src/context.rs
src/utils.rs

Explicitly set cwd for external commands, because some command outputs may depend on it.
I split up  `utils::exec_cmd` into `exec_timeout` and `mock_cmd` and made `context.exec_cmd` and `utils::exec_cmd` use these new functions and `create_command`.
Closes #2869

fix: set cwd for command execution

---

src/modules/rust.rs

After checking directory overrides we were directly falling back to the
relatively slow call to `rustc --version`.
Inserting a call to `rustup default` leads to a quicker response when using `rustup`.
The only way to make this even faster would be to try to read
`.rustup/settings.toml`, though [this is not part of the official `rustup`
API](https://rust-lang.github.io/rustup/configuration.html). Also we might safe the second call to `rustup` when we find out it doesn't exist in the first call. 
I'm not sure about the classification (`perf`/`fix`), I'm happy to change it if
needed. Same goes for any other implementation parts, or when I might have
missed something that made `rustup default` give us the wrong result? I checked
<https://github.com/starship/starship/pull/426> and didn't find …

perf(rust): additionally check `rustup default` for faster result.

---

docs/config/README.md

Fixes the variable docs for hostname, which appear to have been accidentally copied from a language module. Specifically, the `symbol` variable does not exist for hostnames.
Closes #

docs: Fix incorrect variables for hostname module

---

README.md
docs/README.md
install/install.sh
src/init/starship.elv

The shell integration for elvish printed deprecation warnings on the current stable version v0.17. This PR updates the shell integration to avoid this and switches from shell hooks to `$edit:command-duration` for getting command durations.
Because of incompatibilities, support for versions <v0.17 was dropped.
Closes #3307

fix(elvish): upgrade shell integration for v0.17

---

docs/config/README.md
src/configs/git_status.rs
src/modules/git_status.rs

`git status` can be prohibitively slow on some repos, so allow the config to influence what flags are passed to git. For instance, if there is no configured symbol for untracked files, tell git to omit them from its output.
Note that since this requires the user to opt-in to omitting certain details from the module (and does not change the defaults), this is not really a "fix" for #2625.
A follow-up to this might be to read `git config` data to customize this behaviour per-repo. There is precedent for this in [oh-my-zsh git prompts](https://github.com/ohmyzsh/ohmyzsh/blob/e86c6f5e7fc9f024a427e2870ab70644b5454725/lib/git.zsh#L40), so looking for the config entries that people are already using in the wild might be nice.
With the repos I mentioned in [my …

perf(git_status): tweak exec flags to omit unnecessary info

---

docs/config/README.md

Adds a missing option `nu_indicator` to the documentation for the shell module.
Closes #

docs: Add nu_indicator to doc tables

---

src/modules/directory.rs

Fixed typo.
```
seperators -> separators
```

chore(directory): fix typo

---

docs/advanced-config/README.md
src/config.rs
src/configs/mod.rs
src/configs/starship_root.rs

This PR updates the continuation prompt to be a more minimal alternative to the current yellow chevron.
I think the yellow chevron may be a little bold and visually loud for something that I feel is more of an accent than an actionable piece of information. Interested to hear your thoughts @raccog, @chipbuster, @davidkna.
**Changes**
- Replace the chevron with a gray (bright black) bullet
- Add a space after the prompt to better align with the default prompt
Closes #
**Current continuation prompt defaults**
**Proposed update**

fix: update continuation prompt to be more minimal

---

src/utils.rs

The older `process_control::Timeout` API has been deprecated.
Related #3381

refactor(process_control): switch to new API

---

Cargo.lock
Cargo.toml
src/configure.rs
src/context.rs
src/main.rs
src/modules/character.rs
src/modules/cmd_duration.rs
src/modules/jobs.rs
src/modules/pulumi.rs
src/modules/rust.rs
src/modules/shell.rs
src/modules/status.rs
src/print.rs
src/test/mod.rs

Updates clap to v3. I switched the implementation to the new `derive`/`structopt` style because there were so many breaking changes.
Completions are now handled by `clap-completions`. ~~I changed some arguments to allow setting them from environment variables.~~ Shared `module`/`prompt`/`explain` arguments are now handled by `context::Properties` and `--right`/`--continuation` are handled separately for `prompt` and passed on as a `Target` (the other subcommands ignore target and set it to `Main`). 
Closes #

refactor: update clap to v3

---

docs/config/README.md
src/init/starship.elv

This PR adds showing last command status in elvish.
Elvish's built-in commands have no status code, but the error passed to `edit:after-command` has a status code when the external command fails.
This PR uses the `edit:after-command` hook and treat the error.
Closes #
Taken on windows, with status package:

feat(elvish): last command status

---

.github/workflows/deploy.yml
Cargo.lock
Cargo.toml
src/bug_report.rs

This PR removes [git.io](https://git.io/) link shortening for the bug-report subcommand, because it doesn't accept submissions anymore.
This also removes `attohttpc` and thereby `openssl` from the dependency list and thereby the `feature `for vendoring openssl.
Closes #

fix(bug-report): remove git.io link shortening

---

src/init/starship.ps1

This is an alternative to #3386 using `New-Module` to create a new dynamic script module and `Export-ModuleMemeber` to make it not export anything, other than the global prompt function, instead of prefixing the functions.
> #3322 changed the PowerShell init in order to pass the current starship arguments to starship prompt --continuation. This PR reverts these changes and just uses plain &starship prompt --continuation (Invoke-Native isn't really needed there, and the zsh init does not pass along the arguments either) to avoid polluting the global function namespace with Invoke-Native and Get-Arguments. I also moved the continuation prompt code to ensure $STARSHIP_SHELL and $STARSHIP_SESSION_KEY are set beforehand.
> 
> To avoid putting functions into the user scope with common names, …

fix(pwsh): Avoid polluting the global function namespace

---

src/context.rs

Recent changes made the lifetime `'a` become unused if the `battery` feature was disabled. This PR adds a `PhantomData` field to `context` that hold a phantom reference to the lifetime.
Closes #3434

fix: allow compilation without battery feature

---

src/context.rs
src/init/starship.fish
src/modules/character.rs
src/modules/status.rs
src/test/mod.rs

`--status` can be an empty string in some cases with zsh, and it looks like this can't be ignored with clap-derive right now - as a fix switch to `String` which permits empty values.
`--terminal-width` can also be an empty string in some cases, use custom parsing that falls back to `default_width()` if the argument is empty.
clap v3 also changed how `Vec<_>` arguments are treated (it looks like you need to use `-o 1 -o 2 -o 3`). `multiple_values` can restore the old behavior, but this breaks when passing an empty string. To work around this, quote the arguments in all the init scripts and set `value_delimiter = ' '`.
I tried testing the pipestatus changes in fish, but it doesn't seem to work for unrelated reasons (stable also doesn't work for me).
Closes #3438

fix(properties): fix regressions in `status`, `pipestatus` and `terminal-width` handling

---

docs/config/README.md

config file during creation and when used as export variable into shells are different.
Fixed to make it uniform and avoid errors
I was installing starship today while reading the documentation for the same.
The configuration file location while creation and when it was exported to shells were different.
[here](https://starship.rs/config/#configuration)

docs: Fixed starship config location

---

.github/workflows/workflow.yml

Augmenting #3435: These jobs will check that compilation still succeeds when no features are selected and with all features selected.
I was also hit by #3434, and quickly #3435 was added, so I figured this would be useful. The idea would be that, when in the future new features are added, these quick checks can prevent miss-compilation for users that like to tweak with feature sets.
While these CI operations can be run under the same `cargo_check` job, I decided to add two more independent jobs so they run in parallel. I'll be happy to roll them up into the `cargo_check` job if y'all decide it's not worth it.
```
$ cargo check --workspace --locked --all-features
$ cargo check --workspace --locked --no-default-features
```

ci: Add jobs for `cargo check` with all features and no features

---

README.md

As the number of supported systems and shells has grown, we've had to hand-pick what installation methods would be the "blessed" ones to show on our README. This change changes that to include _all_ installation methods, but hides them each into OS and shell-specific collapsed sections, as is done by the excellent [ajeetdsouza/zoxide](https://github.com/ajeetdsouza/zoxide).
**👉 [Preview the changes here](https://github.com/starship/starship/blob/rework-readme/README.md)**

docs: break installation instructions to collapsable sections 

---

src/init/starship.elv

Use built-in `randint` to create STARSHIP_SESSION_KEY and reduce `starship session` call, like in fish.
Closes #

perf(elvish): Use built-in `randint` instead of `starship session`.

---

CONTRIBUTING.md
docs/config/README.md
src/configs/container.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/context.rs
src/module.rs
src/modules/container.rs
src/modules/mod.rs
src/test/mod.rs
src/utils.rs

Adds a container type indicator, if inside a container, detected via the presence of some marker files.
E.g. inside a podman container entered with `toolbox enter`:
```
starship on  container_rebased [$!] is 📦 v1.0.0 via 🦀 v1.56.1
❯ toolbox enter
starship on  container_rebased [$!] is 📦 v1.0.0 via 🦀 v1.56.1
⬢ [fedora-toolbox:35] ❯
```
Additionally a test method for absolute file names is added.
Closes #2590
Closes #3104

feat: add a container indicator

---

install/install.sh

This adds a POSIX check for the most common shells (`bash`, `zsh`) to try to ensure that the shell running the install script is POSIX-compliant
We have had at least one (I suspect two) issues recently where running the install script in `zsh` led to errors because of different semantics.
Closes #3468
Closes #3413

feat(install): Add posix shell check

---

src/modules/aws.rs

Adds multiple allowed values to the aws::expiration_date_set_from_file, allowing for up to a two-second delay between when the config file is written and when the module is rendered.
Closes #3377
While `aws::expiration_date_set_from_file` will almost-always work
perfectly locally, it is theoretically possible for the thread running
the test to be scheduled away betwen writing the file with timing
information and then actually reading it, resulting in a
shorter-than-expected time appearing in the module. This can also happen
if the test triggers right at the very end of a second (e.g. at
10:45:47.999995).
This appears to actually happen sometimes on heavily-loaded GitHub
Actions runners. To fix this issue, we allow for up to a two-second
delay between when the file is written and when the …

ci: Fix aws::expiration_date_set_from_file race

---

.github/workflows/format-workflow.yml

Changes the branch detection method from an envar (which has [known issues](https://github.community/t/github-head-ref-is-inconsistent/185017)) to something API-based.
Hopefully fixes the issue with crowdin  PRs (e.g. #3460) where changes are being inappropriately blocked.
Checked that the appropriate properties exist and appear to match using the Github JSON API--unfortunately, these types of changes can really only be tested in production.

ci: Change branch detection method for crowdin

---

docs/config/README.md
src/configs/pulumi.rs
src/modules/mod.rs
src/modules/pulumi.rs

Adds the "username" of the current Pulumi account to the prompt.
Parses ~/.pulumi/credentials.json to retrieve the username on the currently active account.
Enables users to know what their current user account is when logged in to Pulumi.
Added one and modified one unit test, and validated against credentials.json on Linux (Ubuntu 20.04).

feat: add username to Pulumi module

---

src/bug_report.rs

Set the syntax highlighting for the config file in starship bug-report, using the triple backtick syntax.
It seemed unintuitive that the syntax highlighting for the config file was set to bash even when it was known that it was in another language, such as powershell or lua.
I have confirmed that this works for powershell, and all tests that pass on master pass on this branch.

feat: starship bug-report sets syntax highlighting for config file

---

src/init/starship.elv

The `$PWD` environment variable used by starship is not updated on startup by `elvish`. `elvish` also provides a separate `$pwd` variable that does get updated and seems to be be a better indicator for the current logical path.
Closes #3512

fix(elvish): use `$pwd` for `logical-path`

---

docs/config/README.md
src/config.rs
src/configs/cmd_duration.rs
src/modules/cmd_duration.rs

The default hard-coded notification timeout is very brief. This PR allows it to be configured.
This PR adds the notification_timeout option to cmd_duration. This allows for the notification timeout to be configured by the user if starship is compiled with notify-rust support. The default value is equal to the previous hardcoded value.
The notification_timeout is coded as a u64, but the notify-rust TImeout::Milliseconds is coded to take u32, so the u64 is cast down. If there is a better way to handle this I am open to suggestions.
The hardcoded notification timeout was brief and lacked customization. Making this option configurable will allow the notification feature to be more useful.
Closes #2194
Closes #2268
Make sure starship is compiled with ```--features "notify-rust"```
Run …

feat(cmd_duration): Make notification timeout configurable

---

CONTRIBUTING.md
docs/config/README.md
docs/presets/README.md
src/configs/nodejs.rs
src/modules/nodejs.rs

Use e718 as the default of symbol in node configuration
Closes #2546 
Visually checked on Iterm2, hyper and mac terminal.

fix(nodejs): use e718 as the default of symbol in node configuration

---

src/init/starship.bash

Restore the previous exit status so that any subsequent hooks in the PROMPT_COMMAND pipeline can run with the correct return code.
Closes #2918
I've confirmed that this doesn't negatively affect bash init, but I haven't confirmed that this actually causes the behavior intended. The fix is based on a comment by lilyball on the linked issue.

fix(bash): Restore previous exit status in bash init

---

Cargo.lock
Cargo.toml
docs/config/README.md
src/configs/localip.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/localip.rs
src/modules/mod.rs

This PR adds support for printing your current ip to the prompt. By default it behaves like the hostname module and is therefore only rendered if an SSH session is present.
The way it obtains the localip is by opening a UDP socket to `8.8.8.8:80` and connecting to it. This is a very fast cross platform way to determine your primary interface's IP address.
Since I'm using SSH a lot, it is very handy to have the IP of the remote machine always shown.

feat(localip): add module to print the current ipv4 address

---

.github/workflows/workflow.yml
Cargo.toml
docs/config/README.md
src/modules/cmd_duration.rs

In #1019 the undistract feature has been added to starship without
enabling it by default due to the system dependency on libdbus. With
recent versions of notify-rust the dependency is no longer required and
the feature can be enabled by default.
Closes #

feat: Enable Undistract Me for Linux

---

docs/config/README.md

This PR removes a leftover `:::` from #3547.
Closes #

docs: remove stray `:::`

---

src/bug_report.rs

Will lead to correct detection of older versions of powershell using starship bug-report. Special-cases the version code on `powershell` (can be extended to any shell, but all the others support `--version` for now).
Has been tested in a Windows VM against powershell 5.1 and the most recent version of pwsh available on the store.
Closes #3531

fix: Correctly detect older versions of powershell in bug-report

---

src/init/starship.zsh

Zsh's `promptinit` expects a theme's hook functions to be named `prompt_<theme>_<hook>`. See https://github.com/zsh-users/zsh/blob/2876c25a28b8052d6683027998cc118fc9b50157/Functions/Prompts/promptinit#L155
* Rename `starship_precmd` to `prompt_starship_precmd`.
* Rename `starship_preexec` to `prompt_starship_preexec`.
Adhering to this de facto standard makes it easier for `promptinit` and other Zsh software following these conventions (such as [Znap's `prompt` command](https://github.com/marlonrichert/zsh-snap/issues/163)) to interact correctly with Starship.
I started Zsh with the new output of `starship init zsh --print-full-init` and it works the same as the old one.
This does not cause any changes in documentation or tests.

refactor: Improve compatibility with Zsh prompt theme system

---

docs/config/README.md
src/context.rs
src/modules/status.rs
src/test/mod.rs

This PR will enable to convert from i64 to hex_status by casting instead of parsing status.
In elvish shell on Windows, the status code is passed as u32, and it can't parse as i32, so `hex_status` is same as `status`.
This PR will replace parsing status to i32 by casting from i64 to i32 and accept this.
The status code out of i32 will be rounded by underflow/overflow.
Closes #
Related #3459
| In powershell | In elvish before fix | In elvish after fix |
|-|-|-|
| ![A screenshot in powershell](https://user-images.githubusercontent.com/16546008/150048679-172e1ffe-8232-41de-8e38-7c89dd29ac1a.png) | ![A screenshot in elvish before fix](https://user-images.githubusercontent.com/16546008/150048683-fe2bbc9d-ede4-428b-86b3-75c6066c938b.png) | ![A screenshot in elvish after …

fix(status): Enable to convert from i64 to hex_status by casting instead of parsing status.

---

src/init/starship.zsh

As https://github.com/starship/starship/pull/3480#discussion_r790280291, 
using add-zsh-hook instead of add hook manually.
It is recommended by official document.
https://github.com/starship/starship/pull/3480#discussion_r790196431
https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Writing-Themes

refactor(zsh): using add-zsh-hook instead of add hook manually

---

src/main.rs

I've changed `main` in `src/main.rs` to call `Cli::try_parse` instead
of `Cli::parse` to manage the error case manually and print the arguments passed
to starship when argv parsing error, just like the issue explains. Other code has not been touched;
thoughts on those changes are in the commit message.
I'm not sure how to test this properly, but I certainly want to discuss:
- whether all arguments are printed correctly:
- what does 'correctly' mean?
- do we need any escaping?
- do we need any measure of 'easy to read'?
- exiting with code 2 when having an error (code 2 is what [`clap::Error`](https://docs.rs/clap/latest/clap/struct.Error.html#method.exit) uses)
- exit 0 on `--help`/`-h`
- whether to exit with code 2/print arguments if `ErrorKind` is `DisplayHelp*`
- certainly, exiting …

feat(cli): Print arguments if argument parsing fails

---

src/init/starship.ps1

Use global:error[0] for most recent error in powershell
Replace $error[0] with $global:error[0] to correctly obtain the most recent error in powershell
Comments are also updated
Closes #3485
The current version uses $error[0], which is for the module starship instead of the global status and is always $null, so the $lastExitCodeForPrompot is always $origLastExitCode and starship cannot correctly display error_symbol.

fix(pwsh): Use global:error[0] for most recent error in powershell

---

src/print.rs

Emitting the `[J` escape sequence in right prompt caused problems with fish text rendering, like during multiline input and during menu-completion. This PR restricts the escape sequence to just the left prompt part.
Closes #3305
Closes #3603
See the linked issue for more details.

fix(fish): Emit clear-screen escape sequence only in left prompt

---

src/context.rs

In some instances, shell managers might prevent shell hooks from running before the first prompt draw, causing the starship CLI args like `--jobs=` to be empty and fail at argument parsing. To improve robustness, treat empty `--jobs` arguments as 0. This PR handles this with a new `parse_trim` function used for both `--jobs` and the prior `--cmd-duration` parsing.
Related #3480

fix: ignore empty `--jobs` argument

---

docs/config/README.md
src/configs/gcloud.rs
src/modules/gcloud.rs

Add option `gcloud.project_aliases`, replace the GCP project name with configured alias, like `gcloud.region_aliases`. 
Closes #3538 
related configs:
```
❯ cat ~/.config/gcloud/active_config
minecraft
❯ cat ~/.config/gcloud/configurations/config_minecraft
[core]
account = example@example.com # replaced
project = minecraft-abekoh
[compute]
zone = asia-northeast1-b
region = asia-northeast1
❯ cat ~/.config/starship.toml
[gcloud]
format = 'on [$symbol($project)]($style)'
[gcloud.project_aliases]
minecraft-abekoh = "mc"
```

Add option gcloud.project_aliases

---

src/modules/localip.rs

Disable localip module default as it is documented.
As it is documented, the `localip` modules is disabled by default, but it is not actually disabled if we have no config.
https://github.com/starship/starship/blob/5a26355b0e8211b42832eaaad205c8f2541abc20/src/configs/localip.rs#L14-L23

fix(localip): disable localip module default

---

docs/config/README.md

Fixed typo.
```
seperator -> separator
```

docs: fix typo in config/README.md

---

docs/config/README.md

I misread the lowercase l as uppercase I because all other headings are uppercase.

docs: Rename Heading localip -> Local IP

---

docs/config/README.md

The chapter is currently sorted in the wrong place.

docs: "Local IP" chapter in alphabetical order

---

.dprint.json

Removes vuepress generated files from dprint formatting to avoid a potential OOM condition when running dprint locally.
Avoids triggering https://github.com/dprint/dprint/issues/472

fix: Exclude vuepress output from dprint

---

docs/config/README.md
src/modules/aws.rs

Adds guard, and relevant tests to only display AWS data if either a credential_process is defined in `.aws/config` or there are valid credentials for the same profile in `.aws/credentials`.
Closes #3457
Closes #2184
Closes #2871
Closes #2461
I've tested these changes on WSL2 (Ubuntu 18.04 and 20.04)
I'm not sure if this change requires the documentation to be updated.
If so, please let me know where I should change it.

fix(aws): Only display AWS if there are credentials configured

---

docs/config/README.md
src/modules/kubernetes.rs

Added the `user` and `cluster` field for kubeconfig context. It's my first contribution to open source hehe.
Closes #3487 
I followed the CONTRIBUTING.md

feat(kubernetes): add context user and cluster variables

---

Cargo.lock
Cargo.toml
build.rs
starship-res.rc
starship.exe.manifest

Add a Windows application manifest using [`embed-resource`](https://crates.io/crates/embed-resource). This should disable any Windows compatibility shims/switchback which could possibly slow down process startup, and also UAC virtualization for 32-bit, if anyone is still on 32-bit Windows that is.
Closes #3589

feat: Add a Windows application manifest

---

docs/config/README.md

This commit adds an entry for this option and a *details* section for its variables.
Thinking there was a bug in the formatting of git directories (my format was not respected), I realized that the option `directory.repo_root_format` was not documented. 
Also, the doc entry of `directory.repo_root_style` was not the actual behavior of the code. I update it.
Documentation changes. Doc rendering using `npm run dev` as shown above.

docs(directory): add missing doc on option directory.repo_root_format

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml

I noticed #3623 was green despite deprecation warnings from the rust compiler. This PR sets the `RUSTFLAGS` env var to `-Dwarnings` to make this fail in CI.
I also added some extra useful env vars used by some other rust projects to enable backtraces, increase cargo/rustup network retries and disable incremental compilation (less useful in a CI context, the cache action also sets this).
I did not add `-Dwarnings` to the deployment workflow to prevent it from breaking it. Furthermore, I also removed the cache action from `deploy.yml` because it is less useful in release builds, and it was still using the old cache action.
Closes #

ci: deny warnings, useful env vars, do not cache deploy

---

Cargo.lock
Cargo.toml
clippy.toml
src/context.rs
src/modules/directory.rs
src/modules/pulumi.rs

This PR replaces `std::fs::canonicalize` with `dunce::canonicalize` which will strip extended paths prefixes from verbatim paths if the paths also works without the prefix (long paths, reserved names). Paths without the prefix are more widely compatible.
Closes #3582

fix(windows): avoid verbatim paths

---

src/context.rs
src/formatter/string_formatter.rs
src/init/mod.rs
src/lib.rs
src/main.rs
src/module.rs
src/modules/custom.rs
src/modules/docker_context.rs
src/modules/pulumi.rs
src/modules/status.rs
src/utils.rs

This PR fixes the new Rust 1.59 compiler and clippy warnings. This release also adds `strip =` to release profiles in `Cargo.toml`, but this printed some warnings on macOS, so I've kept that as-is for now.
Closes #

refactor: fix new clippy/compiler warnings

---

src/main.rs

Currently, [starship will spawn a thread for each logical cpu core](https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html#method.num_threads). On systems with high core counts, this can be expensive.
Thus, limit the maximum core count to 8. This is still cheap if there is nothing to do, but it doesn't seem to performance when a high number of modules are enabled.
Right now, different thread counts can also be set with the `RAYON_NUM_THREADS` variable.
Related #3180

perf(rayon): restrict thread count

---

src/main.rs

Fixed typo.
```
Intialize -> Initialize
```

refactor: fix typo in main.rs

---

docs/installing/README.md

(it's true by default)
Closes #

docs: remove enableZshIntegration from homemanager installation

---

docs/config/README.md
src/config.rs
src/configs/git_status.rs
src/modules/git_status.rs

Because I/O is slow on Windows paths with WSL, add the option to render `git_status` with a Windows `starship.exe`. This is 10x faster. This still uses the linux starship config.
Closes #

perf(git_status): add option to use windows starship.exe to render in wsl

---

src/modules/rust.rs

Fix fixes a bug introduced in #3359, an override for `~/some/folder` was also used for `~/some/folder_with_suffix`. Not the first time that the difference of `Path::starts_with` and `str::starts_with` bites someone (`Path::starts_with` only matches full segments).

fix(rust): overrides should only check full segments

---

.github/workflows/deploy.yml

Changes the github release dependencies to include the notarization step so that notarized binaries get properly deployed
Closes #3714

ci: Correct dependencies for deploy workflow

---

install/install.sh

The installation script warns about `BIN_DIR` not being found in `$PATH` when the users pass a trailing forward slash.
This has been discussed in #1310, #1341, and #3486.
Closes #3493
As discussed in #1310, #1341, and #3486, we see that all users passed a trailing slash for `bin-dir`;`/usr/bin/`, `/c/Users/slapbot/starship/` and `"$HOME/.starship/bin/"`, respectively.
Since it is possible to have a trailing slash on a directory in `$PATH`, this prevents false-negatives when either or both directories contain a forward slash.
I couldn't find tests for this, but I'll be happy to add them if required.

refactor(install): remove trailing slash from `BIN_DIR`

---

install/install.sh

By default, unzip will attempt to query the user when files to be
installed already exist. Unfortunately, if the install script is run
with `sh -s`, unzip will read the remaining portion of the script as
input, resulting in a mess on the terminal.
This commit changes the unzip behavior to clobber existing files: this
already happens for platforms using tar, so it's not hugely breaking
(and I could find no evidence that we believe this is more likely to
cause issues on Windows)
Closes #3726

fix(install): Add -o flag to unzip to match tar

---

docs/.vuepress/config.js
docs/faq/README.md
docs/installing/README.md
docs/presets/README.md
docs/presets/bracketed-segments.md
docs/presets/nerd-font.md
docs/presets/no-runtimes.md
docs/presets/plain-text.md
docs/presets/pure-preset.md

- Use relative links: so they can be picked up by VuePress
- Remove [v0.45.0](https://github.com/starship/starship/releases/tag/v0.45.0) migration link from the sidebar: it's been almost 1.5 years
- Fix wrong zh-TW and zh-CN config position: previously they don't have any effect
- Refactor sidebar: languages besides the en-US now have "Advanced Installation" in the sidebar, also makes the sidebar more maintainable
- Enable VuePress evergreen: make the site smaller and faster
Regarding the sidebar refactor, this is the biggest part of this PR. Currently overrides are configured so existing sidebar items stay the same, but eventually the each translated pages should have the right title and then remove the override. [Refer to comments in the …

fix(docs): fix and cleanup VuePress config

---

docs/config/README.md
src/configs/aws.rs
src/modules/aws.rs

Add an aws.profile_aliases feature just like aws.region_aliases
AWS regions might have slightly irritating names, but it's nothing compared to the enterprise naming schemes sometimes applied to team profile names.
Added two simple unit tests, one with and one without similar alias used for region.

feat(aws): Add profile aliases

---

Cargo.toml

starship now uses `std::thread::available_parallelism` which stablized at Rust version 1.59.
https://github.com/starship/starship/blob/master/src/main.rs#L235
therefore, This PR sets MSRV to 1.59 to make sure everyone can build.
Does same thing as #3722 , but I deleted forked repository because I thought #3719 would be merged.
Let me know if my English is wrong in the comments with correct sentense. I will fix it quickly.
Closes #3716
Closed #3719

docs: Specify MSRV

---

src/modules/aws.rs

Making environmental values `AWS_REGION` overrides `AWS_DEFAULT_REGION`, if both values is existing.
Closes #3619

fix(aws): Make AWS_REGION orverrides AWS_DEFAULT_REGION (#3619)

---

docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/config/README.md
src/configs/haskell.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/haskell.rs
src/modules/mod.rs
src/utils.rs

Add Haskell module to detect the version of GHC and/or the selected Stack resolver.
Support one more popular industrial-strength programming language.
Fixes #1458
Fixes #2601
Tested by running it on my machine.
- I have GHC 9.0.2 installed (via GHCup) as a default GHC compiler.
- Stack is also popular among Haskellers: it manages GHC version itself, so [a resolver version (e.g. `lts-18.12`) determines a specific GHC version](https://www.stackage.org), and Stack will install it when necessary.
This is a standalone module and it does not affect other code.
(I don't have Linux and Windows environments at the moment.)

feat(haskell): Add Haskell module

---

Cargo.lock
Cargo.toml
src/bug_report.rs
src/main.rs

The bump to shadow v0.10.0 allow getting rid of the `Box::leak`-hack (https://github.com/baoyachi/shadow-rs/issues/86). I also needed to bump `git2` to v0.14.2 to make it build, which raises libgit2 to v1.4.
Closes #

build: bump shadow to 0.10.0 & git2 to 0.14.2

---

docs/config/README.md

The entry describing the container style config was missing backticks.
This results in a broken render as can be seen [here](https://starship.rs/config/#container).

docs: Fix entry for container config

---

.github/ISSUE_TEMPLATE/Bug_report.md
Cargo.lock
Cargo.toml
README.md
docs/README.md
docs/config/README.md
install/install.sh
src/bug_report.rs
src/init/starship.nu
src/utils.rs

This PR updates the nu init for the upcoming v0.60 release. `directories-next` is also replaced by `dirs-next` again to match nushell behavior.
Closes #1716
Closes #3526

fix(init): Change Nushell init for nu 0.60

---

docs/config/README.md
src/configs/aws.rs
src/modules/aws.rs

Add an option in the AWS module to force displaying AWS info, even if there is no credentials or credential_process defined for this profile.
The option is called: `force_display` and its default value is `false`.
When this option is set to `true` the profile info are displayed in the prompt even if there is no creds directly associated.
It's a kind of bypass of the feature merged in the PR #3504.
When leaved to `false` it doesn't change the behaviour: if no creds are found, no info are displayed in the prompt.
Closes #3762
After the PR #3504 has been merged, if there is no credentials nor credential_process defined for the profile, nothing is displayed. But I heavily use the `source_profile` feature for profiles. 
Example of `~/.aws/config` and `~/.aws/credentials`:
```ini
#~/.aws/config …
```

feat(aws): add option to force AWS display

---

src/init/starship.fish

To prevent initialization errors with older fish shell, I modified the way to generate random session keys.
`random` in older fish shell cannot generate random integers within the specified range, so executing `starship init fish | source` with fish shell will output some errors.
I modified the init script to generate random integers without range specification.
Session keys will be generated in the manner same as `src/init/starship.bash`.
Closes #3696

fix(fish): allow generating session keys in older versions of fish

---

docs/advanced-config/README.md
docs/config/README.md

Anchor in link was broken, I fixed it.
Edit: change «when there is a csproj file» to «when there is a `.csproj` file», and add backticks forgotten around a `true`.

docs(dotnet): fix link to Microsoft’s documentation for Dotnet

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/mod.rs
src/configs/spack.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/spack.rs

Adds support for the [Spack](https://spack.io/) package manager, displaying the name of the spack environment based on `$SPACK_ENV` env variable.
Closes https://github.com/starship/starship/issues/3446
Tested on Fedora 35 using Gnome Terminal. Wrote unit tests to test rendering of the module based on presence of `$SPACK_ENV` env variable.

feat(spack): Add `Spack` module

---

src/init/starship.bash

Without `checkwinsize` `bash` may not properly set `$COLUMNS`, which is passed along by the bash init for the terminal width.
I can't actually reproduce the bug by disabling `checkwinsize`, but it reportedly fixes #3793, and it doesn't seem to break anything.
Closes #3793

fix(bash): ensure `checkwinsize` is enabled for `$COLUMNS`

---

src/init/starship.nu

Clap (?) doesn't like to parse negative integers like this: `--status -1`.
Changing it to `--status=-1` fixes that.
With this change the nu script also follows the fish and powershell script more closely. 
This fixes https://github.com/nushell/nushell/issues/5074

fix(nu): Use `=` instead of space to pass command line parameters

---

src/modules/docker_context.rs

The [documentation](https://starship.rs/config/#docker-context) states that
> The docker_context module shows the currently active [Docker context (opens new window)](https://docs.docker.com/engine/context/working-with-contexts/) if it's not set to default [...]
This PR checks for the "default" docker context and only shows the module, if the context is not "default", in agreement with the documentation.
The PR checks the docker context, which was discovered earlier, for the word "default".
Closes #3803
I have tested the before/after behavior by running `test_docker_context_default`, and also in a directory with a Dockerfile where I ran into the issue before.

fix(docker_context): ignore the "default" context

---

src/modules/gcloud.rs

This PR changes the gcloud module config file parsing to use the `rust-ini` library. This simplifies the code and improves the handling of leading whitespace characters.
Closes #

refactor(gcloud): improve parsing of config files

---

.codecov.yml
.github/workflows/workflow.yml

This adds code coverage collection to the CI configuration, and uploads it to [codecov.io](https://app.codecov.io/gh/starship/starship/). 
Personally I prefer just having codecov status checks instead of the detailed coverage comments, so I disabled them. I'm happy to change that again if preferred. 
While touching that, I removed `-Z unstable-options` since `--include-ignored` now works without it.

ci: add test coverage reporting with codecov

---

.github/config-schema.json
docs/config/README.md
src/configs/custom.rs
src/modules/custom.rs
src/modules/mod.rs

Various changes to custom modules:
- Add `ModuleRenderer` support
- Add support for shells that expect script input as arguments (cmd, nu)
- Add an option to choose between using an argument and stdin script input
- Add timeout support (this should reduce the impact of infinite recursion if the prompt gets rendered again in custom modules)
- Timeouts can be disabled with a new option
- Support using `bool`s for `when` (to simplify the tests, I could also remove this again)
- Set cwd for the external commands
- Rename the `files`… options to align with other modules, with an alias for the old names
- Reduce duplication between windows/non-windows
Closes #2066
Closes #2182
Closes #3601
Related #2624
Related #2629
Closes #3801
Closes #2965
Closes #3445

refactor(custom): various improvements

---

Cargo.toml
src/modules/cmd_duration.rs

the notify-rust has some very cryptic compilation error on nix and darwin. (reference issue https://github.com/NixOS/nixpkgs/issues/160876)
In the meanwhile, version has been moved forward in nix to not penalize linux users.
Hopefully we can find the source of the error, but in the meanwhile, making this dependency optional is very helpful!
Thank you again for your terminal! (going a month without it, feels like going back to the stone age #addicted)
Closes #
I ran `cargo test`, `cargo test --no-default-features`, `cargo clippy --all-features --all-targets` and couldn't find problems with it, let me know however if you need changes.

feat(cmd_duration): make notify feature optional (compat with nix darwin)

---

docs/config/README.md

I forgot documenting `ignore_timeout` in #3829.
Closes #

docs(custom): add missing `ignore_timeout` option documentation

---

src/modules/git_status.rs
src/test/mod.rs

This PR changes the configuration for the fixture git repos to make git issue `fsync`. This enables both the just-released [`core.fsync`](https://github.blog/2022-04-18-highlights-from-git-2-36/) option and the older, now-deprecated `core.fsyncObjectFiles` option. Windows git tests in CI now also seem to work without `barrier` sleep calls. Hopefully, this will reduce intermittent git test failures.
Closes #

test(git): enable `fsync` for git operations

---

.github/config-schema.json
docs/config/README.md
src/configs/aws.rs
src/modules/aws.rs

Adds a missing space to the duration variable in the AWS module.
Styling
before:
after:
I have manually added the format string to my toml config
```toml
[aws]
format = "on [$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"
```
Hopefully, I have updated everything, documentation and tests.

chore(aws): adds space to the duration variable

---

Cargo.lock
Cargo.toml
src/modules/utils/directory_nix.rs
src/modules/utils/directory_win.rs

#2791 reminded me I wanted to replace `winapi` with `windows` at some point. `windows` has a higher API coverage (this PR removes a manual binding, a number of arguments are now marked as constant), better type safety, built-in error handling facilities, and it is officially backed by Microsoft.
The type safety isn't complete (constant are typed, but most function arguments are just `u32`), so some breaking changes could still happen, but I feel like the crate has already matured somewhat.
The only functional changes are that the exit code of the first `GetFileSecurityW` is verified for `ERROR_INSUFFICIENT_BUFFER` and `STANDARD_RIGHTS_READ` is replaced with `TOKEN_READ_CONTROL` which is supposed to do the same thing but has the expected type (both are accepted arguments). In addition, …

refactor(windows): replace winapi with windows

---

src/context.rs
src/modules/haskell.rs
src/modules/nodejs.rs
src/modules/package.rs
src/utils.rs

Have refactored the package module to improve performance. Before this
change the module would try to open every single file that could contain
some package information until it found a valid version. This resulted
in a lot of unneeded disk IO. Have added a new fn, `read_file_from_pwd`
that uses the current context to check if that file already exists and
fast failing if it doesn't. 
From my local testing this speeds up the package module from taking ~1ms to ~50µs in an empty directory.

perf(package): only try to read files that exist

---

docs/README.md
docs/config/README.md

Have added so additional spaces around the vuepress markers, `:::`, to
ensure that the don't get included in the line above and below and cause
formatting errors in the translated versions of the documentation.
Closes #3836
See also https://starship.rs/it-IT/#elvish

docs: Fix spacing for translations

---

.github/config-schema.json
docs/config/README.md
src/configs/git_branch.rs
src/modules/git_branch.rs

When I was implementing #3883, I noticed the `$remote` variable referenced in the default `git_branch` module format string does not exist. I replaced it with `$remote_branch` (though I am not sure what the original intent was) and simplified the format string by merging the remote and local style segments.
I also added a test because there wasn't any test for this feature.
Closes #

fix(git_branch): correct variable name for remote branch

---

.github/workflows/deploy.yml

Explicitly provide a repo owner/name so that the Crowdin PR could be merged by its branch name.
Address failure in CI where `gh` was unable to determine the base repo:
https://github.com/starship/starship/runs/6181720956?check_suite_focus=true#step:2:10

ci: explicitly provide repo owner/name when merging PR

---

src/main.rs

The current version of starship will fail to run `starship module --list`, citing that a module name was not given. Here is the code currently on `master`:
```rs
/// The name of the module to be printed
#[clap(required = true, required_unless_present = "list")]
name: Option<String>,
```
`required_unless_present` itself implies `required`, but by additionally providing `required` it is superseded and does nothing. I have fixed that issue as well as changing the syntax to match [clap's documentation](https://docs.rs/clap/3.0.0-beta.2/clap/struct.Arg.html#method.required_unless_present).
For those interested, I also started a [discussion](https://github.com/clap-rs/clap/discussions/3658) on clap's repo about this, as I was surprised this doesn't result in an actual error.

fix(module): list option not working

---

docs/.vuepress/public/presets/toml/pastel-powerline.toml

This change adds symbols for C, Docker, Elixir, Elm, Go, Haskell, Java,
Julia and Nim.
n/a
I have tested that configuration by using it as my `~/.config/starship.toml`.

docs(preset): Add more symbols to Pastel Powerline preset

---

src/configure.rs
src/main.rs

Redoes error handling around `starship config` so that it will not panic if the editor cannot be found on the path.
Closes #3758
I have tested this by hand, but I'd like to insert an automated test in here (since this is not the first time we've had this issue). The problem is that get_editor_internal relies on global state (`env::var`) without an obvious way to inject artificial values, so I'm not sure what the best way is to rearchitect this.

fix: Do not panic in config if editor not found

---

docs/config/README.md
src/modules/package.rs

This PR adds a function to the package module to extract the package version from a [PEP 621](https://peps.python.org/pep-0621/) compliant `pyproject.toml`
Closes #3949 
Ran `cargo test`, `cargo clippy --all-targets --all-features` and `cargo fmt`

feat(package): Extract package version from PEP 621 compliant pyproject.toml

---

src/modules/custom.rs

As the test that ensures custom commands are still run if a timeout is set have been timing out on Windows CI, increase the timeout duration to avoid intermittent test failures.
Closes #

test(custom): increase timeout in timeout test

---

Cargo.lock
Cargo.toml
docs/config/README.md
src/modules/rust.rs

#559 was approved and then sat around waiting to be merged for over 18 months. I'm not sure what happened, but I want to extend my sincerest apologies to for @qryxip for the state of that PR. We clearly should have merged it before things got this bad.
I attempted to rebase this PR onto master several times, but to no avail: the PR comes from **before the format strings change**, so there were some incompatibilities with how it was structured.
This PR is an attempt to make things right: I have manually ported over the changes made by @qryxip in #559. Because they would have potentially constituted breaking changes (I'm not sure what we consider breaking right now), I have segmented off two code paths. The old codepath uses exactly the same code as is present on master. The new code path, …

feat(rust): Option to display toolchain names by qryxip

---

README.md
docs/README.md
install/install.sh

The old nushell init approach caused the init only to update if the shell was opened a second time due to how nu handles sourcing (https://github.com/starship/starship/pull/3773#issuecomment-1076625914).
Thanks to @ajeetdsouza (thanks for notifying me!), there's a different approach that doesn't have this issue, by utilizing the nushell env file: https://github.com/nushell/nushell/issues/4773#issuecomment-1106114104
The default env file also contains some prompt-related configuration, so using it for this seems reasonable. The supported nushell version needed to be raised to 0.61, because that version introduced the env file feature.
Closes #

fix(nu): use the most recent starship init

---

.dprint.json
docs/README.md

~It seems like dprint has had a formatter behavior change~ (Or perhaps just the #3908 master-conflict-merge?). Fix the formatting error and also upgrade the dprint plugins (`dprint config update && dprint fmt`). Because the upgrade changes the default typescript indention width to 2, also set it back to 4 to avoid unnecessary changes.
https://github.com/starship/starship/pull/3968#issuecomment-1119697272

chore(dprint): fmt & upgrade plugins

---

.dprint.json
.github/config-schema.json
docs/README.md
docs/config/README.md
src/configs/go.rs
src/modules/golang.rs

- Show Go module if `go.work` file is found in the project's root directory
- Earlier only these files were being checked: `"go.mod", "go.sum", "glide.yaml", "Gopkg.yml", "Gopkg.lock", ".go-version"`. With this change, starship also checks for `go.work` file
- Golang has introduced the concept of [workspaces](https://go.dev/ref/mod#workspaces) since [v1.18](https://go.dev/blog/get-familiar-with-workspaces) to let users work on multiple modules simultaneously.
- It works by creating a `go.work` file in the project root directory. There is no `go.mod` file in project root directory; they are only present in respective module directories.
- This change effectively adds `Go v1.18` support to starship

feat(go): check for go.work file to show Go module in prompt

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml

Sets MACOSX_DEPLOYMENT_TARGET to 10.7 to force backwards compatibility for x64 MacOS builds.
I have tested this on #3945 and it does resolve the error. I've also tested it for aarch64 builds and it doesn't screw up cargo at all (a binary is generated which correctly targets MacOS 11.0 even though the deployment target is set lower). I'm assuming that non-MacOS builds won't look at this variable, so it shouldn't affect them.
In the absence of this variable, [rust is supposed to target 10.7 as a minimum version on x64 anyways](https://github.com/rust-lang/rust/blob/6af09d2505f38e4f1df291df56d497fb2ad935ed/compiler/rustc_target/src/spec/apple_base.rs#L68), and it's not doing so right now. ~I was unable to find anything in [the documentation on the MacOS …

ci: Set MacOS deployment target at 10.7 in CI

---

.github/workflows/crowdin-pretranslate.yml

Adds a Github CI action which fires every 24 hours, running "Pre-Translate with Translation Memory" on the CrowdIn project.
Closes #3790
The action has been run against a test repository which triggered on push, so I've created a lot of pre-translate requests, all of which appear to have gone through. It seems that if there have been no translations suggested on Crowdin since the last pre-translate, the translation is a no-op, so there's not a great way for me to guarantee it's working with this repo until we get some more suggestions on Crowdin.

ci: Add daily Crowdin Pretranslation trigger

---

.github/workflows/crowdin-pretranslate.yml

Turns out you need to name the `api_key` the right thing in order for the CI to work, otherwise it just fails :(
Also update the Action from v0.1.0 to v0.1.1, which will correctly call `setFailed` if the GitHub action fails, instead of printing error messages but then pretending everything worked fine.
Closes #

fix(ci): Version bump and fix Crowdin Pretranslate

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/daml.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/daml.rs
src/modules/mod.rs
src/modules/package.rs

- Add a `daml` module that reads the currently used SDK version for a project using the one indicated in the `daml.yaml` file or overrides it with `DAML_SDK_VERSION`
- Add Daml support to the `package` module (uses the `version` key in the `daml.yaml` file)
Closes #3903
Apart from the relevant automated tests, I opened a sample Daml project and touched the `sdk-version` and `version` keys in the `daml.yaml` file, as well as the `DAML_SDK_VERSION` environment variable to see whether the changes were picked up correctly. Also went into a sub-directory to see whether the information disappeared as expected. I further made sure that the example in the documentation works, as well as checking that every option works as expected.

feat: Add support for Daml

---

src/formatter/string_formatter.rs

In addition to `map` also handle escape for `Text` segments  in meta variables in `parse_format` for `map_meta` akin to the handling for regular `map`. I'm not very familiar with this area of the code, but it seems to work.
Closes #3222

fix: escape text segments in meta variables

---

Cargo.toml

Bumping the MSRV to 1.60 due to our dependency on git2
Related to #4022

chore: Bump MSRV in Cargo.toml

---

Cargo.lock
Cargo.toml
src/modules/memory_usage.rs

This PR replaces `sys-info` with `systemstat`.
systemstat is still at 0.1 (which is why I specified the version with `=`), but I feel much better about the codebase (it's much less likely to get us another rustsec warning) and the support for different operating systems is comparable to sys-info.
While working on this, I also tried improving the test coverage, but it still doesn't verify the complete module outputs.
Related?: #3951

refactor(memory_usage): replace `sys-info` with `systemstat`

---

.github/config-schema.json
docs/config/README.md
src/configs/kubernetes.rs
src/modules/kubernetes.rs

Implemented user alias resolution in the kubernetes module as it has been done for context aliases aswell. This has been discussed in #3870. 
Likewise the kubernetes user can be aliased using regular matching, regex matching and regex replacement.
As mentioned in the documentation update the following configuration example is now possible:
```toml
[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
[kubernetes.user_aliases]
"dev.local.cluster.k8s" = "dev"
"root/.*" = "root"
```
Closes #3870

feat(kubernetes): add user alias

---

src/init/mod.rs

Changed nushell init to use standard path to starship instead of looking for cygpath
Closes #3997 
Closes #4025
It is my opinion that Nushell should be treated as a native Windows shell by default, since it is. If a user wishes to use nu on some unix-y layer on Windows, then I imagine they can figure out how to modify the init script appropriately (it would be no different to pwsh in that regard)

fix(nu): don't use `cygpath` for starship binary path in init

---

.github/config-schema.json
docs/config/README.md
src/configs/character.rs
src/modules/character.rs

Adds separate symbols for the rest of the missing vi keymap modes for Fish shell. I don't know how to do it for zsh because it's much more complicated for zsh: https://github.com/starship/starship/issues/625#issuecomment-732454148
Currently it shows the insert mode icon for any vi mode other than normal which is incredibly confusing and not correct.
Closes #625 
I don't have a Linux or Windows machine to test on.
I couldn't find the right place to update the documentation. Please inform me where and I'll update it.

fix(fish): add proper vi mode detection for fish shell

---

install/install.sh

If the install script used `sudo` to install Starship from a tarball, it left the file with what the userid/groupid was in the tarball. That user/group might or might not actually exist. This change fixes that.
We now use the `-o` flag when untarring, to force tar to use the current user's userid/groupid instead of whatever is in the tarball. That is on by default for non-root users, but not for root.
Closes #4039
The script claims to support FreeBSD but doesn't - it can't find a binary to download.

fix(install): ignore tarfile ownership values when installing as root

---

.cargo/audit.toml

One of the warnings has been un-withdrawn, and the other might follow at some point (because they also called `tzset`).
This reverts commit b1ad1c79f53fcc27373cd6128191a867b50fb579.
Closes #

chore(audit): add back `RUSTSEC-2020-0071` & `RUSTSEC-2020-0159` to ignore list

---

Cargo.lock
Cargo.toml

A dependency upgrade, no breaking changes.

build: upgrade open for non-blocking 'open::that()' on linux

---

docs/config/README.md

Small typo in docs. Starship is great :+1:

docs: Fix typo in custom command docs

---

.github/config-schema.json
docs/config/README.md
src/configs/character.rs
src/modules/character.rs

Have switched all vi/vim symbols to have the same prefix 'vim'. To
preserve backwards compatibility with existing configs I have added an
alias for the previous config name, I left the existing test to check this.
Closes #4074

fix(character): Standadise Vim config names

---

.github/workflows/release.yml
README.md

Adds a release step for publishing Starship to the [winget](https://github.com/microsoft/winget-cli) package manager for Windows
Thought I would kick this off now that #4031 is complete. Still requires an initial [`wingetcreate new`](https://github.com/microsoft/winget-create/blob/main/doc/new.md) once #4029 releases so that the `wingetcreate` tool can download and analyze the MSI installers and generate a manifest that this pipeline step can update thereafter. After that, testing this pipeline step will become possible.
Closes #1295

feat(winget): Add support for winget package manager

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/mod.rs
src/configs/raku.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/raku.rs
src/utils.rs

Implement a module to support [Raku](https://www.raku.org/) programming language, it prints the version (and the vm type it's built on) for Raku, for example: `🦋 v6.d-moar`. 🦋 (a butterfly) is Raku's logo called Camelia.
I followed the checklist from [CONTRIBUTING.md](https://github.com/sergot/starship/blob/master/CONTRIBUTING.md#new-module-checklist).
As a developer who likes to code using Raku language, I'd like to see the current version of raku in the command line.

feat: add Raku module

---

Cargo.lock

Running `cargo update` removes the deprecated `tempdir`crate from the dependency tree.
Closes #3952

build: run `cargo update`

---

.github/workflows/release.yml

The upload of MSI files failed in the last release. One issue that both of the MSI had the same name. For some reason, the git checkout was also causing some issues with the upload (I did some testing, but with `gh` instead of `softprops/action-gh-release@v1` because it was easier). `softprops/action-gh-release@v1` is supposed to be able to recognize the repo without any checkout via the GitHub env.
Closes #

ci(release): fix msi upload

---

.github/workflows/release.yml

Fix issues encountered during the release of v1.9.1:
- Draft release couldn't be found by `mislav/bump-homebrew-formula-action`
Fixed by providing a GitHub token with permissions to view draft release
- Draft release was not updated by `softprops/action-gh-release`
Fixed by publishing the draft release before adding artifacts

ci: fix release hiccups caused by draft release

---

.github/config-schema.json
docs/config/README.md
src/configs/pulumi.rs
src/modules/pulumi.rs

I noticed the module was slowing down the prompt a bit on a system with networked drives. This PR disables this upwards discovery by default to avoid this and adds an `search_upwards` option to revert to the old behavior. If this is considered a breaking change, I can also change the default value to `true`.
Closes #

perf(pulumi): allow disabling upwards discovery

---

.github/config-schema.json
docs/config/README.md
src/configs/kubernetes.rs
src/modules/kubernetes.rs

Have added configuration options to the k8s module to allow activating
the module only in directories that contains certain files or folders.
To ensure this is backwards compatible and because there are not really
any standard files or folders for Kubernetes I have set the defaults to
empty and will activate the module for all directories.
Closes #4126

feat(k8s): Add folder detection to the k8s module.

---

Cargo.lock
Cargo.toml
src/modules/directory.rs

adjust starship code to introduced breaking change
Closes #4151
Closes #4153

build: bump path-slash from 0.1.4 to 0.2.0 

---

docs/advanced-config/README.md
src/init/starship.lua
src/init/starship.ps1

Enables both left and right transience for Cmd.
Enables only left transience for PowerShell.
Related to #888
[![asciicast](https://asciinema.org/a/Vl7k1E3IpRFBvpV33Y1h1OyUv.png)](https://asciinema.org/a/Vl7k1E3IpRFBvpV33Y1h1OyUv?autoplay=1)

feat: Enable transience for Cmd and PowerShell

---

docs/config/README.md
src/context.rs
src/modules/directory.rs
src/modules/nodejs.rs

This adds "negative extensions" to `detect_extensions`. A negative extension, signified by starting with a "!" character, will prevent a module from triggering.
You can now add "negative extensions" to any `detect_extensions` variable. If any file is found that matches any negative extension then the module will not be triggered.
I also added support for multi-part extensions like "tar.gz" and "video.ts" because for my particular use case I need to prevent the Node module from triggering on "video.ts" files.
Closes #4033
Aside from adding unit tests, I have also tested this for real with `detect_extensions = ["ts", "!video.ts"]` in my config and verified that after adding `"!video.ts"` the directory was no longer showing up as a Node project in my prompt.

feat: Add the ability to have some file extensions *prevent* a module from triggering

---

docs/advanced-config/README.md
src/config.rs

Add support for `blink`, `hidden`, and `strikethrough` format strings. The underlying `ansi_term` library supports them on supported terminals; this PR merely exposes those options.
I find it useful to occasionally use blinking text in my prompts to _really_ get me to pay attention, so it would be nice to be able to style things using blinking text. I noticed strikethrough and hidden could be added trivially, so I threw them into the mix too.
* I noticed that iTerm supports blinking and strikethrough, but does _not_ support hidden text (https://gitlab.com/gnachman/iterm2/-/issues/4564).
* Terminal.app _does_ support hidden text, but does not appear to support strikethrough text.
* Tested with Gnome Terminal; supports all three of `blink`, `hidden`, and `strikethrough`
* Tested both in the …

feat: Add support for blink, hidden, and strikethrough styles.

---

.cargo/audit.toml
Cargo.lock
Cargo.toml

This PR bumps chrono to [v0.4.20](https://github.com/chronotope/chrono/releases/tag/v0.4.20), which fixes RUSTSEC-2020-0159. In addition, restrict the default feature set to remove the "oldtime" feature. This would also remove the dependency on time v0.1 (solving #3163), if the (default) feature wasn't getting enabled via systemstat. But their next release is going to replace chrono with time v0.3, so this ensures its update will get rid of that.
Closes #3166
Closes #4234

build: bump chrono from 0.4.19 to 0.4.20

---

Cargo.lock
Cargo.toml
docs/config/README.md
src/context.rs
src/modules/directory.rs
src/modules/git_branch.rs
src/modules/git_commit.rs
src/modules/git_state.rs
src/modules/git_status.rs
src/modules/hg_branch.rs
src/modules/hostname.rs

This PR replaces the `libgit2`-based `git2` crate with the `gitoxide` `git-repository` crate.
~~In addition, add some ownership-based trust handling to the `git_status` and `git_metrics` modules with `git-sec`.~~
In addition, improve the `git_branch` output by preferring the reference name over plain `HEAD`.
Closes #4022
Closes #3482
Closes #4131

feat(git): replace `git2` with `git-repository`

---

src/modules/aws.rs

> According to [current AWS Documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html), the CLI actually looks for the `AWS_SHARED_CREDENTIALS_FILE` variable and not `AWS_CREDENTIALS_FILE`.
This is #4192, but with fixed tests and support for `AWS_CREDENTIALS_FILE` to avoid the possibility of breaking something.
Closes #4192
Closes https://github.com/starship/starship/issues/4167
Closes https://github.com/starship/starship/issues/4213

fix(aws): support official `AWS_SHARED_CREDENTIALS_FILE` variable

---

.github/workflows/release.yml
Cargo.toml

Use `strip = true` in `Cargo.toml` to strip the release binaries instead of manually calling `strip` manually in CI.
In the past, this printed some warnings on macOS, but I've fixed the issue in rust 1.63 (which already seems to be public in rustup).
Closes #

build: use cargo for stripping release binaries

---

Cargo.lock
Cargo.toml

Even though that theoretically makes some filesystem iterations slower,
I don't think it matters much for typical repositories, so this fix
could be permanent.
One can explore to have this issue fixed upstream in `jwalk` as well
and I will bring it up there provided I can make a minimal reproducible
example.
With this fix, `STARSHIP_NUM_THREAD=1 starship prompt` won't hang anymore, 
which resolves #4251.

fix: Disable multithreading in `jwalk` (via `gitoxide`) as workaround for #4251

---

Cargo.lock
Cargo.toml
src/modules/git_commit.rs

This release comes with lenient configuration handling by default,
allowing to open repositories even their configuration values are
invalid (even for git), as long as there are viable defaults.
Furthermore this release adds the ability to open submodule repsitories.
Fixes https://github.com/starship/starship/issues/4266 and
fixes https://github.com/starship/starship/issues/4272
addresses performance in #4275

fix(git): upgrade `gitoxide` to v0.21

---

.github/config-schema.json
docs/config/README.md
src/configs/git_commit.rs
src/modules/git_commit.rs

I noticed another major difference with the old git tag implementation is that only exact matches were considered, whereas this new one was looking at up to 10 commits. This restores performance to previous levels.
I also added an option `tag_max_candidates` to restore the previous behavior.
Closes #4275

perf(git_commit): only use exact match for tag by default

---

Cargo.lock
Cargo.toml
build.rs

Rust 1.61 had some lifetime-changes related to `io::stdout`. Rust 1.59 should be supported again with the next shadows-rs update.
Closes #4268

chore: support rust 1.59 again

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml

Adding icons for the nerd font preset for `lua`, `rlang`, and `ruby` modules. Also moved the `spack` module to the end to keep it alphabetized.

docs(preset): Add more icons to nerd font preset

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml

Update the Nerd Font symbol used for nix_shell to use the Nix project logo, instead of the similar looking snowflake.
The current snowflake symbol is an approximation for the real Nix project logo. Nerd Fonts includes the actual logo so we should use that instead. I couldn't find an exact release date for its inclusion in Nerd Fonts but it has been present in the Nerd Font codebase for at least 5 years, so this should be available for users on any reasonably recent Nerd Fonts version.

docs(preset): Update nix_shell nerd font icon

---

Cargo.lock
Cargo.toml
src/context.rs

Use the fixed `git-revision` crate via Cargo.lock to fix https://github.com/Byron/gitoxide/issues/503 .
Closes #4291

build: gitoxide upgrade

---

.github/workflows/workflow.yml

Dependabot PRs are triggering both `push` and `pull_request` events. Avoid this by only running `push` for `master`.
Closes #

ci: avoid running tests twice for dependabot prs

---

src/init/starship.ps1

If the stdout buffer was completely filled while `StandardError.ReadToEnd()` was running, a deadlock could have occurred. Use asynchronous methods instead which don't have this issue: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-6.0#remarks
Closes #

fix(pwsh): avoid potential deadlock in init

---

Cargo.lock
Cargo.toml
src/context.rs

Bumps [git-repository](https://github.com/Byron/gitoxide) from 0.23.1 to 0.24.0. It just required a small one-line change.
- [Release notes](https://github.com/Byron/gitoxide/releases)
- [Changelog](https://github.com/Byron/gitoxide/blob/main/CHANGELOG.md)
- [Commits](https://github.com/Byron/gitoxide/compare/git-repository-v0.23.1...git-repository-v0.24.0)
Closes #4390

build: bump git-repository from 0.23.1 to 0.24.0

---

docs/config/README.md

The Clojure tools.deps build file is called `deps.edn`, not `.deps.edn` (with a dot at the beginning). The Starship code itself looks for the correct file name, the typo is only in the docs.
I replaced `.deps.edn` with `deps.edn` in the `docs/config/README.md` file. I did NOT replace it in any of the translated files, since, if I understand https://github.com/starship/starship/blob/d93074d0569db4bafb1788aa3f39136b734b5370/CONTRIBUTING.md#crowdin-translated-pages correctly, that could cause merge problems.
If you need someone to update the Crowdin files after this is merged, I can do that.
This fixes a minor, but slightly confusing, typo in the Java identification docs.
This has not been tested, but I'm not sure tests are warranted in this case.

docs(java): Fix typo in file detection list

---

Cargo.lock
Cargo.toml
src/main.rs
src/print.rs

This PR updates clap to v4. I removed the exact-match requirement for the version, because the `unstable-v4` feature isn't required or available anymore, and handled a few renamings. I also amended the MSRV to match the new clap version requirement of rust 1.60.
Closes #

build: bump clap from v3 to v4

---

Cargo.lock
Cargo.toml
src/modules/utils/directory_win.rs

Bumps [windows](https://github.com/microsoft/windows-rs) from 0.39.0 to 0.42.0.
- [Release notes](https://github.com/microsoft/windows-rs/releases)
- [Commits](https://github.com/microsoft/windows-rs/compare/0.39.0...0.42.0)
It looks like the major changes in `windows 0.40` were reverted. Now only a small single-line in `AccessCheck` is required.
Closes #4382
Closes #4399
Closes #4412

build: bump windows from 0.39.0 to 0.42.0

---

src/modules/directory.rs

The `[directory]` config values for either `truncate_to_repo` or `repo_root_style` are evaluated before attempting to get the git repo for a given directory. 
This change solves the performance issues with traversing large directories (particularly NFSs), when you've explicitly opted out of git status based formatting on the path.
This change stems from my discussion here https://github.com/starship/starship/discussions/4363 as well as the https://github.com/starship/starship/issues/4352#issuecomment-1245312472 in the feature request for disabling modules for specific directors. #1891 is also similar, WRT performance issues on network drives.
n/a
Existing tests and documentation are still valid and should not require a change.

perf(directory): Skip repo resolution if unused by directory config

---

docs/config/README.md
src/modules/status.rs

This PR adds formatting of the `pipestatus_separator` string in the "status" module before `pipestatus_separator` is used to join the pipestatus segments.
The `$style` variable can also be used in the format string, though I did not include the other variables as they seem irrelevant for formatting the pipestatus separator.
I could not find a way to format the pipestatus separator, so it sticks out from the rest of the status segments when they have a background color.
before:
with status config:
```toml
[status]
style = "bg:57 fg:255 bold"
format = '[ $symbol $common_meaning$signal_name$maybe_int ]($style)'
disabled = false
pipestatus = true
pipestatus_format = '[ \[]($style)$pipestatus[\] => $symbol $common_meaning$signal_name$maybe_int ]($style)'
```
and after:
with the added status …

feat(status): Support formatting of pipestatus separator

---

docs/config/README.md

The custom shell example `custom.foo` does not work. A correct equality check using the shell builtin `test` command is `test "a" = "b"` and not `test "a" == "b"`.
Fix wrong docs.
None
I tested the `custom.foo` example using `zsh` on MacOS.

docs(custom): use single equal sign for 'when' clause of 'custom.foo' example

---

.github/config-schema.json
docs/config/README.md
src/configs/buf.rs
src/modules/buf.rs

This change adds a trailing whitespace character after the printed version to align with behaviour of other modules. I've used the configuration for the `node` and `bun` modules as reference points.
Additionally:
- Updated documentation to specify `version` instead of incorrect `buf_version`
- Use bison emoji in-line with documentation.
The lack of trailing whitespace leads to rendering error when used with other modules.
Currently `buf` version is printed as:

fix(buf): fix spacing & harmonize docs with actual configuration

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/meson.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/meson.rs
src/modules/mod.rs
src/modules/utils/mod.rs
src/modules/utils/truncate.rs

Adds a Meson Developer Environment indicator, if the `$MESON_DEVENV` and `$MESON_PROJECT_NAME` variables are set.
Inside a `meson devenv`, the prompt will include the current Meson project name, in similar fashion to a container. The name is retrieved from the `$MESON_PROJECT_NAME` variable.
A meson dev environment changes some environment variables for testing an application without installing to the root system. A full list of changes can be found at https://mesonbuild.com/Release-notes-for-0-58-0.html#developer-environment
Since variables such as the system PATH are being modified, I believe it is necessary to show that I am using a custom environment.
You can think of this as similar to a Python virtual environment, and how that is supported in Starship.
I use Linux primarily, and …

feat(module): Add a meson devenv indicator

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/.vuepress/public/presets/toml/pastel-powerline.toml

Update the following presets with the nerd font for Scala:
* nerd-font-symbols.toml
* pastel-powerline.toml
For completeness Scala is a supported module.
Tested both presets on a Scala project.

docs(preset): update presets with Scala nerd font.

---

Cargo.lock
Cargo.toml

`fs-walkdir-single-threaded` was replaced with an opposite `fs-walkdir-parallel` in the gitoxide update which is now part of the default `max-perfomance` feature level. As far as I know it's not possible to disable a single feature from a set, so to fix this and still benefit from most of the performance improvements, I've basically pulled in #4334. Alternatively, for the time being, just enabling `max-perfomance-safe` would likely be sufficient.
Closes #4480

build(deps): update gitoxide crates

---

src/init/starship.nu

The -c parameter has been removed through nushell/nushell#6651

fix(nu): remove -c parameter from `term size`

---

.github/config-schema.json
docs/config/README.md
src/configs/status.rs
src/modules/status.rs

The symbol of the status module was provided by the multiply-emoji (`✖️`). This PR replaces it with the "cross mark" emoji `❌`. It is a better fit semantically, and the multiplication emoji misrenders as a plus on some versions of Windows 11 (#4345). 
Closes #4345

fix(status): replace multiply with cross mark emoji

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/mod.rs
src/configs/opa.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/opa.rs
src/utils.rs

Adds a module for the [Open Policy Agent](https://www.openpolicyagent.org/) tool, `opa`.
This assumes that people put the opa binary on $PATH, as it seems to not really be packaged apart from Docker Hub.
Emoji was picked because it's the closest to the official logo, which is a horned hat.
Largely based on the bun module and other modules that just run a command and parse it.
Upstream will likely not change the output of `opa version`, as they're conscious of it potentially being parsed; see https://github.com/open-policy-agent/opa/blob/15b9a884cd5f5fd403cec9929fa58d86b0a9046f/cmd/version.go
Closes #1740

feat: Open Policy Agent module (#1740)

---

src/init/starship.nu

[starship.nu L11](https://github.com/starship/starship/blob/0b173c263e510be572db3ac88f3df7ca01aa486a/src/init/starship.nu#L11) uses multiple piping commands to pull the terminal width from `term size` and convert the result into a string. These actions can be condensed and combined into one of nushell's subexpressions, which makes the code cleaner and easier to read. The proposal is shown below.
Before:
```nu
let width = (term size | get columns | into string)
```
After:
```nu
let width = (term size).columns
```
Remove piping chain and reduce points of failure to only `term size` and the requested value `columns`.

refactor(nu): simplify getting term width

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/guix_shell.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/guix_shell.rs
src/modules/mod.rs

Added guix_shell module to display a symbol when a guix shell is active.
It makes it a lot easier to see if a current guix shell is active. Additionally, the feature is requested in #3999 
Closes #3999
As seen in the screenshot the icon does not represent the Guix logo. However, this is the icon I get when I copy the icon from the [Nerd fonts cheat sheet](https://www.nerdfonts.com/cheat-sheet) (search for guix). The icon does not seem to exist in v2.2.2, at least not in Victor Mono (the font I use).

feat(guix_shell): Initial implementation

---

Cargo.toml
src/serde_utils.rs

This PR bumps the MSRV to rust 1.64 (the latest rust release), because #4541 already increased it indirectly.
Closes #

chore: bump msrv to 1.64

---

docs/config/README.md

In the config `$all` has special meaning, as it is and contains the default value for `format`.
Using `$all` in the example for conditional format strings with multiple variables is potentially misleading and confusing.  
Using a neutral variable `$combined` has no conflict with other meanings and is thus preferable.

docs(config): Replace misleading $all reference

---

CONTRIBUTING.md

#3683 moved the presets' location, but the contribution docs are still pointing to the old location.
Closes #

docs(contributing): switch to current presets dir

---

docs/config/README.md

Resolve inconsistencies in string value declarations.
Consistently use literal strings like we recommend, and like `starship print-config` outputs.
~Based on/includes PR #4520~
Fixes #2935

docs(config): Resolve string inconsistencies

---

Cargo.lock
Cargo.toml
src/context.rs
src/modules/git_commit.rs

Please note that the only fix was for obtaining the name of a remote, which is now
strongly typed.
Even though it works as before, it's now made obvious that this remote may also be
a URL which might be relevant to `starship`.

build(deps): upgrade to git-repository v0.27

---

snapcraft.yaml

This pull request fixes snap package building using 1.11.0 sources
Closes #4574.
No code change outside of the packaging recipe, snap with bash integration appears to run without noticeable issues.

build(snap): Fix snap package not buildable in v1.11.0

---

Cargo.lock
Cargo.toml
src/modules/aws.rs
src/modules/time.rs

This PR updates chrono to 0.4.23 and fixes the new depreciations, mostly by switching to `_opt` function variants that don't panic.
Closes #

build(deps): update rust crate chrono to 0.4.23

---

Cargo.lock
src/init/mod.rs

The idea here is to search for Starship on the PATH when printing out its command path during shell command generation. This is particularly helpful for people using Homebrew, which deletes the old version of any software it installs upon upgrade. Prior to this change, _starship_ would print out the fully resolved path to the binary on disk, and not the symlink that Homebrew creates and is generally available on the path. Consequently, `starship` would print out a path that no longer exists after Homebrew's cleanup, and this in turn would break any already open terminal.
Apologies, but I'm not familiar with conventional commits and don't know whether this is a feature or a fix.
This change looks for `starship` on the `PATH` by way of the [which crate](https://crates.io/crates/which). …

Favor finding Starship on the PATH over its absolute path on disk (#910)

---

src/modules/container.rs
src/modules/git_metrics.rs
src/modules/git_state.rs
src/utils.rs

WSL with systemd triggers the container module, because it creates a `/run/systemd/container` file. For WSL with systemd this file contains `wsl`, so this PR disables container detection if the file contains that.
I also included some test-refactorings.
Closes #4555

fix(container): avoid detecting WSL as a systemd-container

---

src/config.rs
src/serde_utils.rs

Fixes an issue where the config was not being loaded when ignored properties are present. This still prints a warning log indicating a possible misconfiguration.
~~The deserializer wrapper has been updated such that deserialization of ignored properties does not return an error, and instead returns the `visitor.visit_none()`. This function now includes a warning log statement since the [log statement for reporting the error](https://github.com/starship/starship/blob/master/src/config.rs#L34) as shown in the bug ticket is no longer reached.~~ (this described the initial implementation before PR review)
The `ValueDeserializer` wrapper has been updated so that warnings can be either ignored or cause an `Err` result. At this time, the only warning that gets emitted is the warning from ignored …

fix(config): unrecognized config properties don't cause config error

---

src/modules/java.rs

Modified regex for extracting Java version to get the version number expected by most users rather than a vendor-specific version.
Closes #4610
Ran "./target/debug/starship module java" with multiple versions of JDK from Azul.
No doc or test changes needed.

fix(java): Improved regex for Java version (starship#4610)

---

.github/workflows/workflow.yml

I noticed the CI initializes the cache BEFORE installing the toolchain.
However, the documentation of [rust-cache](https://github.com/Swatinem/rust-cache#example-usage) says you should call the rust-cache action AFTER you install the toolchain

fix(ci): cache after selecting the toolchain

---

Cargo.lock
Cargo.toml
src/modules/git_commit.rs

This PR changes the tag search in the `git_commit` to included lightweight tags. As part of the changes, I bumped `git-repository` to the latest version, because it includes upstream changes I made to ensure duplicate lightweight are ordered lexicographically (matching `git describe --tags`). I also changed the existing git tag tests to use `GIT_COMMITTER_DATE` instead of sleeping, which should be more reliable.
Closes #2282

feat(git_commit): support showing lightweight tags

---

README.md

Removes the retired Fedora package from Starship's installation docs, as mentioned here: https://github.com/starship/starship/issues/4630#issuecomment-1323784543
Since the package was retired, I think it'd be best if we removed it from our installation docs until a new package is published: https://bugzilla.redhat.com/show_bug.cgi?id=2051601#c19

docs: remove Fedora from install docs

---

src/bug_report.rs

Privacy concerns have been voiced about the privacy tool (https://github.com/starship/starship/issues/3757). To avoid any data from being exposed unintentionally, ask for confirmation before forwarding issue reports to GitHub.
Unlike https://github.com/starship/starship/issues/3794, this PR avoids complexity by simply asking for confirmation instead of allowing edits of generated reports.
Closes https://github.com/starship/starship/issues/3757
Closes https://github.com/starship/starship/issues/3794

feat(bug-report): ask for confirmation before opening issue

---

docs/config/README.md

The Bun docs mentioned displaying the icon for Node.js which is not accurate. This PR changes that to Bun.
The docs are wrong there. They display the icon for Bun, not Node.js.

docs: Fix mention of Node.js in Bun docs

---

docs/config/README.md
src/modules/azure.rs

Allows a user to show the currently logged in account to azure cli by adding $username as an available variable for the Azure Module configuration. 
Some companies/users work across many Azure tenants or leverage several accounts for separation of environment access, these changes help provide additional visibility to the context of the user you are currently working as.

feat(azure): add username to azure module config

---

src/modules/aws.rs

-------
Check in the AWS credentials file for the `credential_process` in order to enable
the `aws` module, not just in the `.aws/config` file (and all related configured 
locations for same.)
Closes #4603

fix(aws): enable when using .aws/credentials

---

Cargo.lock
Cargo.toml

The `sha-1` crate has been renamed to `sha1` ([as documented in the crate description](https://crates.io/crates/sha-1)).
Closes #

chore: replace sha-1 with sha1 crate

---

Cargo.lock
Cargo.toml
src/modules/localip.rs

Instead of the remote address of 8.8.8.8 (Google DNS) in the crate `local_ipaddress` use a reserved IPv4 address, that should never be assigned.
Also forward the underlying error on failure.
The current used crate `local_ipaddress` connects an UDP socket to 8.8.8.8 (Google DNS), which might trigger some privacy concerns (although no actual packet should be send). 
Supersedes: #4614

feat(localip): use reserved remote address

---

docs/advanced-config/README.md
src/init/starship.nu

This PR enables right prompt of nushell. It depends on nushell/reedline#492 and nushell/nushell#6781.
I think it's ready for review since both nushell/reedline#492 and nushell/nushell#6781 have been merged by upstream. @davidkna 
Closes #3982 
* `new_line` `line_break`
* `new_line`  ~~`line_break`~~
* ~~`new_line`~~  `line_break`
* ~~`new_line`~~ ~~`line_break`~~

feat(nu): enable right prompt

---

src/init/starship.ps1

Older versions of PowerShell will print `System.Threading.Tasks.Task``1[System.String]` instead of a warning, when the `$stderr`-async object is used without `Result`.
Related #4646

fix(pwsh): fix error log display on older versions of pwsh

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/config/README.md
src/configs/haxe.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/haxe.rs
src/modules/mod.rs

This adds a [Haxe](https://www.haxe.org) module that will display currently installed / active Haxe version when in a directory that contains Haxe related files and folders, e.g. files ending with `.hx` or `.hxml`, or a folder named `.haxelib` or `haxe_libraries` or specific file names used in Haxe development environments.
module detects Haxe version either by looking at contents of `.haxerc` file (which implies use of [lix package manager](https://github.com/lix-pm/lix.client)) or by calling `haxe --version`.
As a developer working on Haxe projects you might have different Haxe versions installed on your system (like current release version and a nightly build) and you switch between them to e.g. test compatibility.
This module is similar to e.g. nim module so I took that as a template. …

feat: add Haxe support

---

docs/config/README.md

One word fix of a copy-paste error in the configuration doc.

docs: Fix "vimcmd_visual_symbol" description in doc

---

.github/config-schema.json
docs/config/README.md
src/configs/buf.rs
src/modules/buf.rs

This PR changes the symbol for the buf icon from the buffalo/bison emoji to a 🐃 (Water Buffalo).
The buf icon for the Windows operating system is broken if the user is using a Windows operating system other than Windows 11. This change gives a fixed icon to users who are using Windows 10 or any other Windows operating system.
Closes #4608

fix(buf): broken icon on windows 10

---

src/bug_report.rs
src/configs/os.rs
src/init/mod.rs
src/logger.rs
src/main.rs
src/module.rs
src/modules/aws.rs
src/modules/git_branch.rs
src/modules/haxe.rs
src/modules/hg_branch.rs
src/modules/kubernetes.rs
src/modules/mod.rs
src/modules/os.rs
src/modules/rust.rs
src/modules/utils/directory_nix.rs
src/utils.rs

This PR fixes the clippy warnings as shipped in the [rust 1.66 preview](https://blog.rust-lang.org/inside-rust/2022/12/12/1.66.0-prerelease.html). 
Closes #4696

chore: fix clippy warnings for rust 1.66

---

docs/config/README.md

The `git_commit` module uses a `tag` variable in its format string, which is not explained in the Variables section of this module.
Missing clarification of this `tag` variable is added to the documentation of the `git_commit` module.
Closes #4640

docs(config): clarify git-commit tag variable

---

README.md

Changes the URL to the badge as according to https://github.com/badges/shields/issues/8671
Closes #4737 
The change does not involve changes in code

docs: fix README shields badge

---

src/modules/kubernetes.rs

Kubernetes module was previously a bit messy, with lots of unnecessarily nested options. Clean this up using filter_map and find_map, with two major results:
1. `ctx_components` is now a Vec<KubeCtxComponent> instead of a Vec<Option<KubeCtxComponent>>. This greatly simplified downstream processing of these context components.
2. Instead of storing a partial computation of the namespace in variables `kube_ns`, etc, compute them directly in the formatter mapping. This is made simpler (read: actually doable) by change 1. This change also removes nonlocal commenting (i.e. "This is safe because `var` contains a `Some` value") and replaces it with operations that do not require `unwrap` at all. 
Nested options made it difficult to understand and manipulate the operations of the Kubernetes …

refactor(kubernetes): Remove nested Options

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/no-empty-icons.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/fennel.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/fennel.rs
src/modules/mod.rs
src/utils.rs

I added a fennel module that displays the current version of fennel.
I followed the checklist from [CONTRIBUTING.md](https://github.com/fold-squirrel/starship/blob/master/CONTRIBUTING.md#new-module-checklist), I tried to update the  `docs/.vuepress/public/presets/toml` to the best of my ability.
I recently tried using fennel to configure neovim and was annoyed that starship didn't support it, and I also like rust so I decided to add a fennel module.
Closes #4698
NA

feat(fennel): add fennel module

---

.cargo/audit.toml
Cargo.lock
Cargo.toml

The dependency is optional for chrono and enabled by default for backward compatibility only.
RUSTSEC-2020-0071: https://rustsec.org/advisories/RUSTSEC-2020-0071
Closes #3163

fix: Remove vulnerable time-0.1.x chrono dependency

---

src/modules/package.rs

Changed regex to ```(?m)^\s*version\s*=\s*(?P<version>.*)``` to account for comment lines and possible whitespace.
Closes #4759
Added test with build.gradle file that contains commented out ```version=``` that was picked up by previous regex and with whitespace around the '='
- [x ] I have tested using **MacOS**

fix(package): Improve regex for extracting gradle version from gradle.properties

---

.github/config-schema.json
docs/config/README.md
src/configs/nix_shell.rs
src/modules/nix_shell.rs

Closes #2950.
Adds two options for `nix_shell`:
- `heuristic`: Enables detection of `nix shell` with the heuristic described below (default: disabled)
- `unknown_msg`: Like `pure/impure_msg` for when we can't detect which shell type it is
The current `nix_shell` module only works with `nix-shell`, not `nix shell`.
There's no straightforward way to detect if we're in a `nix shell` yet, so I've used a workaround that checks if we have a nix store path in our `PATH` to detect if we're in a `nix shell`.
I've added tests in the `nix_shell` module.

feat(nix): support new `nix shell` command

---

README.md
docs/README.md
install/install.sh

I noticed that I had to edit an instruction to make the integration with NuShell work (see https://github.com/starship/starship/issues/4701). All that was needed was to add a '-f' flag, but the documentation did not include that. Without this flag, a file would not be overwritten, which causes an error on startup.
Closes #4701
Closes #4757

docs(nu): Add `-f` flag

---

.github/config-schema.json
docs/config/README.md
src/configs/hg_branch.rs
src/modules/hg_branch.rs
src/modules/mod.rs
src/modules/utils/path.rs

This change introduce a new variable that store the active topic name and also it finds the root directory of the mercurial repo.
I am aware that there is already a similar PR : https://github.com/starship/starship/pull/3970 but I noticed it only after I wrote my code :smile:. Anyway I think the remark that @davidkna made on this PR can be fixed by using https://github.com/speedy37/mountpoints-rs/ but I don't know what is the policy regarding including libraries that are quite young and seldomly used.
`hg_branch` does not work when the directory is not at the root of the repository.
I introduced the topic in this change because we started using it in our project and it's a nice way to have lightweight branches in mercurial.
Closes #3970
Closes #1461 
Closes #1384
Closes #870
I ran this …

feat(hg_branch): Add support for mercurial topics and find hg root dir

---

Cargo.toml
src/logger.rs
src/main.rs
src/test/mod.rs

During startup, delete log files that haven't changed in 24 hours. In addition, the in-memory list of printed messages is updated in memory now. This prevents the same log message from showing up multiple times in a single prompt invocation.
As part of this refactoring, I removed all panics from the logging module, added some initial tests to the module and replaced one instance of `Lazy` with a more appropriate `Once` elsewhere.
Closes #

feat(logger): delete old logs & avoid more dup logs

---

.github/workflows/crowdin-pretranslate.yml

I get a weekly email that the crowdin workflow has failed in my fork. This change should prevent that from happening by only running the task on the primary repo (starship/starship)

chore: Don't run crowdin workflow on forks

---

docs/advanced-config/README.md
src/init/starship.nu

Removed the nu shell version check codes for supporting older versions of nu shell.
Closes https://github.com/starship/starship/issues/4778

chore: remove version check for unsupported nushell version

---

docs/advanced-config/README.md

continuation_prompt should be set to a literal string so it should have ' instead of " in the doc/examples.
UPDATE:
Using " even without any variables doesn't work . -> not true, a shell refresh was needed
Closes #
- [ x] I have tested using **Linux**

docs: use literal toml strings in `continuation_prompt` docs

---

src/modules/nodejs.rs

Allowed `nodejs_version` to be unset (node isn't installed) and assign the node configuration
Closes https://github.com/starship/starship/issues/4705
I don't believe they are applicable.

fix(nodejs): apply `style` even if node version is unavailable

---

src/modules/aws.rs

Because its mocking is not enough, The test may unintentionally fails if `~/.aws/credentials` exists.
This commit fixes this issue by mocking `credentials` file as well.
This issue may prevent to build `starship` locally. I hit this issue while building ArchLinux user repository package `starship-git`.
having `~/.aws/credentials` setup by AWS CLI.
I don't know whether if this kind of change should be documented. If needed, I'd happy to write them!

chore(aws): fix unintended test failure of `aws::missing_any_credentials`

---

src/modules/container.rs

Ubuntu's LTS images include  `/run/systemd/container` with contents `docker` and were detected as Systemd because that code ran before podman detection. 
Details:
- the module's podman containerenv detection and processing now happens before systemd detection (provides the expected behavior for image running in podman, even when the `/run/systemd/container` file exists)
- if `/run/systemd/container` contains "docker", the module now shows "Docker" (the expected behavior for image running in docker)
- maintains behavior from #4593 to prevent 'Systemd' display on WSL
- refactors tests for systemd detection for general cleanup of duplicate test code
Closes #3821 
Does NOT address PR #3828  related changes for docker detection, but I see that as a distinct concern from the actual bug report. …

fix(container): reduce docker, podman and systemd confusion

---

Cargo.lock
Cargo.toml
src/config.rs
src/configure.rs
src/modules/hg_branch.rs
src/modules/kubernetes.rs
src/modules/os.rs
src/modules/package.rs
src/modules/pijul_channel.rs
src/modules/python.rs
src/serde_utils.rs
src/test/mod.rs

This PR updates the TOML crates. With this release, they should be using the same parser implementation.
`toml::toml!` was changed to return a `toml::Table` instead of a `toml::Value` containing one. I replaced many of the `toml::Value` uses with `toml::Table`.
To still allow for constructing `Value::ValueDeserializer` with both `&Table` and `&toml::Value`, I added a `ValueRef` type, because `&Value` can't be constructed from a `&Table`.
Closes #

build(deps): update toml crates

---

src/init/starship.fish

Fix prompt transience in `fish` if using vi binding.
The current `enable_transience` function only works when using emacs/default bindings. This is because a command (`transient_execute`) is bound to `\r`. However with vi binding enabled, the bindings are modal. This PR updates `enable_transience` to also bind `\r` in `insert` mode.
This also updates the `disable_transience` function to erase the new bindings rather than redefine them back to `execute`. This will cause the default "preset" bindings to be effective again. Not strictly required to get transience working in vi mode, but it is closer to what is trying to be accomplished. It also doesn't depend on fish keeping `execute` as the default command.

fix(fish): enable transient prompt when in vi mode

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/nerd-font-symbols.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/fossil_branch.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/fossil_branch.rs
src/modules/mod.rs
src/test/mod.rs
src/utils.rs

Add a module to print the active branch of a [Fossil](https://www.fossil-scm.org/) check-out, if the current directory is a Fossil check-out. The module is analogous to the `git_branch` and `hg_branch` modules.
This is part of adding initial Fossil support to Starship, as this was currently missing. This lets users of Fossil repositories have some of the same functionality available in their check-outs as they already enjoy in their Git repositories. While Fossil users usually don't switch branches for a single directory as often as e.g. Git users, this module provides a nice indicator that the directory is version controlled and would work nicely together with a `fossil_metrics` module. The `fossil_metrics` module will be implemented in a follow-up pull request.
Contributes to the …

feat(fossil_branch): add fossil_branch module

---

README.md

This is what the font is called on the linked page.
Trying to Control+F for "Fira Code" does not yield any results.

docs: "Fira Code Nerd Font" -> "FiraCode Nerd Font"

---

.github/renovate.json5
.github/workflows/workflow.yml

Enables ["Branch Automerging"](https://docs.renovatebot.com/noise-reduction/#branch-automerging) in Renovate.
Configure Renovate to try performing version updates and status checks on a branch rather than in a PR, only opening a PR if the status checks fail. Passing version bumps will be committed directly to `master`.
Reduces the amount of PR noise that we get from Renovate, which doesn't require intervention.

ci: reduce renovate PR noise

---

src/init/starship.nu

The nushell warns about not using `let-env` for configuring `config`. I have removed the `load-env` and just added a `let-env` for the `config` as the documentation recommends: https://www.nushell.sh/book/environment.html#let-env.
The fix solves a warning that is visible when opening nushell with starship. I haven't seen any issues  opened explaining this.
I haven't contributed to anything of this size before, and my motivation of getting nushell and starship was to try to help out on a couple of rust projects. I actually just compiled and set up starship and nushell, to get started using these tools, when i saw this error. I am therefore _not_ a nushell expert, so i have spent a couple of days reading up on nushell, before trying out this fix.
It would be advised to get a nushell expert …

fix: let-env warning when using nushell

---

docs/config/README.md

In the example, `[\\w-]` would match a literal backspace `\`, the character `w` or a dash `-`. By removing the backspace, instead it matches any "word character" `\w` or a dash `-`.
Closes #
After removing the extra `\`, I could use a similar regular expression to match the context name of a kubernetes cluster in my local environment.

docs(kubernetes): Remove extra backspace from regex in example

---

.github/renovate.json5
Cargo.lock
Cargo.toml
src/context.rs
src/modules/git_commit.rs
src/modules/git_state.rs

`git-repository` was renamed to `gix` and the other `git-*` crates were renamed to `gix-*`.
Closes #

chore: use updated gitoxide crate names

---

install/install.sh

Consistently use `save -f` rather than `save`; the latter fails if the file already exists
If Nu has been launched once with Starship, `~/.cache/starship/init.nu` already exists and using `save` without `-f` will fail

docs(install): update nushell instructions in installation script

---

.github/workflows/security-audit.yml
Cargo.lock
deny.toml

This PR replaces the `actions-rs/audit-check` actions with the `EmbarkStudios/cargo-deny-action` using `cargo deny`. We may want to raise some `advisories` to `deny`, but the configured level is probably sufficient.
Cargo deny includes some additional checks for license compliance, yanked crates, and allowed crate sources, but unlike the old action it cannot create an issue to track new advisories, which is why I remove the scheduled task trigger. 
I also upgrade the yanked crates from the lockfile that were highlighted.
Partial fix for #4725

ci: replace `audit` with `deny` action

---

build.rs
docs/presets/bracketed-segments.md
docs/presets/nerd-font.md
docs/presets/no-empty-icons.md
docs/presets/no-nerd-font.md
docs/presets/no-runtimes.md
docs/presets/pastel-powerline.md
docs/presets/plain-text.md
docs/presets/pure-preset.md
docs/presets/tokyo-night.md
src/main.rs
src/print.rs

Using pipes to store preset files on PowerShell may modify their encoding format, to avoid this adds a flag to have starship write the files by itself (`-o`,`--output`).
Closes #4866

fix(preset): add output-flag to avoid encoding issues

---

docs/config/README.md

docs(character): use updated `vimcmd_symbol` instead of older `vicmd_symbol` variant

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml

My current font shows a square instead of the ssh symbol, even with the nerd font preset, so I guess this is missing in the preset.
I took nf-cod-globe \ueb01 / 
before:
after:

docs(preset): Add `hostname.ssh_symbol` to nerd font preset

---

src/modules/fossil_branch.rs
src/test/mod.rs

When running on Windows, use `_FOSSIL_` as checkout database file name instead of `.fslckout`.
On Windows, the checkout database file name is `_FOSSIL_` (see [this document](https://www.fossil-scm.org/home/doc/trunk/www/tech_overview.wiki) for details). As a result, the `fossil_branch` module is not able to detect fossil checkout directories.
This PR sets the correct checkout database file name for all platforms, fixing the issue.

fix(fossil_branch): fossil checkout database file name on windows

---

docs/.vuepress/public/presets/toml/no-runtime-versions.toml

The preset `no-runtime-version` does not provide any configuration for Java. This looks like an outlier to me and by summoning the `no-runtime-version` preset, I would have expected no runtime version for java as well.
The `no-runtime-version` preset should generate a default for all languages with Java being no exception.
Manually checked the build and the output of `starship preset no-runtime-versions` showing the newly added config for Java as follows:
```
❯ cargo run -- preset no-runtime-versions | rg -C 5 java
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running `target/debug/starship preset no-runtime-versions`
format = 'via [$symbol]($style)'
[helm]
format = 'via [$symbol]($style)'
[java]
format = 'via [$symbol]($style)'
[julia]
format = 'via [$symbol]($style)'
``` …

docs(preset): add missing config for Java to no-runtime-version

---

src/modules/gradle.rs

Adjusts how Gradle version is parsed from the wrapper properties to account for pre-release builds.
It allows for accurately representing release candidates such as `8.1-rc-1` and snapshots such as `7.5.1-20220729132837+0000`, which otherwise show up as `8.1` and `7.5.1` respectively.

fix(gradle): add support for unstable Gradle versions

---

src/modules/pulumi.rs

Sanitize `pulumi version` output to remove leading 'v' character and trailing newlines.
The output of `pulumi version` currently contains a leading 'v' character and trailing newline character in version 3.60.0. This creates a duplicate v and unexpected newline when leveraging $version in the pulumi module configuration. I'm not certain when the behavior change occurred in the `pulumi version` command, but I believe the change proposed in this PR preserves backwards compatibility.
Updated test cases in the PR.

fix(pulumi): Fix formatting on pulumi module when using version

---

src/modules/aws.rs

Display `AWS` module when setting `AWS_PROFILE` that uses `source_profile` in the config file.
Closes #3834
The rust tests are passing, but I couldn't make it work by running the actual executable from `cargo build`. I'm probably missing something, but couldn't find any documentation on how to do it properly.
Any help is appreciated!
EDIT: with some help from discord, I was able to test this and works well!

feat(aws): add support for source_profile

---

src/init/starship.nu

Nushell recently made a change to require that all closures have an explicit parameter list, even if it's empty, in https://github.com/nushell/nushell/pull/8290.
This updates starship.nu to conform to this requirement.
Without this change, Starship will break on Nushell when the next version of Nushell is released.
Closes #5016
Closes #5061
Closes #5060
I have casually tested this against both the latest released version of Nushell, and the latest version on HEAD; the changed code works well (for me) on both.

chore(nu): use updated closure syntax

---

src/modules/java.rs

When using the JDK provided by Android Studio, the Java version number is `v7284624`. This is because the regular expression used to extract the version catch an SVN revision found later in the returned string.
Add `, built on` to the end of the regex to ensure it stops earlier.
Screenshot below shows the prompt before and after the fix.
- Extended unit-test
- Built starship with the changes and used it

fix(java): wrong version number when using Android Studio JDK

---

README.md

As part of #4954, non-edge packages of Starship were removed from Snapcraft. This means the only way to install Starship is through the `edge` channel using `snap install --edge starship`.
Relates to #4954.
N/A
Tested on Pop!_OS 22.04, Ubuntu 22.04 and Raspbian 11.

docs: update snap instructions

---

.github/config-schema.json
docs/config/README.md
src/configs/azure.rs
src/modules/azure.rs

- Added `subscription_aliases` field for the `azure` module.
- Similar to the `gcloud` module, takes `[azure.subscription_aliases]` from `starship.toml` and replaces the subscription name. If there is no alias, defaults to the normal name.
Closes #4448

feat(azure): subscription name aliases

---

.devenv/profile
.github/config-schema.json
docs/config/README.md
src/configs/git_metrics.rs
src/modules/git_metrics.rs

There's an option in [`git_status`](https://starship.rs/config/#git-status) to ignore git submodules, this does the same for the `git_metrics` module.
I have a repository with a Very Large Git Submodule™️ causing the git_metrics module to not show in my starship prompt due to the starship timeout configuration. It's inconvenient having the prompt not paint for ~300ms (my timeout configuration) so this adds a configuration option to the `git_metrics` module to pass the `--ignore-submodules` flag to `git diff`.
N/A
- (I'm using Nix, so I'm omitting irrelevant steps/info)
- Add `git_metrics.ignore_submodules = true` to my starship config
- Build my edited version of starship
- `export PATH="/path/to/starship/repo/target/debug:$PATH"`
- `eval $(starship init zsh)`
- went to my repo with the …

feat(git_metrics): add option to ignore submodules

---

src/formatter/model.rs
src/formatter/string_formatter.rs

Current logic used to identify style variables in the `StringFormatter` does not descend into nested `TextGroup`s causing improper style formats when style variables are used in nested contexts. This change trivially fixes that.
Closes #4327

fix(style): ensure nested style variables are processed during formatting

---

src/context.rs
src/print.rs
src/test/mod.rs

Since the `ModuleRenderer` config method simply manipulates the context config fields, I added a `.set_config()` method within `Context` that directly overrides the config fields, and let the `config` method in `ModuleRenderer` call that method instead. 
This way, any tests that use a module renderer will continue functioning like normal, and now maintainers can use `set_config` to directly set the configuration of `Context` structs.
I've added a test to show that the configuration is completely overwritten by calling the method. Let me know if this seems like a good idea or not!
Implemented an idea from @davidkna about giving a `.config()` method to `Context` to match `ModuleRenderer`. Mentioned in #5077.

refactor(Context): `set_config` method for `Context`

---

Cargo.lock
Cargo.toml
src/context.rs

Please note that there is a new `dot_git_only` option which would further
speedup discovery. On even moderatly fast disks that probably not going
to make a difference, but it will on incredibly slow (networked) disks.
See https://github.com/helix-editor/helix/issues/6867 for reference.

build(deps): upgrade gitoxide to v0.44 for performance improvements during discovery

---

snapcraft.yaml

Add the [personal-files](https://forum.snapcraft.io/t/the-personal-files-interface/9357) interface to `snapcraft.yaml` so `starship` can access `$HOME/.config/`
Documentation currently says to put config in `$HOME/.config` but this breaks with snap, and has to be put into `$HOME/snap/starship/`. This fixes that.
Closes #4987
This has not been tested since it's just a snap distribution change to `snapcraft.yaml` and not a change to the application itself.
I don't believe these are applicable.

fix(snap): Update snapcraft.yaml to add personal-files interface

---

docs/.vuepress/public/presets/toml/bracketed-segments.toml

There was no ($style) in format for module `sudo`. I added it. 
`sudo` module is not working by default when Bracketed Segments preset used. 
Before changes
After changes

fix(presets): Added ($style) to format in module 'sudo' in Bracketed Segments Preset

---

.github/workflows/release.yml
.github/workflows/workflow.yml

This PR replaces the remaining actions-rs actions with the alternatives discussed in #4725.
The clippy action is set to the latest revision to pull in a commit, which makes setting the GitHub token optional, pulling it from the environment instead. Using something like a personal access token would allow it to make reviews with comments containing suggestions, but as far as I can tell from reading the documentation, any secret would be in danger of being leaked.
A major difference with the new clippy action is that it is only considering the added lines (by default). I feel like this is an improvement, because it should prevent new rust releases from causing clippy CI failures in PRs that don't touch any related lines.
Closes #4725

ci: remove actions-rs actions

---

Cargo.lock
Cargo.toml
deny.toml

#5167, with changes to allow `CC0-1.0` in `cargo-deny` because it is used by a new transitive dependency.
Closes #5167

build(deps): update rust crate rust-ini to 0.19.0

---

docs/config/README.md
src/modules/aws.rs

Currently, starship only supports AWS SSO with [legacy non-refreshable configuration](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-legacy.html).
This PR adds a support for the newer and recommended configuration for AWS CLI to authenticate AWS SSO with [automatic authentication refresh](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html).
Example of the config file with refreshable token (taken from their [documentation](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html#sso-configure-profile-token-auto-sso)):
```
[profile my-dev-profile]
sso_session = my-sso
sso_account_id = 123456789011
sso_role_name = readOnly
region = us-west-2
output = json
[sso-session my-sso]
sso_region = us-east-1
sso_start_url …
```

feat(aws): support aws sso with automatic authentication refresh

---

.github/config-schema.json
docs/config/README.md
src/configs/gcloud.rs
src/context.rs
src/modules/gcloud.rs

This implements a `detect_env_vars` feature to allow flexibly disabling the `gcloud` module, following the discussion in #2671 . 
Closes: #2671

feat(gcloud): add `detect_env_vars` option

---

build.rs

the shadow_rs [new function](https://github.com/baoyachi/shadow-rs/blob/618e28af4d/src/lib.rs#L222-L225) vs [new_hook function](https://github.com/baoyachi/shadow-rs/blob/618e28af4d/src/lib.rs#L271-L276) is similar, but the difference is that `new_hook` function exposes file handles for external use. So, if use `new_hook` function, can remove the `new` function.

refactor: simplify `shadow-rs` setup in `build.rs`

---

.github/config-schema.json
docs/config/README.md
src/configs/go.rs
src/modules/golang.rs

Adding `$mod_version` variable for `golang` module. Mirrors the go directive value found in the `go.mod` file, if present. If installed Go version fulfills the requirement, `$mod_version` is automatically hidden.
Closes #5143. A similar implementation to the `$engines_version` feature I've written for the `nodejs` module.

feat(golang): adding `mod_version` variable

---

docs/config/README.md
src/modules/nodejs.rs

Allow users to use `$expected_version` as a variable for `nodejs`. Mirrors the value of `$.engines.node` in the `package.json` file. Currently set to show only if the node version does not match the parameters set in `package.json`, will be hidden otherwise.
Closes #5066. As raised by the person who opened the issue, a similar implementation of this can also be used for other modules that have declarative versioning.

feat(nodejs): Add `expected_version` variable

---

src/init/starship.ps1
src/modules/character.rs

Updates the `character` module to support showing vicmd-mode when specified for powershell, and changes `starship.ps1` to detect the mode when drawing the prompt and trigger a prompt redraw when needed. The triggering of prompt redraw doesn't work on PS5's builtin version of PSReadLine, so an error when setting it up is silently ignored.
Increases feature parity of the PowerShell support with other shells.
Tested on PowerShell 7.3.2 with PSReadLine 2.2.6 and PowerShell 5.1 with PSReadLine 2.2.6 and 2.0.0 (which doesn't _work_ because you can't get it to redraw the prompt, but it still runs as it did previously).

feat(pwsh): Support vi command mode indicator

---

src/init/starship.bash

Fixes https://github.com/starship/starship/issues/5159
Due to a bug in certain Bash versions, any external process launched inside $PROMPT_COMMAND will be reported by `jobs` as a background job:
```bash
[1]  42135 Done                    /bin/echo
```
This is a workaround - we run `jobs` once to clear out any completed jobs first, and then we run it again and count the number of jobs.
More context: https://github.com/starship/starship/issues/5159
Original bug: https://lists.gnu.org/archive/html/bug-bash/2022-07/msg00117.html

fix(bash): Clear out completed jobs before counting NUM_JOBS

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml

Replace non-nerd-font symbols in the nerd-fonts-symbols preset.
Namely:
- Haxe is set to use the actual Haxe logo (was the mac option key symbol)
- Pijul is set to use the same branch symbol as the other VCSs (was bird nest emoji, even though the vanilla settings use regular branch symbol)
- Spack is removed from the preset since this is the default symbol (🅢)
Some symbols in the Nerd Font preset were not using symbols from the Nerd Font range.
Screenshots of the new symbols if your browser can't display them:
I checked that this produces the correct symbols using the latest patched JetBrainMono Nerd Font. Should work the same on other OSs and not affect anything else.
This should be no-op since no test or doc changes are necessary.

docs: fix symbols in nerd-font-symbols preset

---

src/print.rs

As part of introducing profiles, `right_format` regressed and no longer had access to the left prompt module list to remove from `$all`. The PR is a partial version of https://github.com/starship/starship/pull/4819.
Closes #4953

fix(rprompt): remove lprompt modules from `$all` again

---

.github/config-schema.json
docs/config/README.md
src/configs/shlvl.rs
src/modules/shlvl.rs

I've modified `shlvl` module's behavior for repeat. Now it repeat symbol `SHLVL - repeat_offset` times too.
I wanted a prompt where number of symbols correspond to shlvl at the same time I didn't want to lose color coded theme that `character` module provides. Inspiration is from [Greg Hurrell's prompt](https://github.com/wincent/wincent#prompt
).
Closes #5306
I build a local copy from source and tested against it with appropriate settings.
I'm pasting verbatim output from shell.
```sh
$ export PS1='$ '
$ git log --oneline -3 
b14790d7 (HEAD -> repeat-offset-for-shlvl) feat(shlvl): add repeat_offset for repeated symbol
73e3cdc2 (starship/master, starship/HEAD, origin/master, master) build(deps): update rust crate clap to 4.3.10
a26b5b0f build(deps): update crate-ci/typos action to v1.15.9 …
```

feat(shlvl): add repeat_offset for repeated symbol

---

docs/config/README.md

Specify the name of the option being referenced in the example.  (`fish_style_pwd_dir_length`)
It took me longer than I'd like to admit to figure out what option this example was referring to. It didn't help that the referenced option is hidden in a collapsible, which evaded any attempt made through the browser's find (`ctrl+f`) functionality.

docs(directory): specify option name in example

---

build.rs

Sort toml input file list for reproducible build results.
Without this patch, the resulting `starship` binary varied, depending on random filesystem readdir order.
See https://reproducible-builds.org/ for why this matters.
This patch was done while working on reproducible builds for openSUSE.

build: Sort toml preset files

---

src/context.rs
src/modules/git_metrics.rs
src/modules/git_status.rs

This PR ensures `core.fsmonitor` is unset unless it is set to `true`.
I created a `exec_git` wrapper in `Context::Repo` in order to allow controlling all instances of external git commands centrally. In that function, `core.fsmonitor` is unset as required.
`exec_git` also handles all extra flags previously shared by all external git commands (`--no-optional-locks`, `-C`). Some external git commands used `-C` and some used `--git-dir` and `--work-tree` to set the active repo. I've opted to use both since `--work-tree` isn't always available.
Partial fix for #3974
Closes? #4263
Closes #4712

fix(git): prevent `core.fsmonitor` from executing external commands

---

src/init/mod.rs

The installation instructions indicate that one should add this snippet to zsh's configuration:
eval "$(starship init zsh)"
The command `starship init zsh` prints a little shell script for zsh to execute:
> starship init zsh
source <(/usr/bin/starship init zsh --print-full-init)%
Running `starship init zsh --print-full-init` prints yet another script that zsh executes. There is an intermediate step that seems redundant; starship prints a script for zsh to execute, and this script prints another script for zsh to execute.
This patch skips the intermediate execution and prints the final script in `starship init`. This is backwards compatible and does not require any changes in the installation instructions, so it could be release without a major version bump.
Note that it would still be …

perf: Skip unnecessary indirection in starship init zsh

---

.github/config-schema.json
docs/config/README.md
src/configs/kubernetes.rs
src/modules/kubernetes.rs

This PR implements the suggestion from https://github.com/starship/starship/issues/570 to add an ability to customize the configuration of the kubernetes module style, based on the current context.
A new variable is added to the config section, called environments, which is a list of possible customizations. Each such customization is an object with a context_pattern regex, which matches context name, and an optional style and icon that will override the global configuration, if the currently used context matched the context_pattern.
Based on multiple attempts to add per-context styling and symbols to the kubernetes module.
- https://github.com/starship/starship/pull/1568 by @lht  -> base (rebased and adjusted to current HEAD)
- https://github.com/starship/starship/pull/614 by @nomaed -> …

feat(kubernetes): Add styling based on current context

---

Cargo.lock
Cargo.toml

Replacement for #5343, `schemars` now supports Indexmap v2 via a new feature.
Closes #5271

build(deps): update rust crate indexmap to v2

---

Cargo.lock
Cargo.toml

This also reduces the binary size from
-rwxr-xr-x  1 byron  staff  6482184 Sep  9 08:52 ./target/release/starship
to
-rwxr-xr-x  1 byron  staff  6399544 Sep  9 08:56 ./target/release/starship

build(deps): upgrade to `gix` 0.53

---

src/init/starship.bash

I am installing starship on a Docker container, and every now and then I see the following:
`/dev/fd/63: line 24: STARSHIP_PREEXEC_READY: unbound variable`
On this particular use case I installed https://github.com/junegunn/fzf on the container and then running:
`/opt/fzf/install --help` just gives the above error. Not sure why it. doesn't happen to every command.
I figured this is because STARSHIP_PREEXEC_READY can be non existent at some point. Exporting STARSHIP_PREEXEC_READY=true in the terminal fixes it.
I propose to account for this scenario in the bash-init script.
EDIT: I made a script to easily reproduce this:
Obviously is the `set -u` that triggers it
```bash
#!/usr/bin/env bash
set -u
sleep 1
```

fix(bash): unbound variable error with STARSHIP_PREEXEC_READY

---

.github/workflows/release.yml
install/macos_packages/build_component_package.sh
install/macos_packages/common.sh

Modify how the starship version is obtained in CI to be more strict.
#5137 notes that the version in the distribution XML is broken. This PR changes how the starship version is obtained to be more robust to the errors that occurred.
1. Use Release Please to set the version as an environment variable, and use this environment variable if it exists, filtering out just the numeric portion.
2. If the first step does not work, try to run the starship binary to obtain a version. This line previously had a bug with the ordering of redirect statements which caused an error message to be printed if this step failed. The version here should suppress all errors.
3. If neither of the two steps work, try to grab the first key from `Cargo.toml` using a grep command. This PR fixes two bugs from the …

ci: Fix how version is obtained for pkgbuild

---

install/install.sh

Changes the install script to check if the resolved `curl` is within `/snap`. If it is, the script prints a warning and acts as if `curl` is not installed, searching for other download programs.
For some reason, `curl` which comes from the default package on snapcraft is badly broken. Among its deficiencies are:
1. Attempting to download from a GitHub URL to a location in the home directory results in an empty file being created, even though cURL reports success.
2. Attempting to download from a GitHub URL to a location in `/tmp` results in *no* file being created at all, even though cURL reports success.
3. [Attempting to download to a path with a hidden directory results in spurious failures.](https://askubuntu.com/questions/1356327/cant-write-to-a-hidden-path-using-curl)
While the …

fix(install): do not use curl installed through snap

---

src/modules/status.rs

This PR adds additional exit status code meaning mappings from the [standard C library (/usr/include/sysexits.h)](https://manpages.ubuntu.com/manpages/lunar/man3/sysexits.h.3head.html) to the status module, specifically status codes 64 to 78. In addition to libc the [Python standard library](https://docs.python.org/3/library/os.html#os.EX_USAGE) also includes defined constants for these status codes.
This change provides additional meaning and context when applications exit with status codes 64­­ to 78
Closes #5051

feat: add additional exit status code meanings from libc

---

docs/config/README.md

docs(config): Add quote to unquoted strings, unifying quotes
There are some unquoted default value strings in module's "options" table, I've quote them with proper quotes.
Looking at all modules' "options" table, there are some default value strings wrapped in double quotes and others that are wrapped in single quotes, unifying them to use single quotes.
It looks like all values in `Option` table are quote by backtick, for all types of strings. I've found an unquoted string in C module's option table, and quote it using backtick.
"string" type in TOML file should be quoted using either single slash or double slash, There are some unquoted string in "Default" column of some Modules' `Option` table. I tried to find all of them and have quote them properly.
Most of the "string" type in …

docs(config): Add quote to unquoted strings, unifying quotes

---

.github/config-schema.json
docs/config/README.md
src/configs/starship_root.rs
src/context.rs

Never consider a symlink to be a subdirectory; this prevents hanging when the symlink points to a slow/inaccessible filesystem.
Instead of using `is_dir`, which follows symlinks, use [`symlink_metadata`](https://doc.rust-lang.org/std/fs/fn.symlink_metadata.html), which doesn't.
If the current directory has a symlink to a slow filesystem (e.g. an inaccessible network filesystem), `is_dir` hangs indefinitely, disregarding `scan_timeout`.
This should help with some instances of #312.
n/a
I've tested by running `starship timings` with network disconnected in a directory which includes a symlink to a network filesystem. Without my change it hangs, with my change it doesn't.

feat(scanner): add option not to follow symlinks

---

docs/.vuepress/public/presets/toml/pastel-powerline.toml

I removed the `$path` attribute for the docker context in the Pastel Powerline preset. The `$path` attribute does not exist for docker context as per your [documentation](https://starship.rs/config/#docker-context). 
With the `$path` present.  there is an unpleasant one letter wide vertical gap in the prompt background where the non-existent  `$path` is not rendered. 
Fixes a visual bug in the pastel powerline preset. 
Before removal of `$path`:
After removal of `$path`:

fix(pastel-powerline): remove `$path` from docker-context module format string

---

src/init/starship.zsh

Using Zsh with Status module enabled, the exit code sticks around for as long as there's another command being run.
This change clears the exit code between prompts if no command was being executed, resulting in the correct behavior.
```sh
~/GitHub/starship zsh-fix-status-code ❯ return 1
~/GitHub/starship zsh-fix-status-code ❯                           ↵ 1
~/GitHub/starship zsh-fix-status-code ❯                           ↵ 1 # not cleared
~/GitHub/starship zsh-fix-status-code ❯ return 1
~/GitHub/starship zsh-fix-status-code ❯                           ↵ 1
~/GitHub/starship zsh-fix-status-code ❯                               # cleared
```
Having an irrelevant status code sticking around is slightly annoying.

fix(zsh): clear exit code between prompts

---

Cargo.lock
Cargo.toml
src/configure.rs
src/modules/aws.rs
src/modules/hostname.rs
src/modules/username.rs
src/print.rs

1. get username by `whoami` crate, because the `USER` env may be changed.
2. fix some clippy warning
3. get hostname by `whoami`, and remove the `gethostname` crate from dependencies.
Closes #

refactor(modules): use whoami crate to get username

---

README.md

Added installation instructions for openSUSE Tumbleweed package manager.
Providing additional installation options is always nice.
Installed it myself like this.

docs: Include openSUSE in installation instructions

---

.github/config-schema.json
src/configs/rlang.rs
src/modules/package.rs
src/modules/rlang.rs

- R lang packages version #5586
- remove .Rprofile from rlang detection #2817
- proper detection of R packages #5590
Closes #5586, closes #2817, closes #5590
Have not been tested, `cargo test` getting stuck for many minutes with
```
test modules::git_commit::tests::test_latest_tag_shown_with_tag_enabled has been running for over 60 seconds
test modules::git_commit::tests::test_latest_tag_shown_with_tag_enabled_lightweight has been running for over 60 seconds
```
submitting here so at least CI can test it.

feat: R lang packages version, remove .Rprofile from rlang detection

---

src/context.rs
src/modules/git_status.rs
src/test/mod.rs

This change adjusts the git_status module to no longer attempt to generate git_status for a bare repository as this is not possible when a repository does not have a work tree.
Currently entering a bare repository throws an error, as described in the associated issue.
Closes #5544 
When entering a bare repository the error is no longer visible:
Locally by entering a bare repository as per the above screenshot.
You can also see the correct behaviour from the unit test output (I believe I've used the fixture correctly although not familiar with the setup):
```
cargo test --package starship --lib -- modules::git_status::tests::doesnt_generate_git_status_for_bare_repo --exact --nocapture
Finished test [unoptimized + debuginfo] target(s) in 0.69s
Running unittests src/lib.rs …
```

perf(git_status): avoid running in bare repos

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml

+ add many symbol 
+ replace the `elixir` symbol to actual
Some symbols in the Nerd Font preset were not using symbols from the Nerd Font range.

docs: add more symbols to nerd-font-symbols preset

---

src/modules/docker_context.rs

fix(modules): ignore unix domain socket path from Docker Context
Implemented functionality to slice long Unix domain socket paths in Docker Context within the terminal prompt. This optimization ensures the prompt remains concise and user-friendly, especially in environments where Unix domain socket paths are lengthy.
This enhancement addresses the issue of excessively long terminal prompts when Unix domain sockets are used in Docker Contexts. The change is aimed at improving the user experience by maintaining a manageable prompt length. Relevant issue:
Closes #5548
Before:
After:

fix(docker_context): ignore unix domain socket path from Docker Context

---

.github/config-schema.json
docs/config/README.md
src/configs/direnv.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/direnv.rs
src/modules/mod.rs

Adds a new module `direnv` to display the status of the current rc file if one is present.
Closes #4962

feat(direnv): add new direnv module

---

docs/faq/README.md

Per [the comment](https://github.com/starship/starship/issues/5190#issuecomment-1553411366) in #5190, I've added an FAQ entry that includes an example script to install Starship without requiring `sudo`.
I ran into the same issue that #5190 was about and figured it might be helpful for others to include an FAQ entry as suggested in the issue.
Closes #5190
Closes #5665

docs(install): Add FAQ entry for installing Starship without sudo

---

Cargo.lock
Cargo.toml
src/modules/hostname.rs
src/modules/username.rs

Reverts starship/starship#5521
The switch to `whoami` was causing too many issues. Revert the change for now until the fallible API is available, and we can get the unmodified hostname.
Closes #5587
Closes #5666

revert: refactor(modules): use whoami crate to get username

---

.github/workflows/release.yml

The job has actually never worked, but there is a sensible error message now, [which points to insufficient token permissions](https://github.com/starship/starship/actions/runs/7389237018/job/20101664902). This PR replaces the `GITHUB_TOKEN` with `GH_PAT` which hopefully has the required permissions.
https://github.com/starship/starship/pull/5661#issuecomment-1876829590

ci(release): use PAT for Merge Crowdin PR job

---

src/init/starship.zsh

Move `::STARSHIP::` outside the out `'`-string to avoid escaping conflicts.
Closes #5465

fix(zsh): improve starship binary path escaping

---

src/modules/aws.rs

Similar to https://github.com/starship/starship/pull/3484, relax constrant in testcase to fix flaky test on relevant slow machines.
To fix starship build for slower RISC-V platform.
Error log:
```
thread 'modules::aws::tests::expiration_date_set' panicked at src/modules/aws.rs:713:13:
assertion `left == right` failed
left: Some("on \u{1b}[1;33m☁\u{fe0f}  astronauts (ap-northeast-2) [30m] \u{1b}[0m")
right: Some("on \u{1b}[1;33m☁\u{fe0f}  astronauts (ap-northeast-2) [29m59s] \u{1b}[0m")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

test(aws): fix flaky tests `expiration_date_set` `expiration_date_set_from_file`

---

Cargo.lock

so `aarch64-pc-windows-gnullvm` will become buildable again
update libz-sys deps
this is needed for supporting `aarch64-pc-windows-gnullvm` as it contains important fix
patch bumping, I don't think it's needed to be tested :)
that's surely not about deps...

chore: bump libz-sys crates to 1.1.13

---

Cargo.lock

actually at first update needed fix wasn't applied, see https://github.com/rust-lang/libz-sys/issues/169. 
now the things should work properly
finally resolves problem with `*-gnullvm` targets
_skip_
_skip_

chore: bump libz-sys crates to 1.1.14

---

docs/config/README.md

https://github.com/starship/starship/blob/fd32e35c3d144f361f432f9ca05bb2d9340fb949/docs/config/README.md?plain=1#L529-L536
A space follows a symbol.

docs(battery): add space after symbol in example

---

src/modules/direnv.rs

Starting with version `2.33.0` _direnv_ produces machine parsable status output in the form of JSON. These changes update the direnv module to utilize the JSON output when possible to avoid parsing unstructured output.
Improves maintainability of the direnv module

feat(direnv): use JSON status with direnv >= 2.33.0

---

src/init/starship.bash

If you run starship with `set -u` in Bash you get several unbounded variables errors. This pr fixes that by first checking if the variables are set or empty and continues accordingly.
Closes https://github.com/starship/starship/issues/4540
Built from source using Nix and then tested with:
```bash
set -u
run any command
observe no more unbounded variable errors
```

fix(bash): Handle Unbound Variables Errors in Bash

---

Cargo.lock
Cargo.toml
src/modules/utils/directory_win.rs

Update windows to 0.52.
The functions now directly return `Result`s-types, and calling `ok()` is no longer required. Since `CloseHandle`
now returns errors, create a wrapper `struct` that closes them on drop and writes a debug log-message on failure to do so.
Closes #5377

build(deps): update rust crate windows to 0.52.0

---

src/init/starship.bash

1. For bash-preexec detection, a check for the official `bash_preexec_imported` variable in addition to the private `__bp_imported` for prior versions (see https://github.com/rcaloras/bash-preexec/issues/146 and https://github.com/starship/starship/issues/5686) I also removed the check for the explicit value `defined` since that matches the official sample check more strongly.
2. Always use `BP_PIPESTATUS` if its length is greater than 0, because the value of `PIPESTATUS` could be unpredictable (https://github.com/starship/starship/pull/4902#discussion_r1456513201).
Closes #

fix(bash): improve integration with bash-preexec

---

.github/workflows/release.yml

The artifacts v4 actions did not allow overwriting artifacts anymore, which [would have required adjusting our release workflows](https://github.com/starship/starship/pull/5637#pullrequestreview-1785178689) to still support signing the non-installer binaries, but an `overwrite` option was introduced since then requiring only a single-line change.
Closes #

build(deps): update github artifact actions to v4

---

src/modules/character.rs

After landing #5478 vi edit mode doesn't update the character as expected. This adds the new Shell type to properly show it on Pwsh.
Mentioned in https://github.com/starship/starship/pull/5478#issuecomment-1886829331 that this broke. This works correctly in powershell.exe, but char doesn't update in pwsh.exe
This will fix the character change for Pwsh.

fix(character): also handle vi edit mode in pwsh

---

src/modules/git_branch.rs

According to [the docs](https://github.com/starship/starship/blob/fed7445ecf8959a32a8690a5fa36c4d9765663ba/docs/config/README.md?plain=1#L1799), the `branch` variable in the git branch module should fall back to `HEAD` if there's no current branch (detached HEAD). The code has been changed to do this.
The existing code sets `branch` to be empty in the case that there isn't a current branch.

fix(git_branch): fall back to "HEAD" when there is no current branch

---

Cargo.toml
src/context.rs
src/modules/direnv.rs
src/modules/dotnet.rs
src/utils.rs

Rust 1.76 has been released recently with update clippy. This PR uses this occasion to fix some in-repo clippy warnings. I also updated the MSRV to align with the current requirements.
Closes #5712

chore: apply clippy for rust 1.76 & bump msrv

---

src/init/starship.bash

If ble.sh and bash-preexec are not available, use `PS0` instead of debug traps on bash 4.4+. This may help performance a bit and will hopefully lead to fewer conflicts with other shell scrips (kitty shell integration?).
#4973

feat(bash): use PS0 for preexec hook

---

docs/config/README.md

Running a unknown binary in a subfolder (in this case `.venv/bin/python`) has at least two drawbacks with some security implication:
- In case of a unknown directory, simply cd'ing into a subdirectory could lead to starship executing a unknown binary (usually the binary MUST be in path so it's a decision taken by the user, e.g. by activating the venv)
- starship would show the result of the venv python even if the venv is not active but calling `python3` on the cli would NOT run that `python3` in the venv but a different one (most likely the system python3).
Activating the env will of course display the python version within the venv. But that was a conscious decision of the user to activate the venv.
Closes #5582

docs(python): Remove a bad config example in the python

---

src/context.rs
src/context_env.rs
src/modules/aws.rs
src/test/mod.rs

Rust 1.77 will be released soon with an update to clippy. This PR uses this occasion to a new warning, other nightly-clippy warning, and the use of deprecated `chrono` functions.
Closes #

chore: fix upcoming rust 1.77 clippy issues and chrono deprecations

---

.github/config-schema.json
Cargo.lock
Cargo.toml
docs/config/README.md
docs/package-lock.json
docs/package.json
src/configs/username.rs
src/modules/username.rs

Hello everybody,
I don't use the default `username` module and instead use a custom module because I frequently use terminal multiplexers like `tmux`, `screen`, or `Zellji`. These multiplexers display the hostname in the status bar, so I don't want or need to see it in the terminal as well.
To achieve this, I added the `context::detect_env_vars` function to the `username` module, analogous to the `hostname` module.

feat(username): add detect_env_vars as option

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/no-empty-icons.toml
docs/public/presets/toml/no-runtime-versions.toml
docs/public/presets/toml/plain-text-symbols.toml
src/configs/mod.rs
src/configs/quarto.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/quarto.rs
src/utils.rs

I added a module for the [Quarto](https://quarto.org/) publishing system on the model of the Typst module.

feat(quarto): Add Quarto module

---

.dprint.json
docs/config/README.md
src/modules/ruby.rs

Adding an assignable variable called `$gemset` to the Ruby module. This will read the path provided by the environment variable `GEM_HOME` and capture the gemset information at the end of the path.
Closes #5305

feat: $gemset variable for Ruby module

---

src/modules/status.rs
src/test/mod.rs

The pipestatus string was passed as a string instead of a list of segments, which lead to the ANSI color escapes being included in width calculations. This PR is an updated version of #3741
Closes #3741
Closes #3162

fix(status): fix pipestatus width calculation

---

src/init/starship.nu

Most minimal change possible. Other simplification are possible but not known to be backwards compatible. Also considered `with-env` or `STARSHIP_SHELL=nu starship` but they'd be worse. Happy to reformat indentation if desired.
Closes #5847:
> The bug is `starship prompt --continuation` reads the `STARSHIP_SHELL` environment variable before it's set. The easiest fix would be to set `$env.STARSHIP_SHELL = "nu";` immediately before `load-env`. Happy to PR.
Tested locally by replacing my script and loading it both from my config as well as with`nu --no-config`.

fix(nu): continuation prompt not being displayed correctly

---

docs/config/README.md

As discussed in #5805 using the bun module creates a "double prompt" situation which is easily remedied in user config.
Adding it to the default shipped config I think does not make sense.

docs(bun): Add nodejs override to bun config documentation

---

Cargo.lock
Cargo.toml

Previous versions were yanked because they did not build on FreeBSD.
Closes #
I've verified that starship can be cross-compiled for the FreeBSD target again.

fix(deps): update rust crate os_info to 3.8.2

---

.dprint.json
.github/workflows/format-workflow.yml
Cargo.toml
install/macos_packages/build_and_notarize.sh
install/macos_packages/build_component_package.sh
src/modules/os.rs

Some files were still referencing the old locations used by vuepress instead of those used by vitepress. The incorrect in `Cargo.toml` is likely the cause for the failed publishing to crates.io.
Related #5865

fix: replace all remaining paths referring to vuepress

---

Cargo.lock
Cargo.toml

This reverts commit 19ae0fbe8c815af48a0ec5a729ad1a19c16dff24.
Related #5876. gix 0.61.1 was yanked, the reason is related to networking, which we don't enable, but it makes installing the binary more difficult.
Closes #

revert: "build(deps): update rust crate gix to 0.61.1"

---

Cargo.lock
Cargo.toml
src/bug_report.rs
src/logger.rs
src/modules/daml.rs
src/modules/haskell.rs
src/modules/kubernetes.rs
src/modules/openstack.rs
src/modules/package.rs
src/modules/pulumi.rs
src/utils.rs

`yaml-rust` was declared unmaintained, the suggested alternative is `yaml-rust`.
`dirs-next` is not declared unmaintained outright, but seems close to being unmaintained. At least it looks like `dirs` again has more maintenance right now.
Closes #

fix: replace unmaintained crates `yaml-rust`, `dirs-next`

---

deny.toml

The options that were used `vulnerability`, `unmaintained` etc. are deprecated. Set `version = 2` to opt in to the new behavior that mostly seems to match the options configured in the past. (https://github.com/EmbarkStudios/cargo-deny/pull/611)
Closes #

chore(cargo-deny): migrate to advisories & licenses v2 config

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/no-empty-icons.toml
docs/public/presets/toml/no-runtime-versions.toml
docs/public/presets/toml/plain-text-symbols.toml
src/configs/gleam.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/gleam.rs
src/modules/mod.rs
src/utils.rs

This module adds support for the [Gleam](https://gleam.run/) programming language ⭐
I noticed that Gleam was not supported yet

feat(gleam): Add Gleam module

---

.github/config-schema.json
docs/config/README.md
src/configs/kubernetes.rs
src/modules/kubernetes.rs

Have added the option to trigger the k8s module based on what env vars are set, this has been done in a backwards compatible way so if nothing is changed from the defaults the module will still behave the same way as before. This is similar to what I did in #4486 for the python module and if goes well I'd like to rollout to other modules.
Closes #4238
Closes #4898

feat(k8s): Add detect env vars option

---

src/init/mod.rs
src/init/starship.xsh

Caused by use of cat on Windows platforms.
Removed |cat thanks to davidkna pointing out that the workaround that introduced it has been fixed upstream.
Removed cat within starship.xsh as it is no longer needed and causes issues on Windows.
cat does not work on Windows and causes problems when running starship with xonsh
Closes #4900
Closes #3795
Closes #3646
Ran starship with xonsh with both the latest release and my fork (the error was removed)
Ran cargo test to ensure tests are still passing

fix(xonsh): remove `| cat` workaround from xonsh init

---

docs/advanced-config/README.md

There are six types of changes. The main ones are (1)--(4):
- (1) Replaced *this option* with "*the option `prompt_ps1_transient`*".
- (2) Replaced the phrases "*the value*" with "*\<value\>*".
- (3) Fix "*`~/.bashrc`*" to "*`~/.blerc` (or in `~/.config/blesh/init.sh`)*" for the place to put the `bleopt` settings.
- (4) Fix "*`bleopt prompt_ps1_final="$(starship module character)"`*" to "*`bleopt prompt_ps1_final='$(starship module character)'`*" to use single quotes and delay the evaluation.
- (5) Replace "*filled in*" with "filled-in".
- (6) Add periods to some list items
The number corresponds to the change of the same number in the previous section.
- (1) The description seems to be copied from the section of `prompt_ps1_transient` in the manual of ble.sh. However, in the Starship …

docs(advanced-config): fix descriptions of the ble.sh settings

---

src/init/starship.bash

> Describe your changes in detail
Three changes are included in this PR. Two of them are fixes to the handling of the DEBUG trap (used in Bash <= 4.3 for `starship_preexec`), and the other is a related variable name change. I include these changes in one PR here because they overlap with each other. However, if you would like separate PRs, I can happily separate them into four PRs and submit them one by one (because otherwise, they would produce conflicts).
- a46625ad This commit fixes the problem that the original `DEBUG` trap containing space is not correctly preserved. For example, when the user sets a custom DEBUG trap e.g. `trap 'echo hello' DEBUG` before Starship is initialized, Starship only preserves the first word, `echo`, for *the preserved DEBUG trap*. This is because the …

fix(bash): fix handling of the preserved DEBUG trap (used in Bash <= 4.3)

---

.github/workflows/release.yml

The Wix v3 version on the gh windows images has been updated at some point and now supports building `aarch64-pc-windows-msvc` MSI installer without needing to upgrade to wix v4/v5 (#5407).
I uncommented the special checks excluding `aarch64-pc-windows-msvc` and refactored the wingetcreate invocation to push all installers.
Closes #

ci: enable aarch64 msi building

---

.github/workflows/release.yml
.github/workflows/workflow.yml
README.md

This PR adds windows code signing via signpath on a preliminary basis to test the integration until we are issued a release certificate.
To sign the executables and installers at the same time, I also modified the workflows to put both in the same directory.
Closes #

ci: add preliminary windows codesigning via signpath

---

src/modules/scala.rs
src/utils.rs

- update Scala module to try first to retrieve the current version with `scala-cli` and fallback to current ( slower ) `scclac` 
- update `utils.rs` mock commands to call `scala-cli` and get back the current Scala version `3.4.1` before `scalac` which returns `... 2.13.5 ...` . Keep them distinct for clearer testing.
Partial fix to #5583
`scalac --version` has some noticeable ( most likely jvm ) startup time. Depending on the computer, this can cause a timeout. `scala-cli version --scala` usually has little to no startup time since it is either compiled to a native binary or use its own embedded GraalVM. It also outputs exactly and only the version number which avoids some string parsing.
This can only be considered a partial fix as `scala-cli` is not a hard requirement to work with Scala …

perf(scala): use scala-cli first to avoid timeout

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/plain-text-symbols.toml
src/configs/mod.rs
src/configs/nats.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/nats.rs
src/utils.rs

Adds a module for getting the current NATS context. Uses the nats cli to get the current context name.
This is similar to having the Kubernetes context displayed so it's always known which context you are in.
Added the mock nats cli and then created tests to make sure styling matched.
Also built locally and tested changing contexts and styles.

feat(nats): Add NATS Context

---

Cargo.lock
Cargo.toml

Updates `gix` and `gix-features` in order to re-enable building on all windows targets using a toolchain other than `*-windows-msvc`.
Updates `shadow-rs` to latest stable.
Tests have been run locally, the only failure relates to the global UTF-8 support flag in Windows, which I have off due to breakage in some legacy work stuff. Turning it on makes the test pass, turning it off makes the test fail on the second assert, where all of the wide characters get turned into question marks. Please run CI to confirm everything still works as intended just in case.
This change is required to fix building of direct dependencies `gix` and `gix-features` for the Rust tier 1 targets `i686-pc-windows-gnu` and `x86_64-pc-windows-gnu`, as well as several tier 2 and 3 `*-windows-gnullvm` targets and any …

fix: improve non-msvc windows support by bumping stable dependencies

---

docs/config/README.md

The symbol config line for Gleam was copied from Go, for Haxe was copied from Helm, and for Typst was copied from Daml.
The lines describing `symbol` config value for Gleam and Haxe were incorrect; they referenced Go and Helm respectively, likely a copy-paste error from those languages.
Fix the documentation to refer to the right language.
Documentation-only change, no tests

docs: fix copy-paste typo in config docs

---

.github/config-schema.json
src/configs/direnv.rs
src/modules/direnv.rs

`bold orange` doesn't exist in `predefined_color` and the module text was therefore just white.
By manually adjusting my config to be `style = 'bold bright-yellow'.
- Can I directly update the default in all translations?

fix(direnv): replace nonexistent "orange" color with "bright-yellow"

---

docs/config/README.md

The `disabled` option in the config docs for Typst was copied from Daml.
The line describing the `disabled` option for Typst instead referred to Daml. This is likely a copy-paste error.
Fix the docs to refer to the correct language.
This is a continuation of https://github.com/starship/starship/pull/5995 but the `disabled` option was missed.
Documentation-only change, no tests

docs: fix Typst copy paste typo

---

src/modules/kubernetes.rs

Because both the scan config for files and the env var config are optional, additional handling is needed.
This PR changes for the checks for the `return None` to prevent a default-empty `detect_env_vars from always preventing the module from being ignore.
Closes #5978

fix(k8s): don't trigger if scan config is set but env vars are not

---

.github/config-schema.json
src/context.rs
src/module.rs
src/modules/username.rs
src/print.rs
src/serde_utils.rs

Rust 1.79 has just released with an update to clippy. This PR also uses this occasion to update the config-schema (`null` was removed and added back in updates that were nevertheless auto-merged) ~~and fix more warnings from nightly clippy~~ (dropped).
Closes #

chore: fix rust 1.79 lint warnings

---

.github/workflows/release.yml
.github/workflows/workflow.yml

Renovate inadvertently broke the signpath integration because an upcoming breaking change to the action parameters did not cause a CI failure.
~~Signpath infrastructure doesn't support v0.4 either until Monday, so I will keep this PR as a draft until then.~~
Closes #

chore(deps): handle signpath update

---

.github/config-schema.json
docs/config/README.md
src/configs/purescript.rs
src/modules/purescript.rs

Updates purescript detection for spago-next projects
In upcoming spago projects, the configuration file is changing from spago.dhall -> spago.yaml and spago.lock. This will detect both styles for the time being. See [intro post](https://discourse.purescript.org/t/announcing-spago-next-a-purescript-rewrite-registry-support-and-more/3737) for further details
Will support detection of newer created purescript projects started with spago

feat(purescript): add support for spago-next configuration files

---

.github/config-schema.json
docs/advanced-config/README.md
src/config.rs
src/formatter/string_formatter.rs
src/module.rs
src/segment.rs

This is a rebase and clean up of #4945 incorporating the review comments by @davidkna.
Original Description:
> #### Description
> 
> This PR adds the `prevfg` and `prevbg` specifiers that are allowed to appear in `fg:` or `bg:` style elements. The value will be based on the previous segment's `AnsiString`. This allows powerline-like separators to have the correct colors when so configured.
> #### Motivation and Context
> 
> I am migrating from [powerline](https://github.com/powerline/powerline) and one of the features of the prompt strings there is pretty filled status segments. This PR is based off a suggestion in #528 to allow the previous foreground/background color to be available in style specifiers. This PR does not enable all the functionality of Powerline (e.g. directory …

feat(color): add prev_fg and prev_bg as color specifiers based on the previous foreground/background colors respectively

---

.github/config-schema.json
src/modules/gcloud.rs

This change will disable Google Cloud module when there is no active config set
It has been suggested to implement there https://github.com/starship/starship/issues/3658
This PR is based on those:
closes #4092
closes #3692
closes #3658

feat(gcloud): Disabled gcloud module when active config hasn't been set

---

src/modules/dotnet.rs

This PR matches #5987 (rebased) with a test added.
Closes #5987
> Every language version provider returns the version without a leading 'v', and the shared code then prepends the 'v'. Take a look at Python for example.
> 
> The Dotnet provider prepends a 'v' however, causing the version to be printed like 'vv8.0.203'.
> 
> This happens for example with this configuration
> 
> ```
> [dotnet]
> symbol = '🥅 '
> style = 'bg:color_blue'
> format = '[[$symbol($version)](fg:color_fg0 bg:color_blue)]($style)'
> heuristic = false
> ```
> 
> Where simply `$dotnet\` would be used somewhere in the prompt. Then navigate to a folder contain a dotnet project.
> 
> 
> 
> 
> 
> #### Description
> Removes the string formatting which prepends the 'v' character.
> 
> #### Motivation and Context
> Removes …

fix(dotnet): Remove duplicate v in dotnet version 

---

.github/config-schema.json
src/modules/kubernetes.rs

This module currently takes about 200 ms when using our ~10MiB kubeconfig. This change improves its performance by:
* Only parsing the file once: Reduces time to around 130 ms
* (Naively) checking if the content is yaml or json and potentially parse as the latter, as that seems to be much faster, reducing the runtime to ~30ms
All timings with warm page cache.
Closes #

perf(k8s): Improve performance of kubeconfig module

---

src/configs/fossil_branch.rs
src/configs/git_branch.rs
src/configs/hg_branch.rs
src/configs/meson.rs
src/configs/pijul_channel.rs
src/modules/fossil_branch.rs
src/modules/git_branch.rs
src/modules/git_status.rs
src/modules/hg_branch.rs

Change the starship code to ask integer types for their maximum values directly, instead of using a constant from the standard library. The standard library constants have been deprecated for some time.
Simplify a couple of `match` expressions to not use nested expressions with blocks in them, to make the code a little easier to follow.
I was going to try to create a new module, and as my first steps I ran `cargo test` (passed) and `cargo clippy` (found problems). I wanted to start from a clean slate, so I'm offering these changes to make the code be more idiomatic for current Rust.
(Neither documentation nor tests needed to be changed.)

chore: Minor changes to use more idiomatic Rust (integer max values; complicates nested expressions)

---

docs/public/presets/toml/no-empty-icons.toml

Fix Open Policy Agent module typos in the No Empty Icons preset
👀

fix(preset): fix typo in Open Policy Agent module format string

---

Cargo.lock
Cargo.toml
src/bug_report.rs
src/config.rs
src/formatter/string_formatter.rs
src/module.rs
src/modules/dotnet.rs
src/modules/kubernetes.rs
src/modules/package.rs
src/modules/utils/directory_nix.rs
src/segment.rs

This PR bumps dependencies that renovate failed to update recently (though that issue should be fixed soon) and addresses upcoming rust beta clippy warnings and some more from the nightly version. The quick-xml update also required two single-line changes. I also bumped the MSRV to match the decencies.
The gix issue that was triggering the audit warning was already fixed by c3c640081d0d631a3d83231de32a77275fa4e7cd.
Closes #

chore: bump deps and address clippy warnings

---

src/modules/gcloud.rs

Rust 1.80 prefers a different formatting to this line. I assume that something related to the Unicode handling in the formatter was changed.
Previous rustfmt versions revert will try to revert this change, so I also added a rustfmt-skip directive to the statements.
Closes #

chore: cargo fmt

---

.github/workflows/release.yml

`macos-11` is no longer available.
Closes #6128
Closes #6129

fix(ci): move to macos-latest image

---

docs/config/README.md

These seem to have been copied from hostname and did not make sense
These username config options seem to have been copied from hostname and did not make sense
Make the docs less confusing
its a doc change
it is a doc change and there are no tests

fix(docs): correct username options

---

src/init/starship.bash

This PR contains several trivial fixes to the Bash integration.
The most significant one is a fix for the variable leak. I suggest localizing the variable `job` used in the shell function `starship_precmd` (see commit 1edc7fec0075e92d943b4d91b01f632dab2dd257).
The others are protection for the custom `IFS` set by users. Commit 778694d71210acf1ed07a448ed72e5b42b5d4252 locally sets the variable `IFS` to the standard value `$' \t\n'`. Commit 8a73d3890e5310dd207f4329503f2659fb490f47 properly quotes the array expansions `${arr[@]}` as `"${arr[@]}"`.
> *Why is this change required?*
In the Bash integration, the variable `job` locally used in the shell function `starship_precmd` is not declared to be local. This makes the variable leak to the global context. The variable `job` is not intended to …

fix(bash): fix variable leak in Bash integration

---

docs/config/README.md

This PR fixes two types of typos:
(1) One is a rather trivial one. In the description of the option and variable `typechanged` for the `git_status` module, `typechange` appears. These are oversights of the modification `typechange{ => d}` after [a comment](https://github.com/starship/starship/pull/4829#discussion_r1084307216) in [#4829](https://github.com/starship/starship/pull/4829).
(2) The other is a (seemingly) incorrect usage of "i.e.". "i.e." is used to rephrase the previous grammatical element, but in the following part (**boldfaced by me**), there doesn't seem to be something equivalent to "Java" in preceding texts.
> `substitutions` allows you to define arbitrary replacements for literal strings that occur in the path, for example long network
prefixes or development directories …

docs(config): fix typos

---

src/init/starship.fish

This PR fixes the problem that the transient prompt in fish does not work when pressing Enter without entering a command.
In addition, it also fixes the problem that the transient prompt is incorrectly triggered when pressing Enter to confirm an entry in Tab Completion.
Improve transient prompt in fish.
Before:
After:

fix(fish): improve fish transient prompt

---

src/modules/package.rs

I changed the regex in [`src/modules/package.rs:113`](https://github.com/starship/starship/blob/796a411602c9ca4e5103c54247440f4efe892918/src/modules/package.rs#L113)
https://github.com/starship/starship/blob/796a411602c9ca4e5103c54247440f4efe892918/src/modules/package.rs#L113
... so it matches lines like
```groovy
version = '1.0'
```
... in addition to the syntax that was previously supported. 
My Gradle projects use the [version setting notation recommended in the documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#declaring_module_versions) and I want the version to show up in my prompt.
Closes #6079
Added a unit test and ran `cargo test --lib`.

fix(package): support alternative gradle module version syntax

---

src/modules/aws.rs
src/utils.rs

- Make timing format always show enabled components after te\he first nonzero component (see #5822 )
- Reduce the dynamic string allocation part of the `render_time` function to a single string allocation by pre-allocating the (pretty much fixed size for a given input) string
- Make `render_time` return `0s` instead of `0ms` when `show_millis` is `false` (that result is not rendered anyways though)
- Prefix the tests for the `render_time` function with `render_time_` to make them runnable via `cargo test render_time`
Closes #5822
- Passed the old tests except the ones it shouldn't
- Added new tests

fix(cmd_duration): Make render_time format more consistent

---

docs/public/presets/toml/gruvbox-rainbow.toml

There was an extra space in the Java symbol in gruvbox-rainbox.toml
There was an extra space in the Java symbol in gruvbox-rainbox.toml
Fixes aesthetic alignment issue caused by extra space in Java symbol
- [] I have tested using **MacOS**

docs(preset): remove extraneous space in gruvbox-rainbow

---

src/modules/python.rs

Some python virtual environments have `prompt` set to a path, which in Windows would include the `\` symbol here. We will accidentally escape something like `\n` to a line break here, and similarly symbols like `\r` will be converted. I got around this by rewriting `\` to `\\` before parsing the `pyvenv.cfg` file.
Closes #6125

fix(python): improve parsing of `pyvenv.cfg` files

---

src/context.rs

It seems like this is referencing the wrong config value, so it is unsetting the config value when running git statuses
`core.fs_monitor` is not a valid config value, the proper name is `core.fsmonitor`
This should help speed up git status by using the `core.fsmonitor` git config
See the git status is overriding the `core.fsmonitor` to empty

fix(git_status): read proper name for core.fsmonitor flag

---

docs/config/README.md

Uppon viewing the original doc, on the `config/node.js` module options, the `.nvmrc` is missing on the default value of `detect_files` option.
Missing on docs > config > node.js  `detect_files` options
While present on default config from `src/configs/nodejs.rs`

docs(nodejs): Add missing `.nvmrc` to `detect_files` option

---

.github/config-schema.json
docs/config/README.md
src/configs/python.rs
src/modules/python.rs

Allow the env vars that trigger the python module to be configured, if an empty list is passed then the module will fall back to just triggering based on the configured files, folders and extensions.
Closes #4471
Closes #6198
Closes #6197

feat(python): Add detect env vars option 

---

docs/public/presets/toml/nerd-font-symbols.toml

The Nerd Font Symbols preset is missing a Nerd Font icon for the `git_commit` module `tag_symbol`. This PR sets it to the Octicon `tag` icon.
n.b. This PR incorporates the fix from https://github.com/starship/starship/pull/6186 (i.e. there is only 1 trailing space after the icon, instead of the current 2).
Makes the Nerd Font Symbols preset do what it's supposed to.

docs(preset): add `git_commit` tag symbol to Nerd Font Symbols preset

---

docs/config/README.md
docs/public/presets/toml/no-empty-icons.toml

Update config docs because the Buf module is shown even if the `buf` CLI is not installed.
Also update the No Empty Icons preset to make the Buf module consistent with other modules. I noticed this because (unlike all but one of the other modules in this preset) this one doesn't have `$version ` in parentheses.

docs(config, preset): fix Buf module config docs and No Empty Icons preset

---

src/modules/package.rs

This PR fixes a typo to make the spell-checker pass again. 
spell-check CI runs were failing due to this typo.

chore: fix typo in comment to make spell-check pass

---

docs/public/presets/toml/nerd-font-symbols.toml

Simply set the symbol for gradle on the nerd-font-symbols preset to (, \ue660), which corresponds to the gradle icon on nerd-fonts.
Similar to #5724, but following the proper instructions as indicated by the first comment,

docs(presets): Add gradle icon to nerd-font-symbols preset

---

docs/config/README.md

The [documented default](https://starship.rs/config/#options-32) for `tag_symbol` has one trailing space, but it actually has 2 trailing spaces. This removes the extra trailing space.
Removes an extra trailing space to match the documented default.

docs(git_commit): add extra trailing space to `tag_symbol`

---

src/init/starship.fish

#6107 (unreleased) introduced a bug that mistakenly make `Enter` `accept-autosuggestion` when pager is open:
https://github.com/user-attachments/assets/fdd3b897-4421-4916-957c-0d05bafa87a6
This pull request uses the check from tide's transient prompt implementation, which in essence falls back to `execute` to only accept the selection in pager:
https://github.com/IlanCosman/tide/blob/44c521ab292f0eb659a9e2e1b6f83f5f0595fcbd/functions/fish_prompt.fish#L154-L164
Closes #

fix(fish): use correct input function in transient execute

---

Cargo.lock
Cargo.toml
src/modules/git_branch.rs
src/modules/utils/truncate.rs

The `unicode-segmentation` update appears to segment the text differently (into three characters). The tests are fixed by truncating one character more.
The `process-control` update from #6260 which also requires manual intervention.
Closes #

chore: fix hindi truncation tests and bump deps

---

src/init/starship.fish

Fixed an issue where required arguments were not passed when calling `starship_transient_prompt_func` and `starship_transient_rprompt_func`. This caused some modules such as `cmd_duration` and `status` not to work correctly in the transient prompt in fish.
Closes #6180

fix(fish): add missing arguments for fish transient prompt functions

---

Cargo.lock
Cargo.toml
src/modules/hostname.rs
src/modules/username.rs

This should allow reading the username even if the environment variable is unset.
This was reverted previously in #5669, but with the fallible API introduced in 1.5.0, we can now fall back to reading env variables for the username if the crate fails to read it (https://github.com/starship/starship/issues/5587) and no longer changes hostname-casing with the fallible API (https://github.com/starship/starship/issues/5666).
I also bumped the MSRV to simplify error handling via `inspect_err`.
May resolve
#6193

fix: use `whoami` for user/hostname queries again

---

docs/config/README.md
src/modules/docker_context.rs

Docker Desktop uses `desktop-linux` instead of `default` as the default context since version 3.5.
This filters `desktop-linux` in the same way as "default".
Closes #6170
Using Docker Desktop on Linux. Before this change my prompt included "via 🐳 desktop-linux". After this change, it does not show the default context.

fix(docker_context): Ignore Docker Desktop "desktop-linux" context.

---

docs/config/README.md

Clarify in Custom Command's documentation that the same `shell` is used for both the `command` and the `when` test.
It's plausible that `when` could either use `STARSHIP_SHELL` or the custom `shell`. So it should be disambiguated.
Not applicable.

docs(config): custom shell is used for when command

---

.dprint.json
Cargo.lock
Cargo.toml
deny.toml
src/context.rs
src/formatter/string_formatter.rs
src/formatter/version.rs
src/logger.rs
src/modules/aws.rs
src/modules/c.rs
src/modules/dotnet.rs
src/modules/elixir.rs
src/modules/gcloud.rs
src/modules/git_status.rs
src/modules/golang.rs
src/modules/hostname.rs
src/modules/mojo.rs
src/modules/nodejs.rs
src/modules/ocaml.rs
src/modules/raku.rs
src/modules/rust.rs
src/test/mod.rs

This PR bumps the MSRV to 1.80. This enables replacing `once_cell` with std-provided `LazyLock` and `OnceLock`. The std version does not provide `get_or_try_init yet ` so I switched relevant code to store `Result<_, _>`instead. This might be the better anyway because the documentation sounds like any errors would not be cached.
I also made the `test_cleanup` for the logger target-agnostic, but it still does not run as-is on Windows due to requiring elevated permissions to change file dates.
I also fixed a few clippy warnings to get ahead of the upcoming rust v1.82 release.
Edit: also handled the recent dprint TOML-formatter upgrade.
Closes #

refactor: bump msrv to remove once-cell, improve logger test & handle clippy warnings

---

docs/public/presets/toml/gruvbox-rainbow.toml

style
Included the Pop!_OS nerdfont symbol for the Gruvbox-rainbow preset under [os.symbols]
This will  show the nerdfont Pop!_OS symbol on the terminal for people using Pop!_OS 
I'm currently using a system76 laptop with Pop!_OS running on it.  I found your project and enjoyed trying out all the different presets. I was testing out the gruvbox rainbow preset and noticed the os symbol was a lollipop and thought including the Pop!_OS nerdfont symbol would be enjoyed by other Pop!_OS users. 
Closes #
I ran starship on the GNOME Terminal, within Pop!_OS using the Gruvbox Rainbow Preset.
- [ x] I have tested using **Linux**

docs(preset/gruvbox-rainbow): add Pop_OS icon to os module

---

src/init/mod.rs

This reverts commit 798f64033f5348793003ddd74fa0ce1c744c300b (PR #6253).
`source (starship init)` now errors (I thought I tested it, but I can reproduce it now):
```
fish: Expected end of the statement, but found end of the input
```
Closes #6325

Revert "perf(fish): Skip unnecessary indirection in starship init fish"

---

src/modules/username.rs

Makes `is_root()` default to `false` for tests on all OSes instead of just Windows
First contribution with a tiny fix. Note that the [comment from davidkna](https://github.com/starship/starship/issues/6330#issuecomment-2423931927) was ignored, as running `cargo test` with elevated privileges (tested via `sudo -E cargo test`) does change the username to `root`, and also technically the name of the superuser can be changed, which is an edge case
Closes #6330
Testing on Windows is irrelevant
Updating documentation and tests seems irrelevant

test(username): Default to `false` for `is_root_user()` regardless of the OS

---

src/init/starship.fish

The `"$()"`-syntax used in #6265 was [only added in fish v3.4.0](https://fishshell.com/docs/3.4/relnotes.html#notable-improvements-and-fixes). This PR restores support for previous versions of fish by using the previous syntax mentioned in the release notes.
Closes #6336

fix(fish): restore support for fish <v3.4.0

---

.github/config-schema.json
docs/config/README.md
src/configs/status.rs

Forgotten space in the default format of the `status` module
Closes #6401

fix(status): add trailing space to `pipestatus_format`

---

docs/public/presets/toml/plain-text-symbols.toml

Add buf key in plain text symbols preset
Add buf key in plain text symbols preset
In plain text preset it's 🐃, but It should be "plain text" :-)

docs(preset): add buf symbol to plain text symbols preset

---

src/modules/battery.rs

Previously the selection code for `battery.display` styles simply filtered for the first style found within the config with a threshold larger than the current battery percentage. If the config defined multiple display thresholds that were above the battery percentage it would only select the first one that was encountered rather than the one that was closest to the current battery percentage.
If the battery percentage is currently 50% and I had defined in my config something akin to the following:
```toml
[[battery.display]]
threshold = 100
style = "red"
[[battery.display]]
threshold = 60
style = "green bold"
```
Starship would output the battery module in red, even though the 60% entry is closer to the 50% battery charge. And if the entries were reversed within the config:
```toml …
```

feat(battery): Use best match instead of first match for `battery.display` threshold

---

.github/config-schema.json
docs/config/README.md
src/configs/bun.rs
src/modules/bun.rs

Bun version 1.1.39 introduced a new plaintext lockfile. Currently it is opt-in only, but it will become the default in bun version 1.2.
The new filename is `bun.lock`, instead of `bun.lockb`. Either of these should cause Starship to detect bun.
Currently, a project that has opted in to the new lockfile format is not detected as a bun project.
Tests have been updated and run, as well as manual visual verification on Windows.

feat(bun): Detect bun using new text-format lockfile

---

src/modules/git_commit.rs

This fixes a typo in a comment in the `git_commit` module. 
This typo causes CI failures in other PRs that have nothing to do with it.
N/A
N/A

docs: fix typo in comment of git_commit module

---

docs/public/presets/toml/nerd-font-symbols.toml

The CMake logo is available in Nerd Fonts, but was not being used in the given preset. I have added it here.
The given presets should be complete!
- [ x] I have updated the documentation accordingly.
- [ x] I have updated the tests accordingly.

docs(preset/nerd-fonts): Add CMake symbol to Nerd Fonts preset

---

src/modules/username.rs

The crate does not officially support android yet and returns unexpected username values in Termux environments. I assume that the `whoami` hostname is fine, since the implementation should mostly match the previous `gethostname ` crate.
Closes #6340

fix(username): avoid using `whoami` on android

---

Cargo.lock
Cargo.toml

Downgrade the log crate to v0.4.22 since v0.4.23 and v0.4.24 are yanked
Closes #6494

fix: Change to a non-yanked version of the log crate

---

docs/public/presets/toml/plain-text-symbols.toml

R language configuration is missing in the `plain-text-symbols` preset, so I added it.

fix(preset): add missing rlang to plain-text-symbols preset

---

src/modules/fossil_metrics.rs
src/utils.rs

#6448
This pull request includes a small change to the `src/modules/fossil_metrics.rs` file. The change modifies the `exec_cmd` call to include the `-i` flag when running the `fossil diff` command.
* [`src/modules/fossil_metrics.rs`](diffhunk://#diff-f2faf7236fc5096af8b85713a599931dff87898e5ff07b1cd0363ef0b08d2171L32-R34): Updated the `exec_cmd` call to include the `-i` flag for the `fossil diff` command to improve the diff output.

fix(fossil_metrics): Add -i flag to the fossil_metrics module's command

---

src/context.rs
src/modules/hg_branch.rs

To improve performances, reuse a single allocation in `ScanAncestors::scan()`
Testing on a fairly deep path (7 folders), this makes a `.marker` dir search go from ~1ms to ~600µs somewhat consistently. Since `starship` is run extremely often, I think any kind of perf improvement (for notably the case where there is no `.marker`) is nice.
Here it makes the code longer, and probably a little more complex, but I don't think it's hard to understand by any means, especially with the comments
The tests must not be updated, else it means I broke something

perf(ancestor-scan): preallocate and reuse a single `PathBuf`

---

.github/config-schema.json
docs/config/README.md
src/configs/mod.rs
src/configs/netns.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/netns.rs

This module displays the name of the current [Linux network namespace](https://www.man7.org/linux/man-pages/man7/network_namespaces.7.html), if it's not the default one. This is in a similar vein to the container module.
Useful for people who develop on or administrate systems that use multiple network namespaces.
Closes #5541.
In addition to the unit tests, I ran `cargo run -- module netns` from within a netns created using `ip-netns`, as well as the default namespace. In both cases, the output is correct.

feat: add network namespace module

---

.github/config-schema.json
docs/config/README.md
src/configs/nodejs.rs

Hide the Node.js prompt by default if Bun project files are detected.
The current default prompt shows both the Node.js and Bun prompts in Bun projects, because both runtimes use `package.json` to specify dependencies. However, in Bun projects, this file doesn't actually indicate that Node.js is used. This is a common enough use case that it was added to the docs in #5834.
It was suggested that this should be the default behavior in #4298 but was never implemented.
Closes #5805
I have not tested this but have tested the equivalent behavior via config file

feat(nodejs): disable if bun project files detected

---

src/modules/battery.rs
typos.toml

For calculating the current battery charge percentage, starship divides the current capacity with the fully charged capacity. Some operating systems have APIs that instead return a percentage directly, which is expected to be more accurate. `starship-battery` has an API for this as `state_of_charge()`, which this PR switches to instead.
To still allow merging of multiple batteries, I've kept the internal struct with `energy` and `energy_full`, but set `energy` to the product of the current rate of charge and the full battery capacity.
Once https://github.com/starship/rust-battery/pull/85 is merged should close https://github.com/starship/starship/issues/5212

fix(battery): prefer charge ratio over current capacity

---

Cargo.lock
Cargo.toml
src/modules/hostname.rs

Updates whoami to 1.6.0, which removes the need for an instance of conditional compilation for windows which is reverted in this PR.  The `hostname()` function now returns the `PhysicalDnsHostname` instead of the `NetBIOS` name, while `devicename()` (no longer used) currently returns `DnsHostname` (but may change in a future release).
Original issue: https://github.com/starship/starship/issues/6411
PR introducing change: https://github.com/starship/starship/pull/6343
Commit in whoami changing behavior: https://github.com/ardaku/whoami/commit/d9df51768d6b4b0d5fb611722bc72bdedb5fb936

revert: Remove specialized whoami hostname function choice for windows

---

docs/public/presets/toml/nerd-font-symbols.toml

I've added `bun` and `deno` symbols to nerd-font-symbols preset.
I found that Bun and Deno symbols are available in Nerd Fonts, but they were missing from the preset.
N/A

docs(preset/nerd-fonts): add bun and deno to nerd-font-symbols preset

---

Cargo.lock
Cargo.toml

This should be merged quickly to avoid breakage for developers.

downgrade to `gix 0.71` - `gix 0.72` was yanked.

---

.github/config-schema.json
Cargo.lock
Cargo.toml
docs/config/README.md
src/configs/git_status.rs
src/context.rs
src/lib.rs
src/main.rs
src/modules/git_metrics.rs
src/modules/git_status.rs
src/modules/mod.rs
src/test/mod.rs
typos.toml

I have been waiting for a long time to be able to start working on this, but here we are.
The promise of doing so is that `status` will run only once, instead of twice, and using `gix` means it's 35% (on Linux Kernel) to 200% (on WebKit) faster as measured on MacOS.
This means that in theory, less then half the work will be performed which should be good for very noticable performance improvements.
- it was `core.autocrlf=true` being picked up, and also an incorrectly configured filter
* **2x** on WebKit
* **2x** on the Linux kernel
* **up to 6.75x** faster in the Rust repository with lots of huge submodules
- The trick is that `gitoxide` also has dirty-checking so it can abort early if it finds something
* **3x** on the LLVM repository with all files staged as added, 33.5 million line …

perf: use `gitoxide` for `git_status` and `git_metrics` modules

---

.github/config-schema.json
docs/config/README.md
src/configs/mise.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mise.rs
src/modules/mod.rs

Adds a new module for reporting _mise_ status when _mise_ configuration is present.
Closes #5654

feat: added mise module

---

docs/public/presets/toml/nerd-font-symbols.toml

Add gcloud symbol to nerd-fonts preset to match aws
So the gcloud icon matches the AWS icon when using the nerd-fonts preset

feat(preset): Add gcloud symbol to nerd-fonts preset to match aws

---

docs/config/README.md

Hello there,
I've fixed the `pixi` command to update ps1 in the docs.
More precisely: `pixi config set change-ps1 false` → `pixi config set shell.change-ps1 false`.
`pixi config set change-ps1 false` is now deprecated.

docs: fix `pixi` command to change ps1.

---

.github/config-schema.json
docs/config/README.md
src/configs/pixi.rs

follow-up of #6335.
I just noticed that this also triggers in `~` because there is a `.pixi` directory present as well but isn't a pixi project.
This directory is a special case that contains configuration files of pixi, the module shouldn't be triggered in `~`.
Since all pixi projects contain a `pixi.lock` anyway, removing this shouldn't produce any new issues.
Closes #6707

fix(pixi): Don't trigger pixi module by `.pixi` directory

---

src/modules/aws.rs
src/modules/pulumi.rs
src/test/mod.rs

show time until expiration of credentials from `aws sso`
#5170 added support for showing profiles from `aws sso`
but `duration` still only works for credentials in `~/.aws/credentials`
`starship.toml`:
```toml
[aws]
format = '[($profile )($duration)]'
```
`~/.aws/config`:
```ini
[default]
sso_start_url = https://[redacted].awsapps.com/start
sso_region = us-east-1
```
`~/.aws/sso/cache/[redacted].json`:
```json
{"startUrl": "https://[redacted].awsapps.com/start", "region": "us-east-1", "accessToken": "[redacted]", "expiresAt": "2025-03-08T05:32:14Z", "clientId": "[redacted]", "clientSecret": "[redacted]", "registrationExpiresAt": "2025-05-29T17:37:08Z"}
```
```
$ target/debug/starship module aws
44m14s
```
I don't know if there is any documentation to update. Let me know if you'd like …

feat(aws): support duration for aws sso

---

src/module.rs
src/modules/custom.rs
src/modules/env_var.rs

1. removes two instances where a string is converted to a reference and then back to a string

style: tiny refactor of the Module constructor

---

docs/public/presets/toml/pure-preset.toml

~This PR, inspired by the `no-empty-icons` preset, wraps the venv name and the trailing whitespace in a *conditional* format string. So if the venv name is not available (i.e empty, due to inactive venv), the trailing whitespace will not be either.~
This PR makes it so that the python module is enabled only when a venv is active. All file [& extension] based detection has been disabled.
When a python module is detected (due to the presence of `.py` or `.ipynb` file(s)) but a venv is not active, only the trailing whitespace is displayed and since, in pure, it is placed before the prompt character, this leads to indentation of the prompt character by a single whitespace.

fix(preset/pure): only enable python module if venv is active

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/bracketed-segments.toml
src/configs/hg_state.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/hg_state.rs
src/modules/mod.rs

Add a module to display the current state of mercurial repository.
It extends the support of mercurial.

feat: add mercurial state

---

src/modules/hg_branch.rs

HG topic file, like the branch file, can end with a newline. Strip it out the same way to avoid dumping extra newlines into the prompt.
I'm currently running mercurial version 6.9.4. In this version, the .hg/topic file ends with a newline. The code to handle branch files strips out similar newlines, so I preserved the structure from `hg_branch::get_hg_branch_name`. Interestingly the current bookmark file does still seem to end without a newline. I am unsure if this is a change in behavior across mercurial versions, but the new code will still work fine if no newline is generated.

fix(hg_branch): Strip extraneous newlines from hg topic.

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/nerd-font-symbols.toml
src/configs/opa.rs
src/configs/os.rs
src/modules/opa.rs
src/modules/os.rs

Command run: `for file in $(rg --hidden '".  "' -l); do sed -i '/".  "/s/  ",/ ",/' $file; done`
Double spaces between blocks look weird and inconsistent (cuz everything else is separated by single spaces).
**Before**:
- Emacs (Vterm)
- Alacritty
**After**:
- Emacs
- Alacritty

fix: remove double spaces in default values

---

docs/README.md
docs/advanced-config/README.md
docs/config/README.md
docs/presets/README.md

This PR replaces the VitePress [custom containers](https://vitepress.dev/guide/markdown#custom-containers) with [GitHub-flavored alerts](https://vitepress.dev/guide/markdown#github-flavored-alerts) on the vitepres doc files.
Unlike custom containers, these alerts can render in markdown previews on GitHub. In addition, because ghf alerts use markdown-style blockquotes with a special header, it should be more resilient against inadvertent syntax changes in translations (missing closing `:::` etc).

docs: use GitHub-flavored alerts

---

docs/presets/catppuccin-powerline.md

This PR fixes the broken `markdown` link in the [Catppuccin Powerline](https://starship.rs/presets/catppuccin-powerline). 
The file changed is [this markdown file](https://github.com/starship/starship/edit/master/docs/presets/catppuccin-powerline.md). 
This is a minor change where I change the link in [this line](https://github.com/starship/starship/blob/master/docs/presets/catppuccin-powerline.md?plain=1#L1https://github.com/starship/starship/blob/master/docs/presets/catppuccin-powerline.md?plain=1#L1) from `./README.md#catppuccin-powerline` to `./#catppuccin-powerline`. This prevents the `404` page error while clicking the link.
While navigating the [Catppuccin Powerline](https://starship.rs/presets/catppuccin-powerline) page, on clicking the link `return to presets`, it shows a `404` …

docs(presets): fix broken link to parent on Catppuccin Powerline preset page

---

docs/public/presets/toml/jetpack.toml

docs(preset/jetpack): fix typo in color name

---

README.md

Adds a Fedora 38+ entry to the install table using the existing atim/starship COPR repo.
While Fedora users can technically follow the CentOS instructions, having a dedicated Fedora row improves:
- **Clarity:** Fedora users won’t assume the CentOS instructions are incompatible.
- **Discoverability:** Makes installation instructions easier to find when scanning the table.
- **Accuracy:** Clearly reflects verified support—this method has been personally tested on Fedora.
- **Ease of Maintenance:** Ensures Fedora users have a straightforward way to install and update Starship via COPR.

docs: add Fedora installation instructions using COPR

---

docs/config/README.md

The default `format` string contains `$version`, so the note is incorrect and should be removed.

docs(c, cpp): remove incorrect note about default `format` string

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/bracketed-segments.toml
docs/public/presets/toml/jetpack.toml
docs/public/presets/toml/nerd-font-symbols.toml
docs/public/presets/toml/no-empty-icons.toml
docs/public/presets/toml/no-runtime-versions.toml
docs/public/presets/toml/plain-text-symbols.toml
src/configs/mod.rs
src/configs/starship_root.rs
src/configs/xmake.rs
src/module.rs
src/modules/mod.rs
src/modules/xmake.rs
src/utils.rs

Add new module `xmake` for [XMake](https://xmake.io), which is a cross-platform build utility for C++ based on Lua.
XMake is not natively supported by Starship.

feat: new module `xmake`

---

docs/config/README.md

Replace "Zig" by "Odin" in the symbol description.

docs(odin): fix symbol description

---

src/init/starship.nu

Handle the initial value of `$env.CMD_DURATION_MS` (`'0823'`), and treat it as `0ms`.
Closes #6853

fix(nushell): Startup `cmd_duration` should be 0ms not 823ms

---

install/install.sh

Improve input handling in `install/install.sh` for confirmation prompts. Specifically:
- Interprets user responses case-insensitively to correctly handle both affirmative and negative answers.
- Adds clearer error messages when the user aborts input with `Ctrl+C` or `Ctrl+D`.
- Ensures that if the user declines installation in the default folder, the prompt exits gracefully with appropriate messaging.
This change ensures a more robust and user-friendly install experience, particularly when users provide lowercase or uppercase variants of "no" (`n`, `N`, `no`, `NO`) or interrupt input unexpectedly. Previously, such responses could lead to unclear errors or unintended behaviour.
Closes #5608 
Manually tested the following cases in Starship:
- User inputs `y`, `Y`, `yes`, `YES` → script …

feat(install.sh): handle installation directory prompt responses case-insensitively

---

src/configure.rs
src/context.rs
src/formatter/parser.rs
src/module.rs
src/modules/git_commit.rs
src/segment.rs

The 
```bash
cargo test
```
command was stalling indefinitely for me in `test_latest_tag_shown_with_tag_enabled_lightweight` and `test_latest_tag_shown_with_tag_enabled` tests. The reason being git was launching my editor for me to add a message for the tags in background which wasn't visible to me as a user for commands like 
```bash
git tag l0
```
when launched from cargo tests.
The changes essentially enable proper testing of git modules by simply providing the tag message inline instead of waiting for user to provide input to an invisible editor.
**issue before my changes:**
image showing these tests stalling.
**the same test with my changes.**
- the full test suite runs properly.
- the two tests properly working.

fix(test/git_commit): avoid spawning an editor lead to timeout if tag signing is enabled

---

docs/config/README.md

Add a link to https://github.com/starship/starship/issues/new/choose for filing an issue, instead of linking to the repo root.

docs(c, cpp): add specific link to file an issue

---

src/init/starship.fish

Adding the `fish_helix_key_bindings` value to the possible values of `fish_key_bindings`.
There is a project providing helix editor keybindings to fish: https://github.com/sshilovsky/fish-helix
I would like to see the mode with fish and starship.

feat(fish): support input-mode detection for helix-keybinds

---

src/modules/container.rs

Adds awareness of running inside an [incus](https://linuxcontainers.org/incus/) by checking for the existence of `/dev/incus/sock`, which is created by default.
Without this the prompt falls-back to `[Systemd]`.
- [/] I have tested using **Linux**
- [/] I have updated the tests accordingly.

feat(container): Add detection of Incus containers

---

Cargo.lock
Cargo.toml

`rust-ini` 0.21.2 has been yanked. This downgrades it to the previous valid release, 0.21.1.
- [/] I have tested using **Linux**

fix: rust-ini 0.21.2 has been yanked from crates.io.

---

src/formatter/string_formatter.rs
src/modules/shell.rs

Meta variables were only considered set if they contained another variable, and it was set, just like conditionals themselves. This caused issues with the way the shell module was working, and the behaviour was non-obvious because explicitly set values were not considered set.
Detailed descriptions of the issue are also available in the linked issues.
Closes #3409
Closes #5295
Closes #5885
Closes #6546

fix: consider text-only meta variables in conditionals set if non-empty

---

docs/config/README.md

According to https://github.com/starship/starship/blob/678ce4758b5fa8b42400aec1879f9d4888254db0/src/configs/xmake.rs#L27 the xmake's color is `green`, not `blue`.
Fix a copy/paste (?) error: s/cmake/xmake/
Closes #

docs(xmake): correct style color from blue to green

---

docs/config/README.md

docs(kubernetes): fix typo `environmental` in module documentation
