README.md
src/modules/directory.rs

Let's make that README a little more colorful! 🌈  
- Discord badge
- Azure pipelines badge

Add README.md badges

---

Cargo.lock
Cargo.toml
src/modules/character.rs
src/modules/directory.rs
src/modules/line_break.rs
src/modules/mod.rs
src/modules/nodejs.rs
src/print.rs
tests/character.rs
tests/common.rs
tests/directory.rs

- Added current_dir param to segments to make them more testable
- Moved all existing integration tests to a `tests/` dir
- A whole bunch of new integration tests

Add integration tests for directory segment

---

README.md

We could defs add more here but I think its a start.
@matchai any thoughts on what else to add? Maybe a discord link?

Add a Contributing section to README.md

---

README.md
src/modules/mod.rs
src/modules/python.rs
src/print.rs

This is a quick implementation ... would love feedback!
Closes #22

Add Python version segment

---

.github/ISSUE_TEMPLATE/Bug_report.md

📝 💃 🐛 
A lot of this comes our bug report in SpaceFish: 
https://github.com/matchai/spacefish/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

Add bug report template

---

.github/ISSUE_TEMPLATE/Feature_request.md

🚀 📝 Adds a template for feature requests. Very similar to the default feature template provided by GitHub and used in Spacefish (https://github.com/matchai/spacefish/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md)

Add feature request template

---

src/lib.rs
src/main.rs
src/module.rs
src/modules/character.rs
src/modules/directory.rs
src/modules/git_branch.rs
src/modules/line_break.rs
src/modules/mod.rs
src/modules/nodejs.rs
src/modules/package.rs
src/modules/python.rs
src/modules/rust.rs
src/print.rs
src/segment.rs
tests/character.rs
tests/common.rs
tests/directory.rs
tests/nodejs.rs

Heeeeere's a big one! 🎣 
This PR does _a lot_! I'm really sorry for the amount that there is to review. 😅 
Many of the lines are just tests being updated. Don't worry too much about those.
This API is _not_ set in stone. All feedback is appreciated.
I don't mind redoing this if it means we're redoing it correctly! 😄 
I'll be doing another pass over these files tomorrow to add documentation where I might've forgotten it.
Breaks down what were previously "segments" into "modules" and "segments".
For a quick idea, I suggest taking a look at `nodejs.rs` in this PR.
- Created the `Module` struct and builder functions
- Retrofit all existing segments to be modules
Other stuff that was fixed in the process:
- Skip printing the first module's prefix
- No longer using constructors in tests. Turned …

Refactor segments into modules

---

README.md
azure-pipelines.yml
src/modules/go.rs
src/modules/mod.rs
src/print.rs
tests/Dockerfile
tests/go.rs

Add Go version module

---

Cargo.lock
Cargo.toml
README.md
src/main.rs
src/modules/battery.rs
src/modules/mod.rs
src/print.rs

- Add battery module
Closes no issue.

feat: Add battery module

---

.gitignore
README.md
ci/azure-test-docker.yml
ci/azure-test-stable.yml
integration_test
tests/Dockerfile

Our code coverage is slipping because I've been a little lazy lately. I'd be nice to have visibility over where we are most lacking in coverage. 😄 
Closes #

Use tarpaulin and Codecov for adding code coverage to project

---

README.md

`fisher $PWD` is not a valid command. `fisher add $PWD` can be used to install.

📝 · Fix fisher command in README.

---

src/config.rs
src/module.rs
src/modules/battery.rs
src/modules/directory.rs
src/modules/git_branch.rs
src/modules/go.rs
src/modules/package.rs
src/modules/python.rs
src/modules/rust.rs
src/modules/username.rs

- A small refactor to what will soon be a common process; getting config that are of type string
Closes #

chore: Refactor getting string values from config

---

README.md

Fixes a small error in the README. The code snippet forgets the fish folder in the path to the config.
❤️

docs: fix path to fish config in code snippet

---

README.md

- Add links to our new website and configuration docs
[📝 Click here to view the updated README.md](https://github.com/starship/starship/blob/bd2bb2301deb0482fcbcf66f57fba5804138f019/README.md)

docs: Add links to website and missing detail

---

README.md

- Rearrange the top of the README to have the links above the divider
- Add some line breaks in big chunks of text
- Add emoji to top-level headings 🙌 
- Build out our "Contributing" section to detail where we need help
[**📝 Click here to preview the new README.md**](https://github.com/starship/starship/blob/pretty-readme/README.md)

docs: Make our README.md prettier (with a few added details)

---

LICENSE
README.md
docs/README.md

Update the license and docs to attribute copyright to the contributors of Starship.

docs: Attribute copyright to Starship Contributors

---

azure-pipelines.yml
ci/cargo-clippy.yml
ci/cargo-publish.yml
ci/github-release.yml
src/config.rs
src/context.rs
src/init.rs
src/module.rs
src/modules/directory.rs
src/modules/git_branch.rs
src/modules/git_status.rs
src/modules/golang.rs
src/modules/package.rs
src/modules/python.rs
src/modules/username.rs
src/segment.rs

This PR was initially opened to add publishing to Crates.io, but it grew and ended up also involving fixing longstanding linting errors. Sorry about that. 😅
All linter-related changes were squashed into a single commit that can be reviewed separately.
- Add CI job to publish crate to Crates.io
- Split jobs into stages
- Make `cargo clippy` fail CI
- Fix all linting errors
Closes #

ci: Publish crate to Crates.io with CI

---

src/modules/cmd_duration.rs

Fix an issue in cmd_duration where most tests weren't actually being run.
Turns out a number of the tests in cmd_duration weren't actually running, and one was flat-out wrong.

fix: Add test attribute to cmd_duration tests

---

azure-pipelines.yml
ci/bump-brew-formula.yml
ci/install-cross-rust.yml

Automate the process of updating the Homebrew formula, using `brew bump-formula-pr`.

ci: Automate the bumping of the starship Brew formula

---

docs/config/README.md

Fixed a typo in the Ruby module description.
Without it a user might be confused when reading the docs...

docs: Fix typo in Ruby module description

---

docs/.vuepress/config.js
docs/advanced-config/README.md
src/init.rs

Allows bash users to run a function before the shell is drawn, by defining a function and setting its name equal to `starship_precmd_user_func`, e.g.
```
function derp(){
}
starship_precmd_user_func=derp
eval $(starship init bash)
```
will cause `derp` to be run before drawing the prompt.
This can be combined with other bash features to do things like, e.g. setting the terminal title.
Closes #161 (though somewhat indirectly)
The feature requested in #161 can already be done for zsh by adding a function to `precmd_functions` and is done by default in fish. This adds support to be able to do it in `bash` as well.

feat: Allow bash users to specify a precmd function

---

docs/README.md

It looks like the landing page docs were not updated when we changed the setup instructions.

docs: Update setup instructions on landing page

---

README.md
docs/README.md

Edited both READMEs
Tell people how to install starship on Nix

feat: READMEs: add Nix instructions

---

README.md

Fixed hyperlink to point to the correct location (added 🌱 emoji and a whitespace in the start)
I changed the hyperlink to first good issue inside the README.md file
Closes #206
Checked the new link and made sure it points to the correct location now

docs: Fixed good first issue's link

---

docs/config/README.md

I fixed a mistake of Rust document.
This PR is too small.
Closes #

docs: Description of rust symbol

---

CONTRIBUTING.md
tests/testsuite/directory.rs

fix: Failing Tests if home is a git directory

---

README.md

docs: fix LICENSE and CONTRIBUTING links

---

src/config.rs

There was a typo in a comment
Keeps the comments accurate
Not tested - it's just a comment.
(No docs or tests changes required).

Fix typo in comment

---

docs/config/README.md

Document previously undocumented config options.
Closes #

docs: Add undocumented config options

---

.github/PULL_REQUEST_TEMPLATE.md

Have updated the PR template to add the semantic versioning types this
should make it easier to pass the [semantic-pull-requests](https://github.com/probot/semantic-pull-requests) checks.
Closes #250

chore: Update PR template to add semver types

---

tests/testsuite/common.rs

Remove some `unwrap`s and replace with `?`.
Quick refactor PR responding to https://github.com/starship/starship/pull/307#discussion_r321969299.

refactor: Cleanup unwraps in create_fixture_repo function

---

CONTRIBUTING.md

Includes instruction to set up and use Docker.
Using Docker is hard.
Additional guidance might be helpful.

docs: Include Docker related information in CONTRIBUTING

---

src/modules/time.rs
src/print.rs

- Fix unused imports in unit tests
- Add accidently remove module "battery"

fix: Fixups for #138

---

docs/.vuepress/config.js
docs/ja/advanced-config/README.md

Thanks @unhappychoice and @heyrict !
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/3018/ja/review/10437)

docs(i18n): Translated advanced config to Japanese

---

docs/ja/config/README.md

translated https://github.com/starship/starship/pull/369 to Japanese
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/3018/ja/review/10438)

docs(i18n): Translate #369 to Japanese

---

docs/ja/config/README.md

Thanks for translation, @bookun :tada:
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/3018/ja/review/10466)
https://github.com/starship/starship/pull/379/commits/578d8fb554f418b3aca1d8b817bdf8679d4dc671 is translated by @bookun, describes #367 .
And I reflected 8f03c14582ad61bf4f95a6b69642d8 to Japanese doc.

docs(i18n): Translate #367 to Japanese

---

docs/config/README.md

This PR ​fix a typo (confguring ➜ configuring) in the documentation dedicated to how configure Starship.
Reading the guide I detect this little typo. It isn't a big error but at least I can contribute with this kind of errors, because my knowledge about Rust programming is very very very low. If I detect someone more I will report it too.
I would like to take advantage of this issue to thank to all the Starship contributors. I found this awesome prompt and I am testing and configuring it, but I just can say I really love the idea and what it does.

Docs: ​fix typo (confguring ➜ configuring)

---

README.ja.md

I add the all-contributor's table to `README.ja.md` (#388 )
But I can't fix conflict after all because the table's emoji can't be clicked and edited.
I sent #389 but If README.ja.md is deleted, there seems to be no change in GitLocalize.
(I tested this behavior using my repo: https://gitlocalize.com/repo/3120)
So, I want to reset README.ja.md.
@matchai I'm sorry for confusing you...
Closes #

docs: reset translation of README

---

tests/Dockerfile

Have corrected a typo in the test Dockerfile that was causing the
an error in the docker build output.
This simply corrects a typo in the Dockerfile that was causing the
docker build to display an error.

ci: Fix typo in Dockerfile

---

src/modules/battery.rs

Have removed some dead code from the battery module.
This just removes some dead code that was causing some linter errors.

refactor: Remove dead code in battery module

---

Cargo.lock
README.md
docs/config/README.md
starship/Cargo.toml
starship/src/module.rs
starship/src/modules/kubernetes.rs
starship/src/modules/mod.rs

Have added a new module to add information about the current Kubernetes
cluster. This displays the current contexts and if set the namespace.
Have implemented this by parsing the kubeconfig file rather than calling
`kubectl` which is an order of magnitude slower.
Closes #201

feat: Add Kubernetes module

---

starship/src/configs/battery.rs
starship/src/modules/battery.rs

refactor: Rewrite battery module to use module config

---

src/module.rs

`fn new_module()` seems to have loaded the config uncorrectly.
Closes #481

fix: Fix module configuration loading

---

src/configs/go.rs
src/configs/mod.rs
src/modules/golang.rs

Have refactored the Go module to use the new module configuration.
Update the Go Module to use the new configuration.

refactor: Refactor Go module to the new module config

---

README.md
docs/config/README.md
src/configs/aws.rs
tests/testsuite/aws.rs

This updates the default AWS default symbol to include a space after the
symbol to make it a little bit more readable. Have also updated the
README to include the AWS module.
Makes the AWS module a bit more usable.

fix: Fix the spacing around the AWS default symbol

---

docs/config/README.md
src/configs/git_branch.rs
src/configs/mod.rs
src/modules/git_branch.rs

Refactored git_branch module to use new module config. The documentation for the module was also incorrect, a value that was supposed to be an integer was a string in the example, so I fixed that too after it tripped me up when I was testing the module.
Related #383

refactor: Refactor git_branch module to use new module config

---

src/modules/python.rs
tests/testsuite/python.rs

Just a visual change to separate Python version string and virtualenv name
Closes #
After fix:

fix: Separate Python version string and env name

---

CONTRIBUTING.md

Implement setup documentation for running VuePress site locally inside of Contributing.md.
It clearly demonstrates how to run the VuePress website for those contributing to the visual web design.
Closes #543 in particular
Opened and tested changes on Windows 10 in Visual Studio Code.

docs: Add docs for running the starship website locally

---

src/modules/python.rs

This is a quick fix to stop the python module from displaying error
messages that have been printed to stderr as the version.
Closes #542

fix: Fix the python module ignoring error codes

---

docs/de-DE/guide/README.md
docs/fr-FR/guide/README.md
docs/ja-JP/guide/README.md
docs/ru-RU/guide/README.md
docs/zh-CN/guide/README.md
docs/zh-TW/guide/README.md

docs(i18n) Add links Traditional Chinese docs

---

src/modules/git_branch.rs
src/print.rs

Have removed a couple of unneeded `mut`s that were pointed out by `cargo
check`.
Just a small cleanup of the code to remove some of the warning.

refactor: Remove to remove unneeded mutability

---

README.md
docs/README.md
docs/de-DE/README.md
docs/de-DE/guide/README.md
docs/fr-FR/README.md
docs/fr-FR/guide/README.md
docs/ja-JP/README.md
docs/ja-JP/guide/README.md
docs/ru-RU/README.md
docs/ru-RU/guide/README.md
docs/zh-CN/README.md
docs/zh-CN/guide/README.md
docs/zh-TW/README.md
docs/zh-TW/guide/README.md

Starship could not be built any more with Rust 1.36.
Now, the most recent version 1.38 is recommended.
This closes #591.
modified:   README.md
modified:   docs/README.md
modified:   docs/de-DE/README.md
modified:   docs/de-DE/guide/README.md
modified:   docs/fr-FR/README.md
modified:   docs/fr-FR/guide/README.md
modified:   docs/ja-JP/README.md
modified:   docs/ja-JP/guide/README.md
modified:   docs/ru-RU/README.md
modified:   docs/ru-RU/guide/README.md
modified:   docs/zh-CN/README.md
modified:   docs/zh-CN/guide/README.md
modified:   docs/zh-TW/README.md
modified:   docs/zh-TW/guide/README.md
Update recommended version of Rust to 1.38 - was 1.33 before.
Closes #591

docs: Update required Rust version to v1.38

---

README.md
docs/README.md
docs/de-DE/README.md
docs/de-DE/guide/README.md
docs/fr-FR/README.md
docs/fr-FR/guide/README.md
docs/ja-JP/README.md
docs/ja-JP/guide/README.md
docs/ru-RU/README.md
docs/ru-RU/guide/README.md
docs/zh-CN/README.md
docs/zh-CN/guide/README.md
docs/zh-TW/README.md
docs/zh-TW/guide/README.md

Current instruction is wrong and it breaks a lot. The new instruction is correct for Fish and works correctly. To avoid confusing many people, the documentation should be correct. This fixes the wrong documentation.
Closes #251
Related issue #474
not work as expected)

docs: fix bad instructions for fish-shell

---

src/modules/golang.rs

Cleaned up a few things in the go module. All the changes here are style things, like removing a `match` in favor of propagating an `Option`.
Neater/nicer code is better :)

style: cleanup go module

---

.github/workflows/workflow.yml
tests/Dockerfile
tests/testsuite/python.rs

Stop test failure caused by Python 3.7.4 being made unavailable in the latest GitHub Actions images.
Closes #

ci: Update Python to 3.7.5

---

src/configs/git_state.rs
src/configs/mod.rs
src/modules/git_state.rs

The last module will use the new configuration when this PR gets merged :)

refactor: Refactor git_state module to use module config

---

src/config.rs
src/module.rs
src/modules/cmd_duration.rs
src/modules/env_var.rs
src/modules/hostname.rs

This PR removes the deprecated functions from the code base.

chore: Cleanup after config refactoring

---

src/utils.rs

Have added a little helper function for executing commands. Note this just adds the function further PRs will be required to start using it.
Closes #568
This is my best guess at what we need most of the time from having a look at the existing modules. Please feel free to suggest alternatives if I've missed something.

chore: Add a helper function for executing commands

---

src/modules/directory.rs

fix: Fix panic when using fish-style pwd with unicode symbols

---

docs/.vuepress/config.js
docs/faq/README.md

We encounter _a lot_ of repeated questions on GitHub and the Starship Discord, so this is a good opportunity to compile them all into an FAQ to be put on the website and linked to from the repo.
These were the first questions to come to mind. I'd like to flesh it out a little more with a few more questions that are commonly asked before adding it to the docs.
Any ideas for things to cover, @starship/astronauts?

docs: Add an FAQ page to website

---

src/modules/battery.rs

I update the battery module, in order to implement an aggregating view of all the batteries present in the notebook.
The percentage of the battery is calculated with a weighted average of the energy of all the batteries. Instead, the battery state is calculated with the following rule:
- Charging if at least one is Charging
- Discharging if at least one is Discharging
- Full if all are Full
- Empty if all are Empty
- Unknown otherwise 
As stated in issue #656 if there are multiple batteries in the notebook the battery module gives inconsistent values of the battery percentage and state.
I test it on my Lenovo T450s that has two batteries. For now, there is not any unit test on the battery module.

fix: multiple batteries support in the battery module

---

README.md
docs/.vuepress/public/install.sh
install/install.sh

Add a one-line installer for starship. For the time being, it will install the latest suitable version for the user's platform and architecture.
I also took the opportunity to clean up the installation docs, which have recently gotten cluttered, giving the impression that we have a lengthy installation process at a glance. 
[**📝 Click here to view the new README.md**](https://github.com/starship/starship/blob/update-install/README.md)
Closes #

docs: Simplify installation process and docs

---

docs/config/README.md
src/configs/starship_root.rs

fix: Add php to the default prompt_order

---

snap/snapcraft.yaml

Adds support for building snaps out of starship.
This enables `snapcraft` to build a snap of `starship` which can then be published in the Snap Store. As discussed over email I published a build of `starship` to the Snap Store, and offered to hand this over to the upstream developers.  I have [requested](https://forum.snapcraft.io/t/please-transfer-starship-to-matankushner/14558) the transfer on the snapcraft forum.
Using the snapcraft command line utility on a Linux developer machine, in CI, or using build.snapcraft.io, this yaml will build a strictly confined snap of starship. It has a conditional build section. 
If hooked up to build.snapcraft.io - the following will happen.
* On each commit, a new build will be triggered, and published to the edge channel in the Snap Store. Users who …

build: Add snapcraft.yaml to build snap of starship

---

README.md

The install script includes some bash only commands so needs to use base
to be piped into bash rather than sh.
Closes #701

docs: Fix install script instructions

---

README.md
docs/.vuepress/config.js
install/install.sh
src/init/mod.rs
src/init/starship.ion
src/main.rs

This commit adds support for the jobs and status options of the starship prompt.
Support for the cmd-duration is also added if you are using the latest
ion shell. The cmd-duration is implemented using the ION_CMD_DURATION variable.
This variable keeps track of the time spent executing the last command. (This is
similar to the CMD_DURATION of the fish shell).
See this MR for more information: https://gitlab.redox-os.org/redox-os/ion/merge_requests/1176
Closes #678 
This change is useful for anyone who likes to use ion and starship together.
The ion shell is only supported on linux and redox-os.
I have updated the documentation and README with references to ion. But I haven't updated the translations, since I don't speak those other languages.
I also haven't added any tests, since I …

feat: Add support for the ion shell

---

src/init/starship.ps1

When using powershell on linux and the directory is changed the starship prompt stays the same:
```
~
❯ cd foo
~
❯
```
after the fix:
```
~
❯ cd foo
~/foo
❯
```

fix(powershell): Fix prompt not updating on -nix systems

---

src/modules/battery.rs
src/modules/memory_usage.rs

Closes #729 
Still need to test this. Don't merge until tested.

fix(powershell): % sign was prefixed with  `

---

docs/de-DE/faq/README.md
docs/faq/README.md
docs/fr-FR/faq/README.md
docs/ja-JP/faq/README.md
docs/ru-RU/faq/README.md
docs/zh-CN/faq/README.md
docs/zh-TW/faq/README.md

Have fixed a minor typo in the FAQs to use the `--help` flag rather than
the `--version` flag.
This is just a minor correction to make the docs a bit cleaner.

docs: Correct a typo in the FAQs

---

docs/config/README.md

The summary of the `git_commit` module is wrong. I guess it was copied from the `git_branch` module, but wasn't adapted.
Documentation of `git_commit` was misleading.

docs: Correct summary of `git_commit` module

---

src/bug_report.rs

Extend the `bug-report` feature added in #725 to include terminal emulator.
Closes #

feat: Extend bug-report to include terminal emulator

---

install/install.sh

Running `shellcheck` on install.sh, there were quite a lot of warnings (and some errors).
This fixes them.
Many of these were just SC2059 and SC2155.
Also: SC2034, SC2145 (fixed by fixing SC2059), SC2162, SC2236.
Imo, even if small, these things would pile up over time if not fixed early.

fix: Fix shellcheck issues in install.sh

---

.github/workflows/workflow.yml

Fetch performance has been improved since version 2.

Bump checkout action from 1 to 2

---

README.md

Fix lack of spaces between the word version and the open parentheses in two of the supported languages shown in the features section of the README.
I saw this lack of spaces translating to Spanish in translate.starship.rs.
None of the above. This is a little fix in the README.
It isn't necessary.

Fix lack of spaces in the README

---

docs/config/README.md

Closes https://github.com/starship/starship/issues/794

docs: Document STARSHIP_CONFIG env variable

---

src/modules/mod.rs

The `starship explain` texts for `git_branch` and `git_commit` are the same, this triggers me badly. 😅 
It satisfies my self-diagnosed OCD

fix: explain text for git_commit

---

README.md

For users who already have Rust/Cargo installed, installation with Cargo may be the preferred approach.
The "Install Latest Version" section now contains two subsections, "From binary" (for the existing curlbash command) and "From source (with Rust)" (for the new command).
Since attempting to go "off the beaten path" when installing software often leads to unintended problems, I installed Starship using a recommended approach (`brew`) before attempting to install with Cargo, even though I generally prefer Cargo. Assuming there is no special reason _not_ to recommend Cargo, I think it's worth mentioning it in the README so that other users don't avoid it unnecessarily.
I just `brew unlink`ed my first install, then ran `cargo install starship` and confirmed that Starship worked (after …

docs: Explicitly mention 'cargo install' in README

---

src/utils.rs

This adds the ability to mock the output of `utils::exec_cmd` when running tests. Further work will be required to update the existing tests.
Closes #289

feat: Add ability to mock commands during tests

---

src/modules/php.rs

Have refactored the php module to use the util::exec_cmd rather than the
Command module directly.
Related to #676, #768 and #289

refactor(php): Use `exec_cmd` util

---

README.md

Have fixed the indentation of the Battery symbols and added a few
modules that were missing to the list of features.
Just keep the docs up to date.

docs: Fix indentation and missing modules in README

---

.github/workflows/workflow.yml
tests/testsuite/python.rs
tests/testsuite/ruby.rs

Fixes the ongoing CI failures.
- Update the version of the runtimes depended on by CI
- Implement caching for cargo registry, index, and build

ci: Update CI dependencies

---

docs/.vuepress/config.js

See #449
By the way, really love Starship. Thanks for creating it! 🎉

docs(i18n): Add Russian to the website language dropdown

---

.github/workflows/workflow.yml
README.md
docs/config/README.md
src/configs/haskell.rs
src/configs/mod.rs
src/module.rs
src/modules/haskell.rs
src/modules/mod.rs
tests/testsuite/common.rs
tests/testsuite/haskell.rs
tests/testsuite/main.rs

* Add a Haskell Stack module, when it detects `stack.yaml` file.
~Closes #~
I have a bunch of Haskell projects and I'm really missing support for Haskell in `starship`.

feat: add Haskell Stack support

---

CONTRIBUTING.md

When I submitted my first PR to this project the other, I wasn't sure if the way I had used git would be acceptable. Some open source project are quite specific about the way they want you to use git. Fortunately it was fine, but I thought it would be a nice idea to be explicit about it in the contributing guidelines. 🙂

docs: Add git workflow to CONTRIBUTING.md

---

docs/ja-JP/presets/README.md

docs(i18n): Fix links in Japanese docs

---

Cargo.lock
Cargo.toml
src/bug_report.rs

This reverts commit d869b3a09870d432a71d63623bb235b5345e680f, as was merged in #844.
[As mentioned by @q66](https://github.com/starship/starship/pull/844#issuecomment-581069176):
> This breaks starship on any architecture other than x86 and ARM by pulling in ring (via rustls, which is needed for the tls feature) which is assembly-only without portable fallbacks, and doesn't seem to have any plans to change this, or accept additional platform support.

revert: "refactor: replace reqwest with ureq (#844)"

---

src/modules/haskell.rs

Added support for [cabal](https://www.haskell.org/cabal/) and [hpack](sol/hpack)

feat: Added cabal and hpack support to the haskell module

---

install/install.sh

Ask sudo password if needed
Closes #835 
Closes #793
Closes #810

feat: Adds support to ask sudo password if needed

---

src/modules/git_status.rs

Refactor the git status module to make only one pass on the statuses vector for counting.
This will make git status module faster.

refactor: git status to use HashMap to count

---

docs/config/README.md

Adds a paragraph with examples describing how fish-style pwd shortening interacts with the default
truncation options. I'm open to rewording on this part.
Also includes some whitespace changes my editor insisted were necessary.
Closes #412

docs: Update docs w/ details on fish-style dir truncation

---

docs/config/README.md

This fixes https://github.com/starship/starship/issues/965
Closes https://github.com/starship/starship/issues/965
Before:
After:

docs(time): add missing quotations in options and examples

---

docs/config/README.md

Fixes a minor typo in the newly-added Elixir module.
Closes #

docs: Minor typo fix for Elixir config docs

---

src/modules/package.rs

as discussed in https://github.com/starship/starship/pull/776#pullrequestreview-368933093, this PR adjusts the `package` module to ignore JS packages that have specified `private: true` in their `package.json` file.
see https://github.com/starship/starship/pull/776#issuecomment-594555121

feat: package: Ignore private JS packages

---

.github/FUNDING.yml

🎉 Starship is on Open Collective now!
@matchai Maybe we should also add a link in the readme as well? 🤔
Should probably also tweet about this 😉 If you want me to create a PR for that, lmk!
Closes #

chore: Add Open Collective to Sponsor badge

---

src/modules/dotnet.rs
src/modules/kubernetes.rs

This just cleans up a few new suggestions from Clippy.
Fixes the broken build in #1004.

refactor: Fix new Clippy suggestions

---

CONTRIBUTING.md
Cargo.lock
Cargo.toml
src/context.rs
src/modules/crystal.rs
src/modules/elixir.rs
src/modules/elm.rs
src/modules/golang.rs
src/modules/haskell.rs
src/modules/nodejs.rs
src/modules/php.rs
src/modules/ruby.rs
tests/testsuite/aws.rs
tests/testsuite/common.rs
tests/testsuite/directory.rs
tests/testsuite/dotnet.rs
tests/testsuite/git_branch.rs
tests/testsuite/git_commit.rs
tests/testsuite/git_status.rs
tests/testsuite/hg_branch.rs
tests/testsuite/python.rs
tests/testsuite/terraform.rs

The recent Test Failures in GH Actions (#886) might be caused be premature tempdir cleanup. This PR attempts to remidy that by closing the tempdirs either expcilitly with `close` or using `into_path` and cleaning them up with `remove_dir_all`.
Possible fix for #886

fix: possible fix for Intermittent Test Failures in GH Actions

---

docs/config/README.md

Add to disabled = true to [memory_usage] in the config documentation
Closes #1023

docs(memory_usage): Update example to have `disabled = false`

---

src/modules/dotnet.rs

For finding the necessary files to determine the version and if the module should be enabled the `dotnet` module is currently iterating through all files in the current directory (`O(n)`) to find relevant files.
This PR makes the module exit early in case the relevant files aren't present and only does the work of finding these files if they are present.
Possible breakage:
`estimate_dotnet_version` is case insentive but `context.is_match()` is not.
Tested with hyperfine in `starship/src/modules`:
before:
`starship module dotnet 63.9 ms ±   4.6 ms`
after:
`starship module dotnet 23.9 ms ±   2.5 ms`

perf(dotnet): fail faster in the dotnet module

---

docs/config/README.md
src/configs/julia.rs
src/modules/julia.rs

* I implemented the julia module(#1030 )
* Example icon is not compliant with [Julia's community standards](https://julialang.org/community/standards/) (ref: https://github.com/starship/starship/pull/1030#discussion_r404284920)
Closes #

fix(julia): julia icon based on Julia's community standards.

---

src/module.rs

Fix typo: set_segment -> set_segments

fix: Fix typo

---

docs/presets/README.md

Added some missing NerdFont configurations for new modules. Couldn't find good replacements for the [`crystal`](https://starship.rs/config/#crystal), [`dotnet`](https://starship.rs/config/#dotnet), and [`kubernetes`](https://starship.rs/config/#kubernetes) modules.
Closes #1060

docs: update NerdFont preset to include new modules

---

src/formatter/string_formatter.rs
src/segment.rs

This PR fixes forwarding styles from upper scope to variables.
Related #1066

fix: Fix variable styles in string formatter

---

README.md
docs/faq/README.md

Added an explanation of the musl build to the readme, in case anyone else tries to use starship with CentOS 7
Just a documentation update.
References #342
Fixes #1052

docs: Add details about musl build to readme

---

src/modules/git_branch.rs
src/modules/git_status.rs

revert: fix(git_branch,git_status): implement fallback branch_name for bare git repos

---

src/utils.rs

This makes some changes to the logging to make debugging what is
happening a bit easier when we run external commands.
I was trying to debug some changes I was making locally and found it
useful to have the full details of what happened rather than just when
the command failed. Since this mght be useful to others I've added it
here.

chore: Add more detailed logging for executing cmds

---

tests/testsuite/python.rs

Fix the python tests that depend of having the correct version of Python
installed on the build system.
No open issues but partially related to #941 and #942.

ci(python): Fix broken tests

---

tests/testsuite/git_branch.rs
tests/testsuite/git_commit.rs
tests/testsuite/git_state.rs
tests/testsuite/git_status.rs
tests/testsuite/hg_branch.rs
tests/testsuite/python.rs
tests/testsuite/singularity.rs

Have added some null tests to modules that don't already have them.
Closes #1099

test: Add null tests to modules that don't have them

---

src/bug_report.rs
src/config.rs
src/modules/crystal.rs
src/modules/elixir.rs
src/modules/elm.rs
src/modules/golang.rs
src/modules/haskell.rs
src/modules/julia.rs
src/modules/kubernetes.rs
src/modules/nodejs.rs
src/modules/package.rs
src/modules/php.rs
src/modules/ruby.rs
tests/testsuite/aws.rs
tests/testsuite/git_branch.rs
tests/testsuite/git_state.rs
tests/testsuite/git_status.rs
tests/testsuite/hg_branch.rs
tests/testsuite/python.rs
tests/testsuite/terraform.rs

Have removed some imports that Clippy says are not needed anymore.

fix: Fix latest clippy suggestions

---

src/configure.rs
src/main.rs

- Alias `starship configure` to `starship config`
- You can now pass in a key (e.g. `character.symbol`) and value (e.g. `"$"`) to `starship config` and it will update Starship's configuration file for you.
Closes #1080

feat: Modify config keys from shell

---

docs/config/README.md
src/configs/erlang.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/erlang.rs
src/modules/mod.rs
src/utils.rs

Add Erlang module and more precise OTP version reading (could be used in the Elixir module as well).

feat(erlang): Add Erlang module

---

src/formatter/model.rs
src/formatter/parser.rs
src/formatter/spec.pest
src/formatter/string_formatter.rs

This PR renames the syntax `()` which renders when all variables inside are not none, to `Conditional` to avoid ambiguity.

chore: Rename conditional syntax

---

.github/workflows/workflow.yml
tests/testsuite/python.rs

Stop test failure caused by Python 3.7.6 being made unavailable in the latest GitHub Actions images.
Closes #

ci: Update Python to 3.8.2

---

LICENSE

The license needs updating since it is now 2020!

docs: 📅 — We are now in the future! (2020)

---

docs/config/README.md

Have made some fixes to the correction docs these docs consist of fixing
the a few missing style options, updating the defaults which had
diverged from the current values, correcting the order of the modules to
make sure they are still sorted alphabetically and rewording the docs
for the Python module to make it clear that it also displays the current
virtualenv.
Just make sure the docs are correct.

docs: Correct the configuration docs

---

docs/config/README.md

Added a tip with information about how a PowerShell user can
override default starship.toml file location path in his PowerShell
profile.
It took me a while to figure out a way how I can change the default file location for starship configuration in PowerShell. The main motivation for me was to make one config file, which could be shared across shells on my computer (zsh and PowerShell).
Closes #

docs: Updated config with a tip for PowerShell user

---

docs/config/README.md
src/configs/mod.rs
src/configs/ocaml.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/ocaml.rs
src/utils.rs

Added the module which displays the currently installed OCaml version.
Closes #903

feat(ocaml): Add OCaml module

---

docs/config/README.md
src/configs/mod.rs
src/configs/starship_root.rs
src/configs/zig.rs
src/module.rs
src/modules/mod.rs
src/modules/zig.rs
src/utils.rs

Added the module which displays the currently installed Zig version.
Closes #1139

feat(zig): Add Zig module

---

.github/workflows/workflow.yml
tests/testsuite/python.rs

The latest upgrade to the GitHub Actions toolcache only updated the Python versions available for macOS and Windows. This PR changes the version of Python used to one that is available on the previous and upcoming toolcache upgrades.
Python 3.8.2 → Python 3.7.7
Fixes the ongoing CI failures caused by Python setup.

ci: upgrade Python for integration tests

---

docs/config/README.md
src/configs/mod.rs
src/configs/purescript.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/purescript.rs
src/utils.rs

Added the module which displays the currently installed PureScript version.
Because there is no PureScript support yet.

feat(PureScript): Add Purescript module

---

.github/PULL_REQUEST_TEMPLATE.md

Remove the `Types of Changes` section of the PR template.
With conventional commits, it's just an extra step that no longer provides useful information.

chore: remove redundant section from PR template

---

.github/workflows/security_audit.yml
.github/workflows/workflow.yml

Have refactored the Github Actions workflow to speed up the runs. The main savings come from moving the Security Audit into a separate workflow, running all the jobs in parallel and being a bit more aggressive in the use of the cache.
Going forwards there are some other changes that it might make sense to make such as separating the `fmt` and `clippy` checks into separate workflows, removing the compile job since the testsuite will compile the app and taking a better look at the steps in the release workflow. 
This speeds up the CI run so that they now consistently take less than 4 minutes rather than the 6 or 7 minutes that are currently taking.

ci: Refactor Github Actions workflow file

---

.github/workflows/security_audit.yml

This fixes the Security Audit github workflow by consolidating the two
separte yaml documents that Github Actions didn't like into a single
workflow with multiple triggers. I also added a trigger for PRs as well
as pushes.
Fixes the github security audit action not running correctly.

ci: Fix security audit github action

---

docs/config/README.md
src/configs/time.rs
src/modules/time.rs

Allow for the time module to be shown depending on a configurable time range.
Closes #945

feat(time): Show module with time range 

---

docs/.vuepress/styles/index.styl

https://twitter.com/kwuchu/status/1267436741692133376
We should also add a banner to support the [Equal Justice Initiative](https://support.eji.org/give/153413/#!/donation/checkout). But I'm not familiar with Vuepress, so don't know how to edit the default site layout.
Closes #

docs: #blacklivesmatter

---

src/main.rs

This PR adds a new subcommand, `completions`, which generates `starship` shell completions. This is a [built-in feature](https://docs.rs/clap/2.33.0/clap/struct.App.html#method.gen_completions_to) for clap, so it's a fairly small change.
Shell completions are self explanatory: it's helpful for `starship` users to be able to explore and understand the command-line subcommands and their arguments.
Fixes #1145 
Just manual testing for now. Because the output will depend on both `starship`'s CLI design and `clap` completion generator, it was unclear to me how to write a robust integration test for this feature, though I'm open to suggestions or ideas.
- Added help entries to the CLI subcommand. The website doesn't appear to summarize the subcommands, and there doesn't seem to be a man page, …

feat: Add clap shell completions

---

src/print.rs

Have refactored to include the latest fixes from clippy.

refactor:  Latest suggestions from Clippy

---

src/init/starship.zsh

Uses stored command status and duration when re-rendering the prompt for keymap changes, only updating the status when a new command is run, and duration when a new command is run or blank command (I could remove the clearing here as well, so that hitting enter on a blank line would keep both status and duration from the most recent command).
Closes #957

fix: Retain previous command state on zsh keymap select

---

docs/config/README.md
docs/presets/README.md
src/configs/mod.rs
src/configs/nim.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/nim.rs
src/utils.rs

Adds a nim module for nim.
Nim is a popular enough language to warrant supporting.
closes #159 
Testing was done with 5 new tests, one for each file type and extension and one for version parsing. The tests use temporary directories and files and check if its appropriate to show the nim version.
Ran on Debian 10 Amd64 in bash. Tested config in starship.toml.

feat(nim-lang): Nim module and tests

---

install/install.sh

Adds several cross-platform utility functions to the install.sh script and rewrites core functionality so that it might work on Windows. Among these are:
- Correct platform extensions to match the output of `detect_platform`
- Check to make sure installation directory actually exists
- If sudo is not available, print a message asking the user to manually escalate
- Unpack zip files (used for Windows builds) without using pipes, since zip files cannot be read through pipes
There are still several ways this can fail, e.g. if `unzip` does not exist on the Windows platform, then this script will still error out. However, I think making this bulletproof across platforms might be fairly difficult, so I'll settle for "working under a few conditions on my machine" for the time being.
Closes #1258

fix: Update install.sh to work better on Windows

---

tests/testsuite/directory.rs

This PR fixes the failure in integration tests introduced by format string update in directory on branch feat/format-string

test(directory): Fix integration tests in directory

---

docs/config/README.md
src/configs/username.rs
src/modules/username.rs

This PR refactors the username module text output by using the new string formatter feature.

refactor(username): Added formatter support for the username module

---

src/modules/nodejs.rs

I forgot to mark all tests with `#[test]` attribute.
Continuation of #1311

test(nodejs): add test attribute to omitted tests

---

README.md

I just went through the fresh setup process on a new computer and realized that the suggestion to install Fira Code left users without any of the Nerd Font icons we occasionally use.
This PR updates the docs to suggest folks install a Nerd Font.

docs: instruct users to install a nerd-font

---

src/config.rs

Have added some additional logging to detect problems with malformed
toml.
Relates to #1386 and #1213.

refactor(config): Add additional logging to debug config issues

---

tests/testsuite/directory.rs

This PR fixes the CI error in feat/format-string

test(directory): Quickfix on directory integration test

---

.github/workflows/workflow.yml

Bump Homebrew formula as part of the release workflow.
Automate all the things 🤖 
Special thanks go to @ATiltedTree who's PR #1360 inspired me to do this.

chore: bump Homebrew formula on new release

---

src/modules/custom.rs

Have added some additional logging to the custom module to log an error
that was getting silently dropped.
Related to #1347

refactor(custom): Add additional logging to the custom module

---

docs/config/README.md

Have fixed a leftover from a merge conflict in the config docs.
Related to #1057

docs: Fix merge conflict leftover in config docs

---

src/modules/ocaml.rs

Trim trailing newline from formatted OCaml version.
Addresses https://github.com/starship/starship/pull/1433#issuecomment-653964705
/cc @oteku

fix(ocaml): trim OCaml verison

---

src/modules/ocaml.rs

This removes an unused variable in the ocaml module that I didn't notice
when I merged in the latest changes from the master page.
Keep the code base clean.

refactor(ocaml): Remove unused variable in the ocaml module

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml

A general overhaul for our CI.
Some of the changes include:
- Switching from [actions-rs/toolchain](https://github.com/actions-rs/toolchain) to [ATiltedTree/setup-rust](https://github.com/ATiltedTree/setup-rust) as it's pretty stale
- Adding a consistent naming scheme to our steps
- Separating our deploy steps into a different file
- Condense our cache hits
Also I have been running *a lot* of CI and have yet to see this arbitrarily fail like in #886. But that might change at any moment.
All of this was thoroughly tested and a test release was also created [on my fork](https://github.com/ATiltedTree/starship/releases/tag/v0.45.0). It includes more commit than it should because my fork is missing some tags.
Clean code is better code.
Might solve #886

ci: General overhaul

---

docs/config/README.md
src/configs/cmake.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/cmake.rs
src/modules/mod.rs
src/utils.rs

feat(cmake): Add CMake module

---

docs/config/README.md
src/configs/helm.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/helm.rs
src/modules/mod.rs
src/utils.rs

Signed-off-by: Furkan <furkan.turkal@hotmail.com>
Closes #1443

feat(helm): Add Helm module

---

docs/faq/README.md

According to our docs website analytics, the single most searched term is "uninstall", which signals that we need more clarity on that front.
This PR aims to address that gap in our docs.

docs: add uninstallation instructions to FAQ

---

docs/.vuepress/styles/index.styl

Fix code overflow inside docs.
Overflowed code elements introduce horizontal scroll on mobile devices and move BLM banner outside of viewport.
| Before | After |
| --- | --- |
| ![starship rs_(iPhone X)](https://user-images.githubusercontent.com/1170440/87865842-417b1580-c97a-11ea-856b-e99a87daf4f4.png) | ![localhost_8080_(iPhone X)](https://user-images.githubusercontent.com/1170440/87865844-450e9c80-c97a-11ea-8799-0eab3a6da7d7.png) |

docs: fix code block overflow

---

.gitignore

Add Sublime Text configuration to `.gitignore`.
`.gitignore` file already contains VS Code and IntelliJ IDE configuration patterns so adding another one for editor I use 🙃

chore: add sublime configuration to gitignore

---

src/context.rs

When listing directory content, only check timeout every 256 files
I noticed when listing directory content, the iterator will check system time against timeout for every single item. I thought changing it to check once in a while instead would be faster for large directories. I tried to compare timing locally for a large directory and it decreased the time by about 40-45% so I decided to open this PR to see if this is actually a good idea.
Note I actually use a stripped down fork from a quite old version (0.25.2) though it looks like this particular code hasn't changed that much between now and then. (but the log messages are different it seems)
I tested this change in a directory with 1685 files, without the change the logs read:
```
TRACE starship::context             > Building a …
```

perf: Only check timeout every 256 files

---

docs/config/README.md

Have updated the example toml config to remove an old var and replace it
with the updated replacement.
Keeping the docs updated

docs: Update example configto remove old var

---

.github/workflows/workflow.yml

Have updated the CI config to run clippy on all OSs. This will catch any
issues in OS specific codes. This might increase the amount of
annotations that are created in any of the common code but it should be
better than the alternative.
Related to #1544

ci: Run clippy on all OSs

---

docs/presets/README.md

Add NerdFont icon code for perl
Closes #

docs: Add perl official logo in NerdFont

---

docs/config/README.md
src/configs/mod.rs
src/configs/shlvl.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/shlvl.rs
tests/testsuite/main.rs
tests/testsuite/shlvl.rs

Adds support for the `SHLVL` environment variable as new module.
Closes #1286

feat(shlvl): Add shlvl module

---

docs/config/README.md
src/configs/starship_root.rs
src/modules/line_break.rs

It looks like I rushed my way through writing #1592 and tangled up the functionality of `add_newline` and the `line_break` module in that PR. 
Closes #

revert: "fix: restore add_newline configuration"

---

docs/config/README.md
src/configs/starship_root.rs
src/print.rs

Re-implements the `add_newline` root configuration option, along with documentation.
Closes #1549

fix: re-add add_newline to root config

---

CONTRIBUTING.md

Have updated the clippy command in the CONTRIBUTING.md to match the one
that is used by the CI system.
Related to https://github.com/starship/starship/pull/1664#issuecomment-695050568

docs: update clippy command in the CONTRIBUTING.md

---

docs/migrating-to-0.45.0/README.md

Add a migration guide for the format string changes introduced in v0.45.0.
Closes #1404

docs: add a migration guide for the format string changes

---

docs/config/README.md
docs/migrating-to-0.45.0/README.md

Have updated the configuration docs for the `git_status` to remove a
non-existing option and to add an example for how to achieve the same
effect as with the new format strings.
Closes #1559

docs(git_status): Update git_status module docs

---

docs/.vuepress/config.js
docs/migrating-to-0.45.0/README.md
src/config.rs
starship_module_config_derive/src/lib.rs

- Update the deprecation notice to clarify what was deprecated
- Add a link to docs sidebar with the migration guide
Closes #

chore: update v0.45.0 removal notice

---

docs/.vuepress/config.js

I have translated this.
Closes #

docs: Add a migration guide's link to sidebar for jp 

---

install/install.sh

fixed only coding style (ShellCheck gave me a hint ;-))

style(install): Simple code style fix in install.sh

---

src/utils.rs

Have reduced the log level when we fail to execute a command since this
is happening a lot more that expected, for example if a user checks out
a repo that contains a `.js` file but they don't have node installed.
Closes #1723 
Closes #1701

fix(utils): reduce log level of errors in utils.

---

docs/config/README.md

Have updated the documentation to make the `python_binary` option a bit
more prominent, since this is becoming a more requested requirement now
that more and more systems don't have a default `python` command.
Closes #1700

docs(python): Update the python_binary option

---

src/modules/directory.rs

Powershell prepends `Microsoft.PowerShell.Core\FileSystem::` to some paths e.g. `Microsoft.PowerShell.Core\FileSystem::\\NAS\Share`.  Strip them because they are long and don't really give any useful informaiton.
I haven't seen this with powershell on with linux yet.
Closes #

feat(directory): strip Microsoft.PowerShell.Core\FileSystem:: prefix on windows

---

docs/config/README.md
docs/migrating-to-0.45.0/README.md

Have updated some of the config docs to correct the git_status default
that was incorrect. Have also taken the time to switch some of the
format strings to use toml literal strings rather than normal strings to
simplify the escape strings.
Related to #1741

docs: Update defaults in config docs

---

Cargo.lock
Cargo.toml

There's been a few CI failures with errors about missing `serde_derive` (#1756)
Add it to the dependency list to hopefully prevent this kind of test failure in the future.
Closes #

fix(build): add serde_derive to dependency list

---

src/formatter/string_formatter.rs
src/print.rs

Our CI recently failed and clippy suggested these fixes so I applied them.
Keep clippy happy.

fix: Apply clippy suggestions

---

src/context.rs

Have switched to use a monotonic clock for calculating the timeout when
indexing the current directory for the context to avoid any issues with
calculating the timeout when the systems clock might change.
Closes #1530

chore(context): Use monotonic clock for timeout

---

install/install.sh

Have refactored the platform detection in the install script to try to
better detect Windows when running the Windows install script.
Closes #1341
I have only tested this on Linux since that is the only system I have access to at the moment, hopefully some other  @starship/astronauts can give this a test this on the other platforms.

fix(install): Better platform detection

---

src/logger.rs

I noticed that the logger created lots of empty files on my system. This PR prevents that by only opening the log file for writing when needed.
I also removed `Arc` from `log_file` and `log_file_content` for simplicity. @ATiltedTree is there any reason these needed to be `Arc`?
Closes #

feat(logger): don't create empty log files

---

src/modules/gcloud.rs

The active gclould configuration name can be overridden by setting the shell variable `CLOUDSDK_ACTIVE_CONFIG_NAME`. This patch ensures that a manual override is respected by the gcloud module: previous behaviour was to always look at the globally active config name which is lower in precedence than the contents of this variable. Fixes #1845.

fix(gcloud): respect overrides of the active cloud config

---

src/formatter/string_formatter.rs
src/modules/dotnet.rs
src/modules/hostname.rs
src/modules/nim.rs
src/modules/time.rs
src/modules/utils/directory.rs
src/modules/utils/directory_win.rs
src/print.rs

I ran `cargo fmt` and `cargo clippy` on nightly rust and fixed the suggesions. This could prevent a future rust release from breaking ci.
Closes #

fix: apply nightly clippy & fmt suggestions

---

src/modules/git_branch.rs
src/modules/openstack.rs
src/modules/username.rs
src/print.rs

A few low hanging optimization to avoid allocating `Vec`s that are always the same, and make openstack config reading lazy and more robust.

refactor: a few low-hanging optimizations

---

src/formatter/string_formatter.rs
src/modules/cmd_duration.rs
src/test/mod.rs

Have fixed a few new suggestions from the latest version of clippy.
Closes #

style: Latest clippy suggestions

---

.github/workflows/deploy.yml

Have updated the deploy workflow to build a 32 bit version of Starship
for Linux. This switches the build steps to use the action-rs cargo
since it makes using cross a lot easier.
Closes #1368
Closes #1835
Closes #1843

ci(i686): Build Linux 32-bit version of Starship

---

docs/config/README.md

https://github.com/starship/starship/blob/master/src/configs/package.rs#L17
Closes #

docs: Update package default format to replace /via/is

---

src/init/starship.bash

This fixes a regression where the exit code of the most recently run
command was not correctly recorded in the bash init script.
Closes  #2097

fix(bash): Fix broken bash init script

---

src/init/mod.rs

see #1652 
Refactored the init logic.
Clean commit tree.
fixes #1354
fixes #634
fixes #590

feat: Add support for cygwin/msys2/git-bash evironment

---

README.md
docs/config/README.md

Vuepress couldn't handle syntax-highlighting the `ps1` language. I replace the usage with `powershell` which both Github and vuepress understand. I also replaced on instance of `sh` with `powershell`.
Closes #

docs: highlight powershell in vuepress

---

src/context.rs
src/modules/character.rs
src/modules/dotnet.rs
src/modules/gcloud.rs
src/modules/git_state.rs
src/modules/nodejs.rs
src/modules/package.rs
src/modules/php.rs

Basically applies clippy suggestions. Aside from minor styling issues, they are relevant.
1. Prefer `std::path::Path` over `std::path::PathBuf`.
2. Simplified `String` formatting code.
3. Remove unnecessary `Option` wrapper.
Closes #

fix: Applied clippy warnings

---

docs/config/README.md
src/configs/python.rs
src/modules/python.rs

Does the changes as proposed in the issue to python format string and version string evaluation strategy

perf(python): Lazy eval of python version command

---

docs/config/README.md
src/configs/dotnet.rs
src/configs/erlang.rs
src/configs/go.rs
src/configs/helm.rs
src/configs/julia.rs
src/configs/nim.rs
src/configs/ruby.rs
src/configs/rust.rs
src/modules/dotnet.rs
src/modules/erlang.rs
src/modules/golang.rs
src/modules/helm.rs
src/modules/julia.rs
src/modules/nim.rs
src/modules/ruby.rs

Adjust format strings for all modules where format is already lazily executed
Referring to #2111

fix: Adjust default format strings

---

docs/config/README.md
src/configs/elm.rs
src/modules/elm.rs

Lazy format evaulation and format string change for elmlang
Related to #2111

perf(elm): Lazy eval elm

---

docs/config/README.md
src/configs/java.rs
src/modules/java.rs

Lazy format evaulation and format string change for java
relates to #2111

perf(java): Lazy eval java

---

docs/config/README.md
src/configs/dart.rs
src/modules/dart.rs

Lazy format evaulation and format string change for dartlang

perf(dart): Lazy eval dart

---

docs/config/README.md
src/configs/lua.rs
src/modules/lua.rs

Execute version for Lua Lazily and update format string

perf(lua): Lazy eval lua

---

src/context.rs
src/formatter/string_formatter.rs
src/modules/package.rs
src/print.rs

Minor code cleanups, and clippy lint fixes. No functional changes intended.

Misc cleanup and clippy lints

---

docs/config/README.md
src/configs/purescript.rs
src/modules/purescript.rs

Evaluate purescript version command lazily and update format string

Perf(purescript): Lazy eval purescript

---

docs/config/README.md
src/configs/zig.rs
src/modules/zig.rs

Evaluate format call of zig lazily, update format string
Relates to: #2111

perf(zig): Lazy eval zig

---

src/init/starship.zsh

We currently invoke `starship time` in a sub-shell to compute time, which is non-performant. By using $EPOCHREALTIME,
which is an inbuilt env-var in ZSH5, we can get better performance. This commit only targets ZSH5+ and maintains the
old behaviour.
Ref [docs on EPOCHREALTIME](http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#index-EPOCHREALTIME).
The current approach is not very performant and this provides a reliable optimization to prompt startup for virtually all ZSH users. (ZSH5 released in 2012 so userbase not in ZSH5 will be small).
Closes #1750 
```
~ ❯ echo "No Prompt" && benchmark_zsh
No Prompt
Benchmark #1: zsh -i -c exit;
Time (mean ± σ):      58.8 ms ±   3.2 ms    [User: 29.7 ms, System: 22.9 ms]
Range (min … max):    55.6 ms …  70.2 ms    50 runs
~ ❯ echo "Starship …
```

perf: use built-in EPOCHREALTIME envvar to compute cmd_duration for ZSH5+

---

docs/config/README.md

This intends to make the performance issue with the terraform version
more obvious.
Closes #2084

docs(terraform): Make version perf issue obvious

---

docs/config/README.md

I edited based on this:
https://github.com/starship/starship/blob/3c31c4b99d509ca0ca06bf9b4addbea1259cdac9/src/configs/status.rs#L22
This was not working when I just copy and paste this part in my `starship.toml`.

docs: fix the format of status.format

---

LICENSE

The license needs updating since it is now 2021!

docs: update license to include 2021

---

docs/config/README.md
src/modules/docker_context.rs

This adds some basic tests to the docker_context module. Have also fixed the docs to match the default config. 
Closes #2133

test(docker_context): Add basic tests to module

---

.github/workflows/deploy.yml

During the release process, if a build fails, the whole release process is thrown out the window.
This will cause the release to proceed with the artifacts that are correctly built.

ci: continue release on error

---

README.md
docs/README.md
docs/config/README.md
src/bug_report.rs
src/context.rs
src/init/mod.rs
src/init/starship.elv
src/main.rs

Adds support for the elvish shell.
This does not yet work with the currently released version of elvish because only `HEAD` (v0.15) supports ANSI color escapes in the prompt.
elvish has an error system and does not expose exit codes.
Closes #1115

feat: add support for elvish shell

---

src/modules/username.rs

Based on #1157. This PR makes the username module use `nix::unistd::geteuid()` to get the current user id instead of the external command `id -u`. This should be faster and more reliable.
Closes #2285

perf(username): get uid without external command

---

src/modules/aws.rs
src/modules/character.rs
src/modules/cmd_duration.rs
src/modules/conda.rs
src/modules/directory.rs
src/modules/dotnet.rs
src/modules/env_var.rs
src/modules/git_status.rs
src/modules/hg_branch.rs
src/modules/hostname.rs
src/modules/jobs.rs
src/modules/line_break.rs
src/modules/nix_shell.rs
src/modules/package.rs
src/modules/ruby.rs
src/modules/shlvl.rs
src/modules/singularity.rs
src/modules/status.rs
src/modules/time.rs
src/modules/username.rs

This PR fixes the new rust 1.50 clippy lints.
Closes #

refactor(clippy): fix new lints

---

.github/workflows/deploy.yml

For building starship for the `aarch64-apple-darwin` instead of switching the base image to `macOS-11.0` it's also possible to switch to a newer `SDKROOT` in the existing `macOS-latest` image.
Closes #

build: fix aarch64-apple-darwin builds

---

docs/config/README.md

Have clarified changing the starship config file using the
`STARSHIP_CONFIG` env var.
Closes #2227

docs(config): Clarify changing starship config file

---

docs/faq/README.md

Have added `starship explain` to the FAQ.
Related to #2232

docs(faq): Add `starship explain` to FAQ

---

.github/workflows/deploy.yml

The AUR package was adopted as a community package so we don't need to run the AUR deploy action anymore:
https://archlinux.org/packages/community/x86_64/starship/
Also some small YAML formatting changes.
I just saw it was adopted so I created this PR

chore(github-actions): Remove AUR deploy

---

docs/faq/README.md

Change case of reference to match what is needed.
The correct doc location isn't opened otherwise.

fix(docs): "Command Duration" section link target

---

docs/config/README.md
docs/presets/README.md
src/configs/mod.rs
src/configs/scala.rs
src/configs/starship_root.rs
src/module.rs
src/modules/mod.rs
src/modules/scala.rs
src/utils.rs

Add a module for identifying scala version. 
Tested on scala 2 + dotty/scala 3
As a starship user, I'd like to be able to see my current scala version while happily traversing projects. 
Closes #651 ( at least partially ) 
It's important to note that: 
* Scala tooling is a bit on the slow side, so it may require changing ``command_timeout``, especially when using version shims like asdf
```
Benchmark #1: ./scala -version
Time (mean ± σ):     536.7 ms ±  73.6 ms    [User: 703.9 ms, System: 101.9 ms]
Range (min … max):   504.6 ms … 745.4 ms    10 runs
Benchmark #1: ./scalac -version
Time (mean ± σ):     397.4 ms ±   5.2 ms    [User: 536.2 ms, System: 86.3 ms]
Range (min … max):   390.3 ms … 408.0 ms    10 runs
Benchmark #1: starship module scala
Time (mean ± σ):     402.6 ms ±   4.7 ms …
```

feat(scala): Add scala module

---

src/init/starship.zsh

No need to forcefully set the `PROMPT` variable every time the prompt is to be shown. Just set it once, leaving the command to be evaluated every time the prompt is to be shown, by enabling the `promptsubst` option.
Setting it once is also friendlier to users that want to experiment with another prompt theme by temporarily setting `PROMPT` to something else.  This would currently not be possible, because the variable is always reset before every prompt draw (precmd) and keymap change (zle-keymap-select).
Some other updates to take better advantage of the zsh script dialect:
* `$` is not required to read variables inside `(( ))` arithmetic expressions.
* The zsh dialect to check if a variable is set is `${+var}`. Better than `${var+1}`, which substitutes 1 if var is set, which is intended …

fix(zsh): Set PROMPT just once

---

README.md
docs/config/README.md

Remove trailing whitespace and extra newlines.
NodeJS **Variables** subsection inside configuration docs is broken https://github.com/starship/starship/blob/3513aae/docs/config/README.md#nodejs

docs: format markdown

---

src/config.rs
src/context.rs
src/formatter/parser.rs
src/modules/git_branch.rs
src/modules/git_commit.rs
src/modules/git_status.rs
src/modules/hg_branch.rs
src/modules/kubernetes.rs
src/modules/utils/path.rs
src/test/mod.rs

chore(clippy): fix new lints

---

src/modules/singularity.rs

Dealing with string instead of an option by leveraging `?` operator.
This is rather a small change that aligns this module with similar implementations.

refactor(singularity): use `?` operator

---

src/modules/username.rs

Reformat code to match module documentation. Added ordinal numbers serving as _link_ between conditions listed inside docs and corresponding code clauses used as building blocks for username display toggling.
Synchronize documentation with actual code flow.

refactor(username): reformat code to match docs

---

.cargo/audit.toml

`sys-info` was updated, so the audit warning doesn't need to be ignored anymore.
Closes #

chore: remove audit.toml again

---

README.md
docs/README.md

Added documentation about upgrading starship itself via bash script.
Closes #2395

docs: Add update documentation

---

Cargo.toml
starship_module_config_derive/Cargo.toml

Filter out unnecessary crate contents.
Currently published (`v0.51.0`) [crate](https://static.crates.io/crates/starship/starship-0.51.0.crate) contains ~a lot of~ some unnecessary stuff.
<details>
<summary>Complete <code>starship-0.51.0.crate</code> contents listing</summary>
```
starship-0.51.0/.cargo/audit.toml
starship-0.51.0/.cargo_vcs_info.json
starship-0.51.0/.github/FUNDING.yml
starship-0.51.0/.github/ISSUE_TEMPLATE/Bug_report.md
starship-0.51.0/.github/ISSUE_TEMPLATE/Feature_request.md
starship-0.51.0/.github/ISSUE_TEMPLATE/config.yml
starship-0.51.0/.github/PULL_REQUEST_TEMPLATE.md
starship-0.51.0/.github/chglog/CHANGELOG.tpl.md
starship-0.51.0/.github/chglog/RELEASE.tpl.md
starship-0.51.0/.github/chglog/changelog.yml
starship-0.51.0/.github/chglog/release.yml …
```

chore: filter crate/s contents

---

src/modules/directory.rs

Have added some comments to explain the settings we are using in some
tests.
Related to #2497

style(directory): Add comments for test settings

---

docs/faq/README.md

Use POSIX `sh` instead of Bash to make uninstall instructions shell agnostic.
As suggested here: https://github.com/starship/starship/pull/2483#issuecomment-803616815

docs(faq): change uninstall snippet to use `sh`

---

docs/config/README.md

Have added documentation for the top level `command_timeout` option.
Closes #2544

docs: Document the `command_timeout` option

---

docs/config/README.md

Add links of official website/documentation to software (terms), if necessary.
Please correct if there are any missing/wrong/better links.
I also took the chance to correct a few case issues and made Terraform section title more specific to prevent it from breaking in the future.
Some modules are for less known software (Singularity, Red, VCSH, to name a few), therefore a link to their official sources in order to inform the user and help them consider which modules are needed.

docs(config): add links to software

---

.gitattributes

This change adds a `.gitattributes` file that ensures all text files are checked out with lf line endings, to improve combability with linux executables on windows.
This does not seem to break the old PowerShell 5.1 or PowerShell 7.
Closes #2449

fix(init): always use lf line endings

---

.github/workflows/merge-dependabot.yml

ci: auto-merge dependabot PRs on a schedule

---

src/modules/gcloud.rs

Honor `CLOUDSDK_CORE_PROJECT` environment variable.
This is essentially #2588 rebased/stacked onto #2592
Closes #2588
Closes #2540
---
/cc @cymruu

feat(gcloud): honor `CLOUDSDK_CORE_PROJECT` env variable

---

.github/workflows/deploy.yml

We've had some cases where the release process failed mid-way, but the version was still rolled out to Brew and Cargo.
This updates the release process to depend on a successful build before being published on those repos.

ci: publish on successful release

---

src/print.rs

This introduces a new `Grapheme` type (wrapper for `str`) together with `UnicodeWidthGraphemes` trait that allows calculating grapheme aware widths of strings and graphemes.
I wanted to abstract away grapheme aware width calculations behind the simple `.width_grapheme()` interface. In order to do that completely, this should probably get moved elsewhere, any suggestions? :thinking:

refactor(print): introduce `UnicodeWidthGraphemes` trait

---

src/modules/ocaml.rs

Extend test suite with custom switch indicator test cases.
Continuation of #2503

test(ocaml): test custom switch indicators

---

src/modules/deno.rs
src/modules/red.rs

Add missing project filter rules.
Without necessary wiring respective config sections are ignored. :warning:

fix: add missing project filter rules

---

docs/config/README.md
src/configs/mod.rs
src/configs/v.rs
src/modules/package.rs
src/modules/vlang.rs

Add support for [`vpkg`](https://vpkg-project.github.io/) - an alternative package manager for V. 
Expand the default set of detected files for V to make detection more accurate.

feat(vlang): support `vpkg`

---

docs/config/README.md
src/modules/package.rs
src/utils.rs

This PR adds support for the package module for a nimble project to show version number in the project directory.
~~I have added a new function `find_file`  that takes a directory and a predicate. It iterates over all files in a given directory and returns a filename if it satisfies the given predicate. This function is used to detect if a given directory is a nimble project by checking `file_name.ends_with(".nimble")`.~~
If a directory is found to be a nimble project, `extract_nimble_version` then calls `nimble dump --json` to get the package version. I used `json` instead of the default `ini` format for dump because I could not find an existing `ini` parser used in the project but `json` parser was already there used predominantly for most packages.
It now uses context to check for the …

feat(nim): add support for nimble project package version

---

docs/config/README.md

Have added an additional example for the `python_binary` option to show
how to display the version of python from inside a local virtual
environment.
Closes #1529

docs(python): Add additional python_binary example

---

README.md
install/install.sh

Have added a basic help to the install script to make it a bit easier to
use.
Closes #2727

feat(install): Add help argument to install.sh

---

src/utils.rs

Have added some additional logging to the `read_file` util to make
debugging issues easier.
Related to #2723

refactor(utils): Add extra logging to read_file

---

docs/presets/README.md

A few of the supported segments were missing from the preset, have now
been added.

docs: Added more bracketed segments

---

src/modules/mod.rs

This PR fixes a new clippy warning ahead of the release of rust 1.53.0.
Closes #

fix(clippy): fix new lint warning

---

Cargo.lock
Cargo.toml
src/context.rs
src/modules/battery.rs
src/modules/mod.rs
src/test/mod.rs

Add some tests to the battery module, make it testable by mocking out the code that fetches battery info.
Closes #2598
I don't have a device with a battery handy atm, but I did test on my linux desktop. It didn't crash, and in theory this doesn't change anything...

test(battery): add battery tests

---

README.md
docs/README.md

A slight addition to the nushell setup instructions, guiding people to find their nushell config path.

docs(nu): specify how to get nushell config path

---

src/modules/git_status.rs

Have updated the git_status module to work if the worktree has been
changed to a different directory than the repository root directory.
Closes #2808

fix(git_status): Fix when the worktree != root dir

---

src/config.rs
src/configs/starship_root.rs
src/modules/directory.rs
src/modules/dotnet.rs
src/modules/kubernetes.rs
src/modules/status.rs
src/modules/utils/directory_win.rs
src/print.rs
starship_module_config_derive/src/lib.rs

Removes some redundant `.iter()`/`.into_iter()` calls to improve code readability
Closes #

refactor: simplify iterator usage

---

src/modules/package.rs

The setup.cfg version key allows [`attr:` and `file:` directives][1] to load the actual value from elsewhere. Treat these as if no version was found, since the text of the directive isn't the version number we're after.
[1]: https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#specifying-values
Parsing of `setup.cfg` was introduced in #2890.
I added tests covering the `attr:` and `file:` directives. I ran `cargo test` to verify that they failed without implementation changes.
I then changed the implementation and ran Clippy and `cargo test`.
I'm not sure if a documentation update is required.

fix(package): Ignore setup.cfg attr: and file:

---

docs/config/README.md

docs: fix grammar in config README

---

src/modules/mod.rs

This PR adds descriptions for the elixir, elm and singularity modules and sorts the modules in the `match`-statement. I also added a test to ensure all future modules have a description.
Related: #3076

docs(modules): add missing module descriptions

---

.github/workflows/workflow.yml

This implements a system for caching dependencies.
Closes #
This makes the CI run faster

ci: use an alternative caching method

---

CONTRIBUTING.md

Adds a module checklist in CONTRIBUTING.md to make it easier to remember (for both authors and reviewers)
what steps need to be taken when merging a new module.
It's really hard to remember everything that needs to be done sometimes.
This is very much a draft and I would appreciate any suggestions for how to change the wording/structure.
N/A, but would appreciate to see if there's anything I missed.

docs: Add a checklist for new modules

---

docs/faq/README.md

Have added a question and answer about commands timing out and what to
do along with  some basic docs on debugging to the FAQ.
Closes #2821

docs(faq): Add debugging and timeout Q&As

---

src/modules/memory_usage.rs

This PR removes the `%` character handling for `zsh` from the `memory_usage` module, which caused them to be escaped twice. Instead, this is handled globally with #3192. #3192 mistakenly only removed earlier `%`-handling from the `battery` module, and the `memory_usage` was missed.
Closes #3192

fix(memory_usage): remove duplicate `%` handling

---

docs/config/README.md

fixes #3199
this PR adds quotes to the battery example in the docs  
Closes #3199 
- [ x] I have updated the documentation accordingly.

docs(battery): add quotes in example

---

Cargo.lock
Cargo.toml
src/modules/battery.rs

Replaces the unmaintained [`rust-battery`](https://github.com/svartalf/rust-battery) dependency with a fork owned by the starship org, [`starship-battery`](https://github.com/starship/rust-battery).
The aim of this fork is to not deviate too far from the original, only merging fixes for known issues affecting Starship or restricting any planned features.
Besides some reshuffling of the repo, the only two meaningful changes in our fork so far have been:
- https://github.com/starship/rust-battery/commit/ae72f727197b17f9297a78cd10e2a5e036be5c16
- https://github.com/starship/rust-battery/commit/904cd36b4f552d775d2363b3d5ced6f3b290548f
Merging the following two PRs in the original repo:
- https://github.com/svartalf/rust-battery/pull/92
- https://github.com/svartalf/rust-battery/pull/93
Closes …

fix: replace battery with starship-battery

---

.github/chglog/changelog.yml
.github/chglog/release.yml

Have updated the chglog `changelog` config file to match the `release`
config and use the same order for the titles. Have also removed some
commented out config from both config files.
Closes #

chore(chglog): Clean up chglog config

---

.github/chglog/changelog.yml
.github/chglog/release.yml
.github/workflows/deploy.yml

Have updated the version of chglog we use in the deployment pipeline to
the most recent version and updated the config order the config
correctly.
Related to #3205

ci(chglog): Update chglog and clean up config

---

src/modules/conda.rs
src/modules/directory.rs
src/modules/utils/directory.rs

This PR improves truncation detection by tracking if a path was truncated instead of using heuristics. Previously, certain paths or substitutions were detected as truncated incorrectly.
Closes #2253
Closes #3246

fix(directory): improve truncation detection

---

src/configs/line_break.rs
src/modules/gcloud.rs
src/modules/git_branch.rs
src/modules/git_commit.rs
src/modules/golang.rs
src/modules/helm.rs
src/modules/julia.rs
src/modules/status.rs

This PR fixes the new rust v1.57.0 clippy lints (and some more from nightly).
Closes #

chore(clippy): fix new clippy lints

---

src/modules/aws.rs

This fixes #3334 . 
When opening a directory as a file the intial open works, while
subsequent line-reads will fail with _is a directory_.
Since erroring line-reads were just skipped this lead to an
endless loop.
Locally I was able to easily reproduce the endless loop, and that the change fixes it.

fix(aws): prevent endless loop when AWS config file is a directory

---

src/modules/rust.rs

This PR changes override parsing to be more reliable (spaces in filenames, most specific matches) and [makes the prefix detection work properly on Windows](https://github.com/starship/starship/issues/3358#issuecomment-1002265978).
Because #3358 doesn't occur when running from terminal, I assumed this was related to unset cwd like #3309, but that didn't end up fixing it, but I am including the changes anyway because it increases timeout coverage.
Closes #3358

fix(rust): fix overrides on windows and set cwd

---

docs/advanced-config/README.md
src/init/starship.xsh

xonsh supports RPROMPT, but it wasn't used by starship.
Closes #

feat(xonsh): support rprompt

---

.github/ISSUE_TEMPLATE/Bug_report.md

Somehow, the whitespacing on the header for the issue template
got screwed up, leading to odd wrapping behavior on the
website. In addition, added default shell details for shells
that aren't zsh/fish.

docs: Update GitHub ISSUE_TEMPLATE

---

docs/config/README.md
src/modules/package.rs

Add package version extracted from dart package.
flutter and dart project have a package manager with file pubspec.yaml
i added some code for package module to extract dart package version.
configure document with new feat updated also.
Closes #

feat(package): support for dart pub version

---

docs/config/README.md

rust-notify -> notify-rust in cmd_duration's docs
Feature name in Cargo.toml and the crate name using is `notify-rust`, but `rust-notify` was in the docs.
Closes #

docs(cmd_duration): rust-notify -> notify-rust

---

docs/advanced-config/README.md

DEBUG trap mechanism in bash as described [here](https://starship.rs/advanced-config/) did not work without setting the shell option `functrace` first. This PR updates that example code so that it works correctly.
Closes #1524

docs: Add set commands to advanced config doc

---

.github/workflows/format-workflow.yml
docs/config/README.md

Have updated the workflow to only run the "Block Translated Changes" job
on PRs since it will fail when run on pushes to a branch. Have fixed the
formatting while I was here.

ci: Only run translation block work flow on PRs 

---

README.md

Add instructions for installation via `snap`.
Closes #

docs: add snapcraft to installation instructions

---

LICENSE

Another year, another version bump in the LICENSE file :)

chore: Update LICENSE file for 2022

---

CONTRIBUTING.md

Fixed typo of variable in CONTRIBUTING.md
Closes #

fix: typo of variable in CONTRIBUTING.md

---

Cargo.lock
Cargo.toml
src/main.rs

Update clap to 3.1.0 and fix new deprecation warnings.
Closes #3623

build: bump clap from 3.0.14 to 3.1.0

---

Cargo.lock
Cargo.toml
src/main.rs

https://github.com/baoyachi/shadow-rs/pull/76
Closes #3649

build: bump shadow-rs from 0.8.1 to 0.9.0 

---

README.md
docs/README.md
docs/faq/README.md
docs/installing/README.md

Update curl installation method to not use command expansion.
Closes #3664

fix: use shell-compatible curl install

---

Cargo.toml

Add `/starship.exe.manifest` to `Cargo.toml` to fix builds from crates.io.
Closes #3709
N/A

build: Add /starship.exe.manifest to Cargo.toml include

---

install/install.sh

Fix typo in help message.
Currently the help message has a typo in the description of the `--help` option:
```bash
$ curl -sS https://starship.rs/install.sh | sh -s -- --help
install.sh [option]
Fetch and install the latest version of starship, if starship is already
installed it will be updated to the latest version.
Options
-V, --verbose
Enable verbose output for the installer
-f, -y, --force, --yes
Skip the confirmation prompt during installation
-p, --platform
Override the platform identified by the installer [default: apple-darwin]
-b, --bin-dir
Override the bin installation directory [default: /usr/local/bin]
-a, --arch
Override the architecture identified by the installer [default: x86_64]
-B, --base-url
Override the base URL used for downloading releases [default: …
```

chore(install): fix typo in help message

---

docs/config/README.md
src/configs/nodejs.rs
src/modules/nodejs.rs

These are [TypeScript counterparts](https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions
) of Node.js `.mjs` and `.cjs` file extensions.
Tests were added but removed later since they are unnecessary and are probably going to be dropped in the future, see conversations below.
Closes #

feat(nodejs): check for `.mts` and `.cts` files

---

docs/config/README.md
src/modules/aws.rs

Accept `sso_start_url` in addition to `credential_process`. I have not tested this with a real setup.
Closes #3717

fix(aws): accept sso credentials

---

src/modules/aws.rs

This PR changes the AWS module config and credential file parsing to use the `rust-ini` library. This simplifies the code and improves the handling of leading whitespace characters. In addition, this PR ensures the AWS files are only read once by using `OnceCell`s.
This PR should simplify the implementation of #3834.

refactor(aws): improve parsing of config files

---

docs/.vuepress/public/presets/toml/nerd-font-symbols.toml

docs(preset): Add python nerd font icon

---

.github/workflows/workflow.yml

Hopefully, using a token is more reliable. Also restrict coverage upload to the main repo.
Closes #

ci(codecov): use codecov token

---

.github/workflows/deploy.yml

Prevent Release Please PRs from being opened in forks.
Closes #

ci(release-please): only run in main repo

---

.github/workflows/deploy.yml

Locate and merge the existing Crowdin PR as part of the deployment process.
Merging existing Crowdin PRs is currently a manual process that is often forgotten before a release.

ci: automate merging of Crowdin PR before publishing

---

Cargo.toml
Cross.toml

The next cross release will include FreeBSD support without this file. As the docker registry will move to GitHub, removing it will ensure no outdated image will be used.
Closes #

build(freebsd): remove `Cross.toml`

---

docs/config/README.md

Consistent notation about  `package` module 
Closes #3948

docs: package module documentation consistency

---

Cargo.toml

Fixed typo in Cargo.toml
`stablizized -> stabilized`
Closes #

chore: fix typo in Cargo.toml

---

docs/.vuepress/public/presets/toml/plain-text-symbols.toml

docs: add lua to plain text preset

---

.github/workflows/workflow.yml

Run the installer test even if not triggered by `push_event`, because the test wasn't running on master.
Closes #

ci(windows): fix installer condition

---

src/context.rs
src/modules/custom.rs
src/serde_utils.rs
src/utils.rs

Fixed some typos.
All modified Typo's are comments.
Closes #

docs: fix some typos in comments

---

install/install.sh

Have fixed a minor spacing issue in the help output of the install
script.
This annoyed me but not enough to open a ticket.

fix(install): Have fixed a spacing issue in output 

---

Cargo.toml

Including media/icon.ico so that the package published works on Windows.
Closes #4083
I didn't really know how to go about documenting/writing tests for missing files.

build: include media/icon.ico

---

.github/workflows/release.yml

ci(release): draft release until binaries are uploaded

---

src/context.rs
src/formatter/string_formatter.rs
src/init/mod.rs
src/init/starship.bash
src/modules/battery.rs
src/modules/custom.rs
src/modules/docker_context.rs
src/modules/pulumi.rs
src/modules/utils/directory_win.rs
src/print.rs

chore: fix typos in comments

---

src/configs/starship_root.rs
src/context.rs
src/formatter/string_formatter.rs
src/modules/vlang.rs

Fix new rustc 1.62.0 clippy lints.
Closes #

chore: fix new clippy lints

---

src/modules/custom.rs

Return a `Module` instance with timing information for custom modules even if the `when` execution returns `false`.
Closes #4093.
Previously the custom module evaluation function would return early if the `when` execution returned `false`, but the timing information was only added when returning a module instance at the end of the function. This meant that slow `when` commands would invisibly slow down the prompt. This change causes the function to not return early in this case and instead return a proper module instance with timing information whether or not the `when` command indicates that the module should be shown.
I tested this manually with the custom command I described in #4093. I wasn't sure whether I should add a test since it would probably need to have small sleep in it, …

fix(timings): count time spent on custom on 'when' command failure

---

src/modules/rust.rs

This PR changes two things:
1. Instead of running `rustup run <toolchain> rustc --version` try if `~/.rustup/toolchains/<toolchain>/bin/rustc --version` works first
2. Instead of running `rustup default`, try reading `default_toolchain` from `~/.rustup/settings.toml`
I didn't add tests, because I'm not sure how to best approach that in this module.
On Windows, this improves performance from `~45ms` to `~15ms` in `starship timings` for me.
Closes #

perf(rust): avoid calling `rustup` in more conditions

---

src/modules/package.rs

Newer versions of cargo support setting `version` indirectly via `version.workspace = true`. Support reading the version by querying the parent workspace and reading `workspace.package.version`. Additionally, if the initial `Cargo.toml` defines `workspace.package.version`, also try reading that.
Closes #3928

feat(package): support cargo workspace versions

---

docs/config/README.md

Closes #
Update doc.
1. fix order
2. new elements in `$all`

docs: update configuration format list

---

.github/config-schema.json
docs/.vuepress/public/presets/toml/bracketed-segments.toml
docs/.vuepress/public/presets/toml/no-runtime-versions.toml
docs/.vuepress/public/presets/toml/plain-text-symbols.toml
docs/config/README.md
src/configs/bun.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/bun.rs
src/modules/mod.rs
src/utils.rs

This PR adds a module for the [bun](https://bun.sh) JavaScript runtime.
Closes #

feat: add bun module

---

Cargo.lock
Cargo.toml
build.rs
docs/presets/bracketed-segments.md
docs/presets/nerd-font.md
docs/presets/no-runtimes.md
docs/presets/pastel-powerline.md
docs/presets/plain-text.md
docs/presets/pure-preset.md
src/main.rs
src/print.rs

Added `starship preset` subcommand:
- `starship preset -l` lists all available presets.
- `starship preset <name>` prints a preset with a specified name.
Closes  #4006

feat: Add starship preset command

---

docs/.vuepress/public/presets/toml/plain-text-symbols.toml

This adds two more symbols to the plain text preset.

docs(preset): two more plain symbols

---

src/context.rs

Log git repo discovery failures and basic information about the resolved repo location along its trust level.
Closes #

chore(git): improve logging

---

docs/advanced-config/README.md
src/init/starship.fish

Enables left and right transience for Fish shell, similar to Cmd and PowerShell
Closes #888

feat(fish): Enable left and right transience

---

src/modules/directory.rs

Fix the issue #4294 
Closes #4294 
Closes #3998

fix(directory): don't strip duplicate directory names twice

---

README.md

docs: duplicate installation instruction for Nixos in readme

---

docs/config/README.md

Notation distortion has been corrected.
Closes # https://github.com/starship/starship/issues/2935

docs: canonicalize the use of quotes for default values

---

docs/README.md

added [Winget](https://github.com/microsoft/winget-cli) as a installation method in the doc
winget is the official package manager for windows and its installed by default so user's don't have to install other 3rd party package manager such as `scoop` or `chocolatey`  
> which are great package managers
to install starship

docs: added winget

---

docs/config/README.md

Improvement on inconsistencies and incompleteness #2935

docs(config): Add missing default values

---

docs/config/README.md

Hi :wave:
Starship is very cool :+1:
I spend some time thinking about what the sentence should mean.

docs(config): Fix typo in kubernetes section

---

src/modules/git_commit.rs

Check `tag_disabled`, don't show tag info when it is true. I'm not familiar with rust, so the new test is just a modified copy of the below one.
Closes #4526 
The first starship is built from master, and the second is built from this PR.

fix(git): check `tag_disabled` option

---

docs/advanced-config/README.md

* This URL is not able to be directly clicked from the docs website, and is pasted in plaintext
* This change allows the URL to be followed 
* This change makes the page look nicer 
* Linking the URL like this follows precedent for the page

docs: Updated advanced-config link formatting

---

README.md

As our first "Supporter Tier" sponsor, this PR adds their name and link to our README.
Closes #

Add Dimension as Starship sponsor

---

.github/workflows/release.yml
.github/workflows/workflow.yml
install/windows/choco/chocolateyInstall.ps1
install/windows/choco/starship.nuspec
install/windows/choco/update.ps1

This PR adds a chocolatey package publish step to the release pipeline, and a test checking if the package can be created. 
Related #3470

feat(release): add chocolatey publishing

---

src/modules/gradle.rs

#4423 introduced clippy warnings that #4715 did not yet fix.
Closes #

chore: fix clippy warnings in gradle module

---

src/modules/git_commit.rs

Starship git_commit latest tag lightweight test case failed, i fixed the error to pass the test case

fix(git_commit): fix potential test failure

---

Cargo.lock
Cargo.toml
src/modules/git_commit.rs

`apply_environment` is now handled [automatically via git configuration](https://github.com/Byron/gitoxide/releases/tag/git-repository-v0.30.0).
Closes #

build(deps): update gitoxide crates

---

docs/README.md

Fix a small typo: 'to to' -> 'to'
Just see it in the documentation, IMO, it's always better to correct those typos.

docs(typo): replace 'to to' with 'to'

---

docs/.vuepress/public/presets/toml/plain-text-symbols.toml
src/modules/status.rs

Adding status section to plaintext preset.
Closes #4744

docs(preset): Plaintext status added

---

src/configure.rs
src/context.rs
src/logger.rs
src/modules/cmd_duration.rs
src/modules/env_var.rs
src/modules/git_status.rs
src/modules/hg_branch.rs
src/modules/nix_shell.rs
src/modules/nodejs.rs
src/modules/time.rs
src/print.rs

This PR fixes the new rust 1.67 clippy warnings.
Closes #

chore: fix clippy warnings for rust 1.67

---

docs/config/README.md
docs/faq/README.md

Updated docs, mainly fixing typo.
Closes #

docs: fix typo

---

.github/config-schema.json
docs/config/README.md
src/configs/java.rs
src/modules/java.rs

Add https://sdkman.io/ for Java. If a `.sdkmanrc` file is present, show the Java version.

feat(java): Add `.sdkmanrc` for Java

---

.github/workflows/workflow.yml

Instead of `git` commands, this will use the reviewdog action-suggester action to give feedback on required config changes to try it out as a replacement for the `actions-rs` `cargo fmt` action.
Related #4725

ci: use `reviewdog/action-suggester` for config-schema check

---

src/modules/nim.rs

chore: fix clippy warnings for rust 1.68

---

src/init/mod.rs

Needed to make starship work with elvish
https://github.com/starship/starship/issues/4924
Closes #

fix(init): avoid cygpath for starship binary path

---

.github/config-schema.json
.github/workflows/spell-check.yml
Cargo.toml
install/macos_packages/readme.md
install/windows/main.wxs
src/configs/fennel.rs
src/configure.rs
src/modules/env_var.rs
src/modules/fennel.rs
src/modules/nix_shell.rs
src/modules/package.rs
src/modules/rust.rs
src/test/mod.rs
typos.toml

Add `typos` to `workflows` and fix existing typos.
Closes #

chore: add spell checker to workflows

---

install/windows/choco/starship.nuspec
install/windows/choco/update.ps1

Following chocolatey moderator review comments, this PR removes the dependency on chocolatey, since it is safe to assume that no user is using a version older than required.
Closes #

chore(choco): remove chocolatey dependency

---

Cargo.lock
Cargo.toml
src/modules/battery.rs

build(deps): update rust crate starship-battery to 0.8.0

---

docs/advanced-config/README.md

The section is about updating the Window Title but the PowerShell example was about the prompt
Stay on topic, and help people to actually change the window title using PowerShell

docs(pwsh): use a more convenient method to update the window title

---

CONTRIBUTING.md
README.md

Updated CONTRIBUTING.md and README.md.
Closes #

docs: update CONTRIBUTING.md and README.md

---

Cargo.toml

Disable unnecessary/unused regex features.
To reduce the binary size (by ~400 kB).

build(deps): disable unnecessary/unused regex features

---

Cargo.lock

This appears to make stable Windows compile again.
Closes #

fix: bump libz-ng-sys

---

src/modules/swift.rs
typos.toml

chore: fix typos

---

Cargo.lock

Nightly builds are failing, running `cargo update` appears to fix it.
#5284 #5285

chore: run `cargo update` to unblock nightly CI

---

src/modules/git_status.rs

This PR improves `git_status` by querying the stash count with gitoxide library methods instead of an external git-cli command.
Benchmark with `git_status.format = "$stashed"`:
| Data Source | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| git-cli | 13.7 ± 1.2 | 12.3 | 28.6 | 3.04 ± 0.63 |
| gitoxide | 4.5 ± 0.8 | 3.6 | 14.9 | 1.00 |
Closes #5112
Related #4305

perf(git_status): query git stash count via gitoxide

---

src/modules/directory.rs

Avoid some unnecessary string copies by using references.
- [/] I have updated the documentation accordingly.

refactor(directory): avoid unnecessary string copies

---

install/windows/choco/update.ps1

The push location needs to be specified now.
Closes #

ci: fix choco package push

---

build.rs
src/config.rs
src/formatter/string_formatter.rs
src/logger.rs
src/module.rs
src/modules/package.rs
src/modules/time.rs

This pr handles the new rust v1.72 clippy lints and fmt changes (`let else`).
Closes #

chore: handle rust 1.72 clippy & fmt changes

---

src/modules/c.rs
src/modules/pulumi.rs

chore: fix rust 1.74 clippy lints

---

docs/config/README.md

Noticed a small typo in the gcloud description and fixed it
- I'm not sure if need go re-generate anything with regards to translations etc

docs: Fix typo in gcloud description

---

src/modules/git_status.rs

Decrease the default log level to avoid printing warnings too eagerly.
Closes #5432

fix(git_status): Avoid printing error on missing stash ref

---

src/context.rs
src/main.rs
src/modules/direnv.rs
src/modules/dotnet.rs
src/modules/fossil_metrics.rs
src/modules/kubernetes.rs
src/modules/nix_shell.rs
src/modules/openstack.rs
src/modules/python.rs
src/modules/rust.rs
src/modules/shlvl.rs
src/print.rs
src/utils.rs

I noticed some clippy warnings in the repo, and fixed them and some more `clippy::pedantic`-warnings from nightly-rust.
Closes #

chore: apply new rust 1.75 & nightly clippy fixes

---

Cargo.lock
Cargo.toml
src/context.rs

Upgrade `gix` and apply the necessary fixes for more precise branch handling.

build(deps): update rust crate gix to 0.57.0

---

docs/.vuepress/public/presets/toml/gruvbox-rainbow.toml

For the gruvbox-rainbow theme, add conda, following the approach of docker context there.
Provide default including conda. Following the example of docker context there because they have similar meaning. For example, it will show something like ` v3.12.1  🅒  jupyterlab`.

docs(preset): add conda config to gruvbox-rainbow

---

install/install.sh

Added version support so users can choose a specific version to install, instead of it always being the latest.
Added support for users to specify the option `-v` or `--version` followed by the desired version.
Applied the suggestions on #5668 
Closes #5668

feat(install): Add version option to install script

---

Cargo.lock
Cargo.toml
src/configure.rs

This PR updates `toml` and `toml-edit`. `Document` was renamed to `DocumentMut`. The `Document`s are used for mutation, so the new alternative `ImDocument` is not appropriate.
Closes #

build(deps): update toml crates

---

docs/faq/README.md

docs(faq): Tweak some grammar in the FAQ

---

docs/advanced-config/README.md

Related #5860. The prompt features starship uses were only added in ble.sh v0.4, mention this version requirement in the documentation
Closes #

docs: document ble.sh version requirement

---

src/init/mod.rs

Use `eval -- "$(/path/to/starship init bash --print-full-init)"`, which works in any version of Bash and also in the POSIX mode, instead of the current version of `source <(...)` which does not work when the POSIX mode is turned on in Bash <= 5.0. I have added a detailed explanation in the code comments.
~~In Bash 5.0 and below~~ (**edit**: After I submitted this PR, #5735 introduced the approach using `PS0` for Bash 4.4 and above, so the problem arises only in Bash 4.3 and below as of 2024-04-01), Starship initialization failed when the POSIX mode is turned on. This PR fixes the issue.
Closes #1674
Closes #3660
Closes #5382
With the following `bashrc`:
```bash
set -o posix
eval "$(starship init bash)"
```
Before the fix:
After the fix:
There doesn't seem to be any documentation about the …

fix(bash): use `eval` instead of a procsub for the POSIX mode

---

docs/faq/README.md

docs(faq): fix typo

---

.github/config-schema.json
docs/config/README.md
src/configs/username.rs
src/modules/username.rs

As described in #5784 a way to translate the displayed username into something else.

feat(username): add aliases option

---

src/modules/container.rs

Podman exports the name of the container in */run/.containerenv*, which is especially useful for distrobox environments.
Closes: #3592
Closes: #5193
Closes: #4243
Improves: #3304
Closes: #5802

feat(container): show name if available

---

docs/config/README.md

docs: fix typo in README.md

---

docs/installing/README.md

This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
Closes #

docs: link to official nixos wiki

---

Cargo.lock
deny.toml
docs/package-lock.json

#6038 added new deps with unicode-3.0 license that wasn't listed in the cardo-deny config yet.
Closes #6038

build(deps): lock file maintenance & permit new unicode license

---

docs/public/presets/toml/nerd-font-symbols.toml

Made rust icon larger
Looks nicer as the size is more consistent with other icons
before
after

docs(preset): update the nerd-font-symbols preset

---

docs/.vitepress/config.mts

Update the sidebar of a simplified Chinese document.
Localized translation of the sidebar can not be done in Crowdin.

docs(config): Update the sidebar in Simplified Chinese

---

.github/workflows/format-workflow.yml

The block translated changes check stopped working (#5732) some time ago. This PR replaces the external action we used for that with a short script powered by `actions/script` that [works](https://github.com/starship/starship/actions/runs/9389820393/job/25858190487).
Closes #5732

ci: fix prevent prevent file change workflow

---

.github/config-schema.json
docs/config/README.md
src/configs/hostname.rs
src/modules/hostname.rs

* Implemented functionality to set aliases for known hosts
* Added test-cases
* Updated config & documentation
* Updated TOML config schema

feat(hostname): add option to replace hostnames with aliases

---

src/init/mod.rs

In the same vein of #5322. This was discussed in #2637 and is backwards-compatible.
Closes #

perf(fish): Skip unnecessary indirection in starship init fish

---

docs/config/README.md

I fixed the syntax highlighting in the code block under the `Bun > Examples > Replace Node.js` section of the Docs of Configuration.
https://starship.rs/config/#replace-node-js
before:
after:
Closes #
I tested it on localhost.

docs(config): add toml language tag to code blocks

---

.github/workflows/release.yml
.github/workflows/workflow.yml
README.md

This PR updates our README to better comply with the [signpath.org policies](https://signpath.org/terms.html#conditions-for-the-website--repository), enables signing with the newly issued release certificate and updates the signpath action to v1.
Closes #

feat(release): codesign windows release binaries

---

docs/config/README.md

This matches all other modules.

docs: Use inline code for Odin module name

---

src/init/mod.rs

Like #4001, but applies to the main init script.
Fixes #4924 again.

fix(init): do not use cygpath for elvish

---

README.md
docs/README.md
install/install.sh

https://github.com/nushell/nushell/issues/2812#issuecomment-2558182655
Init can now be handled only via commands run in the config file.
Closes #

docs(nu): simplify nushell setup

---

src/modules/hostname.rs

`whoami::hostname` returns the [NetBIOS name](https://github.com/ardaku/whoami/blob/v1/src/os/windows.rs#L280), unlike `gethostname` which used [`COMPUTER_NAME_PHYSICAL_DNS_HOSTNAME`](https://github.com/swsnr/gethostname.rs/blob/main/src/lib.rs#L77`). `whoami::devicename` on Windows uses [`DNS_HOSTNAME`](https://github.com/ardaku/whoami/blob/v1/src/os/windows.rs#L239) which is not completely the same but matches the old output of `gethostname` on my system, and per [the docs](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getcomputernameexw#parameters) it will only makes a difference on cluster nodes. Unlike the NetBIOS variant, `devicename` preservers casing. Unicode hostnames on Windows are also still supported.
Closes #6341
Closes #6411

fix(hostname): use DNS instead of NetBIOS name on Windows

---

Cargo.lock
Cargo.toml

Recent versions of `libz-ng-sys` have trouble building on Windows https://github.com/starship/starship/actions/runs/12725390714/job/35472577713
Related https://github.com/rust-lang/libz-sys/issues/225

fix(windows): downgrade libz-ng-sys

---

README.md

This PR adds mentions to the recently packaged Debian and Ubuntu packages for starship in the repo README, which is also used as `/guide` on the website.
Closes #

docs(guide): mention official debian & ubuntu packages

---

docs/public/presets/toml/plain-text-symbols.toml

This adds three more symbols to the plain text preset.

docs(preset): three more plain symbols

---

typos.toml

Unblocks the CI pipeline.
Closes #

chore: update typo definitions

---

.github/config-schema.json
docs/config/README.md
docs/public/presets/toml/bracketed-segments.toml
docs/public/presets/toml/gruvbox-rainbow.toml
docs/public/presets/toml/jetpack.toml
docs/public/presets/toml/nerd-font-symbols.toml
docs/public/presets/toml/no-empty-icons.toml
docs/public/presets/toml/pastel-powerline.toml
docs/public/presets/toml/plain-text-symbols.toml
src/configs/c.rs
src/configs/cc.rs
src/configs/cpp.rs
src/configs/mod.rs
src/configs/starship_root.rs
src/module.rs
src/modules/c.rs
src/modules/cc.rs
src/modules/cpp.rs
src/modules/mod.rs
src/utils.rs

hello, @davidkna 
Take a look at this PR.
This is for #4583  Implementing a module for C++.
Sorry it took so long.
Implement a c and c++ modules with a common implementation.
Closes #4583

feat(c++): adding c++ module

---

.github/config-schema.json

This PR regenerates the config schema, to revert changes to its formatting introduced in #6335.
Closes #

chore: fix config schema formatting

---

docs/config/README.md

Follow-up of #6335 
cc @davidkna

docs(pixi): Fix typo

---

README.md

docs(install): fix broken Nixpkgs link

---

src/print.rs

Top modules are processed in parallel, but child modules (of env_var|custom) are not. This PR fixed that.
Given a config like this:
```
format = """$custom"""
command_timeout = 3000
[custom.foo]
command = 'sleep 1; echo foo'
when = 'true'
[custom.bar]
command = 'sleep 1; echo bar'
when = 'true'
```
The two custom modules are processed in sequence and takes ~2s:
```
$ time STARSHIP_CONFIG=~/.config/test.toml starship prompt
%{%}foo bar %{%}STARSHIP_CONFIG=~/.config/test.toml starship prompt  0.02s user 0.02s system 1% cpu 2.058 total
```
After parallelization, it takes ~1s, as expected:
```
$ time STARSHIP_CONFIG=~/.config/test.toml ./target/release/starship prompt
%{%}foo bar %{%}STARSHIP_CONFIG=~/.config/test.toml ./target/release/starship prompt  0.02s user 0.03s system 4% cpu 1.038 …
```

perf: Parallelize child modules for env_var|custom

---

README.md

link to good first issue has broken in [Contributiong section](https://github.com/sakuram-dev/starship?tab=readme-ov-file#-contributing)
Fix the link to good first issue and reduce barriers to participate in the project.
Now:
I fixed:

docs: fix link for good first issue

---

src/modules/git_status.rs

Added an extra bit to the `git for-each-ref` call to make sure we have a remote tracking branch.
Closes #6736

fix(git_status): Do not show up-to-date when untracked

---

docs/config/README.md
src/modules/package.rs

Added detection of [Ansible Galaxy](https://galaxy.ansible.com) versions to the package module.
No support for Galaxy yet.

feat(package): Add support for Ansible Galaxy

---

src/print.rs

The string `\x1b[35;49mkai` is, on the screen, only 3 characters long, however the `width_graphemes()` function would say that it is 10 characters long. This is only really an issue for `explain`, as it makes the width of the left column incorrect for the padding. Instead of the following:
```console
$ starship explain
"/" (<1ms)    - <description>
"kai" (<1ms)  - <description>
```
it would print out like this for any parts that don't use ansi escapes internally:
```console
"/" (<1ms)           - <description>
"kai" (<1ms)  - <description>
```
This should cause no problems with any of the unstyled lengths that are generated normally, but any pre-styled strings in `custom` calls will cause this issue.
Tested with my config which uses `starship-jj`.

fix(explain): Filter out non-printing ANSI escape codes

---

docs/public/presets/toml/nerd-font-symbols.toml

docs(preset/nerd-font): Add symbol for status module
