Cargo.lock, Cargo.toml, tests/directory.rs
The tempdir crate was merged into tempfile and is available in 3.x. Replaced tempdir references with tempfile.
=> Replace tempdir with tempfile

benches/my_benchmark.rs, src/context.rs, src/lib.rs, src/main.rs, src/modules/character.rs, src/modules/directory.rs, src/modules/line_break.rs, src/modules/mod.rs, src/modules/nodejs.rs, src/print.rs, tests/common.rs
I noticed we were passing around a whole lot of arguments with the details of the particular run. I did a little refactoring to contain that data in a `context` struct.
In the future, this will contain other details such as:
- A list of files in `PWD`
- A list of binaries in `PATH`
- Configuration parsed from the config file
- Maybe cached values from previous runs? 🤔
=> Use "context" to contain run details

src/modules/mod.rs, src/modules/rust.rs, src/print.rs
Heya!
I started with a very naive implementation:
- It will still display the `-nightly` or `-beta.1` postfix if the user is using that toolchain currently. Not sure what the best default would be, please let me know your thoughts!
- I also did not include the `cargo` version etc but I can if you guys think its a good idea atm.
I think there is some potential refactoring with regards to how the commands work, maybe wrapping them in a struct so we can use dependancy injection to test them might be a good idea? 
was also thinking of doing a more reusable function for the `is_<insert_lang_here>_project()`?
I moved things around in this file but I can make it mirror the node file if you guys think thats a good idea.
Closes #12
=> feat: Add Rust version segment

src/context.rs, src/modules/directory.rs, src/modules/nodejs.rs, src/modules/rust.rs, tests/character.rs, tests/common.rs, tests/directory.rs
- Add `dir_files` to `Context` so current dir is only scanned once
- Restructure the node segment to better match the rust segment
- Use `dir_files` in the rust segment
- Replace mentions of "section" with "segment"
As part of these changes, all tests that use home and root paths have been disabled due to the `Context` constructor now indexing the current directory's files. Because we were testing with non-existant paths, these tests were failing. They will be re-enabled once we figure out a solution for mocking `std::fs`.
=> Share dir_files between segments through Context

README.md
According to #12, the Rust version symbol is `🦀` instead of `𝗥`.
=> Correct the Rust version symbol in README

CODE_OF_CONDUCT.md
In the process of creating the contributing guidelines for the project, I wanted to first add a code of conduct to reference in the guidelines to help keep this project and organization safe, open, and welcoming to anyone who wishes to contribute. ❤️ 
I added the [Contributor Covenant](https://www.contributor-covenant.org/) Code of Conduct, which is widely used throughout the open source community.
=> Add a code of conduct to the project

.build/install-rust.yml, azure-pipelines.yml, tests/Dockerfile
Make `rustup` install a specific version of Rust along with the required Rust toolchain to run the build and tests.
- Split out the Rust installation logic from within `azure-pipelines.yml`
- Define a fixed version to be installed within Azure Pipelines
- Run tests with `rustup run` using the required toolkit
- Make the same changes in the Dockerfile
In order to be able to have integration tests that run `rust --version`, we need the locally used Rust to be a fixed version, while running tests and builds with the current stable/beta/nightly.
=> Install a fixed version of rust for CI integration tests

Cargo.lock, Cargo.toml, benches/my_benchmark.rs, src/context.rs, src/modules/directory.rs, src/modules/git_branch.rs, src/print.rs
- Add Rayon as a dependency
- Parallelize the handling of modules
- Replace `repository` with `repo_root` in `Context`
Initially surfaced as a comment in #45 by @mehcode, it appears git2-rs is not thread safe, which botched future plans to add Rayon to the project. This PR adds Rayon so that we can safely identify thread safety issues moving forward.
=> Parallelize prompt modules

src/context.rs
As per YoussefHabri in the discord chat:
```There's a minor issue with the has_extension function. It acts as if it found a match when dealing with folders with an extension at the end e.g. a folder named test.js```
Added a quick check to make sure we are only scanning paths based on their type ie a file vs a dir.
Closes #
https://github.com/starship/starship/issues/52
=> fix: Don't check extensions of directories

src/modules/python.rs
The Python version wasn't showing for versions < 3.4 (reported by @youssefhabri). The problem was that `python --version` for < 3.4 is outputting to stderr, but we were only checking stdout since for versions >= 3.4, that's where it outputs. I have fixed this bug.
Closes #53
=> Fix python version bug

Cargo.lock, Cargo.toml, src/config.rs, src/context.rs, src/main.rs, src/modules/battery.rs, src/modules/character.rs, src/modules/directory.rs, src/modules/git_branch.rs, src/modules/git_status.rs, src/modules/go.rs, src/modules/line_break.rs, src/modules/mod.rs, src/modules/nodejs.rs, src/modules/package.rs, src/modules/python.rs, src/modules/rust.rs, src/modules/username.rs, src/print.rs, tests/testsuite/character.rs, tests/testsuite/common.rs, tests/testsuite/configuration.rs, tests/testsuite/main.rs, tests/testsuite/username.rs
- Add support for the `disabled` configuration option
This will allow you to selectively disable modules that you don't want or need. 😄 
- Overwrite starship configuration file path with `STARSHIP_CONFIG` environment variable
- Write tests for the two configuration options that are available
Implementation stuff:
- Create an extension of `std::process::Command` with a convenience function for testing configs
- Create an extension of `toml::value::Table` with convenience functions for accessing typed config values
Closes #81
=> feat: Add a `disabled` configuration option for modules

src/init.rs
This adds support for qualified paths (e.g. using
`/usr/local/bin/zsh` instead of `zsh`) to init.rs.
`init` now converts the shell name into an OsStr, then to a Path, then gets the file stem, and unwraps back into a str. While this process can fail (yielding a None), it's highly unlikely to unless the user has messed with their shells or there's an issue in Starship--therefore, the failure message in this case simply asks the user to file a bug report.
I'm a little torn about the design, even though it's probably not terribly consequential either way (just me getting my newbie jitters out, I guess). The alternative would be to simply `unwrap()` the file stem and let it panic if it does--the conversion should almost never fail unless the user has done something bizarre to their shell or …
=> fix: handle path to shell in starship init

src/init.rs
Making use of `PROMPT_COMMAND` in bash and `precmd` in zsh, the prompt is no longer being expanded and rendered when the variable is initially set.
Closes #108
=> fix: prompt now updates on bash and zsh

docs/config/README.md, src/config.rs, src/context.rs, src/module.rs, src/print.rs, tests/testsuite/common.rs, tests/testsuite/configuration.rs
- Replace `TableExt` with a `Config` trait that extends `toml::value::Table`
- Add configuration for `add_newline`
`add_newline` is a root-level configuration value. When set to `false`, the initial newline before the prompt is removed.
What are your thoughts on making `add_newline` a root-level config value?
Closes #
=> feat: Add configuration for add_newline

Cargo.lock, Cargo.toml, src/modules/directory.rs
Prior to this change, starship would use inconsistent slashes when displaying the working directory:
```
~/Desktop\Programming
➜
```
With this change, starship uses Unix-style slashes on all platforms. This is consistent with the Git Bash and Cygwin prompts on Windows.
```
~/Desktop/Programming
➜
```
Added several unit tests and tried out the changes locally.
=> feat: Use Unix-style slash on Windows

docs/config/README.md, src/config.rs, src/module.rs, src/modules/directory.rs, tests/testsuite/directory.rs
This allows the directory truncation length to be configured. Previously, it was hard-coded to truncate to `3` parent directories.
Tested locally on Windows and using Docker.
=> feat: Allow directory truncation length to be configured

docs/config/README.md, src/modules/cmd_duration.rs, src/modules/python.rs, tests/testsuite/python.rs
The prompt will now display the current Python virtual environment like this:
`foo on  master via 🐍 v3.7.4(bar)`
It is handy to show the active Python virtual environment in the prompt
=> feat: Implement Python virtual environment display

src/print.rs
Show the battery module before the character module with the default prompt order.
This better aligns with the implementation in spaceship and spacefish.
=>  fix: Move the battery to the newline before character

ci/setup-test-env.yml, docs/config/README.md, src/modules/python.rs, tests/testsuite/python.rs
Implement pyenv version for the Python module, it looks like this:
`foo on  master via 🐍 pyenv system`
This behavior can be enabled via setting `use_pyenv` to true.
The "pyenv" prefix before the version name can be configured using `pyenv_prefix`
pyenv provides named Python versions, users might want to display that instead of `python --version`
=> feat: Implement Python version from pyenv

src/init.rs, src/modules/jobs.rs
MacOS wc has a habit of leaving nasty spaces in the output, which was
messing up our argparser.
To fix, quote the output from the jobs command, then have Rust trim out
whitespace in the jobs module before parsing.
Quote argument to jobs in prompt setup, then have jobs module trim out whitespace before parsing.
Closes an issue discovered on Discord.
=> fix: Fix issue with jobs and extra whitespace on MacOS with BSD utils

src/modules/golang.rs, src/modules/mod.rs, src/modules/nodejs.rs, tests/testsuite/cmd_duration.rs, tests/testsuite/directory.rs, tests/testsuite/golang.rs, tests/testsuite/nodejs.rs
Until this point, modules could've had multiple names. This has caused some confusion when naming configuration values for modules. This PR makes all table names in the config file consistent with the one name for each module.
Bug reported on Discord.
=> fix: Give all modules a single name

README.md, ci/setup-test-env.yml, docs/config/README.md, src/modules/mod.rs, src/modules/ruby.rs, tests/Dockerfile, tests/testsuite/main.rs, tests/testsuite/ruby.rs
There isn't a ruby prompt, which is one more language for the prompt.
=> feat: implement the ruby module

tests/testsuite/ruby.rs
Ruby tests are environment dependent and should not be run in the default test suite. Add `#[ignore]` to the Ruby integration tests to fix this.  
This issue is breaking deploy on the AUR package, as the installation involves running `cargo test --release` to ensure a basic level of function
=> fix: Don't run tests for ruby outside of the integration tests

src/modules/directory.rs
I noticed a small typo in the documentation of the directory module, so I figured I'd make a PR to fix it. Feel free to push a fix separately and close this if it's easier!
=> docs: Fix typo in directory module description

tests/testsuite/directory.rs
With sandboxing NixOS only has those directories in / :
- /dev
- /etc
- /nix
- /build
- /tmp
- /bin
- /proc
As the `directory_in_root()` test was using `/usr`, it failed.
`/usr` was replaced to `/etc`
Fix compilation on NixOS with sandboxing (which is enabled by default)
=> fix: Fix compilation on NixOS with sandboxing by changing '/usr' to '/etc' in test

.gitignore, docs/config/README.md, src/modules/directory.rs, tests/testsuite/directory.rs
As mentioned in #162, I'd like to be able to to disable truncation of the directory to the git repository root. I'm not sure about proper conventions of naming new config options or how to describe them in the docs, so I'm happy to make any changes to improve the language that I used!
Unrelatedly, I updated the .gitignore to ignore Inteliilj .iml module files in the root of the repository in a separate commit, as importing this project into Intellij created that file for me. If it's preferred not to add this to the config, I'd be happy to rebase to remove that commit.
I modified the `module` function in `src/modules/directory.rs` to read a boolean option called "truncate_to_repo" from the directory module in the TOML config file, which defaults to "true" in order to preserve backwards …
=> feat: Add option to control git directory truncation

docs/config/README.md, src/init.rs, src/main.rs, src/modules/character.rs, src/modules/python.rs, tests/testsuite/character.rs
I enable to change prompt if [zsh: 18 Zsh Line Editor](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Keymaps) is `vicmd`.
KEYMAP is `vicmd`.
KEYMAP is other.
`vicmd_symbol` is configurable.
Closes #129
=> feat: Display Vi mode as PROMPT

docs/config/README.md, src/context.rs, src/modules/username.rs
Just a few fixes to typos in the docs and comments.
=> fix: correct some typos in docs and comments

src/init.rs
Hotfix: if the user does not already have a defined `precmd_functions` or `preexec_functions` array, the zsh init script will not register the starship functions.
This patch fixes that by pre-defining the arrays if they do not already exist.
Closes #
=> fix: Correct broken zsh init in absence of precmd_functions

docs/config/README.md, src/modules/character.rs, tests/testsuite/character.rs
As discussed on Discord, change the default prompt symbol to "❯" to make it more consistent with vi-mode after merging #169 
Closes #
Not really any of these?
=> fix: Set default prompt character to ❯

src/modules/directory.rs, tests/testsuite/directory.rs
This merge request resolves the failing directory_in_root integration test on Windows
The test was failing because `/usr` is an invalid path on Windows. 
I have changed the `directory_in_root` test to have both a Windows and Unix version by using the `#[cfg(target_os)]` attribute.
Closes #97
`cargo test` on Windows
=> fix: Fix directory_in_root integration test on Windows

src/init.rs, src/module.rs
This PR solves issue of cursor location confusion on bash and zsh as discussed over #110 . It solves this issue by modifying out ANSIString and wrap non-printing character escape for all of ansi-term additional parts.  
Closes #110
=> fix: Solve bash & zsh cursor location confusion issue

docs/config/README.md, src/config.rs, src/print.rs
This PR adds functionality for reordering the prompt module it provide out ~~two~~ one configuration setting i.e ```prompt_order``` which can be set as array of string ~~and ```disable_default_order``` as Boolean~~.
1. configuration
```
prompt_order=["rust","git_status","package","character]
```  
2. configuration
```
prompt_order=["rust","git_status","package","line_break","character"] 
```  
3. configuration
```
prompt_order=["rust","line_break","package","line_break","character"]
```
Closes #158
=> feat: Add configuration for reordering the prompt module and disabling default order

Cargo.lock
Hello! I ran [`cargo audit`](https://rustsec.org/) on the crate, and it reported that the `memoffset` transitive dependency (`rayon` -> `crossbeam-deque` -> `crossbeam-epoch` -> `memoffset`) has an advisory published for the version that the `Cargo.lock` is pinned to. While we can't update it directly due to `crossbeam-epoch` requiring an older version, `crossbeam-deque` is happy to take an updated `crossbeam-epoch`, so I ran `cargo update -p crossbeam-epoch`, which in turn updated `memoffset` to the latest version.
=> chore(deps): Update `crossbeam-epoch` dependency

src/init.rs, src/main.rs
Implement a two-phase init procedure in starship. The first phase causes the shell to source a subshell, while the second phase (in the subshell) prints the main init script.
This allows us to have nice init scripts with good styling, comments, and no pile of semicolons. Even better, it works as a drop-in replacement, so we don't need to update the docs.
One of the problems with using `eval` directly is that our scripts all end up on one line. This leads to several problems when it comes to script development:
- You cannot comment the script, because `#` characters continue to the end of the line, which is the rest of the script when it's all on one line.
- Debugging is a nightmare--all you know is that there's an error *somewhere* within the script
- You're forced to place semicolons in …
=> feat: Implement a two-phase init which allows us to write normal init scripts

src/main.rs, src/module.rs, src/modules/mod.rs, src/print.rs, tests/testsuite/main.rs, tests/testsuite/modules.rs
Instead of panicking out over unknown module supplied to `starship module` subcommand this PR print outs standard error over terminal. This PR also adds out new flag for module subcommand --list i.e `starship module --list` which list out all of supported modules.
Closes #190
=> fix: Change panicking on unknown module to error print and support module listing flag

src/init.rs
Fix a line in ZSH init which breaks older versions of ZSH.
Closes #196
=> fix: Correct ZSH init on older ZSH versions

docs/config/README.md, src/print.rs
Adds ruby module to `DEFAULT_PROMPT_ORDER`
Closes #202
=> fix: Restore Ruby module

docs/config/README.md, src/modules/python.rs, tests/testsuite/python.rs
Have added the ability to enable the Python module based on the
existence of the a `Pipfile`.
Closes #218
=> feat: Add support for detecting Python from Pipenv files

src/init.rs, src/main.rs
- get the current exe path with env::current_exe() **(which might cause security problems)**
- put the path in doublequotes to support spaces in the path
- escape doublequotes in the path
I didn't want to touch the big BASH_INIT, ZSH_INIT.. variable so I renamed the `starship` to `STARSHIP_EXEC` and used a replace. I wonder if it's less optimal than using the format macro or something else.
Closes #220
=> fix: Update init to use full path to starship executable

README.md, docs/config/README.md, src/modules/mod.rs, src/modules/nix_shell.rs, src/print.rs, tests/testsuite/main.rs, tests/testsuite/nix_shell.rs
The module determine if inside a nix-shell env using `$IN_NIX_SHELL`.
It's useful to know when you're inside a nix-shell environment (like a python virtualenv).
Closes #172
I didn't do the doc yet.
Is it a bad idea to show the content of `$IN_NIX_SHELL` in the prompt (for security maybe)? Maybe it could be safer if I validate that it's either "1", "pure" or "impure".
Also for some reason, [lorri](https://github.com/target/lorri) (a nix-shell tool) sets `IN_NIX_SHELL` to "1" instead of "pure" or "impure". Is it ok to show "nix-shell" instead of "1"? I can check with the devs if their env is considered "pure" or "impure". Or maybe they could add their own env var.
=> feat: Add nix-shell support

src/init.rs, src/modules/battery.rs
on Zsh, battery percentage character print `%{`.
this PR fix print `%{` -> `%`.
on Zsh, `%` is prompt sequence prefix.
http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
i.e,
`%n` will print username,
`%%` will print `%`, etc.
this problem on only Zsh. Bash and Fish are print `%`.
So, switch percentage character by `STARSHIP_SHELL`.
Closes #226 
those screenshots are change `BATTERY_THRESHOLD` to `100.0` for this.
on Bash:
on Zsh:
on Fish:
=> fix: battery percentage character on Zsh. #226

docs/config/README.md
When the docs were copy pasted for the nix_shell module from the username module the module name wasn't updated.
It makes the docs correct.
Not tested as no code is changed.
=> docs: Correct a copy/paste error in the docs

src/module.rs
Adds `nix_shell` to `module::ALL_MODULES`, so that it is not skipped when generating the user's prompt.
Currently including `nix_shell` in your `prompt_order` has no effect.
Not yet. I'm having some build issues with `git2`...
=> fix: Fixes the `nix_shell` module, allowing it to be used with `starship prompt`

docs/config/README.md, src/init.rs, src/main.rs, src/modules/character.rs, tests/testsuite/character.rs
Bear with me; this is my first foray into Rust. This changeset extends the existing `vicmd_symbol` logic to fish-shell; fish makes this quite simple, but abstracting the existing logic (especially the tests) to be shell-agnostic proved quite challenging. I hope I'm on the right track.
I use fish and it ships with this feature built-in. Most fish prompts support it. I like this prompt but it didn't have this feature, so I added it.
Closes #198 (I think)
Tested locally on Arch Linux in `fish` and `zsh` for breakage; none found. Red colour still applied on nonzero exit codes in both shells. Symbol responds to keymap change in both shells.
```
fish, version 3.0.2
zsh 5.7.1 (x86_64-pc-linux-gnu)
Linux vergadain 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```
=> Support vicmd_symbol in fish-shell

docs/config/README.md
Have corrected the documentation for the git module. The docs now use
the correct option `staged` rather than `added`.
Closes #261
=> docs: Correct missed named git config in docs

Cargo.lock, Cargo.toml, docs/config/README.md, src/modules/git_branch.rs, tests/testsuite/git_branch.rs, tests/testsuite/main.rs
Added a way to truncate git branches
Git branches can become very long (e.g. gitlab auto-generated branch
names), thus it would be nice to be able to truncate them to keep your
prompt lenght in line.
This patch adds two new options to the git_branch module:
* truncation_length: The amount of graphemes to of a gitbranch to
truncate to
* truncation_symbol: The symbol that should be used to indicate that a
branch name was trunctated
To be able to correctly work with UTF-8 graphemes, unicode-segmentation
was added as a dependency.
I made this change because we use GitLab, but it's useful in other scenarios as well. If you have an issue on GitLab you can press a button on that issue to automatically create a merge request and a branch for you. However, the pattern for the branch name is …
=> Added truncation_length/symbol to git_branch

src/modules/git_status.rs, tests/testsuite/git_status.rs
On some repository I have `git config status.showUntrackedFiles no` but when there are untracked files in this repository I still get a permanent `[?]` in the prompt.
I think `showUntrackedFiles` should be respected, and when it's set to `no`, then the prompt should follow it.
None.
=> Respect status.showUntrackedFiles

src/init.rs
Change ZSH jobs to use `jobstates` array provided by zsh/parameters module rather than using `jobs | wc`, which can produce errors.
Marked as draft because it works on my machine, but I'd like to test several ZSH versions across multiple machines before committing it in to the main codebase.
Closes #179
=> Change ZSH init to use jobstates for num jobs

tests/testsuite/common.rs, tests/testsuite/git_branch.rs, tests/testsuite/git_status.rs
I moved the fixture repo creation to common since it is now used by more than one module.
Remove duplicated code.
=> refactor: Move `create_fixture_repo` into common in integration tests

src/init.rs
Changes the bash init fallback to be `Major Version > 3` rather than `Major Version > 4`.
The issue being worked around affects bash 3.2, so `Major Version > 3` is sufficient.
The fallback requires `/dev/stdin`, which may not exist on all systems - so it's preferable to use the normal bootstrap when possible.
This should fix starship for some Windows users who are using bash without full POSIX emulation.
For example: Git Bash, which is part of Git for Windows, does not recognise `/dev/stdin`, but does ship with bash 4.x.
Improve support for starship on Windows 😃 
Bash on Windows is a bit of a minefield, because there are various projects maintaining various POSIX emulation layers and various patch lists. This change will not fix starship for ALL bash users on windows, but it should fix it …
=> fix: Be more restrictive with bash init fallback

src/context.rs
Addresses #52, closes #280.
This ignores filenames starting with a dot and streamlines the matching logic. 
Added a test and ran `cargo test`
=> fix: Don't trigger an extension match on hidden files

tests/testsuite/common.rs, tests/testsuite/git_branch.rs, tests/testsuite/git_status.rs
The common function in the test suite will now clone the repo into the fixture directory, and then set the git config locally to that repo.
Closes #300
=> fix: Fixture repo will now clone and set git config locally

docs/advanced-config/README.md, docs/config/README.md, src/config.rs, src/module.rs, src/modules/battery.rs, src/modules/character.rs, src/modules/cmd_duration.rs, src/modules/directory.rs, src/modules/git_branch.rs, src/modules/git_state.rs, src/modules/git_status.rs, src/modules/golang.rs, src/modules/hostname.rs, src/modules/jobs.rs, src/modules/nix_shell.rs, src/modules/nodejs.rs, src/modules/package.rs, src/modules/python.rs, src/modules/ruby.rs, src/modules/rust.rs, src/modules/username.rs
Allows the user to specify styles on a per-module (and potentially even per-section) basis.
This has two main parts: the first is a new config function which can read a string specifier, e.g. `underlined bold green bg:75` and return the appropriate `ansi_term::Style` object to match that specifier.
The second will be integrating this config function in with existing modules.
Closes #128 and #208
=> feat: Add the ability to configure per-module color styles

docs/config/README.md
Reorder misplaced Ruby option example
Ruby example is misplaced at Linebreak section.
Docs updated
Ruby example shouldn't show at linebreak section.
Need not.
=> docs: reorder misplaced Ruby option example

integration_test
Allows usage of the integration_test script on OS using SELinux.
No influence on other OS is expected.
The configuration is described [here](https://docs.docker.com/engine/reference/run/) 
As discussed in https://github.com/starship/starship/issues/302, mounting of `$(pwd)` into the Docker container fails if an OS with SELinux is used. One option is to use :z or :Z, as discussed [here](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label). However, this might be dangerous of misused.
But it should be rather unproblematic to disable the label confinement for the container all together.
=> fix: Turn off label confinement for docker run.

src/context.rs, src/module.rs, src/modules/golang.rs, src/modules/nodejs.rs, src/modules/python.rs, src/modules/ruby.rs, src/modules/rust.rs, src/modules/time.rs, src/segment.rs, tests/testsuite/git_branch.rs, tests/testsuite/git_status.rs, tests/testsuite/time.rs
Currently starship is guaranteed to enumerate all files in the current directory, and it will not start evaluating modules until this operation completes. This PR will change it so that the list is lazily loaded when it is first used, in a similar fashion to the git details in #306 
Updates `Context` to use `OnceCell<Vec<PathBuf>>`.
One side effect is `new_scan_dir` is now fallible. I've change the name to `try_begin_scan` and `scan` to `is_match`.
Allows modules which do not use `ScanDir` to be evaluated sooner, reducing total latency.
=> perf: Lazy load files from directory

docs/config/README.md, src/modules/python.rs, tests/testsuite/python.rs
Enable the python module if the current directory contains a `tox.ini`
file.
Closes #365
=> feat: Enable the python module for tox files

src/module.rs, src/segment.rs
Change the logic of `Module::is_empty` to use newly created `Segment::is_empty` to determine if the module is empty and should print.
Closes #325
=> fix: Update Module::is_empty to check value of segments

.github/workflows/continuous-integration.yml, Cargo.lock, README.md, docs/config/README.md, src/module.rs, src/modules/java.rs, src/modules/mod.rs, src/print.rs, tests/Dockerfile, tests/testsuite/java.rs, tests/testsuite/main.rs
Implemented a basic `Java` module, that shows the `Java` version, when inside a Java/Maven Project.
* New module `java` that calls `javac --version`, to get the version of Java
* Simple tests for the formatting and call to `javac`
* Updated the `Dockerfile` to install `Java`
Just another language that can be supported.
MacOS:
Linux (WSL):
=> feat: Add Java Module

src/modules/directory.rs
This is likely a more common scenario when a user had `truncation_length = 1`. When the user was in a directory where the final directory name was repeated somewhere else in the `pwd` path.
Closes #394
=> fix: fish_pwd option handles repeated directories properly

docs/config/README.md, src/modules/username.rs, tests/testsuite/username.rs
I added the option to always show the username.
It is possible to activate this by adding "show always = true" to the "username" section.
The default behavior has not changed.
Closes #401
I built a  local version of the starship crate and tried the following scenarios:
Preconditions: user is not root, user is not in a ssh session, current user is the same as the logged in user
1. config without "show_always" entry -> no username visible
2. config with entry "show_always = false" -> no username visible 
3. config with entry "show_always = true" -> username is always visible 
Additionally I added a new test to ensure the user is rendered when this option is set.
I don't think it necessary to write an additional test to cover the default case. This should be covered by the already excisting …
=> feat: Add ability to always show username module

docs/config/README.md, src/init/starship.bash, src/init/starship.fish, src/init/starship.zsh, src/modules/cmd_duration.rs, tests/testsuite/cmd_duration.rs
As a temporary measure, this PR reverts the command duration change from seconds to milliseconds due to incompatibilities with the macOS date utility.
Closes #
=> revert: Revert the command duration in ms feature (#380)

src/config.rs
Hi maintainers 👋 ! This a bit of a test balloon if you are open to refactorings that move the code base towards a more pure functional style, e.g. avoiding mutable variables or using values instead of return statements. I'm an FP Scala developer by day so please excuse any Rust newbie mistakes made.
- Replaced for loop that iterates over mutable state with a fold expression
- Unified the logging for the different accessors. The code is now screaming for further refactoring (`get_module_config`, `get_as_bool`, `get_as_str`, `get_as_i64` and `get_as_array` are basically the same up to higher order functions but I didn't manage to get the life times right)
- Increased test coverage (especially a test case for `none` not at the end)
- Removed code comments that literally repeated the code in …
=> refactor: Refactor config.rs to pure functional style

tests/testsuite/git_status.rs, tests/testsuite/python.rs
I don't know which PR caused this but currently rustfmt will fail due to unformatted code in `tests/testsuite/`.
This will fix the rustfmt CI.
=> style: Fix rustfmt formatting warnings in CI

docs/config/README.md, src/modules/cmd_duration.rs, tests/testsuite/cmd_duration.rs
This PR aims to implement a configurable prefix for the command duration module
Closes #402 
```toml
[cmd_duration]
prefix = "underwent "
```
=> feat: Added ability for setting command duration prefix

docs/config/README.md, src/modules/memory_usage.rs, src/modules/time.rs
This PR disables the `memory_usage` module by default.
The `memory_usage` module is very long  (many characters in length) by default, and can be active in any directory based on current memory usage. For many, this may be considered a little too noisy and unactionable.
The modules we usually have enabled by default should be affected by your working directory, keeping modules that aren't smaller or optional.
=> fix: Disable memory_usage by default

starship/src/configs/mod.rs
When doing the rebase for the kubernetes config module it looks like I
missed adding the module to the default prompt order.
Closes #
=> fix: Add Kubernetes to the default prompt order

src/modules/memory_usage.rs, src/modules/time.rs, tests/testsuite/time.rs
This PR will remove code judging the `disable` option from `src/modules`, as long as related tests.
=> chore: Remove logic for the `disabled` option from modules

docs/config/README.md, src/configs/kubernetes.rs, src/configs/mod.rs, src/modules/kubernetes.rs
Given the global nature of the Kubernetes module have disabled the
module by default. Have also taken this opertunity to refactor the
Kubernetes module to use the new config module.
Closes #484
=> fix: Disable Kubernetes module by default

src/modules/memory_usage.rs, src/modules/time.rs, tests/testsuite/time.rs
Due to the removal of the `disabled` logic, modules that were previously hidden by default are now shown by default:
I mistakenly skimmed this PR and thought that these modules were already refactored, leaving the `disabled` logic as unnecessary artifacts before the refactor.
We'll have to revisit this at a later point. 😅
=> revert: chore: Remove logic for the `disabled` option from modules

src/context.rs, src/modules/kubernetes.rs, src/print.rs
This PR adds one line to skip the module if it is not enabled in the config.
It also renames `fn is_module_enabled` to better reflex its functionality.
I used to think `is_module_enabled` has a higher order functionality to judge if the module is disabled, but it turns out it only reads the user's config and ignores the default one. (Thanks to @andytom to point it out!)
Related #484 #486 #489
=> fix: Add disable option to kubernetes module

docs/config/README.md, docs/de/config/README.md, docs/fr/config/README.md, docs/ja/config/README.md, docs/ru/config/README.md, docs/zh/config/README.md, src/configs/mod.rs, src/configs/time.rs, src/modules/time.rs
Rewrite `time` module to use module config
Since the new module config uses struct fields, we cannot use `12hr` as a config key. So I updated `12hr` to `use_12hr`.
If `ModuleConfig` proc macro has `rename`-like attribute, we can keep backward compatibility.
Related #383
=> refactor: Rewrite `time` module to use module config

src/module.rs, src/print.rs
Not show the prefix of the first module of the 2nd line.
I'd never used Rust before - not sure if there is any more elegant way to do this so feedback is welcome.
Closes #461
I config'ed my prompt to have 2 lines and made sure the prefixes of the 1st modules not show up.
=> fix: Don't print the first module prefix after a line-break

docs/config/README.md, src/modules/java.rs
Java information is also displayed when a build.sbt file is present.
Closes #467
=> feat: Show Java icon and info when build.sbt detected

src/print.rs
This makes it easier to embed Starship into other Rust programs such as shells written in Rust. It also decouples the arguments from the context for more programmatic initialisation of the context.
Partially this issue: https://github.com/nushell/nushell/issues/356 and also just making it easier to use Starship as a Rust library for those building shells in Rust.
Kind of N/A I suppose since the change is internal and tiny.
=> refactor: Allow starship to be better used programmatically

Cargo.toml
Currently, the release profile uses Cargo defaults. It *might* be useful to enable common optimizations - allowing LTO and improving optimization opportunities by restricting parallel code generation.
Numerous projects opt for these options to gain runtime speed and/or smaller binary size at the expense of release build compile times. Since this project aims to run blazing fast it seems like a good fit.
_Feel free to reject this PR if not suitable!_
No reliable runtime benchmarking has been performed. Please, suggest a methodology if you have one.
Release binary sizes with and without the optimizations enabled (and the stripped versions):
`-rwxr-xr-x 1 foo foo 6619120 Oct 12 10:26 starship_v22`
`-rwxr-xr-x 1 foo foo 4773088 Oct 12 10:28 starship_v22_lto`
`-rwxr-xr-x 1 foo foo 3723104 Oct …
=> build: Improve release binary optimization

src/modules/directory.rs
Fixed a bug on unix systems where the leading `/` of the path was being removed when exactly `truncation_length` directories deep into a path.
The issue was that the method used to find the depth leveraged a `<string>.split('/')` which resulted in a vector of `["", "foo", "bar", "baz"]` instead of `["foo", "bar", "baz"]`. This resulted in the leading `/` being removed because the logic considered the user to be 4 directories deep when they were actually only 3 directories deep.
Closes #458 
It works!
- [N/A] I have updated the documentation accordingly.
- [N/A] I have updated the tests accordingly.
=> fix: Show leading slash when truncating from root

README.md
Added installation method for generic x64 Linux to README.md (tested method on Ubuntu 16.04 / bash)
=> docs: Add x86-64 linux binary installation instructions

tests/testsuite/aws.rs, tests/testsuite/common.rs, tests/testsuite/dotnet.rs, tests/testsuite/git_state.rs, tests/testsuite/golang.rs, tests/testsuite/nodejs.rs, tests/testsuite/python.rs, tests/testsuite/ruby.rs
We used to run into problems when running tests with tempdirs in Docker, but it looks like the problem has solved itself (perhaps in an update for tempfile or Docker).
This PR removes the test utility used for creating tempdirs and instead uses `tempfile::tempdir` directly. 
Closes #
=> refactor: Replace tempdir test utility with tempfile::tempdir

src/context.rs, src/modules/character.rs, src/modules/cmd_duration.rs, src/modules/jobs.rs
This removes ArgMatches from the Context struct and replaces it with a simple HashMap.
This work is towards getting Starship in a better place for use as a library in other shells written in Rust so they don't need to use a command-line interface to invoke and configure things.
Contributes to #521
=> refactor: improve as-a-library usage by removing ArgMatches dependencies

src/modules/directory.rs
=> Refactor: Remove unnecessary parentheses in if condition

docs/config/README.md, docs/de-DE/config/README.md, docs/fr-FR/config/README.md, docs/ja-JP/config/README.md, docs/ru-RU/config/README.md, docs/zh-CN/config/README.md, docs/zh-TW/config/README.md
I changed `icon` into `symbol`
`Memory Usage` option key `icon` in [Configuration](https://starship.rs/config/#memory-usage) doesn't work.
So I fixed the documentation in all languages.
=> docs: Fix `Memory Usage` option key

src/configs/mod.rs, src/configs/starship_root.rs
This PR moves `StarshipConfig` and its implementation to `starship_root.rs`.
It makes `src/configs/mod.rs` cleaner, but may make it harder for developers to find the default prompt order..
=> chore: Move StarshipRootConfig to a separate file

src/init/starship.fish
Set the `VIRTUAL_ENV_DISABLE_PROMPT` variable in `starship.fish`, venv status is already shown in the prompt via the python module.
Closes #549
=> fix: Disable venv custom prompt when starship is in use

docs/config/README.md, src/config.rs, src/configs/starship_root.rs, src/context.rs
Starship will now only scan a subset of the current directory to avoid slow down in a folder with a large amount of files. Currently the default limit is 3000.
(The limit is set so that it will cost less than 50ms to render the prompt. 264755 / 2.715 * 0.05 \sim 4876)
Fixes #588
=> feat: Add an option to limit the duration of starship directory scanning

docs/config/README.md, src/modules/python.rs, tests/testsuite/python.rs
This will enable the python module when a virtual environment has been
activated, this is detected via the `VIRTUAL_ENV` env var.
Since the python module displays the currently active virtual env it
makes sense to activate it when a virtual env is active.
=> feat: Enable the python module in virtual envs

.github/workflows/workflow.yml
Changes the github actions from the rust gnu toolchain to msvc
The x86_64-pc-windows-gnu toolchain has a bug where one of the libs is out of date. Switching to the msvc toolchain allows for latest windows builds to compile.
Fix github actions and release builds
see: https://github.com/rust-lang/rust/issues/49078
=> ci: Switch to the msvc rust toolchain

src/modules/kubernetes.rs
This adds support for having multiple Kubeconfig file set as part of the
`KUBECONFIG` env var.
Closes #464
=> fix: Add support for multiple Kubeconfig files

src/modules/package.rs
Have updated the package module to not add a `v` if the version already
has a prefixed `v`.
Closes #647
=> fix: Stop adding duplicated v to package versions

docs/.vuepress/styles/index.styl, docs/.vuepress/styles/palette.styl
Hey boo @matchai 👋 
While working with Vuepress for somethin' else, something pretty neeto if I do say so myself, I copied the structure of this repo's docs. However, I came across these FAQ items:
* https://vuepress.vuejs.org/config/#palette-styl
* https://vuepress.vuejs.org/faq/#why-can-t-palette-styl-and-index-styl-merge-into-one-api
TLDR (about `palette.styl`):
> You should ONLY write color variables in this file. Since palette.styl will be imported at the end of the root Stylus config file, as a config, several files will use it, so once you wrote styles here, your style would be duplicated by multiple times.
Aside from moving these styles to `index.styl`, the only additional change was slapping on an `!important` to the hero image's `max-width`. #css.
Speed, correctness, the desire …
=> docs: Move styles to index

.github/workflows/workflow.yml
When building the release artifacts, generate a shasum for the binaries
For each build step, generate a shasum of the starship binary and separate the build and release jobs to combine them all into one file.
Sample release with shasums here: https://github.com/marblenix/starship/releases/tag/v0.26.5-TEST33
https://github.com/ScoopInstaller/Main/pull/566#issuecomment-553527644
Closes #620
=> ci: Generate release sha256 sums

docs/config/README.md
Our current instructions for setup include the following line:
"To get started configuring starship, create the following file: `~/.config/starship.toml`."
We then instruct the user to run the following command:
`touch ~/.config/starship.toml`
Although most users will have a `~/.config` directory and others will know to create one, there are new users who may not have a ~/.config` directory and may not know that they need to create one. One such user created issue #593.
We could prevent new users from having a similar reaction by adding a `mkdir -p` command to the instructions.
Although most users don't need it, it won't hurt anything and doesn't make the instructions significantly longer or more confusing.
Add `mkdir -p ~/.config` to configuration setup instructions.
Addresses #593.
=> docs: Update README to create ~/.config

src/modules/golang.rs, src/modules/java.rs, src/modules/nodejs.rs, src/modules/python.rs, src/modules/ruby.rs, src/modules/username.rs
Have refactored the golang, java, nodejs, python, ruby and
username modules to use the new `exec_cmd` util.
I am not very familiar with how the command function is being using
in the `rust` and `dotnet` modules so leaving them for a later, or
someone else if they are more familiar than me. 
This is just a refactor to reduce some common code.
=> refactor: Refactor modules to use the exec_cmd util

docs/config/README.md, src/configs/conda.rs, src/modules/conda.rs, src/modules/directory.rs, src/modules/utils/directory.rs, src/modules/utils/mod.rs, tests/testsuite/conda.rs
Environment names created via `conda create -p [path]` tend to be too long for comfort, so this truncates them.
This uses the same function as the `directory` module, since I moved the function into `utils`.
Closes #675
=> fix: Truncate long paths in conda environment names

README.md, docs/config/README.md, src/modules/package.rs
Added an extra function to the Package module, allowing it to display the version number found in `composer.json` in the current folder.
I've never written a single line of Rust before in my life, but I figured I'd see if I could add this tiny feature. It's basically just a modified version of the `package.json` detection.
I've added a unit test (modified version of of the `package.json` test), and all tests are passing.
=> feat: add composer.json version to Package module

src/module.rs
Wrap the module prefix and suffix in shell-specific escape codes. These shell-specific codes help the terminal emulator calculate the size of the prompt.
Closes #290
bash 3.2
zsh 5.7
starship.toml:
```toml
add_newline = false
prompt_order = [
"directory",
"git_branch",
"git_state",
"git_status",
"character"
]
```
Tested on MacOs Catalina with iTerm2 and the built-in Terminal app. Tested on both bash and zsh. Tested rust, node, python and battery modules.
There aren't any unit tests in this area. As a rust newbie I was a little lost on how to approach. Tips welcome.
=> fix: Wrap prefix and suffix in shell-specific escape codes

src/configs/starship_root.rs, src/configure.rs, src/main.rs
This is a implementation of the `starship configure` command that I proposed in https://github.com/starship/starship/issues/743. I don't even know if this enhancement is wanted or not, but if you want a preview, just checkout my branch and run `cargo run -- configure` or something.
Starship is highly configurable and customizing it is a very common thing, at least for me. It is a bit tedious to type `vi ~/.config/starship.toml` each time i want to configure Starship. This PR introduces the flexible and ergonomic `starship configure` command.
**Behavior:** `configure` opens the Starship configuration file in a desired editor. This may be a simple editor like nano or even an editor with a GUI. The command waits for the user to finish editing and then exists.
**Editor configuration and …
=> feat: Implement `starship configure` command

src/init/starship.bash
This fixes the issue reported in #629 
I just modified the `starship.bash` script template, to save the original `$_` special parameter when DEBUG is trapped and restore it at the end of the starship_preexec[_all] function.
Closes #629
When we get our prompt, last executed command is `starship_preexec`. This overwrites the original $_ special parameter.
```bash
~ 
❯ echo foo
foo
~ 
❯ echo $_
starship_preexec
~ 
❯ 
```
```bash
~ 
❯ echo foo
foo
~ 
❯ echo $_
foo
~ 
❯ 
```
=> fix(bash): save and restore "$_"

src/configure.rs
- look for $VISUAL first, then $EDITOR, then the default
- panic if we can't find the home dir
- [This seems to be the standard](https://unix.stackexchange.com/questions/4859/visual-vs-editor-what-s-the-difference/)
- If we can't find the home dir, there's not much reason to continue
(originally, this would open a file called `<unknown config>`
=> fix: Improvements to `starship configure`

.github/workflows/workflow.yml
- Use `v1` tag instead of `master`
- Do not specify patch in `php-version` as the latest one is installed
The action now advocates using `v1` tag.
Versions with patch are not supported, specifying just major and minor like `php-version 7.3` setups the latest patch of PHP for `7.3`
=> ci: Use fixed version of setup-php in test workflow

src/context.rs
Changes the error message that is presented when the current directory can't be read for some reason, so as not to have a ".: <error message>".
This is a pretty common condition - for example, when you create a new directory in a git repo and then `git reset --hard`, or `git checkout`, or whatever - so the error message is important.
The message goes from 
```
thread 'main' panicked at 'Unable to identify current directory.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
```
to
```
thread 'main' panicked at 'Unable to identify current directory. Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
```
I don't think it needs a lot of testing, it's just a change to a constant string.
I …
=> fix: nicer error message when current directory is gone

docs/config/README.md
In the `time` module, bring `disabled` option at the end of the table.
Coherence with all the other modules of the readme.
=> docs(config): Disabled at the end of the options

starship_module_config_derive/src/lib.rs
This PR slightly changes the `ModuleConfig` derive code to use the `Option::and_then()` method. `and_then()` is useful to string multiple `Option` values together so that we only need a single `?` assertion at the end. It also often makes the code simpler to read because the execution order matches the reading order.
> Why is this change required? What problem does it solve?
It is not required but I noticed it during some other development and thought it would be useful to improve this.
=> refactor: ModuleConfig: Simplify generated `from_config()` implementations

src/configure.rs
We thought that Issue https://github.com/starship/starship/issues/769 was a result of empty `$VISUAL` and/or `$EDITOR` variables, which were indeed a problem. However, the same error occurs when an environment variable contains arguments or options. This will cause `starship configure` to panic:
```shell script
export VISUAL="vi -m"
```
While https://github.com/starship/starship/pull/770 fixes the bug for empty environment variables, this PR takes all options like `-m` into account when executing the editor.
Closes https://github.com/starship/starship/issues/769
=> fix: Parse arguments of $VISUAL and $EDITOR

src/modules/package.rs
The `package` module was ignoring the `--path` CLI option. This PR adjusts the implementation to use the `context.current_dir` value to fix this issue.
see above :)
=> fix(package): Use specified directory instead of current working directory

src/init/starship.bash
Remove any trailing semicolon in $PROMPT_COMMAND before appending starship_precmd, to prevent syntax error.
Remove trailing semicolon if exist in PROMPT_COMMAND before appending starship_precmd
Closes #771 
Latest starship release breaks on my system with direnv and pyenv hooks enabled at login. Here is the error message
```shell
-bash: PROMPT_COMMAND: line 5: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 5: `_direnv_hook;_pyenv_virtualenv_hook;;starship_precmd'
```
Semicolon is duplicated on the line and make the command become syntactically wrong. The fix is to remove any trailing semicolon from previous `$PROMPT_COMMAND` before appending `;starship_precmd`
Just tested the variable assigning, not yet build starship
Don't know much, I'm just started using starship …
=> fix: Remove trailing semicolon from `$PROMPT_COMMAND`

docs/config/README.md, src/configs/git_status.rs, src/modules/git_status.rs, tests/testsuite/git_status.rs
Added stash count to the git status module.
The git_module has been updated to add the number of stashes for the current repo after the stash symbol ("$"). Documentation has been updated accordingly.
Closes #595
Tested on mac by running new unit tests and running the docker test. Also built a release build and manually tested that.
---
I'm new to rust so please correct me if I made any obvious mistakes! I'll update the PR as soon as I can.
=> feat: Add stash count to git_status module

src/configure.rs
Makes `starship configure` consider the `$STARSHIP_CONFIG` variable before falling back to the default of `~/.config/starship.toml`.
It seems that @dominikbraun and I both forgot this environment variable.
=> fix: Consider `$STARSHIP_CONFIG` in `configure`

src/modules/hg_branch.rs, tests/testsuite/hg_branch.rs
perf: don't use `hg` process to get branch / bookmark information, each call was taking 250ms and it was making on average 2 calls.
the branch and bookmark information is available in files in the root of the repo, use that instead.
now takes 300 micro seconds
fix: do not use `.hgignore` to decide if it is an hg repo. was providing false positives. #721 
fix: after changing branch the new branch was not show (the old branch was shown), the new branch is now correctly shown. #722 
fix?: if no branch override was set it would say `(no branch)` however if you commited in that state you would commit to the branch `default` so say that instead
Closes #721 and #722 
Perf: 402ms -> 373.4µs (1000x faster)
=> perf: hg_branch, fix: show active branch not previous branch

src/init/starship.bash
feat: Add trailing semicolon to end $PROMPT_COMMAND properly.
This will prevent starship_precmd to accidentally mess with other hooks invoked after it.
Just add trailing semicolon to end the command properly
Just to make starship play nice with any hooks invoked after it.
=> feat: Terminate $PROMPT_COMMAND properly

tests/testsuite/aws.rs
Update AWS module tests to ignore the two tests that can fail if the
`~/.aws/config` file exists.
Note this will fix the issue reported in #748 but long term we should
consider maybe mocking the `read_file` helper function in when running
tests in the future.
Closes #748
=> test: Ignore AWS tests that depend on the File System

src/modules/dotnet.rs
Have refactored the dotnet module to use the util::exec_cmd rather than
the Command module directly.
Related to #676, #768 and #289
=> refactor(dotnet): Use `exec_cmd` util

Cargo.toml, src/bug_report.rs
This fixes the issue reported in #749 
By only using a simple template in the url and instead copy the environment info to the clipboard, I think we can land on a nice middle ground between not loosing to much of the convenience while still being able to handle large configs.
A quick search on the web tells me that most browsers are happy as long as URLs are not much longer than ~2000 character, which may present some problems in regards to larger configs. The URL linked in the issue is almost 10,000 characters long.
Closes #749
This works consistently when testing with HUGE configs (300,000+ characters).
=> fix(bug-report): URLs too long

src/modules/cmd_duration.rs, tests/testsuite/cmd_duration.rs
Fixed the way the cmd_duration module is setting it's prefix to be the
same as the other modules.
Closes #829
=> fix(cmd_duration): Correct prefix usage

Cargo.lock, Cargo.toml, src/bug_report.rs
reqwest is quite a heavy dependency in terms of file size and pulls in a lot of async related dependencies (tokio) despite starship only using the blocking API.
By replacing reqwest with ureq binary size on windows release builds is reduced by ~30%.
=> refactor: replace reqwest with ureq

src/modules/python.rs
The `python --version` command will return "Python 3.6.10 :: Anaconda, Inc." if it is an Anaconda build of Python. This makes the prompt very long. This PR trims that extra text so that the version segment is just the version.
Having the version of python include this text makes it very long.
Here's an example of what I see before this fix:
Added a test case with the version string that appears for Anaconda versions of python.
Docs say "The `python` module shows the currently installed version of Python." which is still accurate.
Added test including the Anaconda text in the version string
=> feat: Trim "Anaconda, Inc." from Python version

docs/config/README.md, src/modules/java.rs
Currently the Java module detection looks for `build.gradle` specifically, but it's possible to rename `build.gradle` to `*.gradle`. This change adds Gradle files to the list of detected file extensions.
Closes #833.
No tests existed for this, so I wasn't sure whether I should add any. I can if you'd like. 😄
=> fix(java): Add detection for *.gradle files

src/context.rs, src/module.rs
An alternative approach to fix the issue of PR #658.
I modify the method `ansi_strings_modified` in the `module` in order to replace the character `$` with `\$`. This avoid the possibility to inject code with the git branch name or other sources.
Alternative solution for PR #658
I used the repo [pw3nage](https://github.com/njhartwell/pw3nage) to test the solution.
=> fix: escape "$" character to avoid bash interpreting

docs/.vuepress/config.js, docs/.vuepress/styles/palette.styl, docs/package-lock.json, docs/package.json
I added a dark theme to the starship documentation. Currently it only supports the `prefers-colorscheme` media query with no manual toggle
=> docs: Added dark theme to documentation

src/context.rs, src/modules/dotnet.rs, src/modules/rust.rs
Changes the `Vec<PathBuf>` containing all files and folders in context.rs to be a new struct called `DirContents` that optimises for lookup time on various relevant entities, e.g. files, folders and file names.
Closes #852.
=> perf: Optimize files, folder and extension lookups in Context

src/utils.rs
Changed a test that failed on my machine (NixOS - `echo` is not in `/bin`):
https://github.com/starship/starship/blob/2968aac3ca173954cfc9eaef22c062a6ec0946cc/src/utils.rs#L105
to use `/bin/sh` like the tests that follow it:
https://github.com/starship/starship/blob/2968aac3ca173954cfc9eaef22c062a6ec0946cc/src/utils.rs#L116
https://github.com/starship/starship/blob/2968aac3ca173954cfc9eaef22c062a6ec0946cc/src/utils.rs#L127
Test no longer fails when `echo` is not in `/bin`.
I have been using starship for a few months now and am loving it. Looking to start contributing back, and just found this issue when running the tests for the first time.
=> fix: make echo test use /bin/sh

src/context.rs, src/module.rs, src/print.rs, src/utils.rs
Moves ANSI colorseq escape functionality into its own functions and adds tests.
One of the proposed changes in #865 involved escaping an ANSI code from within `print.rs`. Currently, escaping these sequences is done inside of a closure inside `module`, which prevents it from being used elsewhere.
This change allows us to escape unprintable characters from anywhere inside starship, as well as allowing a greater variety of escape sequences and tests specific to the escape parser (as opposed to just the module string generator).
Refactoring
=> refactor: Move ANSI escaping into its own functions

src/init/starship.ion
ion shell has apparently changed the name of the command duration variable at some point from `ION_CMD_DURATION` to `CMD_DURATION`. This breaks the prompt script and presents the following message instead of the prompt:
```
ion: prompt expansion failed: expansion error: Variable does not exist
>>> 
```
This changes the variable in the prompt script from `ION_CMD_DURATION` to `CMD_DURATION`.
This could introduce a potential issue where starship would break in older versions of ion. As ion so far has to be compiled from source to use it on MacOS and most LInux distros, there is no _current_ version, so ion users will have starship break whenever they re-compile.
This makes starship work on version of ion compiled the last month (and a half?) or so.
=> fix: Change command duration variable to CMD_DURATION

docs/config/README.md
`dim` doesn't seem to work and `dimmed` works.
I also suggest ⛴ more than ⛵ since k8s's color is blue than red
Closes #
=> docs: Fix kubernetes style dim to dimmed

docs/config/README.md, src/configs/mod.rs, src/configs/singularity.rs, src/configs/starship_root.rs, src/module.rs, src/modules/mod.rs, src/modules/singularity.rs, tests/testsuite/main.rs, tests/testsuite/singularity.rs
(Reopened #602)
Singularity is one of the tools to run containers. A popular use case is to run it as a development environment, especially for older platforms.
As one might use several different images it is useful to display the image we are currently in.
Currently the default display is after hostname wrapped in `[` and `]` as it is the shortest. I'm open to suggestions if another defaults are more reasonable.
=> feat: Add singularity module

docs/config/README.md, src/configs/elixir.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/module.rs, src/modules/elixir.rs, src/modules/mod.rs, src/utils.rs
Add an Elixir module, detecting Elixir and OTP versions when it detects a `mix.exs` file.
I have some Elixir projects and it missed me to not see versions while many others languages have them displayed.
Closes #149
=> feat: Add Elixir module.

src/configure.rs
STD_EDITOR falls back on `vi` if `$EDITOR` and `$VISUAL` is not set.
However, some machines might not have `vi` symlinked or installed and a bad error message is displayed.
This commit adds a better error message.
Was trying to configure starship on a fresh Arch Linux install where I:
- have yet to properly set `$EDITOR` and `$VISUAL`
- have `vim` installed but not `vi`
- have yet to symlink `vi` to `vim`
I was pretty confused about the first error message and had to do some digging to resolve the issue, so I decided to improve the error message.
See above
Not really sure how to write tests for this specific scenario.
Also, these are literally the first few lines of rust I have ever written, so do let me know if I'm doing anything incorrectly or if anything can be improved. Thanks!
=> fix: check if editor is not found for `configure`

Cargo.toml, src/bug_report.rs
reqwest is a heavy dependency and not essential to starship thus gate it behind a `http` feature.
Closes #977
=> feat: make reqwest optional dep

src/utils.rs
This patch prints error log for `utils::exec_cmd` failure.
I was debugging #983 and just found the errors are silenced.
I think this patch will work on most platforms; it's a small fix.
=> fix(utils): Print log for exec_cmd failure

docs/config/README.md
The order of the modules in the configuration section of the documentation, was only partly alphabetical. I changed that, so that all modules (except the _prompt_) are listed alphabetically.
I was confused by the non-alphabetical order ;)
Started the `npm run dev` environment of the VuePress website and checked in a browser.
=> docs: Change the order of the modules in the configuration to reflect alphabetical sorting

docs/config/README.md, src/modules/package.rs
Julia's packages have the version in `Project.toml` .
(ref: [The version field](https://julialang.github.io/Pkg.jl/v1/toml-files/#The-version-field-1))
~Closes~
https://github.com/starship/starship/pull/1030#issuecomment-604921966
I tested in [LanguageServer\.jl/Project\.toml at c3e92a494e8613c9cbd35a65140f9f0fc75208d5 · julia\-vscode/LanguageServer\.jl](https://github.com/julia-vscode/LanguageServer.jl/blob/c3e92a494e8613c9cbd35a65140f9f0fc75208d5/Project.toml).
=> feat(package): Add project version for julia

docs/config/README.md, src/configs/docker_context.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/module.rs, src/modules/docker_context.rs, src/modules/mod.rs
Adds a simple module that checks for a Docker config file and if present, reads the `currentContext` value out and displays on the prompt with a whale.
Closes #995
=> feat: add docker context module

docs/config/README.md, src/modules/aws.rs, tests/testsuite/aws.rs
[aws-vault](https://github.com/99designs/aws-vault) sets the `AWS_VAULT` env var instead of `AWS_PROFILE` when an aws-vault session is active.
This PR adds support for reading the AWS profile value from the `AWS_VAULT` env var, giving priority to `AWS_VAULT` if both it and `AWS_PROFILE` are set.
Tested locally on MacOS:
```
❯ aws-vault exec dev --
Welcome to fish, the friendly interactive shell
☸ kube-dev in ~/s/starship on  aws-vault-profile is 📦 v0.37.0 via 🦀 v1.41.0 on ☁️  us-west-2
❯ env|grep AWS_PROFILE
❯ env|grep AWS_VAULT
AWS_VAULT=dev
❯ ./target/debug/starship prompt
☸ kube-dev in ~/s/starship on  aws-vault-profile is 📦 v0.37.0 via 🦀 v1.41.0 on ☁️  dev(us-west-2)
```
I've also added a test to the `aws` testsuite.
- [?] I have updated the documentation accordingly.
I'm happy to …
=> feat(aws): Use AWS_VAULT as the profile if set

src/modules/git_branch.rs, src/modules/git_status.rs
As described in the linked issue, the `git_branch` and `git_status` modules are not working on bare repos, because they don't have an explicit branch_name (according to libgit2 anyway). 
Since `git status` reports the branch name of empty repos as `master` I implemented that name as a fallback for those two modules.
Closes #686
=> fix(git_branch,git_status): implement fallback branch_name for bare git repos

docs/config/README.md, src/configs/nix_shell.rs, src/modules/nix_shell.rs, tests/testsuite/nix_shell.rs
Add's a ❄️ icon to the nix-shell module. While at it, changed the default color to blue to be consistent with the nix colorscheme.
Closes #1048
Before:
After:
=> feat(nix_shell): add symbol to nix-shell module

docs/config/README.md, src/modules/package.rs
Elixir projects have their version in `mix.exs` and follow:
`MAJOR.MINOR.PATCH-PRERELEASE+BUILDINFORMATION`
See [Elixir Docs](https://hexdocs.pm/elixir/1.10.2/Version.html#content) for details.
I want to see the version number info for Elixir projects.
=> feat(package): Add project version for Elixir

Cargo.lock, Cargo.toml, docs/config/README.md, src/config.rs, src/configs/custom.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/context.rs, src/modules/custom.rs, src/modules/mod.rs, src/print.rs
Add custom modules to starship:
```toml
prompt_order = [
"custom.foo",
"custom.bar",
]
[custom.foo]
command = "echo foo"  # shows output of command
files = ["foo"]       # can specify filters
extensions = ["py"]   # can specify filters (cont)
prefix = " transcending "
[custom.bar]
command = "echo I will never get echo'd"
when = "false"  # if no filter matches, fall back to executing 'when'
```
I also want to have custom commands, especially for personal or company-specific commands and environments. This allows any sort of section to be added.
Closes #664, Closes #790
I tested multiple configurations in the terminal, experimenting with various settings.
=> feat: Add support for custom modules.

tests/testsuite/conda.rs
The user's config is automatically loaded in context.new_module. This change explicitly sets the empty config to avoid depending on the environment.
Without this fix, the tests do not pass for users who have a custom symbol defined for conda. This prevents installing/upgrading from Arch Linux AUR.
N/A
Tests (`cargo test`) no longer fail on my machine.
=> fix(conda): Do not depend on user's config in conda tests

src/modules/python.rs
This fixes an issue where the name of the virtual environment is not
being shown when using the `pyenv_version_name` setting.
Closes #1045
=> fix(python): Fix venv name not showing when using pyenv

docs/config/README.md, src/configs/python.rs, src/modules/python.rs, tests/testsuite/python.rs
Adds a new Python module option to disable detecting `*.py` files in the current directory.
I have a lot of directories with random python files in them, that I don't want/need the Python module cluttering up my prompt. For example my home directory has a `test.py` file, a project I'm working on has a `test-webserver.py` file, and so on.
I only want the Python module activating in my real Python projects. Generally these are covered by the virtualenv detection and existing hardcoded filename checks (`requirements.txt` etc), but I've added `setup.py` and `__init__.py` as additional hardcoded failsafes to support this use-case.
Lots of Python tests are disabled. It seems because the tests hardcode the expected version of Python which requires them to be run with Python 3.7.5. I've added …
=> feat(python): Add scan_for_pyfiles option

src/formatter/parser.rs, src/formatter/spec.pest, src/formatter/string_formatter.rs
This PR improves the format string parser, including the following briefly.
- Allow scoped variables (`${var}`), which means:
- it would be possible to append some characters after a variable, e.g. `${var}s`
- it would be possible to add some additional parameters to a variable, e.g. `${env:HOST}`
- Add documentation to the spec
- Simplification of the spec
- Confine some rules
- In a textgroup `[format](style)`, `style` will not accept escaped characters now. e.g. `[symbol](red \[)` will result in a parse error.
- String started with a number (0-9) will not be recognized as a valid variable name now. e.g. `$9var` will result in a parse error.
=> feat(formatter): Allow scoped variables

docs/config/README.md
Minor fix in configuration README, it showed an unused `:::` tag, this PR removes it.
=> docs: Remove unused closing tag

README.md
README does not include the "🚀" anchor for the installation sub-section.
This adds it.
=> docs: Fix broken installation link anchor on README

src/configs/starship_root.rs, src/modules/mod.rs
This commit adds crystal to prompt_order, in the same position as specified in the docs.
Additionally, a description was missing for crystal, so we add one.
The docs say that the crystal module is part of the default prompt_order.
However, this was not the case in the actual code.
=> fix: Add Crystal module to default prompt order (documentation was updated in f665df2)

src/modules/mod.rs
Add description for the haskell module, used by the explain command.
A description was missing for the haskell module when caling `starship explain`.
=> fix(haskell): add description for haskell, used by the explain command

src/formatter/model.rs, src/formatter/parser.rs, src/formatter/spec.pest, src/formatter/string_formatter.rs
This PR adds a `()` wrapper that hides the format string inside when all variables in that format string are empty (or `None`).
See https://github.com/starship/starship/discussions/1116#discussioncomment-5414 Option 4
=> feat(format_string): Allow positional segments

src/formatter/string_formatter.rs
This PR will make multiple mappers working in `StringFormatter`.
e.g. In the following string formatter
```rust
let formatter = StringFormatter::new(FORMAT_STR)
.unwrap()
.map(|var| match var {
"a" => Some("$a"),
"b" => Some("$b"),
_ => None,
})
.map(|var| match var {
"b" => Some("$B"),
"c" => Some("$c"),
_ => None,
});
```
Variables before:
```json
{
"b": "B",
"c": "c"
}
```
Variables in this PR:
```json
{
"a": "a",
"b": "b",
"c": "c"
}
```
A drawback is that, it becomes impossible to update an existing variable when the variable is already filled.
=> fix(format_string): Allow multiple variable mappers

src/modules/haskell.rs, src/utils.rs
This PR changes the arguments to `stack` in the Haskell module to avoid creating a `stack.yaml.lock` file which interferes with Git. It also reorders the arguments to avoid downloading GHC if the required version isn't already installed.
Starship was creating `stack.yaml.lock` files, even right after deleting them. This made it awkward for me to pull new changes to a Git repo containing a `stack.yaml` -- in fact I had to open a bash shell without Starship.
After I had updated the repo, Starship hung for quite a while before I killed it. I'm not 100% sure, but suspect that it was downloading and building a new version of GHC.
In terms of both the `stack.yaml.lock` and downloading GHC behaviour, I think Starship should generally be side-effect free.
Closes #1146.
- [?] Breaking change (fix …
=> fix(haskell): avoid creating .lock files or downloading GHC

docs/config/README.md, src/configs/package.rs, src/modules/crystal.rs, src/modules/elixir.rs, src/modules/elm.rs, src/modules/erlang.rs, src/modules/golang.rs, src/modules/haskell.rs, src/modules/julia.rs, src/modules/nodejs.rs, src/modules/package.rs, src/modules/php.rs, src/modules/ruby.rs, src/modules/utils/test.rs
This PR adds config `display_private` in package scope.
If true, it will display version for `package.json` marked as private
In my job, we mark as private company packages that are not published to npm registry,
without this i can't see current package version
Closes #1053
=> feat(package): configurable displaying package version for packages marked as private

src/formatter/model.rs, src/formatter/string_formatter.rs
This PR adds error handling to the API of `StringFormatter`.
```rust
impl StringFormatter {
// Before
pub fn map<T, M>(mut self, mapper: M) -> Self
where
T: Into<Cow<'a, str>>
M: Fn(&str) -> Option<T> + Sync
{}
// After
// similar changes are done to `self.map_*()`
pub fn map<T, M>(mut self, mapper: M) -> Self
where
T: Into<Cow<'a, str>>
M: Fn(&str) -> Option<Result<T, StringFormatterError>> + Sync
{}
// Before
pub fn parse(self, default_style: Option<Style>) -> Vec<Segment> {}
// After
pub fn parse(self, default_style: Option<Style>) -> Result<Vec<Segment>, StringFormatterError> {}
}
```
Related https://github.com/starship/starship/discussions/1116#discussioncomment-6878
=> refactor: Add error handling to variables

src/init/starship.ps1, src/modules/directory.rs, tests/testsuite/directory.rs
Powershell supports PSDrives (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7) that allows to create "logical" drives mapped to actual Windows drives.
When using PSDrives, you can use paths that are related to a logical drive.
For example, test: can be "mapped" to c:\test folder.
You can then use "cd test:" to change the current location.
Many other drives exist be default (env, function, variable etc...). 
These "Powershell" paths confuse starship modules that fail to return the correct result.
Changing the --path argument to a Windows path (instead of the Powershell one) fixes the issue.
In our example, with the fix, when "cd test:\" is used, starship is called with --path C:\test (instead of test:\).
Closes:
This change …
=> fix(directory): avoid confusing modules with PowerShell paths

src/context.rs, tests/testsuite/git_branch.rs
Since #1035 didn't quite do what it was supposed to, I had another look and figured out the problem is actually that libgit2 doesn't return a `HEAD` if it's pointing to an unborn branch (like in the case of a freshly initialised repo). 
AFAIK (please correct me if I'm wrong) the only valid case where this error would occur is a fresh repo, so I think it's fine if the module assumes the branch name to be "master" in that case, since the git cli acts the same.
Closes #686
=> fix: branch_name in fresh repo (unborn master)

snapcraft.yaml
Add required dependencies for successful build.
The snap has been failing to build. Apologies for not noticing.
Here's a snippet of a recent [build log](https://snapcraft.io/starship/builds/942067).
```
Compiling starship_module_config_derive v0.1.1 (/build/starship/parts/starship/build/starship_module_config_derive)
Compiling pretty_env_logger v0.4.0
error: failed to run custom build command for `openssl-sys v0.9.55`
Caused by:
process didn't exit successfully: `/build/starship/parts/starship/build/target/release/build/openssl-sys-2d4e1b6abab932ae/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR …
```
=> fix: snap build failure

docs/config/README.md, src/configs/rust.rs, src/modules/rust.rs
This PR deprecates `symbol` `version` `style` keys in `RustConfig`, and adds `format` key instead.
Also can be used as an example of refactoring existing modules.
Related #1057
=> refactor(rust): Use format strings

docs/config/README.md, src/configs/env_var.rs, src/modules/env_var.rs, tests/testsuite/env_var.rs
This PR deprecates `symbol` and `style` keys in the `env_var` module to replace it with the `format` key instead.
=> refactor(env_var): Added formatter support for the env_var module

docs/config/README.md, src/configs/memory_usage.rs, src/modules/memory_usage.rs
This PR adds support for string formatter to the memory_usage module. 
Because the format string allows for more customization, more variables are exposed to the user so that he can control how he exactly wants to display the memory usage string. Hence instead of using boolean configuration options to either display percentage or usage/total values, the user can display one or the other via the format string, or both if he desires so. Also the swap is not hidden via a boolean flag anymore: the user simply has to specify it via the string format. I kept the restriction to only display the SWAP usage though if it is present on the system. The default format string contains an optional SWAP variable so it should not prevent the memory to be displayed if the former is missing. 
Closes # …
=> refactor(memory_usage): Added formatter support for memory_usage module

docs/config/README.md, src/configs/cmd_duration.rs, src/modules/cmd_duration.rs, tests/testsuite/cmd_duration.rs
This PR deprecates `symbol` and `style` keys in the `cmd_duration` module to replace it with the `format` key instead.
=> refactor(cmd_duration): Use format strings

docs/config/README.md, src/configs/singularity.rs, src/modules/singularity.rs
This PR deprecates `symbol`, `style`, `suffix`, `prefix` and `label`  keys in the `singularity` module to replace it with the `format` key instead.
=> refactor(singularity): Use format strings

docs/config/README.md, src/configs/kubernetes.rs, src/modules/kubernetes.rs
This PR deprecates `symbol` and `style` keys in the `kubernetes` module to replace it with the `format` key instead.
~~It also adds a new key named `namespace_spaceholder` which is displayed if no namespace was found.
This is required as with the new format strings it would generate this, if no namespace was found:~~
```
on ☸ test_context ()
```
~~This is a limitation with the new format strings API.
If somebody has a better idea how to handle this, let me know!~~
Just found #1138. It should now only render the namespace if it is set.
=> refactor(kubernetes): Use format strings

docs/config/README.md, src/configs/docker_context.rs, src/modules/docker_context.rs
This PR deprecates `symbol` and `style` keys in the `docker_context` module to replace it with the `format` key instead.
It also now searches for the docker config file in two different location:
1. `$DOCKER_CONFIG/config.json`
2. `$HOME/.docker/config.json`
If `DOCKER_CONFIG` is not set it falls back to Option 2.
=> refactor(docker_context): Use format strings

docs/config/README.md, src/configs/php.rs, src/modules/php.rs
This PR deprecates `symbol` and `style` keys in the `php` module to replace it with the `format` key instead.
=> refactor(php): Use format strings

docs/config/README.md, src/configs/git_commit.rs, src/modules/git_commit.rs, tests/testsuite/git_commit.rs
This PR deprecates `prefix`, `suffix` and `style` keys in the `git_commit` module to replace it with the `format` key instead.
=> refactor(git_commit): Use format strings

docs/config/README.md, src/configs/git_state.rs, src/modules/git_state.rs, tests/testsuite/git_state.rs
This PR deprecates `progress_divider` and `style` keys in the `git_state` module to replace it with the `format` key instead.
It also enables the test that were ignored before.
=> refactor(git_state): Use format strings

docs/config/README.md, src/configs/conda.rs, src/modules/conda.rs, tests/testsuite/conda.rs
This PR deprecates `symbol` and `style` keys in the `conda` module to replace it with the `format` key instead.
It also changes the default symbol to the reference implementation.
=> refactor(conda): Use format strings

docs/config/README.md, src/configs/hg_branch.rs, src/modules/hg_branch.rs
This PR deprecates `symbol` and `style` keys in the `hg_branch` module to replace it with the `format` key instead.
=> refactor(hg_branch): Use format strings

docs/config/README.md, src/configs/crystal.rs, src/modules/crystal.rs
This PR deprecates `symbol` and `style` keys in the `crystal` module to replace it with the `format` key instead.
=> refactor(crystal): Use format strings

docs/config/README.md, src/configs/terraform.rs, src/modules/terraform.rs, tests/testsuite/terraform.rs
This PR deprecates `symbol`, `style` and `show_version` keys in the `terraform` module to replace it with the `format` key instead.
=> refactor(terraform): Use format strings

docs/config/README.md, src/configs/nix_shell.rs, src/modules/nix_shell.rs, tests/testsuite/nix_shell.rs
This PR deprecates `symbol`, `style` and `use_name` keys in the `nix_shell` module to replace it with the `format` key instead.
It also removes the exception for `lorri` as it was fixed [here](https://github.com/target/lorri/pull/164).
=> refactor(nix_shell): Use format strings 

docs/config/README.md, src/configs/zig.rs, src/modules/zig.rs
This PR deprecates `symbol` and `style` keys in the `zig` module to replace it with the `format` key instead. Heavily based on #1224.
Related to issue #1057.
=> refactor(zig): Use format strings

docs/config/README.md, src/config.rs, src/configs/custom.rs, src/modules/custom.rs
In custom modules, add the arguments `-Command -` to the shell arguments when using PowerShell.
Closes #1220.
=> fix(custom): improve handling of Powershell prompts

src/init/starship.bash, src/init/starship.zsh
This PR fixes whitespace and indentation issues inside `bash`/`zsh` init script. Additionally, consistent function definition style is enforced and scripts are examined using `shellcheck`.
Idea is to keep things tidy, consistent and bug-free by running `shellcheck`.
=> style(init): Tidy-up init scripts

docs/config/README.md, src/configs/aws.rs, src/modules/aws.rs, tests/testsuite/aws.rs
This PR deprecates `symbol`, `style` and `displayed_items` keys in the `aws` module to replace it with the `format` key instead.
=> refactor(aws): Use format strings

docs/config/README.md, src/configs/directory.rs, src/modules/directory.rs, tests/testsuite/directory.rs
Hello, this is my first real piece of rust code, so any tips are greatly appreciated! I left some review comments myself.
This adds an option to provide a list of pairs of strings to substitute in the directory string. If this option is used, fish-style PWD is disabled.
The reason for fish-style PWD being disabled is an implementation detail -- I perform the `replace` on the `dir_string`, since it is a string type rather than a path type. To make this work with fish-style PWD would need more code, and IMO I don't see the need to use both features at once. Would definitely appreciate more input here.
I'm currently using this at work to shorten paths that have a long common prefix, interesting middle, and some long development directories. It's a more tailored way of shortening paths while …
=> feat(directory): Add directory substitutions

docs/config/README.md, src/configs/purescript.rs, src/modules/purescript.rs
This PR deprecates `symbol`, `style` keys in the `purescript` module to replace it with the `format` key instead.
=> refactor(purescript): Use format strings

docs/config/README.md, src/configs/ocaml.rs, src/modules/ocaml.rs
This PR deprecates `style` and `symbol` keys in the `ocaml` module to replace it with the `format` key instead.
=> refactor(ocaml): Use format strings

install/install.sh
HOTFIX: curl installer will be broken until this is merged.
There was a space added to a tar command in #1305. While it seems innocuous, it causes tar to either try to extract the file `"v"` or the file `""` instead of reading from stdin like we want. This reverts that change by putting the `VERBOSE` invocation in the middle of the command string, hopefully making it more obvious if it breaks in the future.
Curiously, this did *not* break the script when executing it directly (`./install.sh`) but *did* break it when running it in a new shell (`bash install.sh`). I've determined that that has something to do with the environment, but haven't worked out anything deeper than that.
Closes #1313
=> fix: remove errant whitespace which broke tar command

src/modules/php.rs, src/utils.rs
PHP will output error messages when displaying the version if, for
example, there is something wrong with the local `php.ini` file. Have
updated the command used to get the PHP version to only use the default
PHP config.
Closes #1312
=> fix(php): Stop including error messages in the version

CONTRIBUTING.md, src/main.rs
As discussed in the issue https://github.com/starship/starship/issues/1277.  I've replaced the default RUST_LOG with STARSHIP_LOG to prevent interference for rust developers.
Closes #
=> feat: Switch to dedicated starship logging env var STARSHIP_LOG 

CONTRIBUTING.md
Have removed some redundant settings in the CONTRIBUTING.md since
starship should be the only application using the `STARSHIP_LOG` env
var.
This aims to keep the contributing guide easy to follow.
=> docs: Remove redundant settings in Contributing guide

docs/config/README.md
Fixes a small typo in the python advanced configuration section.
=> docs(python): Fix typo in advanced configuration

docs/faq/README.md
Add an FAQ entry describing common troubleshooting steps for when symbols go missing.
We've had a few people in the Discord and the AUR page have this issue, as well as a (semi-related) issue on [nushell](https://github.com/nushell/nushell/issues/1933) recently. Arguably #1012 could have been fixed by this as well.
=> docs: Add FAQ entry on missing symbols

docs/config/README.md
Removing `$` prefix from some shell snippets to be consistent with others.
There isn't open issue but it makes shell snippets easier to copy without selecting unwanted prefix.
=> style(docs): remove `$` prefix from shell snippets

src/modules/directory.rs, tests/testsuite/directory.rs
This PR fixes path contractions
1. when `full_path` contains symlinks (a logical path), and `top_level_path` is given as a physical path.
2. and when git repository's subdirectory is symlinked to outside of the repo tree.
`&repo.root` returns physical path, not the logical path.
`git rev-parse --show-toplevel` returns worktree [path](https://github.com/git/git/blob/v2.27.0/builtin/rev-parse.c#L803), which is [initialized](https://github.com/git/git/blob/v2.27.0/environment.c#L261) with [`strbuf_realpath`](https://github.com/git/git/blob/v2.27.0/abspath.c#L81).
So, it returns a physical path of a repository (there isn't a symlink in its ancestors). I think libgit2 does too so `&repo.root` does.
However, `PWD` and `std::env::current_dir` gives you a logical path (it might contain symlinks …
=> fix(directory): Fix path contractions for symlinked git repos

docs/config/README.md, src/configs/time.rs, src/modules/time.rs, tests/testsuite/time.rs
This PR deprecates `style` key in the `time` module to replace it with the `format` key instead.
The old `format` key has been renamed to `time_format` to continue to allow custom time formats while also not conflicting with the new standard `format` key.
=> refactor(time): Use format strings

Cargo.lock, Cargo.toml, src/bug_report.rs, src/config.rs, src/configure.rs, src/context.rs, src/modules/aws.rs, src/modules/directory.rs, src/modules/docker_context.rs, src/modules/kubernetes.rs, tests/testsuite/directory.rs
- Replaces the `dirs` dependency with the maintained fork `dirs-next`.
- Uses fully qualified calls in modules where the `home_dir` function is only used once (see suggestions in #1338).
Supercede #1338 due to issues with the CI testing.
As the `dirs` dependency will be unmaintained for the foreseeable future, switch to the maintained fork `dirs-next`. This change has been suggested in #1319.
Closes #1319.
=> refactor: Replace `dirs` with `dirs-next` dependency

docs/config/README.md, src/modules/dotnet.rs, tests/testsuite/dotnet.rs
Adds additional .net specific files to detect.
These are additional files that can be used to detect a .NET Core project.
Closes #1302
Tested with `cargo run` on mac and unit tests
=> feat(dotnet): adds additional files to detect .net projects

docs/config/README.md, src/modules/nodejs.rs
Extend nodejs module support by recognizing additional file patterns.
Closes #1304 Note that `.jsx` and `.tsx` are left out of this. ⚠️
=> feat(nodejs): support additional file patterns

docs/config/README.md, src/configs/character.rs, src/modules/character.rs, tests/testsuite/character.rs
This PR deprecates `style_failure`, `style_success` and `use_symbol_for_status` keys in the `character` module to replace it with the `format` key instead.
=> refactor(character): Use format strings

docs/config/README.md, src/configs/custom.rs, src/modules/custom.rs
This PR refactors `custom` module to use format string.
Related to #1057
=> refactor(custom): Use format string

docs/config/README.md, src/configs/nim.rs, src/modules/nim.rs
This PR refactors module `nim` to use format string.
Related #1057
=> refactor(nim): Use format string

docs/config/README.md, src/formatter/model.rs, src/formatter/string_formatter.rs
When mapping meta variable `$all` to `\[$a$b\]`, a conditional format string `($all)` will always render, no matter if both `$a` and `$b` are `None`.
This PR will make `($all)` work the same as `(\[$a$b\])`.
=> fix(format-string): Forward conditional wrapper to meta variables

docs/config/README.md
Cleans up some inconsistencies introduced by the format-strings refactoring like:
- The `Variable` column in the `Option` section not being renamed to `Option`
- Some tables not being aligned
- Others suggested by markdownlint
Consistency is important.
=> docs: Cleanup some inconsistencies

src/context.rs, tests/testsuite/git_branch.rs
Support `GIT_DIR` environment variable (see https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)
Closes #1108
=> feat(git): honor `GIT_DIR` environment variable

README.md
Update relative URL in readme to absolute to fix broken link in docs
Link to contribute page in guide is causing a 404 on sharship.rs
Tested by clicking updated link in readme and making sure it reaches desired destination
=> fix: broken contribute link on starship.rs

src/modules/custom.rs
Have switched the fallback shell used when the custom module can't use
the default to use `/usr/bin/env sh` rather than `/bin/env` since
`/usr/bin/env` is more commonly available.
Closes #1347
=> fix(custom): Fix fallback shell not working on macOS

docs/advanced-config/README.md
=> docs: show current directory in terminal window title

src/modules/git_status.rs, src/print.rs
Fixes the explain command by properly hiding the `line_break` module and returning none if the repo is clean in `git_status`.
It also now shows the `character` module and the `prefix` and `suffix`.
Fixes the issue found in https://github.com/starship/starship/pull/1374#pullrequestreview-441195953.
=> fix(explain): Fixes the `explain` command

src/modules/nodejs.rs, src/modules/ocaml.rs, src/utils.rs
- Should not display nodejs info for esy.sh OCaml project
- Should display sandboxed version of OCaml instead of global version if any (should be 4.08 not 4.10)
- display sandboxed version of OCaml when managed with esy.sh without global OCaml installation (should be 4.08 not empty)
Closes #1395
=> fix: manage sandboxed version of OCaml

src/context.rs, tests/testsuite/git_branch.rs
On a newly initialized git repo, there are no branches created until a
commit is made. Previously, starship handled this by hardcoding a default
value "master" for when branch `head` could not be read.
However, if a user wants to set a different default branch name, that
name won't appear in starship until a commit is made to the branch.
If git2 provides a way to read the default branch name, we can use that,
but at the moment it's not obvious how.
For the moment, we can directly read `.git/HEAD`, which contains the
name of the default branch head reference. This commit implements this
strategy.
Closes #1327
I've updated the `git_branch::...unborn_master` to `git_branch::...unborn_default_branch`, where the default branch name is set in `.git/HEAD`.
I've also done manual testing on Linux, …
=> feat: git branch: read from HEAD on newly initialized repo

src/configs/git_status.rs, src/configs/starship_root.rs
Rust counts the `\[` as escape chars and fails to compile which is why it was a raw string literal.
I confused `\[` with `\\[` which is why #1374's CI checks fail.
This PR is here to fix that.
Fixes the CI failure in #1374
=> fix(git_status): Fix a mistake made in a review suggestion

.github/workflows/workflow.yml
This removes the hard requirement for a particular version of python in
the CI, and just uses the default version. Since #1297 was merged we
have not depended on the version of python that is installed. 
This should stop us from having to update the version of python when the
github action updates the available versions.
=> ci(python): Use the default version of python in CI

.github/workflows/deploy.yml, .github/workflows/workflow.yml
Revert the Rust install calls from `ATiltedTree/setup-rust` back to `actions-rs/toolchain`.
This was done as we tried if my action would fix the random test failures but it didn't (as seen here #1456 and in this pr) so this reverts it.
`actions-rs/cargo` is only used in the lint step because otherwise we would get duplicate annotations.
Using a wildly known action was [preferred](https://github.com/starship/starship/pull/1450#discussion_r450992120) if my action didn't fix our failures.
=> ci: Revert back to actions-rs

install/install.sh
Fixed a typo: permission -> permissions, just as in the title. Nothing more.
The current installation script prints "Escalated **permission are** required", but it should be "Escalated **permissions are** required".
Ran `install/install.sh` and `cargo test`.
=> fix: Fixed a typo: permission -> permissions

.github/workflows/workflow.yml, src/modules/terraform.rs, src/utils.rs, tests/testsuite/terraform.rs
Moves terraform's tests which do not require env vars into unit tests allowing for version mocking and removing another install step from our CI.
Reduces our CI runtime even further and get a little bit closed to moving all test to unit test.
=> test(terraform): Move tests which do not require env vars

src/modules/nodejs.rs
A recent refactor of modules to use format strings accidentally got rid
of the `trim()` on the NodeJS version string. This just adds it back so
that the prompt doesn't include an unnecessary line break when
showing node version.
This is the change from 2 days ago where it seems the call to `trim()` was removed:
https://github.com/starship/starship/commit/ec76fafff08933f6f31fb99ea974bdb5ae97a0af#diff-c01cecd829b03f2f92c8c68c12409c18L37
Fixes #1465
This is my first time writing any Rust code so I pretty much just copied what was done in
similar modules. I wasn't sure how to add a test for this and if such a test is necessary it
should probably be added to most modules.
=> fix(nodejs): Remove accidental line break from version string

Cargo.lock, Cargo.toml, docs/config/README.md, src/configs/directory.rs, src/modules/directory.rs, src/modules/utils/directory_nix.rs, src/modules/utils/directory_win.rs, src/modules/utils/mod.rs, tests/testsuite/directory.rs
The directory module shows little 'lock' symbol when the current directory can't be written by the current user.
It was requested to Starship have the similar feature as zsh does -- showing a special symbol whenever the current directory can't be written by the current user.
The *nix implementation is straightforward: it uses a built-in sh feature to determine the matter. Windows implementation is complex involving Windows Security API to perform an `AccessCheck`.
Closes #1041
=> feat(directory): Show lock symbol if current directory is read only

src/modules/git_status.rs, tests/testsuite/git_status.rs
This option causes advanced files rename detection which causes inconsistency between `git status` and Starship reports.
Closes #1371
=> fix(git_status): Remove renames_index_to_workdir() option from git status

src/config.rs
When the user gives a hex color that is shorter than expected it caused an out of bounds error. This PR works around this ~by using checked array indexing~ by checking the length of the hex color string beforehand. 
Closes #1467
=> fix(config): don't panic when hex color is too short

src/modules/ocaml.rs, src/utils.rs
This fixes a regression in the ocaml module that caused the excess whitespace
to not be trimmed from the version.
Related to #1436 and
=> fix(ocaml): Stop new line being included in ocaml version

src/modules/crystal.rs, src/modules/erlang.rs, src/modules/php.rs, src/utils.rs
Ensure that output of mocked commands faithfully replicates output of actual commands including any trailing whitespace.
Closes #1484
=> test: fix mocked commands

src/configs/starship_root.rs
Borrow `PROMPT_ORDER` so the length no longer needs to be set.
Closes #1508
=> fix: fix compile with battery feature disabled

Cargo.lock
We have been having some CI builds fail because they can't find some
dependencies on the OSX. I'm not sure if this is something wrong with
the CI setup, something bad in the cache or something wrong with the
Cargo.lock file. To try to narrow down the possible issues I've manually
updated the Cargo.lock file by running `cargo update`. This should
ensure that the the lock file is in a good state and also force a cache
refresh in the CI.
This should help resolve the issues with the builds on OSX.
=> ci: Fix failing CI builds

docs/config/README.md, src/modules/package.rs
Parses a `Chart.yaml` file in the current directory and uses that as the current package version
Closes #1487
I added a unit test.
=> feat(package): Add support for Helm charts

docs/config/README.md, docs/presets/README.md, src/configs/dart.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/module.rs, src/modules/dart.rs, src/modules/mod.rs, src/utils.rs
Add a module for displaying the current Dart version. 
Extending runtime/programming language support.
Closes #609 
Prior art #611
=> feat(dart): add Dart module

src/modules/directory.rs, src/modules/utils/directory_win.rs
Do not try to analyze if the current process can write network location on Windows.
Unfortunately, there's no way on Windows to tell if we can write a network location because it's not being controlled by the OS itself. Thus now the lock symbol is never shown on network locations.
This PR introduces a new unsafe call.
Closes #1476
=> Do not try to analyze write permissions on network locations

docs/config/README.md, src/configs/conda.rs, src/modules/conda.rs, tests/testsuite/conda.rs
Adds an `ignore_base` option to the `conda` module so that the `base` environment is not shown when activated. Defaulted to `true`.
Closes #1536
=> feat(conda): add ignore_base option

.gitignore, docs/config/README.md, src/modules/package.rs
Adds ability to extract version information from a Maven pom.xml if present.
Starship recognises the existence of Maven projects elsewhere (e.g. Java module), but does not extract the version for the package module. This adds that feature.
Testing is via the inline Rust tests.
=> feat(package):  Add Maven pom.xml version support

src/modules/directory.rs, src/modules/utils/directory_nix.rs, src/modules/utils/directory_win.rs
I noticed the recent changes to the directory module in #1506 introduced some clippy errors on windows.
When reviewing I didn't run `cargo clippy` because I thought CI would catch clippy errors, but they weren't caught there because clippy isn't running on windows in CI.
I also replaced the use of `str` in the directory lock helpers with `Path` because the module work with `Path`/`OsStr` internally anyway. This avoids coversion to UTF-8 and back and allows it to work on directories that aren't valid unicode.
Closes #
=>  refactor(directory/lock): fix clippy, replace str with Path

README.md
Fix Explore the Starship docs link in guide
that redirected to homepage instead of docs.
Fixes: https://github.com/starship/starship/issues/1542
Super small fix to one link in starship guide.
Closes #1542
=> fix(docs): Fix Explore The Starship link in guide

src/init/starship.bash
If `PROMPT_COMMAND` includes `starship_precmd` as an intermediate command and `eval "$(starship init bash)` is executed again, then `PROMPT_COMMAND` enters an infinite loop of `starship_precmd` executions. This happens when other tools also hook into the shell using `PROMPT_COMMAND`. In particular this happens with [z](https://github.com/rupa/z/). For example,
```sh
❯ echo $PROMPT_COMMAND
_direnv_hook;starship_precmd
_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null;
```
Ideally the bash init would be idempotent so that the user can run `eval "$(starship init bash)"` without worrying about crashing the shell. It's possible I'm missing some context and the condition is intentionally checking for `starship_precmd` to be last in `PROMPT_COMMAND`.
=> fix(bash): init breaks if PROMPT_COMMAND includes starship_precmd as an intermediate command

docs/config/README.md, src/configs/gcloud.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/module.rs, src/modules/gcloud.rs, src/modules/mod.rs, tests/testsuite/gcloud.rs, tests/testsuite/main.rs
Add a module for displaying the current `gcloud` profile based on the followings:
- `~/.config/gcloud/active_config`
- `~/.config/gcloud/configurations/config_$(cat ~/.config/gcloud/active_config)`
- `CLOUDSDK_CONFIG` env var
This module is based on the AWS module.
Fixes #901
=> feat: Add gcloud module

Cargo.lock, Cargo.toml, src/print.rs
The table in `explain` wasn't aligned correctly. I think this happens because since v0.12.0 textwrap doesn't count ANSI escape sequences anymore. This also means `max_ansi_width` is no longer needed.
I couldn't get `{:width$}` to work the way I wanted so I replaced it with `" ".repeat(width)`.
~Also by using `UnicodeWidthStr::width` the width calculation itself should be a bit better because it can work on the level of graphemes instead of characters.~ Sadly both `UnicodeWidthStr::width` and `UnicodeWidthStr::width` appear to fail at this. I replaced them with a custom textwrapper.
Closes #1480 
Before:
```
starship on  master [!?] is 📦 v0.44.0 via 🦀 v1.44.1
❯ starship explain
Here's a breakdown of your prompt:
starship          -  The current working directory
 master          -  The …
```
=> fix(explain): align table correctly

.github/workflows/workflow.yml, Cargo.lock, Cargo.toml, src/configs/cmd_duration.rs, src/context.rs, src/modules/cmd_duration.rs
Often it is handy to get notified when the execution of a command finished. This feature is inspired by https://github.com/jml/undistract-me/ and includes `rust-notify` to generate a desktop notification. 
This PR is probably not yet done. For example, it should be turned off by default (I think). I want to elaborate if this is an extension worthy to be included into starship.
When long commands are done, it is often handy to get a desktop notification in order to return to the shell and continue with your work.
Fixes #1397
=> feat: Add Undistract Me Feature

src/modules/directory.rs
I replaced the seperate spin and lock with a single atomic swap and made the ordering stronger.
I kept the spinlock but `Mutex` might be cleaner.
I had a lot of test failures in #1573 in a row.
In the previous version this could have happend:
```
T1: while LOCK.load(Ordering::Relaxed) {}
T2: while LOCK.load(Ordering::Relaxed) {}
T1: LOCK.store(true, Ordering::Relaxed);
T2: LOCK.store(true, Ordering::Relaxed);
```
=> fix(test/dir): make lock thread-safe

src/modules/git_state.rs
This pr will fix a panic in the git_state module when doing a `git rebase`.  It is possibly an edge case and might possibly only happen when the rebase only has one command.
I've not done more testing regarding the cause but so far it has only triggered on rebase with one command thus I chose to return (1, 1) as progress. 
Execute `git rebase -i` and put the editor in background (ctrl-z) or dropping to shell will result in
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/modules/git_state.rs:146:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I've recompiled `starship`using `cargo build --release --no-default-features` and verified it will resolve the panic.
=> fix(git_state) panic on interactive git rebase

docs/config/README.md
The hostname module does not provide any "number" variable, its presence
in the documentation is likely due to some copy&paste from the jobs
module section, so let's drop it.
=> docs: Drop inexistent "number" variable from hostname section

install/install.sh
We have had a few issues where users haave run the install script and
have ended up with a non-functioning version of starship because their
system doesn't have a required lib that we link against. To avoid these
problems it seems the easiest solution is to default to using the
statically compiled musl binaries. If a user knows that they are doing
they can use the non-statically compiled binaries by supplying the `-p`
argument to the installer. Note this is what other rust based tools such
as ripgrep do.
Closes #1528 
Closes #1091
=> Switch to install the musl binaries by default

src/formatter/parser.rs, src/formatter/string_formatter.rs, src/module.rs, src/modules/line_break.rs, src/segment.rs
As the title says I removed the
- name property from `Segment` because it wasn't used anywhere
- misleading underscores in function names and variables because it normally means "this isn't used anywhere but we will in the future" which wasn't the case here
Improve the code readability
=> chore: Remove unused name from Segment and remove some of the misleading underscores

docs/config/README.md, src/configs/starship_root.rs, src/modules/line_break.rs
Re-implements the `add_newline` root configuration option, along with documentation and tests.
Closes #1549
=> fix: restore add_newline configuration

src/init/starship.ps1
Currently `Convert-Path` in the powershell prompt script works with `-Path` which interprets paths as wildcard patterns.
Not all valid paths are also valid wildcard patterns, possibly causing the prompt to error (eg `[]*`).
Replace it with `-LiteralPath` that makes `Convert-Path` use the path as-is.
Closes #
=> fix(pwsh): stop paths from being interpreted as patterns

docs/config/README.md, docs/faq/README.md, src/print.rs
* Document that commands are passed in as stdin (so don't use `/usr/bin/zsh -c` as shell as I did for 2 hours without figuring out whats going on...).
* Document that you need curly braces arround individual custom modules in when setting prompt_order
* Add link to #1252 
It took me about 2 hours to figure out how to do this and this is what I would have liked to see in the docs.
=> docs: Improvements in docs for custom modules

docs/config/README.md, src/configs/hostname.rs, src/configs/kubernetes.rs, src/configs/username.rs, src/module.rs, src/modules/hostname.rs, src/modules/mod.rs, src/modules/username.rs
Previously, all modules would have prefixes, which lead to the first
module having a dangling prefix. This change ensures that the first
few modules would instead have suffixes so that we don't start or
end with a prefix or suffix.
Closes #1607 
**Before**
**After**
=> fix: use suffixes for modules before directory

src/init/starship.ps1
Previously the prompt function used in PowerShell would overwrite the $LASTEXITCODE and $? automatic variables that were set by the previous command run the user in the shell. This results in surprising behavior for the user if they inspect those variables looking for the result of the command they last ran.
This fixes the bug reported here: https://github.com/starship/starship/issues/1051
And goes further to also propagate the $? automatic variable which is not mentioned in that bug.
=> fix(pwsh): update init script to propagate $LASTEXITCODE and $?

src/init/starship.zsh
Use a value based instead of an index based method to check if the `starship_pre*` functions are already installed. This works even if the base index of arrays is changed (`KSH_ARRAYS`).
`${list[(r)x}` returns `x` if `x` is in `list` else an empty string.
`${list[(re)x}` ensures string instead of pattern matches are used.
Closes #1610
The issue is explained in detail there.
=> fix(zsh): work when `setopt ksh_arrays` is set

.rustfmt.toml, CONTRIBUTING.md
Add an empty `rustfmt.toml` configuration file to the crate root, making rustfmt use the default configuration for all contributors.
The Starship project requires user contributions to be formatted, presumably in accordance with the standard Rust [style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md). However, many contributors will have their own Rustfmt configurations in either $HOME or parent folders, which need to be overridden by a crate-level `rustfmt.toml`.
=> style: make rustfmt use the default configuration

docs/config/README.md, src/configs/python.rs, src/modules/python.rs, src/utils.rs
Have restored the `pyenv_prefix` option to the python module. This is
added as a new variable that will only be shown if `pyenv` is being used
to determine the version of python that is being used.
Fixes a regression introduced in the format-strings release
=> fix: restore the `pyenv_prefix` option to python

docs/config/README.md, src/configs/git_state.rs, src/modules/git_state.rs
Fixes a discrepancy between v0.44.0 and master:
On 0.44.0 the brackets in the `git_status` module weren't styled but they were on master. 
Minimize breaking changes
=> fix(git-state): Fix discrepancy between v0.44.0 and master

src/modules/hg_branch.rs, src/modules/kubernetes.rs, src/modules/memory_usage.rs, src/modules/shlvl.rs, src/modules/time.rs
The default `disabled: true` is actually only available within the module (when the config struct is used and not the user toml) but not all (the hg_branch) modules checked it there again.
Document this in all places and add the check (+ test) to the hg_branch module.
=> fix: actually disable per default disabled modules

CONTRIBUTING.md, Cargo.lock, Cargo.toml, docs/config/README.md, src/config.rs, src/configs/custom.rs, src/configure.rs, src/init/starship.bash, src/init/starship.fish, src/init/starship.ion, src/init/starship.ps1, src/init/starship.zsh, src/lib.rs, src/logger.rs, src/main.rs, src/modules/aws.rs, src/modules/battery.rs, src/modules/cmd_duration.rs, src/modules/directory.rs, src/modules/dotnet.rs, src/modules/git_branch.rs, src/modules/git_status.rs, src/modules/hg_branch.rs, src/modules/hostname.rs, src/modules/mod.rs, src/utils.rs, starship_module_config_derive/src/lib.rs
Implements error messaging.
This take a bit of a different approach than #1416.
This creates a custom logger for the `log` crate which logs everything to a file (`/tmp/starship/session_$STARSHIP_SESSION_KEY.log`) and it logs everything above `Warn` to stderr but only if the log file does not contain the line that should be logged resulting in an error or warning to be only logged at the first starship invocation after opening the shell.
I choose the temp dir for storing logs as they can become quite large and most temp dir are cleared at reboot.
Closes #1075
Wrong format string:
Broken config:
=> feat: Error messaging

docs/config/README.md
Having a newline there means that an empty newline is printed everytime
the user runs a command or presses Enter, which for short commands
and/or small terminal windows can noticeably decrease the information
density.
=> docs: Remove newline from beginning of example format config.

src/init/starship.ps1
Applies the suggestions form #1696.
Powershell had errors evaluating our session key because the full path replaces `::STARSHIP::` which Powershell didn't like.
Closes #1696
=> fix(powershell): Fix session key syntax error

src/modules/utils/directory_nix.rs
`nix` also doesn't provide `getgroups` for iOS, leading to a compile error.
- [N/A] I have tested using **MacOS**
- [N/A] I have tested using **Linux**
- [N/A] I have tested using **Windows**
- [N/A] I have updated the documentation accordingly.
- [N/A] I have updated the tests accordingly.
=> Fix compiling for iOS targets

src/modules/git_state.rs
The tests for git-state can fail since they assume the default branch is always `master`.
On machines with the global option `init.defaultBranch` set will cause the tests to fail
Currently when trying to install `starship` from [AUR](https://aur.archlinux.org/packages/starship) it runs tests as apart of the package build process. On my machines I have set `init.defaultBranch` & found that the package fails to pass tests.
```
---- modules::git_state::tests::shows_bisecting stdout ----
Error: Kind(Other)
thread 'modules::git_state::tests::shows_bisecting' panicked at 'assertion failed: `(left == right)`
left: `1`,
right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /home/drb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustl …
```
=> test(git-state): tests failing when git init.defaultBranch set

docs/migrating-to-0.45.0/README.md
Some of the changes described for format were missing. In one case, a typo was made in the example.
The translations, I’ll need some help with those; I only speak & write English.
Going through the migration guide, I noticed some errors.
=> docs: Clarify missing info in 0.45.0 migration doc

src/bug_report.rs
The path for the ion config included `~/`. This is wrong because this value is appended to `dirs_next::home_dir()`.
Closes #
=> fix(bug-report): use correct path for ion config

src/configs/directory.rs, src/modules/directory.rs
In ce73f6347fc3a2b07d67ae72854f442573296fd9 the docs for the directory module were changed, but `read_only_symbol` and `read_only_symbol_style` were actually used in the module but remapped to `lock_symbol` and `lock_style` when applying to the format string.
This PR removes the remapping and changes the names in the config.
Related: #1706
=> fix(readonly): change module to match docs

src/modules/git_state.rs, src/modules/git_status.rs
Pass `--no-gpg-sign` to all instances of `git commit` in tests. This prevents the potential need for user interaction for those who have `commit.gpgSign` set to `true`, and in some cases, outright test failure.
Some users have `commit.gpgSign` set to `true` in their global git config, causing tests which run `git commit` to fail if the configured `user.signingKey` is not present, as is often the case with PGP smart cards or other methods of offline PGP key storage (for smart cards the commit may not outright fail, but bring up a dialog box asking for the user's PIN. However, this is also undesirable because tests shouldn't require user interaction).
I ran `cargo test --all-features -- -Z unstable-options --include-ignored` with a signing PGP subkey configured. This key is on a PGP smart …
=> fix: Pass `--no-gpg-sign` to `git commit` in tests

docs/config/README.md, src/configs/directory.rs, src/modules/directory.rs
Adds ellipsis in front of truncated paths: …/
Configurable through new config option: directory.truncation_symbol
~~On~~ Off by default (default is empty string)
Better visual indication of when the path has been truncated
Closes #1162 
Fixes #1626 
~~Updated existing tests~~ No longer needed since default is empty symbol.  Default behaviour is the same as before.
Ran `cargo test && cargo test --tests directory:: -- --ignored`
Added test for new config option: directory.truncation_symbol
=> feat(directory): fix #1162 add ellipsis to truncated paths

Cargo.lock, Cargo.toml, src/config.rs, src/configs/directory.rs, src/modules/directory.rs
Use `IndexMap` instead of `HashMap` to store directory substitutions in order to preserve the insertion order.
The extra crate dependency should be fine because it's already an indirect dependency.
Closes #1765
=> fix(directory): preserve substitution order

docs/config/README.md, src/configs/cmake.rs, src/configs/erlang.rs, src/modules/cmake.rs, src/modules/erlang.rs
The emoji used for the CMake and Erlang modules appear to have little font support, as is shown on the emojipedia entries for the respective emoji:
https://emojipedia.org/triangle-with-rounded-corners/
https://emojipedia.org/three-networked-computers/
This PR replaces the emoji used with NerdFont icons for "Triangle Outline" and "Erlang".
Closes #
=> fix: replace emoji for CMake and Erlang with NerdFonts

src/formatter/string_formatter.rs, src/modules/git_status.rs
There is a race condition that happens between https://github.com/starship/starship/blob/9044f9e14ca36a70d748810a0c4eda89d3f18391/src/modules/git_status.rs#L171
and 
https://github.com/starship/starship/blob/9044f9e14ca36a70d748810a0c4eda89d3f18391/src/modules/git_status.rs#L185
because
https://github.com/starship/starship/blob/9044f9e14ca36a70d748810a0c4eda89d3f18391/src/modules/git_status.rs#L184
takes some time to process. While line 184 is executing line 171 executes of the other maps and returns a `None`. To avoid this I moved the write lock to the earliest point possible. **This is not a long term solution** a race condition can still happen if the processor switches context to a different thread at the wrong point. The real solution would be to pre initialize the `RepoStatus` …
=> perf(git_status): Improved git_status module performance

src/modules/git_state.rs
Instead of only handling `None` when `rebase-merge/msgnum` is missing (#1552), always handle missing rebase progress with `(1, 1)`.
I think `"?"`or `None` might be more appropriate return values, but I've kept the old behaviour in this PR.
Closes #1754
=> fix(git_state): remove unwrap in `describe_rebase`

src/modules/aws.rs
When running the AWS module it will parse the AWS config found in
`~/.aws/config` to get the region. This means that tests that expect no
region to be set will fail if there exists a default profile with a
region set, which is probably true for most AWS users. To avoid this
have set the AWS tests that depend on the non-existance of a
`.aws/config` to be ignored.
Closes #1773
=> test(aws): Ignore tests that check .aws files

docs/README.md, docs/ja-JP/README.md
In present documents, it writes
> Add the following to the end of ~\Documents\PowerShell\Microsoft.PowerShell_profile.ps1 (or ~/.config/powershell/Microsoft.PowerShell_profile.ps1 on -Nix):
for installing on windows. But the location of this file depends on the version of the Windows, so I updated the document for telling users to check the correct path of ps1 file with `$PROFILE` command on PowerShell.
Closes #1753
=> docs: Update document for installing on windows

docs/config/README.md
docs(config/README.md): Remove removed options from Memory example (fix #1799)
Remove the following options (unsupported since ec76faf & v0.45.0):
[memory_usage]
show_percentage = true
show_swap = true
separator = "/"
See commit message above.
Fix #1799 
N/A
Change to documentation only.
=> docs(config/README.md): Remove removed options from Memory example (fix #1799)

src/init/starship.ps1
Instead of forcing the whole shell to use utf-8 only change the `[Console]::OutputEncoding` before `starship prompt` is run and restore the old value afterwards.
Closes #1801
=> fix(pwsh): preserve original console encondings

.github/workflows/workflow.yml
Now that the uom dependency has been updated and compiles on the nightly
version of rust we can enable the builds again in the build matrix.
This reverts the changes added in https://github.com/starship/starship/commit/a8264cdab9245695b6f818166a45db8d2ff940db that were caused by the https://github.com/iliekturtles/uom/issues/210 now that it has been resolved.
=> ci: Run against nightly version of rust

src/modules/kubernetes.rs
Have refactored the kubernetes module to better support stacked
kubeconfigs. Rather than trying to grab both the current-context and
namespace on a single pass we now do two passes. These changes should
fix the problems where the current-context is defined in one file but
the context and the namespace are defined in a different file.
Closes #814
=> fix(kubernetes): Parse stacked kubeconfigs

src/init/starship.zsh
The current zsh-wrapper overwrites `zle-keymap-select` if it exists already. These changes will ensure that we just append our behaviour to the existing function.
For zsh users who already have `zle-keymap-select` defined, we are currently overriding their configuration. This will fix that.
Closes #1804 
Verified the behaviour on zsh-5.8 (MacOS) and zsh-4.3 (EC2 running Amazon Linux/Redhat).
1. Add the following snippet in `zshrc` **BEFORE** sourcing starship.
```
echo -ne '\e[5 q';    # Line Cursor
function myfoo() {
echo -ne '\e[1 q';   # Block Cursor
}
zle -N zle-keymap-select myfoo;
```
1. On starting shell, verify that a line cursor is present.
1. Change keymap mode after starting shell. (eg: ^X^V will trigger vi-mode)
Success Criteria: The cursor will become a block.
<Not …
=> fix(zsh): Ensure existing keymap change functions are not overriden

docs/config/README.md, src/configs/lua.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/module.rs, src/modules/lua.rs, src/modules/mod.rs, src/utils.rs
I added an module for [The Programming Language Lua](https://www.lua.org/).
Closes #
=> feat: Add a Lua module

README.md, docs/README.md
The changes in this PR:
- Add the new powershell init docs to the main repo root `/README.md`
- Change the -Nix powershell profile paths to use the `/` path seperator isntead of `\`
- Remove errant `# ~\Documents\PowerShell\Profile.ps1` (This is the path I first used by mistake in my PR to add powershell support)
Closes #
=> docs(pwsh/init): various fixes for init doc

docs/config/README.md
Added in #1019
Adds documentation for new config options.
This is new and not yet enabled by default in binaries available e.g. via homebrew (see #1830 ). I'm not sure what the best approach is to 
1. document the minimum version required for options
2. whether to document options that many users are unlikely to have available yet (unless they build from source with `--features rust-notify`)
Fixes: #1597
n/a
Documented based on source changed in #1019 .
- n/a I have updated the tests accordingly.
=> docs(cmd_duration): Document cmd_duration notifications

src/init/starship.bash, src/init/starship.zsh
We currently invoke `starship session` in a sub-shell to generate the session-key, which is non-performant. By using $RANDOM instead, we can avoid this and generate the session-key quicker. This commit provides this optimization for ZSH (tested on 5.8 and 4.3) and bash-3.2.
Improves the performance of shell startup.
```
~ ❯ benchmark_zsh
Benchmark #1: zsh -i -c exit;
Time (mean ± σ):      69.0 ms ±   4.6 ms    [User: 33.7 ms, System: 27.2 ms]
Range (min … max):    65.1 ms …  88.7 ms    50 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
~ ❯ benchmark_zsh
Benchmark #1: zsh -i -c exit;
Time (mean ± σ):      60.2 ms ±   2.3 ms    [User: …
```
=> perf(init): Use random for session-key instead of invoking starship session

src/init/starship.ps1
Use powershell builtins instead of `starship session` because it's faster. Based on the work in #1576.
#1755
Benchmark:
```
~
❯ Measure-Command {-join ((48..57) + (65..90) + (97..122) | Get-Random -Count 16 | ForEach-Object { [char]$_ })}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 7
Ticks             : 70925
TotalDays         : 8.20891203703704E-08
TotalHours        : 1.97013888888889E-06
TotalMinutes      : 0.000118208333333333
TotalSeconds      : 0.0070925
TotalMilliseconds : 7.0925
~
❯ Measure-Command {starship session}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 19
Ticks             : 198315
TotalDays         : 2.2953125E-07
TotalHours        : 5.50875E-06 …
```
=> perf(init/pwsh): use get-random for session-key instead of invoking starship session

src/main.rs
Consoles on WIndows don't always have support for ANSI sequences enabled.
Call `ansi_term::enable_ansi_support` to configure the current console to enable support for ANSI sequences.
Potential problems:
`enable_ansi_support` only supports Windows 10, not sure what happens on Windows <10 with this change.
Maybe ANSI support should be disabled again after rendering the prompt?
Might close #1533
I tried testing it in the windows console in legacy mode, but it didn't work with that.
My normal shell already has ANSI support enabled so I wasn't able to test it with a configuration that didn't work previously, but it didn't break anything.
=> fix(windows): configure console to enable ANSI support

src/init/starship.ps1
Older powershell versions don't have `Get-Error`. Handle missing `Get-Error` gracefully.
Before on Powershell 5:
```
~
❯ Write-Error '' -ErrorAction 'Ignore'
PS>
```
After:
```
~
❯ Write-Error '' -ErrorAction 'Ignore'
~
❯ 
```
=> fix(pwsh): fix crash on error in shell with old pwsh

docs/config/README.md, src/modules/terraform.rs
Added `hcl` extension to terraform module to support [different terraform syntax](https://www.terraform.io/docs/configuration/syntax.html) 
When use tools like [Terragrunt](https://terragrunt.gruntwork.io/grunt) Starship doesn't recognize that this repo uses terraform because the terraform files ends with `hcl` extension
Closes #
=> feat(terraform): Add hcl extension support to Terraform module 

docs/config/README.md
Reorders the sections in `docs/config/README.md` so that they are in alpahbetical order (except "Prompt", which stays at the first place because it documents the default section in the TOML file)/
=> docs: alphabetic sorting of configuration subsections

docs/presets/README.md
This changes the suggested nerd font icon for rust from a regular cog to the proper rust icon from devicons (see https://www.nerdfonts.com/cheat-sheet and search for "rust").
=> docs: update rust icon in preset configuration

src/modules/swift.rs
I fixed parsing swift version. Originally, the output of `swift --version` was separated space by spaces and then displayed the third value. It now displays the string after the `version`
Using [tensorflow/swift](https://github.com/tensorflow/swift) toolchains, Starship displays unexpected swift version like `(LLVM`.
`~/GitHub/starship/target/debug/starship` is my version.
=> fix(swift module): parsing swift version

docs/config/README.md, src/configs/git_branch.rs, src/modules/git_branch.rs
This adds a new boolean, `only_attached`, to the configuration for
the `git_branch` module. This mirrors the `only_detached` config
value for the `git_commit` module: setting the value to true causes
the module to suppress its output when the user is not on a branch.
For the sake of backwards compatibility, this new config value
defaults to false.
This allows users to have either a branch name or a commit hash in
their prompt, as opposed to having either a branch name or the
overly-wordy "HEAD (sha1)", using a config such as:
```toml
[git_branch]
symbol = ""
only_attached = true
[git_commit]
format = "(at [$hash]($style) )"
only_detached = true
```
Closes #1905
Adds two new tests to the `git_branch` module, which confirm that
the output of the module is unchanged when the config value is …
=> feat(git_branch): add 'only_attached' config bool

docs/config/README.md, src/configs/git_branch.rs, src/context.rs, src/modules/git_branch.rs
Show the remote tracking branch in case the current branch is named differently than the remote tracking one.
The remote branch name is appended to the branch name, separated by a `:`, as stated in the issue linked below.
Closes #1757
Before
After
=> feat(git_branch): add remote branch name if different than local branch

Cargo.lock, Cargo.toml, src/modules/memory_usage.rs
Sysinfo is slow to get memory usage information both on windows (#1564) and linux (#1879).
This PR replaces it with the `sys-info` library.
Right now `sys-info` calculates swap incorrectly on windows, but I already made a PR for that (FillZpp/sys-info-rs#73)
Closes #1879
Closes #1573
Closes #1564
Benchmark (windows):
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `starship module memory_usage` | 336.9 ± 7.3 | 325.6 | 346.5 | 17.87 ± 5.43 |
| `target/release/starship module memory_usage` | 18.9 ± 5.7 | 16.9 | 78.6 | 1.00 |
Benchmark (linux):
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `starship module memory_usage` | 5.9 ± 1.4 | 4.8 | 31.2 | 1.76 ± 0.58 |
| `target/release/starship module memory_usage` | 3.4 ± …
=> perf(memory_usage): replace sysinfo with sys-info

src/modules/git_state.rs
The first commit makes rebase status more robust by removing some unwraps in the git_state module.
Those unwraps were triggered by rebasing within git repositories using .git files (not directories) that link to the actual gitdir.
The second commit adds support for gitdir indirection.
starfish crashed and garbled the terminal when I was rebasing within git submodules.
Fixes #1859
Tested before/after on local git checkouts.
=> fix(git_state): Handle gitdir indirection when rebasing

docs/config/README.md, src/modules/java.rs
1. Changes the Java module such that it will be shown if any of the configuration files for the three most popular Clojure build tools are present:
* `deps.edn` ([Clojure command-line tools](https://www.clojure.org/guides/deps_and_cli))
* `project.clj` ([Leiningen](https://leiningen.org/))
* `build.boot`([Boot](https://github.com/boot-clj/boot))
2. Changes the Java module such that it will be shown if Clojure source files (`.clj` or `.cljc`) are present. 
Note Java module will not be shown if ClojureScript (`.cljs`) files are present, even though the ClojureScript compiler is a Java program. I'm ambivalent about whether this is the right behavior.
Similarly, the Java module will not be shown if [Extensible Data Notation](https://github.com/edn-format/edn) (`.edn`) files are present. (EDN …
=> feat(java): Show Java module for Clojure projects

Cargo.lock, Cargo.toml, src/modules/rust.rs
This changes the extraction of the currently used Rust version from the `rust-toolchain` file to support the [new format](https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html#new-format-for-rust-toolchain) as well. It reads the first line as before but checks for `[toolchain]` in the resulting string to detect the new TOML format. In that case it parses the whole file as TOML file and extracts the version from the `toolchain.channel` value. In case the first line is empty the TOML parsing is triggered as well, as a TOML file can contain potential empty lines before the `[toolchain]` section.
I added test cases for both versions as well.
Old format (still valid):
```txt
1.34.0
```
New format:
```toml
[toolchain]
channel = "1.34.0"
```
A new version of rustup was released yesterday, …
=> feat(rust): Support new rust-toolchain format

docs/config/README.md, src/configs/python.rs, src/modules/python.rs, src/utils.rs
Have updated the python module to try multiple python binaries when
determining the version. With the new logic if starship doesn't find
`python` on the `PATH`, which is the default for some Linux Distros, it
will fallback to `python3` and then `python2`.
Closes #1670
=> feat(python): Smarter python binary usage

src/init/starship.bash
Without this patch, I always get the indicator for background jobs.
Also it does not rely on `wc` to count.
Closes #1776
=> fix(bash): Fix number of background jobs

docs/advanced-config/README.md, src/config.rs
I changed the parsing of styles a bit so that bg:none will not override other fields.
Background does not have to have a colour. You can do that with `red` or `fg:red` for example. It is confusing if `bg:none` will override foreground just like a standalone `none`.
This has been tested with some new test cases. I also tested it in a Fish shell in a suckless st terminal on Artix Linux 5.9.6.
=> fix: bg:none overwrites foreground colour

src/init/starship.bash
I've added a comment describing the new `NUM_JOBS` variable: why it has to be computed where it is and why it is computed using shell code.
When the PR was originally pushed, I didn't understand what the heck was going on, but I tested it and it fixed all the bugs, so I approved it. Shortly afterwards, a lightbulb went off and I was too embarrassed to take back my approval to ask for a comment. So here are the comments.
=> style: Add comments for bash preexec fix

docs/config/README.md, src/configs/starship_root.rs
cmd_duration moved after custom by default.
Closes #1671 
I launched the current tests with success and build to see the result.
No tests seems to fail so I do not know if a test is needed here.
=> feat: Move cmd_duration after custom module

docs/config/README.md, src/modules/username.rs
In addition to `SSH_CONNECTION`, also try other common environment variables set in an ssh connection: `SSH_CLIENT`, `SSH_TTY`.
Not all servers set `SSH_CONNECTION` in an ssh connection, therefore testing for the existence of `SSH_CONNECTION` is not reliable enough. In fact, testing for `SSH_CLIENT` and `SSH_TTY` is still not good enough, but should be better. Other means (e.g. [link](https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh)) are beyond my capability.
=> feat(username): Try harder to guess if inside ssh

docs/presets/README.md
This PR adds a Nerd Font padlock icon for the property `read_only` for the `[directory]` module.
It helps those who like me can't figure how to get the emoji working on their setup. This icon was missing in the Nerd Font preset
just a cute padlock
=> docs(preset): add a Nerd Font icon for "read_only" directories

src/modules/git_commit.rs
If option to show tag is enabled, it now shows last created tag on current commit.
Fix / improve behavior of `git_commit` module. It makes sense to show latest created tag pointing to current commit instead of oldest one.
=> fix(git_commit): show last created tag on current commit

docs/config/README.md, src/context.rs, src/modules/git_branch.rs
Git Branch module now provides two variables for remote repository:
- remote_name: name of the remote (as set by `git remote add` command)
- remote branch: name of the tracked branch on the remote
Closes #1971
=> feat(git_branch): show remote name

docs/config/README.md
This changes the documentation's default value for the dotnet module's `format` to match what it is in the code.
I was customising my prompt and noticed that copying the default from the documentation did not replicate the default behaviour.
I have not attempted to compile the Starship application itself, but did run the development website to verify it picked up the changes using:
* Windows 10 1909
* NodeJS 12.18.4
* NPM 6.14.6
* Microsoft Edge 87.0.664.55
I have read the contributing document and believe I've followed everything relevant but let me know if not.
=> docs: Correct dotnet module default format to match reality

src/config.rs
Until now all log messages related to failure to read config file contents as a string were not visible by default. The case of a missing config file is innocuous but I think other errors like invalid unicode are worth showing to the user.
This PR increases the log level from `debug` to `error` if the source of the error is not `ErrorKind::NotFound`.
Closes #
=> fix(config): log as error if failure to read config wasn't caused by NotFound

docs/config/README.md, src/configs/shlvl.rs, src/modules/shlvl.rs
Adds an option to the `shlvl` module which causes the `symbol` string to be repeated by the current SHLVL. This enables a nice a visual indicator for SHLVL that in my opinion is more intuitive than just displaying a number.
Closes #1878
A different approach to adding this, instead of repeating the existing `symbol` string, would be to make the `repeat` option itself a string which is repeated, and you have to include that in your format for it to show up. If messing with `symbol` is something that's generally discouraged in Starship then this would be a good alternative.
=> feat(shlvl): Add `repeat` option

src/init/starship.bash, src/init/starship.zsh
I was surprised to see the STATUS and PREEXEC_READY variables being set in my shell. I think
it's better to have them in the STARSHIP_ "namespace". (Actually, STATUS
got the new name STARSHIP_CMD_STATUS.)
For cleanliness :-) And it's unfortunate if users try to use the generic name `STATUS` for themself, not knowing starship will overwrite the variable. 
* I ran `cargo test`:
- on master: `test result: FAILED. 440 passed; 52 failed; 28 ignored; 0 measured; 0 filtered out`
- on this PR: `test result: FAILED. 440 passed; 52 failed; 28 ignored; 0 measured; 0 filtered out`
(So no change.)
* I installed starship from this PR onto my system (with bash).
=> feat: prefix STATUS and PREEXEC_READY shell vars with STARSHIP_

docs/config/README.md, src/modules/package.rs
Adds ability to extract version information from a Meson meson.build if present.
Closes #
=> feat(package): Meson package support

CONTRIBUTING.md, src/init/starship.bash
Add a note to CONTRIBUTING.md which specifies that Crowdin-generated files should not be changed in PRs.
Changing Crowdin-translated pages seems to be common point of confusion for PRs (especially those that edit docs in a way that seems like translation should be trivial, e.g. whitespace change or emoji changes). @twpol noted on #1983 that they looked for a note in CONTRIBUTING.md about that and couldn't find one.
This is a bit of a draft, so I'm very open to changing the wording on this.
Documentation change.
=> docs: Add note about Crowdin-managed files to CONTRIBUTING.md

Cargo.lock, Cargo.toml, src/utils.rs
Have added support to the `utils::exec_cmd` to allow it to execute
commands that are not `.exe` on Windows. Have also added a timer to
measure how long a command took to execute.
Closes #983
Closes #2018
=> feat(utils): Support non-exe commands on Windows

src/modules/username.rs
This switches Windows to use the env var `USERNAME` rather than `USER`
for getting the username of the current user. I have also done some minor
refactoring to simplify some of the code and make the checks to see if
the user is root or another user a bit more robust.
Closes #1554
Closes #1579
Closes #1350
Closes #1157
**Note** - I have not tested this on Windows the changes were made after checking the docs and looking at the related issues.
=> fix(user): Fix username detection on Windows

docs/config/README.md, src/configs/kotlin.rs, src/configs/mod.rs, src/configs/starship_root.rs, src/module.rs, src/modules/kotlin.rs, src/modules/mod.rs, src/utils.rs
Add a module to show the currently installed Kotlin version if a
.kt/.kts file is found in the current folder
I've been using Starship a lot recently, and I've noticed that kotlin support was missing. 
That's how the prompt looks like on my local environment:
=> feat(kotlin): Add the Kotlin module

docs/config/README.md, docs/presets/README.md, src/configs/battery.rs, src/modules/battery.rs
Because there have been a number of bug reports, mainly from linux users, the log level of the message about the failure to get battery information is reduced for those users.
The default icons in the module are replaced with their nerd font counterparts, to make it more obvious battery information is being displayed by the module. I also added icons for the unknown and dead states to ensure a battery related icon is always visible. Because these have default values now I also moved their docs into the main section of the battery module.
fixes #1940
fixes #1932
fixes #1803
fixes #2035
Old: full / charging / discharging / unknown (or dead)
New: full / charging / discharging / unknown / dead
=> feat(battery): make module behaviour more obvious

docs/config/README.md, src/configs/status.rs, src/modules/status.rs
User is able to choose if their want to display the meaning of
known status code in place of number.
Inspired by  go-powerline
https://github.com/justjanne/powerline-go/blob/master/segment-exitcode.go#L9
Having a number doesn't give a lot of information, status number of above 128 give the corresponding signal number of why a program exited 
Closes #1821
There is one unit tests, I successfully use it on my prompt on linux
=> feat(status): Convert known status code to their meaning

.github/workflows/deploy.yml
This fixes the failing Linux 64 bit builds that are linking to GNU libc
that are failing because cross doesn't compile openssl-sys. The fix is
simply to enable the vendored-tls feature so that we get the rust
vendored SSL rather than the system SSL. Have also done a little bit of
refactoring to the deploy script. Now rather than have a matrix of
targets have just included each target individually (this may be
something we want to revisit in the future as the number of platforms
increases). I have also removed the installation of the musl tools since
this is no longer needed when using cross for compilation.
Closes #
=> ci(deploy): Fix failing Linux GNU builds

src/init/starship.fish
Same as #1755 but for fish users
Improves the performance of shell startup
With `starship session`:
```
❯ hyperfine -r500 "fish -i -c exit"
Benchmark #1: fish -i -c exit
Time (mean ± σ):      13.3 ms ±   3.9 ms    [User: 9.8 ms, System: 3.8 ms]
Range (min … max):     5.5 ms …  20.4 ms    500 runs
```
With `random`:
```
❯ hyperfine -r500 "fish -i -c exit"
Benchmark #1: fish -i -c exit
Time (mean ± σ):      10.2 ms ±   2.9 ms    [User: 7.7 ms, System: 2.7 ms]
Range (min … max):     4.1 ms …  15.6 ms    500 runs
Warning: Command took less than 5 ms to complete. Results might be inaccurate.
```
=> perf(init): Use random for session-key in fish

src/init/starship.bash
Change detection and implementation for bash-preexec: now checks for a preexec variable in case bash-preexec is installed at a system level (and so necessarily sourced before anything the user does).
Fixes an issue found in discussion on #2039
=> fix: bash-preexec detection and implementation

src/init/starship.ps1
To prevent duplicate venv entries in the prompt, disable the builtin venv prompt. The `python` module can serve as the replacement.
Closes #2087
Context #551
=> fix(pwsh): disable builtin venv prompt

src/configure.rs, src/main.rs
Closes #894
Signed-off-by: Dentrax <furkan.turkal@hotmail.com>
See the given issue in order to get more description about the `toggle` feature.
As requested at #894 and #1873, this PR adds brand new `toggle` command.
[![asciicast](https://asciinema.org/a/374476.svg)](https://asciinema.org/a/374476)
* Given module name and flag key exist without arg:
```sh
$ dasel select -f ~/.config/starship.toml -p toml -m '.kubernetes.disabled' # returns 'true'
$ cargo run toggle kubernetes
$ dasel select -f ~/.config/starship.toml -p toml -m '.kubernetes.disabled' # returns 'false'
```
* Given module name and flag key exist with arg:
```sh
$ dasel select -f ~/.config/starship.toml -p toml -m '.kubernetes.disabled' # returns 'true'
$ cargo run toggle kubernetes disabled
$ dasel select -f …
```
=> feat(command): add 'toggle' command

src/configs/nix_shell.rs
We have had two attempts now to "fix" the two spaces in the nixshell module's default config, which are needed to provide a workaround for rendering of multiwidth emojis. Adds a comment to the code there describing why the spaces are present so that any would-be contributors know that it is not an accident.
=> docs: Comment about spaces in nix-shell config

install/install.sh
This fixes the install script by detecting `cygwin_nt*` as Windows.
Closes #985
Closes #2103
=> fix(install): Detect cygwin_nt as Windows

docs/config/README.md, src/modules/docker_context.rs
If `only_with_files = true` is set for the docker_context module, then this prompt is only shown in case a `Dockerfile` or `docker-compose.yml` file is found.
This PR also enables it for `docker-compose.yaml` (notice `yml` vs `yaml`).
Fixes the prompt for a valid docker-compose yaml file.
1. Created a docker-compose.yaml file
2. Ran `~/path/to/dev/build/target/starship prompt docker_context`
=> fix(docker_context): enable if either yml or yaml is found

.github/workflows/deploy.yml
I was checking which cross builds build in ci and I noticed the `use-cross` condition in the deploy ci script doesn't ever evaluate to `true` and neither does `${{ contains(matrix.target, 'linux') }}`.
I replaced the condition with a check against `matrix.os`.
Context: #2054
=> ci: fix use-cross condition

docs/config/README.md, src/configs/crystal.rs, src/modules/crystal.rs
This updates the module to lazily execute the `crystal --version`
command only when the `version` variable is used in the format string.
=> perf(crystal): Lazily evaluate version command

install/install.sh
Improve detection of supported platforms. Previously there was only a check to see if the install was on `i386` (this still isn't supported but `i686` now is), instead check against a list of supported install targets.
In addition:
- Detect fake `x64` as `i686` instead of `i386`
- Replace `\n` in `info` and `error` with `printf "\n"`
Closes #
=> fix(install): improve supported target detection

src/logger.rs, src/test/mod.rs
This PR enables logging during testing with `cargo test`. I put the log initialisation into `ModuleRender` because most tests should hit that. The log is shown on test failure. This might help investigate the cause behind #886 and help investigate the cause of test failures in general.
Closes #
=> test: enable logging in tests

docs/config/README.md, src/configs/cmake.rs, src/modules/cmake.rs
This fixes the additional space when the `version` variable can't be
populated.
Related to #2111
=> fix(cmake): Fix spacing with missing variable

docs/config/README.md, src/configs/swift.rs, src/modules/swift.rs
This updates the module to lazily execute the swift --version
command only when the version variable is used in the format string.
=> perf: evaluate swift version lazily

.github/workflows/workflow.yml
On macOS in CI Install `mercurial` with `brew` instead of `pip3`, because installing with `pip3` was brittle lately. `brew` is also a bit faster to install `mercurial`
Closes #
=> ci(macos): install mercurial with brew

src/bug_report.rs, src/context.rs, src/modules/aws.rs, src/modules/directory.rs, src/modules/docker_context.rs, src/modules/gcloud.rs, src/modules/kubernetes.rs, src/modules/openstack.rs
Add a method to `Context` to get the home directory that first attempts to read `$HOME` with mocked environment variables  from `self.get_env` during testing.
Related to #886 might fix to some extent
https://github.com/starship/starship/issues/886#issuecomment-761162673
Beyond what's described in that comment `$HOME` was also being set in `test_get_config_path`.
=> test: avoid setting $HOME

.cargo/audit.toml
This will make the automated checks pass again. RUSTSEC-2020-0100 doesn't affect starship because it doesn't use the vulnerable API. I already opened a PR for the security issue upstream.
Closes #2175
=> ci: ignore RUSTSEC-2020-0100

docs/config/README.md, src/configs/elixir.rs, src/modules/elixir.rs
This updates the module to lazily execute the `elixir --version` command only when the `$version` or `$otp_version` variables are used in the format string.
Because the output of the command is used to provide both `$version` and `$otp_version` I wrapped the call to `get_elixir_version` with `once_cell::sync::Lazy`.
I also updated the format string to better accommodate a missing `elixir` command.
=> perf(elixir): evaluate version lazily

docs/config/README.md, src/configs/custom.rs, src/modules/custom.rs
This updates the module to lazily execute the user command only when the `$output` variable is used in the format string.
I also updated the format string to better accommodate a missing `$output`.
=> perf(custom): evaluate command lazily

docs/config/README.md, src/configs/nodejs.rs, src/modules/nodejs.rs
Update Format string. Does not do lazy loading since the version is also needed for determining the style, so version has to be evaluated at least once.
=> perf(nodejs): evaluate nodejs format string lazily

Cargo.lock, Cargo.toml, src/utils.rs
This adds a timeout to any command executed using the `utils::exec_cmd`.
The initial time limit is hard coded to 500ms but if required we can
make this configurable. Have also switched the tests to be a bit more
granular on which systems they are ignored.
This should fix some issues with slow commands. 
Related to #312
=> perf(utils): Add timeout to `utils::exec_cmd`

docs/config/README.md, src/configs/kotlin.rs, src/modules/kotlin.rs
Evaluate version string for kotlin lazily and update format string
Closes #2111
=> perf(kotlin): Lazy eval kotlin

.github/workflows/deploy.yml, install/install.sh
Add release build targets for:
- `aarch64-unknown-linux-musl` (Pi 3/4)
- `arm-unknown-linux-musleabihf` (I think that still covers the first Pi?)
- `aarch64-apple-darwin` (M1)
- `i686-pc-windows-msvc`
I didn't add `armv7-unknown-linux-musleabihf` because the performance difference to `arm-unknown-linux-musleabihf` was negligible in a quick test on my Pi 3. The ARM targets without `hf` (FPU) didn't build.
FreeBSD didn't build and windows aarch64 is blocked on the next `sys-info` release.
I tested all the binaries and they seem to work fine.
Closes #315
Closes #1736
Closes #1901
Closes #1923
Closes #1074
Partial fix for #1175
=> build: add builds for various targets

docs/config/README.md, src/configs/php.rs, src/modules/php.rs
Evaluate php version command lazily and update format string
=> perf(php): Lazy eval php

docs/config/README.md, src/configs/perl.rs, src/modules/perl.rs
Evaluate perl version command lazily and update format string
=> perf(perl): Lazy eval perl

docs/config/README.md, src/configs/ocaml.rs, src/modules/ocaml.rs
Evaluate ocaml version command lazily and update format string
=> perf(ocaml): lazy eval OCaml

src/modules/git_status.rs
I simplified the code in the git status module by moving everything from `RwLock<_>` to `OnceCell<_>`. I think this should also get rid of any remaining race conditions that remained after #1777.
Performance is about the same:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `starship module git_status` | 10.6 ± 1.6 | 9.4 | 22.9 | 1.04 ± 0.17 |
| `./target/release/starship module git_status` | 10.2 ± 0.6 | 9.3 | 16.9 | 1.00 |
Closes #
=> refactor(git_status): simplify git status with once-cell

docs/config/README.md, src/configs/directory.rs, src/modules/directory.rs
As another prompt libraries, could be good if we can modify and/or add a symbol when the current directoy is home (~). I added the option to enable/disable the symbol (`show_home_symbol`) and also an option to customize it (`home_symbol`), 🏠   by default 
Fixes #1174
=> feat(directory): Add home directory symbol

.github/workflows/deploy.yml, install/install.sh
This PR adds `aarch64-pc-windows-msvc` to the release matrix and lists it as a supported target in `install.sh`.
Now that sys-info has released a new version this finally builds fine. I tested a build and it worked in a VM.
Closes #1175
=> build: add aarch64 windows build

install/install.sh
`install.sh` checks if a system misreports itself as a 64 bit system, but I believe the check was using the wrong architecture name (`x64`). I replaced with with `x86_64`.
Closes #
=> fix(install): use correct arch name in 32-bit test

docs/config/README.md, src/configs/mod.rs, src/configs/starship_root.rs, src/configs/vagrant.rs, src/module.rs, src/modules/mod.rs, src/modules/vagrant.rs, src/utils.rs
Signed-off-by: Dentrax <furkan.turkal@hotmail.com>
This PR adds support for [Vagrant](https://www.vagrantup.com/).
Closes #1792 _(Thanks @developer-guy for the idea!)_
I ran tests but get an error:
```sh
error[E0658]: use of unstable library feature 'str_strip': newly added
--> src/print.rs:298:41
|
298 |     } else if let Some(module) = module.strip_prefix("custom.") {
|                                         ^^^^^^^^^^^^
|
= note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information
```
... but, _vagrant.rs_ unit tests are passing. I'd appreciate if someone who able to build successfully and test it. I couldn't understand exactly what `use of unstable library feature 'str_strip': newly added` error means actually. :)
=> feat(vagrant): Add support for Vagrant

.github/workflows/deploy.yml, Cross.toml, install/install.sh
It looks like `cross` doesn't have the FreeBSD docker image whitelisted, which is why builds for FreeBSD in CI where failing and not using `cross`. This PR adds a `Cross.toml` file that points to the official `cross` FreeBSD image, adds the `x86_64-unknown-freebsd` target to `install.sh` and `deploy.yml` and adds support for FreeBSD in `detect_platform` and `detect-arch` in `install.sh`
Closes #828
=> build: add x86_64 freebsd build

src/init/starship.bash
In #1897 we replaced a `wc -l` with a bash-native job counter, but subsequently discovered that bash on MacOS folds `<<<` output into a single line, preventing line counting.
A for loop works around that problem, is still bash-native, and works the same on MacOS and Linux.
While we're at it, also removed the need for command substitution and an `echo` by doing the work directly on `NUM_JOBS`.
Fixes #2241.
=> fix: count jobs with for loop to fix MacOS count issue

src/modules/username.rs, src/utils.rs
Release 0.49.0 broke ANSI escape sequence processing for some Windows Terminal users by making some subtle changes how commands are now executed.
Closes #2254
Closes #2246
Closes #2252
=> fix(windows): fix windows terminal ANSI escape sequences

docs/config/README.md
When using the `status` module, the [example configuration](https://starship.rs/config/#example-45) references using variables with the `$status_` prefix. This does not work. This PR simply updates the documentation to reference a valid configuration example.
Closes #
With the config as currently described in the documentation:
Removing the `$status_` prefix:
=> docs: Remove status_ prefix from status module variables

.github/workflows/deploy.yml
This PR makes the changelog generator compile again.
Changes:
- Update to go to 1.15
- Pin git-chglog to 0.9.1 because 0.10.0 requires go 1.16 (unreleased) to build. To allow pinning git-chglog `GO111MODULE` needs to be set to `on`.
- Remove `-u` because apparently it can cause issues
Closes #
=> ci: fix changelog generation

docs/config/README.md, src/configs/python.rs, src/modules/python.rs
This makes it possible to configure when the python module is shown
This includes a breaking change since we are removing the
`scan_for_pyfiles` configuration option in favour of setting the
`detect_extensions` to an empty array.
=> feat(python): Configure when the module is shown

docs/config/README.md, src/configs/cmake.rs, src/modules/cmake.rs
This makes it possible to configure when the cmake module is shown
=> feat(cmake): Configure when the module is shown

src/utils.rs
Safely unwrap the output of the commands executed by `utils::exec_cmd`,
this should avoid panics when the output of the command cannot be
decoded.
Closes #2301
=> fix(utils): Safely unwrap the command output

src/logger.rs
Make the colors for debug and trace log levels more visible.
Black and dark grey are illegible on terminals with dark backgrounds. Shades of blue work on light backgrounds as well.
Suggestions welcome for other colors that may be a better compromise.
=> refactor(log): change output colors to shades of blue for trace and debug

src/init/starship.ps1
When starting `starship` with `System.Diagnostics.Process` in `prompt` `stderr` isn't printed to the console even if `$startInfo.RedirectStandardError` is `$false`.
Handle this by manually printing `starship` `stderr`.
Closes #
=> fix(init): make log messages on pwsh visible again

src/modules/directory.rs
Co-Authored-By: Thomas Hurst <tom@hur.st>
Replaces conversions from `Path`/`PathBuf` to strings in `directory.rs`to use lossy versions that don't panic.
Based on the changes by @Freaky (#1426). I only added to test case and fixed another panic for this PR.
Closes #1426
=> fix(directory): Handle non-UTF-8 folder names

src/context.rs, src/modules/java.rs, src/test/mod.rs, src/utils.rs
I added a new method `cmd` to `ModuleRenderer` to allow dynamic mocking of commands and implemented it in `Context`.
I added two additional tests for the java module that make use of this new feature.
In addition, for a small perf boost I gated the `Context.env` `HashMap` with `#[cfg(test)]`.
Closes #942
=> feat(test): allow dynamic mocking of commands

src/init/mod.rs
Added quotes to the init function string of elvish shell.
Closes #2293
This has been a simple edit I did directly in GitHub, I currently don’t have an environment to test this. I added excacty four characters, two escaped quotes, to the init string of elvish, this should not affect any code.
=> fix(init): Quote path for elvish init

docs/config/README.md, src/configs/crystal.rs, src/modules/crystal.rs
This makes it possible to configure when the crystal module is shown
=> feat(crystal): Configure when the module is shown

src/init/starship.fish
In Fish, `export` is a function that wraps the built-in `set` command for compatibility with POSIX shells. It’s more idiomatic and has slightly less overhead to use the built-in `set -x` instead. See https://github.com/fish-shell/fish-shell/issues/2704#issuecomment-178749261.
With `export`:
```
$ hyperfine "fish -ic exit"
Benchmark #1: fish -ic exit
Time (mean ± σ):      41.8 ms ±   1.1 ms    [User: 29.1 ms, System: 12.7 ms]
Range (min … max):    40.2 ms …  45.5 ms    57 runs
```
With `set -x`:
```
$ hyperfine "fish -ic exit"
Benchmark #1: fish -ic exit
Time (mean ± σ):      38.7 ms ±   1.5 ms    [User: 26.6 ms, System: 11.7 ms]
Range (min … max):    35.4 ms …  43.2 ms    60 runs
```
=> perf(init): Prefer set -x over export for fish users

src/modules/directory.rs
Reverts a change that slipped through in the `--logical-path` PR. `display_dir` may not exist (on Windows), but I think that's more uncommon than having symlink in the path (on -nix).
Closes #
=> fix(directory): contract git repo with display path

docs/config/README.md, src/configs/zig.rs, src/modules/zig.rs
This makes it possible to configure when the zig module is shown based on the contents of a directory.
=> feat(zig): Configure when the module is shown

docs/config/README.md, src/configs/dart.rs, src/modules/crystal.rs, src/modules/dart.rs
This makes it possible to configure when the dart module is shown based
on the contents of a directory. This should make it possible to be a lot
more granular when configuring the module.
=> feat(dart): Configure when the module is shown

src/init/starship.fish
Fix syntax error.
Closes #2316
Closes #2319
=> fix: correct fish syntax error when setting variables

docs/config/README.md, src/configs/vagrant.rs, src/modules/vagrant.rs
This makes it possible to configure when the vagrant module is shown based on the contents of a directory.
=> feat(vagrant): Configure when the module is shown

docs/config/README.md, src/configs/docker_context.rs, src/modules/docker_context.rs
This makes it possible to configure when the docker_context module is
shown based on the contents of a directory. This should make it possible
to be a lot more granular when configuring the module.
=> feat(docker_context): Configure when module is shown

.github/workflows/deploy.yml
This PR triggers a Netlify deployment of our docs as part of our release pipeline. When this PR is merged, I'll go ahead and disable automated deployments in the Netlify dashboard:
Closes #2298
This PR ensures that docs aren't updated ahead of the release of the associated features.
=> ci(docs): only publish site on release

src/print.rs
This fallback is the quick-fix for #1588
See https://github.com/starship/starship/issues/1588#issuecomment-674568040
Ran it under `env`, `env 'TERM=dumb` and `env 'TERM=dumber`.
So far this is missing tests and documentation changes.
I'm not sure how to write the test for it (new to rust and this project), nor whether
should this behavior be documented nor where.
=> fix: Add a fallback prompt under TERM=dumb

docs/config/README.md, src/configs/terraform.rs, src/modules/terraform.rs
This makes it possible to configure when the terraform module is shown
=> feat(terraform): Configure when the module is shown

docs/config/README.md, src/configs/go.rs, src/modules/golang.rs
This makes it possible to configure when the golang module is shown
=> feat(golang): Configure when the module is shown

docs/config/README.md, src/configs/lua.rs, src/modules/lua.rs
This makes it possible to configure when the lua module is shown
=> feat(lua): Configure when the module is shown

docs/config/README.md, src/configs/dotnet.rs, src/modules/dotnet.rs
This makes it possible to configure when the dotnet module is shown
based on the contents of a directory. This should make it possible to be
a lot more granular when configuring the module.
=> feat(dotnet): Configure when module is shown

docs/config/README.md, src/configs/mod.rs, src/configs/shell.rs, src/configs/starship_root.rs, src/module.rs, src/modules/mod.rs, src/modules/shell.rs
A "shell" module, which allows to quickly identify which shell is being used.
Closes #1380
Ran cargo test modules::shell, also tested it with powershell on Windows and zsh & bash on Linux.
=> feat: create shell module

docs/config/README.md, src/configs/elixir.rs, src/modules/elixir.rs
This makes it possible to configure when the elixir module is shown
based on the contents of a directory. This should make it possible to be
a lot more granular when configuring the module.
=> feat(elixir): Configure when module is shown

docs/config/README.md, src/configs/elm.rs, src/modules/elm.rs
This makes it possible to configure when the elm module is shown
=> feat(elm): Configure when the module is shown

docs/installing/README.md
Added install steps for termux
Easier install in termux
=> docs: Update README.md with instructions for termux

docs/config/README.md, src/configs/erlang.rs, src/modules/erlang.rs
This makes it possible to configure when the erlang module is shown
=> feat(erlang): Configure when the module is shown

docs/config/README.md, src/configs/nim.rs, src/modules/nim.rs
This makes it possible to configure when the nim module is shown
=> feat(nim): Configure when the module is shown

docs/config/README.md, src/configs/nodejs.rs, src/modules/nodejs.rs
This makes it possible to configure when the nodejs module is shown
=> feat(nodejs): Configure when the module is shown

docs/config/README.md, src/configs/ruby.rs, src/modules/ruby.rs
This makes it possible to configure when the ruby module is shown
=> feat(ruby): Configure when the module is shown

docs/config/README.md, src/configs/rust.rs, src/modules/rust.rs
This makes it possible to configure when the rust module is shown
=> feat(rust): Configure when the module is shown

docs/config/README.md, src/configs/swift.rs, src/modules/swift.rs
This makes it possible to configure when the swift module is shown
=> feat(swift): Configure when the module is shown

docs/config/README.md, src/configs/ocaml.rs, src/modules/ocaml.rs
This makes it possible to configure when the ocaml module is shown
=> feat(ocaml): Configure when the module is shown

docs/config/README.md, src/configs/perl.rs, src/modules/perl.rs
This makes it possible to configure when the perl module is shown
=> feat(perl): Configure when the module is shown

docs/config/README.md, src/configs/php.rs, src/modules/php.rs
This makes it possible to configure when the php module is shown
=> feat(php): Configure when the module is shown

docs/config/README.md, src/configs/purescript.rs, src/modules/purescript.rs
This makes it possible to configure when the purescript module is shown
=> feat(purescript): Configure when the module is shown

docs/config/README.md, src/configs/kotlin.rs, src/modules/kotlin.rs
This makes it possible to configure when the kotlin module is shown
=> feat(kotlin): Configure when the module is shown

docs/config/README.md, src/configs/julia.rs, src/modules/julia.rs
This makes it possible to configure when the julia module is shown
=> feat(julia): Configure when the module is shown

docs/config/README.md, src/configs/java.rs, src/modules/java.rs
This makes it possible to configure when the java module is shown
=> feat(java): Configure when the module is shown

docs/config/README.md, src/configs/helm.rs, src/modules/helm.rs
This makes it possible to configure when the helm module is shown based
on the contents of a directory.
=> feat(helm): Configure when the module is shown

docs/config/README.md, src/configs/nodejs.rs, src/modules/nodejs.rs
Replace unicode hexagon with nodejs-specific nerd-font icon
The unicode hexagon symbol does not actually fit into a single column with a fixed-width font. [ (nf-mdi-nodejs)](https://www.nerdfonts.com/cheat-sheet?set=nf-mdi-nodejs) does. As starship requires a nerd font as a prerequisite, it's safe to assume that this symbol is available.
Visually checked on Linux, with FiraCode Nerd Font Mono at multiple sizes.
=> fix(nodejs): Change nodejs symbol to the nerd-font nodejs one

docs/installing/README.md
This changes the documentation to show the provided Home Manager module instead of manual Home Manager installation instructions. Also fixes a typo in the NixOS instructions and removes the unfinished and now unnecessary section on zsh integration via Home manager (since that is included in the provided module).
=> docs: Update Nix installation documentation

docs/config/README.md
Change wording for the confusing `add_newline` sentence to something that hopefully makes more sense.
It aims to prevent users from being confused by the subtle difference between `add_newline` and `line_break` options
Closes #1987 
Tested by checking the docs local build.
=> docs: Clarify wording on add_newline option

install/install.sh
* update shebang to support posix-compliant shells (like dash)
* replace all usages of echo with printf (to normalise)
* remove locals, which are not posix complaint
* rename `command` variable to `fetch_cmd` as it overloads a posix builtin
* rename `complete` function to `completed` as it overloads the bash builtin for completion
Bash should not be necessary to run the install script on systems that would otherwise not require it. Ubuntu uses dash by default and I use zsh, so no reason to install bash before installing starship. :)
Closes #2226 
Ran install scripts on macOS natively, as well as the following docker containers for linux distributions (not the same as native, but as close as I can get with ease):
* debian
* fedora
* centos
* linuxmint
* ubuntu
=> feat(install): make install script posix compliant

Cargo.lock
This PR updates the vulnerable generic-array (0.12.3) package to 0.12.4.
Closes #2396
=> fix: update vulnerable generic-array package

src/utils.rs
Bash will interpret some characters in the prompt which may lead it to inadvertently execute code. #884 previously fixed this, but it looks like the fix was removed at some point.
I added the fix to `wrap_colorseq_for_shell` which is roughly where the fix was previously located.
Closes #2401
=> fix(bash): escape interpretable characters

docs/config/README.md, docs/presets/README.md, src/configs/aws.rs, src/modules/aws.rs
and also after the symbol when using the Nerd font glyph.
Style of most modules is to have a space between distinguishable segments. The aws module was missing that between the profile and region segments. Also add a space after the Nerd font glyph. See screenshots below.
Style change to follow the look of the prompt modules.
=> style(aws): Add spacing between profile and region

src/modules/package.rs
Fix meson version extraction if 'meson_version' is present.
Previously, if `meson_version` is present after `version`, the meson project version will be extracted from `meson_version`.
=> fix(package): fix meson version extraction if 'meson_version' is present

docs/config/README.md, src/modules/aws.rs
Adds another override, like the `AWS_VAULT` one, that uses another environment variable to resolve the current AWS profile.
When using [awsu](https://github.com/kreuzwerker/awsu) the currently assumed role/profile is a helpful addition to the prompt.
=> feat(aws): add support for getting profile from awsu

src/modules/java.rs
This switches us from just appending `/bin/java` to `$JAVA_HOME` to
treating `$JAVA_HOME` as a path. This should fix any issues on Windows
where $JAVA_HOME might use `\` rather than `/`.
Related to #2427
=> fix(java): use consistent separators for java path

src/modules/python.rs
Add support for parsing PyPy python version.
Before this fix, I get the following prompt:
```
... via 🐍 v3.7.9 (7e6e2bb30ac5fbdbd443619cae28c51d5c162a02, Nov 24 2020, 10:03:59)
[PyPy 7.3.3-beta0 with GCC 10.2.0]
```
With the fix:
```
... via 🐍 v3.7.9
```
=> fix(python): Handle PyPy python version correctly

snapcraft.yaml
I added `arm64` as a build platform to the snapcraft yaml. I also tried building this with `snapcraft build` on my arm64 Ubuntu installation, and it seemed to work 🎉 
Closes #2381 
I tested by running `snapcraft build`.
This now brings in all supported snap platforms, with an allowed failure for `s390x` which currently fails to build:
```text
arch=arm64	state=Successfully built
arch=armhf	state=Successfully built
arch=i386	state=Successfully built
arch=amd64	state=Successfully built
arch=ppc64el	state=Successfully built
arch=s390x	state=Failed to build
```
=> build: add more architectures to Snap package

docs/config/README.md, src/configs/cmake.rs, src/modules/cmake.rs
=> fix(cmake): Change cmake symbol to unicode triangle

src/modules/git_status.rs
The git_status module has been rewritten to directly call the git cli using `git status -b --porcelain=2 -uall (etc.)` and `git stash list`.  Specifically, the Repository and Status structs from git2 are no longer used (and therefore git2 isn't used in this module).  They have been "replaced" by passing the repo directory directly to the git commands and the porcelain info is extracted directly to determine necessary information.  The `RepoStatus` struct has been modified with this new method and the `GitStatusInfo` struct has also been slightly tweaked.
**Important** in the contributing guidelines [testing section](https://github.com/starship/starship/blob/master/CONTRIBUTING.md#testing), it mentions placing code in `src/utils.rs` when an external command is being run.  Given the dynamic …
=> perf(git_status): replace git2 in git status module with git cli

src/modules/shell.rs
Previously attempting to use conditional format strings with `$indicator` would never display an indicator, e.g.:
```toml
[shell]
fish_indicator = ""
bash_indicator = "B "
format = "($indicator )"
disabled = false
```
This would always display an empty string. With this patch, this displays `B ` on bash and nothing on fish, as intended.
Closes #2474.
=> fix(shell): Support conditional format strings for `$indicator`

docs/config/README.md, src/configs/python.rs, src/modules/python.rs
After upgrading from 0.47 to 0.49 I noticed that there was a missing ' ' between
the python format section and the one that comes after that.
Fixes #2342
```
~/p/ideas on  master [$?] via ⬢ v15.3.0 via 🐍 v3.9.1 (python-3.9.1)via 💠 default on ☁️  me(pdx) on ☁️   8 🐟
❯ ../starship/target/debug/starship prompt
~/p/ideas on  master [$?] via ⬢ v15.3.0 via 🐍 v3.9.1 (python-3.9.1) via 💠 default on ☁️  me(pdx) on ☁️   8 🐟
❯ ⏎
```
=> fix(python): Add a missing ' ' to the end of the python prompt

docs/installing/README.md
The link to `home-manager` seems to be missing when the section was added.
Closes #
=> docs(readme): add missing link to home-manager

docs/config/README.md
Update configuration tables:
- lowercase all module names in `disabled` option row
- enhance `truncation_length` description formatting
- format `HEAD` and `SHLVL` occurrences
Fix incorrect manifest filename in NodeJS configuration table.
Currently, there are some module names (in the `disabled` option row) that aren't lowercased, and the NodeJS configuration table lists incorrect manifest filename.
---
**Hint** Use Github's rich diff for reviewing
=> docs: format configuration tables

docs/presets/README.md
- Due to #1649, Node.js symbol is already using the one from Nerd Fonts now, so the preset is not needed anymore.
- Haskell module is removed in #1418
Closes #
=> docs(preset): remove unnecessary Node.js and Haskell symbol config

docs/config/README.md
Fix typo in README.
Prior art: https://github.com/starship/starship/pull/2501#issuecomment-806214169
@erikphansen I've reused your original commit :+1:
=> docs: fix typo `moudle` -> `module`

src/init/mod.rs
Have make a small change to the message that is printed when an unknown
shell is used. This correct the placement of the trailing `"` so that
the two training new lines are correctly printed and updates the list of
supported shells.
Before:
```
❯ eval $(starship init fakesh)
fakesh is not yet supported by starship.
For the time being, we support bash, zsh, fish, and ion.
Please open an issue in the starship repo if you would like to see support for fakesh:
https://github.com/starship/starship/issues/newnn
```
After:
```
❯ eval $(target/debug/starship init fakesh)
fakesh is not yet supported by starship.
For the time being, we support the following shells:
* bash
* elvish
* fish
* ion
* powershell
* tcsh
* zsh
Please open an issue in the starship repo if you would like to see support for …
```
=> style(init): Cleanup the unknown shell message

src/configure.rs, src/modules/conda.rs
Swap `.unwrap_or_else(|| "".into())` pattern with simpler and more idiomatic `.unwrap_or_default()`.
Simplify unwrapping options that default to empty strings.
=> refactor: use `unwrap_or_default`

src/context.rs
This PR removes the `unwrap`/`expect` in `context` when `env::current_dir()` fails and adds a fallback to `--logtical-path` and `$PWD` and finally an empty string.
Closes #2485
=> fix(context): remove unwrap when pwd is unavailable

docs/config/README.md, src/configs/mod.rs, src/configs/starship_root.rs, src/configs/vcsh.rs, src/module.rs, src/modules/mod.rs, src/modules/vcsh.rs
[VCSH](https://github.com/RichiH/vcsh) is a widely used dotfile management system. One of the most common usage patterns is to switch into a nested shell to work on a specific config repository, make changes, then drop back out. These nested shells are spawned with the appropriate GIT variables set such that all `git` actions act on the VCSH repository, not whatever directry you might happen to be in. It's very helful to have a prominant alert that you are acting on one of these config repos so you don't forget and try to do work on the current directory.
While many people will have one such repository (and hence a binary on/off flag would work), it's setup by default to handle many repositories. In my case I have a dozen or so. Hence the most obvious choice for noting the condition is to …
=> feat(vcsh): Add new module for VCSH

docs/presets/README.md
The nerd font preset sets the symbol for the `docker` module, but it's called `docker_context`.
Closes #
=> fix: fix docker_context module name in nf preset

src/modules/directory.rs
Some of the tests in the directory module caused the read_only symbol to show up when not run as admin on windows. Handle this by disabling the module in the tests that triggered this for me.
Closes #
=> test(directory): fix on windows without admin

Cargo.lock, Cargo.toml, src/config.rs, src/configs/starship_root.rs, starship_module_config_derive/Cargo.toml, starship_module_config_derive/src/lib.rs
This PR prints a warning when an unknown config key is encountered:
`[WARN] - (starship::configs::starship_root): Unknown config key 'docker' `
This PR builds on the changes to `starship_module_config_derive` in #2521 to use `default` (https://github.com/starship/starship/pull/2521#issuecomment-808752340).
`load_config(&self, config: &'a Value) -> Self` is replaced by `load_config(&mut self, config: &'a Value)` and it loops over the config table now instead of checking every key individually.
`RootModuleConfig` implements `ModuleConfig` manually now to avoid issues with other modules not being known by the module.
Fixes #1213
=> feat(config): warn about unknown config key names

docs/faq/README.md
The uninstall instructions assume that the user is running Bash, which is a safe bet, but isn't always the case.
This change wraps the uninstall command in `bash -c`, making it shell-independent in most cases. It will close issue #2484.
Closes #2484
N/A
I ran `bash -c 'rm "$(which starship)"'` to uninstall Starship, and it worked, even though I'm using Fish as my shell (this is good).
=> docs(faq): make uninstall instructions shell-independent

src/modules/git_branch.rs
Make the Git branch module support bare repositories.
Bare repositories don't have a working directory, causing the branch module to not show any information.
But bare repositories still have branches, tags, etc. that should still be shown in the prompt.
Initialized a bare repository and tested that the prompt contains the branch name.
Tested on Powershell Core 7.1.3  running on Windows 10.
=> fix(git_branch): Make Git branch module support bare repositories

snapcraft.yaml
build-error is not a valid syntax in snapcraft.yaml
The build-error lines are causing _all_ architecture builds to fail.
```
Running pull phase...
Issues while validating snapcraft.yaml: The 'architectures[4]' property does not match the required schema: additional properties are not allowed ('build-error' was unexpected) or orderedDict([('build-on', 'ppc64el'), ('build-error', 'ignore')]) is not of type 'string'
Build failed
```
Sounds like an interesting option, but not one that exists right now, as far as I can tell! :D
=> build: Update snapcraft.yaml

docs/advanced-config/README.md
Quote expansion of `$PWD` to prevent word-splitting, which would give an incorrect result if there is a single space and an error message if there is more than one space. Without the quoting it functions like this:
❯ basename /tmp/foo
foo
❯ basename /tmp/foo bar
foo
❯ basename /tmp/foo bar baz
basename: extra operand ‘baz’
Try 'basename --help' for more information.
If there are spaces in the directory path the result was often nonsensical.
=> docs: quote `$PWD` in window title example

docs/config/README.md, src/configs/ocaml.rs, src/modules/ocaml.rs, src/utils.rs
Support displaying OPAM switch with configurable global/local indicator. As suggested by OPAM authors: https://opam.ocaml.org/doc/Tricks.html#Display-the-current-quot-opam-switch-quot-in-the-prompt
Closes #2479
Detailed explanation: https://github.com/starship/starship/pull/2479#issuecomment-805504311
---
@cdaringe I reused your initial commit. Please feel free to improve it with your suggestions! :wink:
=> feat(ocaml): add `switch_indicator` and `switch_name` variable

docs/config/README.md, src/configs/battery.rs
Add space between battery symbol and charge percentage.
Original motivation:
> We should unify the visual in Starship.
This is essentially repurposed @LitoMore's work with changes @davidkna suggested: https://github.com/starship/starship/pull/2333#discussion_r579138892
Closes #2333
=> style(battery): add space between icon and text for better visual

src/configs/mod.rs, src/configs/starship_root.rs
This PR fixes issues for `print-config` related to the new `FullConfig` struct.
The `golang` module was incorrectly listed as `go`.
For `RootConfig` `#[serde(flatten)]` wasn't enough to make `print-config` (non `--default`) work. I inlined `RootConfig` instead and added a comment in `starship_root.rs` to ensure both are always changed together.
Closes #
=> fix(configure): fix print-config issues

src/modules/python.rs
Updated the retrieval of the the `prompt` parameter from `pyvenv.cfg` so that it removes extra parentheses. pipenv adds the `prompt` parameter with explicit parentheses when using a local `.venv` or setting the `PIPENV_VENV_IN_PROJECT` flag. This creates the 'double parentheses' in the issue below. Removing the additional parentheses when they are read from `pyvenv.cfg` does not affect the display of other python virtual environments. 
Closes #1844 
Example `pyvenv.cfg` with `prompt` parameter as created by pipenv:
Example `pyvenv.cfg` as created by the standard venv and `prompt` CLI option (`python3 -m venv venv --prompt venv-demo`):
Example of double parentheses (before fix):
After the fix:
=> feat(python): Remove parentheses from pyvenv.cfg prompt parameter

src/init/mod.rs
Reformat init stub generation code and alter `bash` version.
Improve readability of the `init_stub` procedure.
=> refactor(init): cleanup init stub

Cargo.lock, Cargo.toml, src/configs/starship_root.rs, starship_module_config_derive/Cargo.toml, starship_module_config_derive/src/lib.rs
This PR changes the unknown config key message to also include a suggestion which key name should be used instead.
The candidate scoring algorithm/library are the same as what `clap` uses.
Closes #
For this config:
```toml
[go]
symbol = " "
[nodejs]
disable = true
```
Output:
```
[WARN] - (starship::configs::starship_root): Unknown config key 'go'
[WARN] - (starship::configs::starship_root): Did you mean 'golang'?
[WARN] - (starship::configs::nodejs): Unknown config key 'disable'
[WARN] - (starship::configs::nodejs): Did you mean 'disabled'?
```
=> feat(config): print a suggestion for unknown fields

README.md, docs/README.md, docs/faq/README.md, docs/installing/README.md
Use POSIX `sh`, mitigate possible timing attacks.
Install script became (almost fully) POSIX compliant with #2228 landing in. This alters advertised installation snippets as discussed here: https://github.com/starship/starship/pull/2228#issuecomment-794882078
=> docs: update install instructions

src/modules/directory.rs, src/modules/username.rs
Some tests were failing when run as root, because the behaviour of the tested modules changed based on whether they were running as a root user. This caused the `style_root` to appear in `username` tests and in the directory module some paths that were assumed not to be writable, ended up writable.
This PR fixes this by either disabling the root-specific behaviour or by ignoring them by default, so they only run in the controlled CI environment.
Closes #2568
=> test: allow running tests as root

docs/config/README.md, src/formatter/string_formatter.rs, src/formatter/version.rs, src/modules/java.rs, src/modules/nodejs.rs, src/modules/python.rs, src/modules/ruby.rs, src/modules/rust.rs
Propagate errors originating from `VersionFormatter#format_version` to the upper level.
Continuation of #2499
(It got closed before I managed to leave my review.)
---
/cc @offbyone
=> refactor: propagate version formatting errors

install/install.sh
Busybox tar interpreted the empty string `"${flags}"` as a file input. I fixed this by also adding all the other flags to `${flags}`, thus ensuring it is never empty.
Another fix would have been to simply unquote `${flags}`, but that would have caused a shellcheck warning.
Closes #2582
=> fix(install): fix install with busybox tar

src/modules/lua.rs
Parse Lua and LuaJIT version without regex.
Follow convention established by other modules.
=> refactor(lua): parse version w/o regex

src/modules/scala.rs
Parse Scala compiler version without regex.
Follow convention established by other modules.
=> refactor(scala): parse version w/o regex

src/modules/elixir.rs
Modify Elixir version parsing to support dev and RC builds.
Addresses https://github.com/starship/starship/discussions/2572
=> fix(elixir): correctly parse dev and rc versions

docs/config/README.md
This PR fixes wrong formatted markdown tables!.
Markdown tables are written as supposed to be.
=> docs: Fix tables Markdown format

docs/config/README.md
This is a PR for the documentation just replacing the section title "Gcloud" with "gcloud" here: https://starship.rs/config/#gcloud.
The official representation of the `gcloud` command-line tool is `gcloud` not `Gcloud` and there is no chance the word is written as `Gcloud`.  (ref. https://cloud.google.com/sdk/gcloud) The starship module name is also `gcloud`. I understand all section names in the config page start with the capital case but I feel `Gcloud` weired a little and the `gcloud` is more natural.
None
=> docs: Replace the section title "Gcloud" with "gcloud"

docs/config/README.md, src/modules/jobs.rs
First PR here, let me know if anything can be improved!
Currently, if there are 0 jobs running then the jobs module doesn't show anything. However, if a negative threshold is specified (user wants to explicitly see that there are 0 jobs running), then it should show 0.
Closes #2610
=> fix(jobs): Handle zero jobs with zero thresholds

docs/config/README.md, src/modules/aws.rs
We use AWESUME to assume into different accounts. It stores the profile in its own environment variable and sets the environment variables for the access key and secret key. 
Show same info as aws-vault
=> feat(aws): Add support for profile from awsume

.github/workflows/deploy.yml, .github/workflows/workflow.yml
`cargo build` lacks `--locked` argument resulting in `Cargo.lock` being ignored and the latest version of dependencies being used instead.
Ensure build pipeline is deterministic.
=> fix(build): respect the lockfile

docs/config/README.md, src/configs/nodejs.rs, src/modules/nodejs.rs
Check for `.nvmrc` file presence in `nodejs` module.
Starship already checks for `.node-version`, and [`.nvmrc`](https://github.com/nvm-sh/nvm#nvmrc) is another popular alternative that worth considering.
=> feat(nodejs): Check for `.nvmrc`

docs/advanced-config/README.md, src/config.rs
This PR adds support for the `inverted` keyword in style strings. This keyword swaps the foreground and background colors, similar to the `\e[7m` ANSI code.
~~(I chose `reverse` instead of `inverted` as I first proposed, because that's the terminology `ansi_term` uses).~~
Closes #2390
=> feat(config): Add support for `inverted` token in style strings

src/modules/gcloud.rs
Lazily read active gcloud config.
Avoid multiple gcloud config read operations.
=> refactor(gcloud): lazily read active gcloud config

docs/config/README.md
Alter Dart's configuration defaults to use double quotes like the rest of the modules.
Keeping things consistent plus single quote strings in TOML have a different meaning. FWIW, they are treated as raw strings thus ignoring escape sequences.
=> docs(dart): use double quotes for consistency

src/configure.rs
When running `starship config` the editor was being started with plain `Command::new` instead of `utils::exec_cmd` which meant that it wasn't using `which` to find the editor binary. This PR makes the command use `which` to find the appropriate binary. `utils::exec_cmd` can't be used here because it needs a timeout.  Not using `which` prevented `starship config` from launching some editor like Visual Studio Code via `code.cmd`. 
Closes #
=> fix(configure): fix launching .cmd editors

docs/config/README.md
Until #2603 it might be better not to mention `print-config` prominently in the docs, because right now this causes confusing behaviour (#2650).
Closes #
=> docs: remove reference to print-config for now

src/configs/mod.rs, src/configs/starship_root.rs
Instead of the proper default values for starship the root level values in `FullConfig` were just using the derived defaults. I fixed this by implementing `Default` manually.
Closes #2603
Closes #2650
config file:
```
format = "test"
```
old:
```
❯ starship print-config
format = 'test'
scan_timeout = 0
command_timeout = 0
add_newline = false
...
❯ starship print-config -d
format = ''
scan_timeout = 0
command_timeout = 0
add_newline = false
...
```
new:
```
❯ cargo run -- print-config
format = 'test'
scan_timeout = 30
command_timeout = 500
add_newline = true
...
❯ cargo run -- print-config -d
format = '$all'
scan_timeout = 30
command_timeout = 500
add_newline = true
...
```
=> fix(print-config): use proper defaults for top-level values

src/configs/mod.rs
#2605 was missing the new red module
Closes #
=> fix(print-config): add red module to Default impl

src/modules/character.rs, src/modules/jobs.rs
Read `keymap`, `status`, and `jobs` option values as `str`-s.
It makes unwrapping to defaults less clunky.
=> refactor: read CLI options as `str`

src/init/starship.fish
This PR consists of ~~two~~ three changes:
- Remove unnecessary `-l` argument to be consistent with the `set keymap` above, and prefix variable names with Starship to avoid conflicts.
In fish, variables are automatically scoped to parent function if no scope is specified, so `-l` makes no difference for the two changed lines.
(However, this is not the same for `set keymap` case, as `-l/--local` will scope it to `switch`.)
This change is purely for styling.
- Explicitly set `$VIRTUAL_ENV_DISABLE_PROMPT`'s scope to global
In fish, variables have a default scope of global while sourcing scripts. But user may try different things like putting Starship load scripts into a function.
Notice how `$VIRTUAL_ENV_DISABLE_PROMPT` is actually not set if Starship is loaded via a function.
- Erase …
=> fix(fish): explicitly set scope in fish init script

docs/config/README.md, src/configs/gcloud.rs, src/modules/gcloud.rs
Symbols using double-width emojis typically use double trailing space as listed here: https://github.com/starship/starship/issues/2616#issuecomment-829338508
Ensure GCloud follows established conventions.
=> fix(gcloud): add double space after cloud emoji symbol

src/modules/package.rs
npm packages often use semantic release as a tool to automate versioning, by having a program look at conventional commit messages, like those on this repo.
This PR abbreviates long versions like `v0.0.0-semantically-released` to `semantic`
For npm packages, a somewhat common pattern is using semantic release, which allows a ci tool (e.g. github actions) to automatically determine versions based on (a conventional) commit history. This means that the correct version isn't actually in the package.json file.
Normally, you'll see a version like 0.0.0-semantically-released in the package.json, to indicate that the package version is derived elsewhere. In it's current implementation, this is awkward because it conveys little meaning, uses quite a bit of space, and doesn't actually let you know …
=> feat: abbreviate package.json semantic versions

docs/config/README.md, src/configs/gcloud.rs, src/modules/gcloud.rs
Introduces separate `account` & `domain` format string variables.
This is essentially #2587 rebased/stacked onto #2592
Closes #2587
Closes #1737
---
/cc @cymruu
=> feat(gcloud): introduce separate `account` & `domain` format string variables

docs/config/README.md, src/configs/shell.rs, src/modules/shell.rs
This adds a default parameter for the shell module, which is displayed in case Starship is not able to identify the shell.
Fairly simple addition of a 'unknown-indicator' element in the ShellConfig struct. 
Please note that I'm a complete beginner in Rust, so if there's any mistakes, I'll be glad to rectify them 😅
Closes #2541 
Running `cargo test` passes all existing tests. Let me know if I should add one more test case (like `test_default_if_unknown_shell`).
=> feat(shell): add unknown_indicator parameter

docs/config/README.md
The docs list `v{raw}` as the format for version number.
This doesn't work, and after a little bit of experimentation, I found the right string: `"v${raw}"`
It also seems a table in the Perl section has some superfluous characters, messing it up in the output.
I use way to long to figure this out. I assume other have made the same mistake. Lets avoid doing it again.
I've only tested it for Python and CMake, as that is what I use.
I assume that the interpolation here is the same in all instances, but I will not be testing them all.
I updated my config with the updated string format, and it work for raw, minor, major, patch.
=> docs: fix raw string format

src/modules/memory_usage.rs
In some cases on windows (I think when swap utilization is around 0) `swap_free` can be larger than `swap_total`. Work around this by using saturating subtraction to handle the underflow properly.
`sys-info` will probably land the fix for this at some point, but it doesn't hurt making this safer here.
Closes #2646
=> fix(memory_usage): prevent used swap underflow on windows

src/modules/git_status.rs
Adding a new file with `git add -N` adds it but does not stage it. Currently Starship shows this as staged. I added the `1 .A` text to `is_modified` to catch this case, and I added a test case and fixture for it.
Closes #1155. The fix is exactly what @andytom suggested [here](https://github.com/starship/starship/issues/1155#issuecomment-826387786)
Before:
After:
I tested using `cargo test` by adding a test case matching what the author of the issue was seeing. I'm on Windows Subsystem for Linux. The change is isolated to the `git_status` module
=> fix(git_status): Show git add -N files as unstaged

docs/config/README.md, src/configs/git_commit.rs, src/modules/git_commit.rs
This moves the hard-coded leading space on git commit tags into the config file.
Closes #2692
=> fix(git_commit): leading space in git commit tag

src/init/starship.zsh
Fix incorrectly used `local` keyword in zsh init script. Declaring the variable as `local` caused it to be not set anymore inside `starship_zle-keymap-select-wrapped` function.
Also renamed `existing_keymap_select_fn` to `__starship_preserved_zle_keymap_select` for making it obvious that this variable was created by starship.
Closes #2557
=> fix(zsh) preserve zle-keymap-select

docs/config/README.md, src/configs/aws.rs, src/modules/aws.rs, src/modules/cmd_duration.rs, src/utils.rs
This PR adds the possibility to display the remaining duration of temporary AWS credentials in the prompt. The remaining duration is put between brackets after the region in seconds if the credentials are still valid or a customizable symbol if they are expired. 
The duration is retrieved in two different ways :
- by looking at the `AWS_SESSION_EXPIRATION` env variable which is set by `aws-vault` or the `AWSUME_EXPIRATION` which is set by AWsume.
- by looking for a `expiration` line in the profile section in the AWS credentials file (#1978).
Display remaining duration of the temporary credentials associated to the current profile.
Closes #1978 
Valid credentials
Expired credentials (obviously the symbol could be better)
Added some tests to test the new functionality. I ran `cargo test …
=> feat(aws): temporary credentials countdown prompt

src/modules/terraform.rs
Terraform's `$version` includes a single trailing whitespace that restricts the formatting options available to the user.
This PR removes the trailing whitespace that's appended to Terraform's version.
I've styled Starship's modules as 'pills' with a background colour that's different from the terminal. In its current form it's not possible to have Terraform's version flush with the edge.
Example configuration (Nerd Font won't render on GitHub, but you get the idea).
```
[terraform]
format = "[](black)[$symbol$version]($style)[](black) "
version_format = "$raw"
style = "purple bg:black"
symbol = "ﯟ "
```
If the space is desired, it can be added explicitly by the user. This is consistent with how other module's versions are formatted.
```
format = "[$symbol$version $workspace]($style) " …
```
=> fix: Remove trailing whitespace from Terraform version

src/modules/git_commit.rs
I didn't manage to reproduce the error but my changes should get of all `unwrap()` calls in the `git_commit` module code.
Closes #2740
=> fix(git_commit): remove unwraps

install/install.sh
Have removed the `local`s from `install.sh` to allow the script to work
on ksh.
Closes #2433
=> refactor(install): Remove local from install.sh

docs/config/README.md
Have added some additional docs to indicate that `vicmd_symbol` doesn't
work for bash's vi mode.
Closes #1171
=> docs(character): Add warning about missing feature

docs/config/README.md, src/configs/dotnet.rs, src/modules/dotnet.rs
Change the detect_extensions of the .NET module, so that the `.sln` file will not trigger the .NET prompt.
According to the [VS documentation](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019),the `.sln` file is 
> simply **a container for one or more related projects**, along with build information, Visual Studio window settings, and any miscellaneous files that **aren't associated with a particular project**.
The project might be C++ project or something else. **Currently, the .NET module will treat all folders with `.sln` file as .NET project, which is confusing.**
Closes #2567
I found that **the .NET module will be triggered in my C++ project**. 
Here is the screen shot:
After fix, the `.sln` file won't trigger the .NET module
=> fix(dotnet): Don't treat folder with .sln file as a .NET project

docs/config/README.md, src/configs/custom.rs, src/modules/custom.rs
Tries to implement #2750.
Add optional so to custom configs to allow filter them by Operating System.
Internally, it uses [env::consts::OS](https://doc.rust-lang.org/std/env/consts/constant.OS.html) to match against different Operating Systems.
Closes #2750.
=> feat: Add Operating System condition to custom commands

docs/presets/README.md
I feel the default icon `↕️` is a little confusing. It may not be very clear what it represents until one read the docs.
This PR adds a new icon `` (nf-fa-terminal, f120) to Nerd Font Symbols preset in order to solve the issue. Or, if it fits, make it the default icon.
=> docs(preset): add a new SHLVL icon to Nerd Font Symbols preset

src/config.rs, src/context.rs, src/modules/nim.rs, src/modules/time.rs
Fixes new clippy lints introduced in rust 1.53.
This is a continuation of #2803 but this times I also fixed the clippy lint warnings for the test target (`--all-targets`).
Closes #
=> fix(clippy): fix additional clippy lints in tests
